### ISSUE TITLE
options.html adaptivity issue

### ISSUE THREAD

**Issue by ex47** [david-sabata/web-scrobbler#1012]
When options page is less than 768px wide most of "options" button is unclickable.
![screenshot_3](https://cloud.githubusercontent.com/assets/2480069/17466970/7cc0769a-5d21-11e6-86b0-6849e86e08d8.png)
768px
![screenshot_4](https://cloud.githubusercontent.com/assets/2480069/17466990/ae50947e-5d21-11e6-8bfd-68f559b41352.png)
767px
Apparently `<div class="modal-footer">...</div>` is obstructing it. Also if you open and close configuration of any connector "options" is no longer obstructed.

**Comment by inverse** [comment]
When using the responsive mode of chrome dev tools I am unable to reproduce this issue. Anyone else able to confirm?
