### ISSUE TITLE
Bandcamp scrobbling still broken?

### ISSUE THREAD

**Issue by hans-juergen** [david-sabata/web-scrobbler#1014]
I don't think it is really fixed yet: the extension recognises the track, notifies me of that, signals it is scrobbling with the green icon, but the scrobble never lands on my Last.fm profile. Trying it with the other browser extension [scroblr](https://chrome.google.com/webstore/detail/scroblr/mflbcmpjneookibbaeopkfcnegknkgog/related?utm_source=chrome-app-launcher-info-dialog) works fine, although I had to edit the album title for each track while scrobbling. I tested it with this album on Bandcamp which did not exist yet in Last.fm, but now it does:

https://mellowrecords.bandcamp.com/album/roger-waters-napoleon-square-lucca-2006
http://www.last.fm/music/Roger+Waters/Napoleon+Square,+Lucca+2006

**Comment by inverse** [comment]
It's working for me with the URL you've provided.

**Comment by hans-juergen** [comment]
How did you check, only trusting the green icon, or also on your Last.fm profile and in your library? Anyhow, maybe it works now, because the album page now exists on Last.fm which it did not before I scrobbled it with scroblr.

**Comment by inverse** [comment]
Check my screenshot ^^

**Comment by hans-juergen** [comment]
OK, that would be from the wrong album, but better than nothing, I guess.

**Comment by inverse** [comment]
Do you think the issue is the initial scrobbling of the album? Falsely saying its working when it's not?

**Comment by hans-juergen** [comment]
Yes, but I can test this with some more albums from Bandcamp when I have the time. Usually I don't scrobble from there, only for testing purposes now. It looks like the initial album titles are sometimes wrong on that site which may be caused by the labels uploading their stuff there. So it is a big help if the extension is able to edit the album title while scrobbling like scroblr. Is there a related feature request for this extension already? ;-)

**Comment by inverse** [comment]
I don't think we can edit the album. That's def a feature we could support for new unrecognised tracks.

**Comment by hans-juergen** [comment]
Here is another example: https://mellowrecords.bandcamp.com/album/peter-gabriel-live-in-wiltshire-2003-2cd

The extension recognises the tracks (except for the first one), shows me a notification with correct album cover and a green icon that it would scrobble it. Checking my user profile nothing is listed though, maybe because of the wrong album title that Bandcamp / the uploading label "mellow world" uses: "PETER GABRIEL live in Wiltshire 2003 (2CD)" which repeats the artist name in capital letters.

If I could edit each track and album title while scrobbling (also the "recognised" ones), it might get scrobbled correctly, e.g. "CD1" added to each title is wrong, and as mentioned the album title.

**Comment by tdhooper** [comment]
Broken for me on http://hyperboloid.ru/album/cyberghetto

Note that https://mellowrecords.bandcamp.com/album/roger-waters-napoleon-square-lucca-2006 works

**Comment by inverse** [comment]
@tdhooper The reason is because of that URL is on a custom domain which the scrobbler cannot resolve to the bandcamp connector. To work around this you can map custom URLs in the options.

**Comment by tdhooper** [comment]
Great, that woks, thank you.

**Comment by alexesprit** [comment]
@hans-juergen I believe #1215 resolves the issue. Could you check the extension from the latest master and confirm that?

**Comment by hans-juergen** [comment]
I'm playing the Peter Gabriel live bootleg now, and the tracks do scrobble except  for the first one. I get a notification popup from the extension v1.61.0 in Chrome 57 beta when the next track starts, and my Recent Tracks on my Last.fm profile show the Now Scrobbling track with yellow background a few seconds later. The track gets scrobbled after 50% of duration, so that is all OK now. But I would still like to edit the track and album title while scrobbling it, because they are still wrong on Bandcamp.

Last but not least I am not sure what happens if Last.fm does not know the track and album yet that I want to scrobble from Bandcamp. I would have to find one first to check this.

**Comment by hihowarey0u** [comment]
Do I need to connect my Bandcamp account to the extension somehow or should it automatically scrobble anything I play on Bandcamp when using Chrome? 
My Last.fm account is signed in and scrobbing from Spotify works

**Comment by alexesprit** [comment]
@hihowarey0u no, the extension doesn't requre Bandcamp account.

**Comment by Larzans** [comment]
It doesn't work on several analogafrica links either, for example this one:
https://analogafrica.bandcamp.com/album/angola-soundtrack-2-hypnosis-distorsions-other-sonic-innovations-1969-1978
Is there anything i can change in the configuration to fix that? If i click on the 'as' icon the track is shown correctly, but it doesn't scrobble!

**Comment by alexesprit** [comment]
@Larzans can't reproduce, the extesnion scrobbles fine for me from that URL.
[How to debug extensions.](https://github.com/david-sabata/web-scrobbler/wiki/How-to-debug-the-extension)

**Comment by Larzans** [comment]
@alexesprit thanks for the link. That is very strange. Maybe it is related to the fact that there are some special characters in the arbum title? 
`<album corrected="0">Angola Soundtrack 2 - Hypnosis, Distorsions & Other Sonic Innovations 1969ââ1978</album
`
When debugging the plugin shows the correct information in the popu, but the ajax request shows this strange characters and the response from the server is 'Track not found'.

What could be the reason that it works for you and not for me? I have Win 7,  Chrome 58.0.3029.110 (64-bit).

**Comment by Larzans** [comment]
It seems to be the special characters, as i can scrobble other albums from analog africa without any problems (they don't show the special characters in the ajax request)
So i guess this problem is related to the fact that the album titles contain these characters. Is there a way that scrobblr could filter out anything unusual that will probably not be part of a song name anyhow?

**Comment by alexesprit** [comment]
@Larzans Can you provide **full** logs?

**Comment by Larzans** [comment]
@alexesprit I will later when i find the time. How would you like them? You mean the ajax petitions, or the console output (not much there)

**Comment by Larzans** [comment]
The console: https://pastebin.com/gZyb0GxJ
Ajax requests: https://pastebin.com/bqAF7VPg
Bandcamp page: https://analogafrica.bandcamp.com/album/angola-soundtrack-2-hypnosis-distorsions-other-sonic-innovations-1969-1978
Last.fm page: https://www.last.fm/music/Various+Artists/Angola,+Soundtrack+2+(Hypnosis,+Distortions+&+Other+Sonic+Innovations+1969-1978)

Hmm, now looking at it, might the problem be that there are brackets in the last-fm page? But shouldn't that be a match anyhow, or does it have to be the exact match?!

**Comment by alexesprit** [comment]
@Larzans Last.fm ignores some tracks for some reason.
```
<?xml version="1.0" encoding="utf-8"?>
<lfm status="ok">
  <scrobbles ignored="1" accepted="0">
    <scrobble>
      <track corrected="0">Os Anjos - Avante Juventude</track>
      <artist corrected="0">Various</artist>
      <album corrected="0">Angola Soundtrack 2 - Hypnosis, Distorsions &amp; Other Sonic Innovations 1969&#226;&#128;&#139;-&#226;&#128;&#139;1978</album>
      <albumArtist corrected="0"></albumArtist>
      <timestamp>1496418434</timestamp>
      <ignoredMessage code="1"></ignoredMessage>
    </scrobble>
  </scrobbles>
</lfm>
```

But I noticed the logs are from another project called "scroblr". This project is not related to that extension.

**Comment by Larzans** [comment]
Haha, whups, i was searching for scrobblr and didn't actually check the name too closely, sorry :)
Will try this extension then.

**Comment by Larzans** [comment]
Sorry about the confusion, this extension works like a charm for me now!
