### ISSUE TITLE
Pseudo-tutorial screen upon installing

### ISSUE THREAD

**Issue by david-sabata** [david-sabata/web-scrobbler#102]
It seems like people don't know how to "start" the extension

**Comment by alexesprit** [comment]
I suggest to open the page on add0n.com on first install. There're some information how to use the extension on that page, and maybe it will help people to start using the scrobbler.

https://github.com/alexesprit/web-scrobbler/tree/open-on-install

**Comment by inverse** [comment]
Could this be also used when pushing of "significant" changes too?

**Comment by alexesprit** [comment]
Yes, that's would be great to let people know about big changes.

**Comment by marsjaninzmarsa** [comment]
Or even config option:

> - [x] Display changelog after major updates
>  - [ ] And after minor ones too!
