### ISSUE TITLE
redundant definition?

### ISSUE THREAD

**Issue by ex47** [david-sabata/web-scrobbler#1022]
europa 2 - [connectors.js](https://github.com/david-sabata/web-scrobbler/blob/a4944bca28edd535a16acbcbfc4c783cbff6b5be/core/connectors.js#L985-L997)
same js file

spotify - [connectors.js](https://github.com/david-sabata/web-scrobbler/blob/a4944bca28edd535a16acbcbfc4c783cbff6b5be/core/connectors.js#L237-L248)
https://player.spotify.com/ redirects to https://play.spotify.com/

**Comment by alexesprit** [comment]
Yep, `spotify-play.js` is useless. Can't figure out why it's needed.

[onair.evropa2.sk](http://onair.evropa2.sk/) is unavailable for me. Maybe it's worth deleting it? Or is it unavailable just for me?

I can't listen to any music directly on [onair.evropa2.cz](http://onair.evropa2.cz/). But it has redirects to [youradio.cz](http://www.youradio.cz). Don't sure if Evropa2 connector is useful.

**Comment by ex47** [comment]
> onair.evropa2.sk is unavailable for me.

http://www.downforeveryoneorjustme.com/http://onair.evropa2.sk/

> I can't listen to any music directly on onair.evropa2.cz. But it has redirects to youradio.cz. Don't sure if Evropa2 connector is useful.

works, but you have to disable ad blockers/social blockers

**Comment by alexesprit** [comment]
> works, but you have to disable ad blockers/social blockers

Yes, after disabling adblock it started to work. In this case it's enough to drop onair.evropa2.sk from the list.

**Comment by Paszt** [comment]
> Yep, spotify-play.js spotify.js is useless. Can't figure out why it's needed.  
When sites change urls, they often roll out the changes at different times in different locations.  At one point there was an overlap where both urls were valid.  If we can't be absolutely sure that it's not used in some local, there's really no issue in having an extra, unused domain remain.

**Comment by alexesprit** [comment]
The issue should be closed. It's resolved in #1030 and #1085.
