### ISSUE TITLE
Fix  new VK domain ( new.vk.com )

### ISSUE THREAD

**Issue by aVitomin** [david-sabata/web-scrobbler#1027]
Fix  new VK domain ( new.vk.com )
Old: https://vk.com/
New: https://new.vk.com/

**Comment by alexesprit** [comment]
This is already done, isn't it?

**Comment by aVitomin** [comment]
Scrobbler on new.vk does not work for me

**Comment by alexesprit** [comment]
It will in next release.

**Comment by aVitomin** [comment]
thanks alot

**Comment by ex47** [comment]
@aVitomin close the issue then?
