### ISSUE TITLE
Download Chrome extension for Opera

### ISSUE THREAD

**Issue by hans-juergen** [david-sabata/web-scrobbler#1032]
I  don't know if this has been mentioned yet, but this Opera add-on enables downloading any Chrome extension from the Google store:

https://addons.opera.com/extensions/details/app_id/kipjbhgniklcnglfaldilecjomjaddfi

So I just tested it with Opera 40 beta on Windows 7 and of course this scrobbler, the other [scroblr](http://scroblr.fm/) for Chrome and Safari, and [Friends Who Listen](https://chrome.google.com/webstore/detail/friends-who-listen/meggmbmcebhnbamegfmejpokkjhcnmih?hl=en) which shows a list of your Last.fm friends on every artist/album/track page that they listen to. All three extensions seem to work fine in Opera. So hopefully something similar will be offered soon for MS Edge, and Firefox 48 already has something like this, as mentioned in the related Firefox thread.

**Comment by alexesprit** [comment]
I mentioned this in readme.
