### ISSUE TITLE
New vk.com design fails scrobbling

### ISSUE THREAD

**Issue by antergen** [david-sabata/web-scrobbler#1038]
Hi!  Seems like after vk.com made new design, scrobbling is not working anymore.

**Comment by alexesprit** [comment]
Resolved in #1039.

**Comment by pheliksa** [comment]
As for me, VK scrobbling still doesn't work.

**Comment by alexesprit** [comment]
Is it should be? These changes will be in next release.

**Comment by ex47** [comment]
Temporary workaround for those who can't wait for new release:

1. Go [here](https://github.com/alexesprit/web-scrobbler/tree/b93c77961bf86bdc8c3b7edc0dec82d90dd7b277)
2. Download ZIP
![screenshot_19](https://cloud.githubusercontent.com/assets/2480069/17744628/4e528c66-64b1-11e6-9352-6942c3b95c48.png)
3. Unpack ZIP somewhere
![image](https://cloud.githubusercontent.com/assets/2480069/17744788/e59da63c-64b1-11e6-896f-314b8187b246.png)
4. Go to `chrome://extensions/` and enable `developer mode`
![screenshot_21](https://cloud.githubusercontent.com/assets/2480069/17744954/9dffaeb4-64b2-11e6-8076-7e27f6d9dd79.png)
5. Press `Load unpacked extension...` and select the unpacked folder
![screenshot_23](https://cloud.githubusercontent.com/assets/2480069/17745181/888cc82c-64b3-11e6-8c03-9664feb200bc.png)
6. You may now go to [vk.com](https://vk.com) and listen to music.

**Comment by inverse** [comment]
This is now fixed right?

**Comment by ex47** [comment]
merge needed #1039
