### ISSUE TITLE
Last.fm Scrobbler do not work after vk.com re-design.

### ISSUE THREAD

**Issue by radiobulles** [david-sabata/web-scrobbler#1045]
Hello.

Application  stopped working after 17 August, when design of VK changed ((

**Comment by alexesprit** [comment]
Duplicate #1038.

**Comment by ex47** [comment]
@radiobulles https://github.com/david-sabata/web-scrobbler/issues/1038#issuecomment-240474600

**Comment by adFedorovich** [comment]
👍

**Comment by inverse** [comment]
Closing as dupe
