### ISSUE TITLE
Last.fm Scrobbler asks to link account every time Chrome is launched

### ISSUE THREAD

**Issue by Kepee** [david-sabata/web-scrobbler#1046]
Every time I launch Google Chrome, the add-on asks me to link it to my Last.fm account. It doesn't matter how many times I authenticate it, it keeps asking to authenticate every single time I open Chrome. I'm on Windows 10 and Google Chrome 52.0.2743.116 m (64-bit)

**Comment by alexesprit** [comment]
Can you provide logs to help resolve this problem? You can use this howto to collect proper logs: https://github.com/david-sabata/web-scrobbler/issues/981#issuecomment-238158879.

**Comment by Kepee** [comment]
Removing and then reinstalling the extension seems to have fixed this issue for me.
I re-installed Chrome a week ago and the problem appeared then, could it have something to do with the extension having some cached data somewhere that is left behind when Chrome is uninstalled, and then that data messes things up when Chrome is installed and Chrome automatically installs the extension?

I guess I should have taken the logs _before_ I reinstalled the extension. Now that it's working I suppose there's no point providing any logs either.
