### ISSUE TITLE
archive.org failing to scrobble

### ISSUE THREAD

**Issue by datarunsdeep** [david-sabata/web-scrobbler#1047]
Archive.org concerts aren't scrobbling, and I'm not sure what's up -- I can't find anything wrong with my configuration. 

Ex: https://archive.org/details/gd72-08-24.sbd.miller.18093.sbeok.shnf

HTML5 and Flash players both trigger the "Play some music to get started" message when the music is already playing. 

Any thoughts on what might be the cause?

**Comment by alexesprit** [comment]
Seems like it's because of broken connector. It doesn't recognize artist on the page.

**Comment by alexesprit** [comment]
I tried to fix archive.org scrobbling, but I'm no sure if there is no regressions. Can you test it? https://github.com/alexesprit/web-scrobbler/archive/archive-fix.zip

You can see [this HOWTO](https://github.com/david-sabata/web-scrobbler#unpacked-extension) if you don't know how to install unpacked extensions.

**Comment by datarunsdeep** [comment]
It looks like it's working with the unpacked extension -- see attached. 

Thank you for your fast response!

![screenshot_2](https://cloud.githubusercontent.com/assets/20761254/17921631/31d0c568-6a1e-11e6-96fd-48d8f28552dd.jpg)

**Comment by alexesprit** [comment]
Good! Can you also test scrobbling something other on archive.org?

**Comment by datarunsdeep** [comment]
Hmm, it's failing to scrobble on some netlabel releases: 

https://archive.org/details/badpanda074
https://archive.org/details/deepx003
https://archive.org/details/badpanda038


Is it because it can't find the entry in the last.fm database? 

Would parsing the artist and title from the page and sending that to last.fm work? 


![screenshot_4](https://cloud.githubusercontent.com/assets/20761254/17921982/fb0e92c4-6a1f-11e6-8375-86586e94bb97.jpg)

**Comment by alexesprit** [comment]
> https://archive.org/details/badpanda074
https://archive.org/details/badpanda038

These pages don't contain any information about song title.

> https://archive.org/details/deepx003

There is some tricky song info in this page. It's need to fix the archive.org connector to recognize that info.
