### ISSUE TITLE
Doesn't work with gaana.com redesign

### ISSUE THREAD

**Issue by dufferzafar** [david-sabata/web-scrobbler#1049]
Gaana.com has been redesigned and the extension is now broken 😢

**Comment by alexesprit** [comment]
Confirmed.

I can't imagine how it should be fixed. The bottom player bar doesn't contain info about artist of now playing song. There is only song title and song album on the bar.

**Comment by dufferzafar** [comment]
Yeah. I was working on a fix for this right now, but later realized that.
