### ISSUE TITLE
Spotify listed twice in the options

### ISSUE THREAD

**Issue by hans-juergen** [david-sabata/web-scrobbler#1054]
chrome-extension://hhinaapppaileiechjoiifaancjggfjm/options/options.html

I see two entries for Spotify here, both indicated as being v2.

Disabling Spotify scrobbling on that page while playing does not stop scrobbling immediately though, probably I have to restart Chrome or at least the Spotify player in a new tab first?

By the way, at the moment scrobbling from the Spotify Web Player seems to work with all three options: internal scrobbler, your extension and scroblr.

**Comment by alexesprit** [comment]
We discussed this in #1022. One of Spotify connector is no longer useful and should be removed.
