### ISSUE TITLE
findSeparator's character list (low priority)

### ISSUE THREAD

**Issue by elwinmartin** [david-sabata/web-scrobbler#1063]
Hey, 

I was just wondering why '/' wasn't a default separator but '///' is for the Youtube connector?

Is this just not as common, or does this conflict with some titles commonly scrobbled (for example artists who have a single '/' in their name? 

I'm trying to fix some of the issues that I've had with scrobbling Japanese music videos, which often use a naming convention that doesn't really mesh well with the defaults.

**Comment by inverse** [comment]
We should ideally allow the input of custom separators so people can customise the scrobbler to their liking.

**Comment by alexesprit** [comment]
> Is this just not as common, or does this conflict with some titles commonly scrobbled (for example artists who have a single '/' in their name?

I've added '/' symbol in the end of list of separators, so there should be no conflicts with artist names or song titles (e.g. https://www.youtube.com/watch?v=HG6b9GjLhtU). The only thing is the extension now recognizes Youtube titles like "XXX/YYY" where XXX and YYY are random strings, but I don't think it's a big issue.
