### ISSUE TITLE
Amazon.de scrobbling stopped suddenly

### ISSUE THREAD

**Issue by Ausderfinsternis** [david-sabata/web-scrobbler#1065]
So with the latest update Scrobbling from amazon Prime (.de) worked fine again. But it suddenly stopped to scrobble. I listend to an Album while not in front of the PC. then i checked Last.fm and every song from today was scrobbled correctly including the first 2 songs from the Album i was listening to then it suddenly stopped to scrobble. The Extension recognises AmazonPrime but not that I'm listening right now. To fix it i tried Re-install Shut and opened Chrome and rebootet the PC. Still not working tho.

**Comment by alexesprit** [comment]
Does scrobbling work on other websites (e.g. Youtube, Spotify)?
Also, would be good if you provide logs. You can use [this](https://github.com/david-sabata/web-scrobbler/wiki/How-to-debug-the-extension) howto if you don't know how to do it.

**Comment by biggybean** [comment]
Same problem here - it seems to work elsewhere (tried mixcloud just now). At amazon.de however, the first song played after a Chrome restart scrobbles, and then it gets stuck in an endless "looking up/now playing" cycle without ever reaching the scrobbling stage. 

Here's a log from just now (part of it - it just repeats those element all over again): 
Tab 19: new song detected: {"parsed":{"artist":"The Head And The Heart","track":"Down In The Valley","album":null,"uniqueID":null,"duration":null,"currentTime":55,"isPlaying":true,"trackArt":"https://album-art-storage-eu.s3.amazonaws.com/9021def80b800977df59f791c651e…UXIHBOOVMGH5VA&Expires=1474733254&Signature=sqEzHm0SOwZSMD1Y8vcMTab9hY8%3D","url":{"hash":"","search":"","pathname":"/my/songs","port":"","hostname":"music.amazon.de","host":"music.amazon.de","protocol":"https:","origin":"https://music.amazon.de","href":"https://music.amazon.de/my/songs","ancestorOrigins":{}}},"processed":{"artist":"The Head And The Heart","track":"Down In The Valley","album":null,"duration":null},"metadata":{"userloved":false,"startTimestamp":1474647129,"url":{"hash":"","search":"","pathname":"/my/songs","port":"","hostname":"music.amazon.de","host":"music.amazon.de","protocol":"https:","origin":"https://music.amazon.de","href":"https://music.amazon.de/my/songs","ancestorOrigins":{}},"connector":{"label":"Amazon","matches":["*://www.amazon.com/gp/dmusic/cloudplayer/*","*://www.amazon.de/gp/dmusic/cloudplayer/*","*://www.amazon.es/gp/dmusic/cloudplayer/*","*://www.amazon.co.uk/gp/dmusic/cloudplayer/*","*://music.amazon.com/*","*://music.amazon.de/*","*://music.amazon.es/*","*://music.amazon.co.uk/*"],"js":["connectors/v2/amazon.js"],"version":2}},"flags":{"isProcessed":false,"isScrobbled":false,"isCorrectedByUser":false,"isLastfmValid":null,"isMarkedAsPlaying":false}}
controller.js:150 Tab 19: song finished processing  {"parsed":{"artist":"The Head And The Heart","track":"Down In The Valley","album":null,"uniqueID":null,"duration":null,"currentTime":55,"isPlaying":true,"trackArt":"https://album-art-storage-eu.s3.amazonaws.com/9021def80b800977df59f791c651e…UXIHBOOVMGH5VA&Expires=1474733254&Signature=sqEzHm0SOwZSMD1Y8vcMTab9hY8%3D","url":{"hash":"","search":"","pathname":"/my/songs","port":"","hostname":"music.amazon.de","host":"music.amazon.de","protocol":"https:","origin":"https://music.amazon.de","href":"https://music.amazon.de/my/songs","ancestorOrigins":{}}},"processed":{"artist":"The Head and the Heart","track":"Down In The Valley","album":null,"duration":304},"metadata":{"userloved":false,"startTimestamp":1474647129,"url":{"hash":"","search":"","pathname":"/my/songs","port":"","hostname":"music.amazon.de","host":"music.amazon.de","protocol":"https:","origin":"https://music.amazon.de","href":"https://music.amazon.de/my/songs","ancestorOrigins":{}},"connector":{"label":"Amazon","matches":["*://www.amazon.com/gp/dmusic/cloudplayer/*","*://www.amazon.de/gp/dmusic/cloudplayer/*","*://www.amazon.es/gp/dmusic/cloudplayer/*","*://www.amazon.co.uk/gp/dmusic/cloudplayer/*","*://music.amazon.com/*","*://music.amazon.de/*","*://music.amazon.es/*","*://music.amazon.co.uk/*"],"js":["connectors/v2/amazon.js"],"version":2},"artistUrl":"https://www.last.fm/music/The+Head+and+the+Heart","trackUrl":"https://www.last.fm/music/The+Head+and+the+Heart/_/Down+In+The+Valley","artistThumbUrl":"https://album-art-storage-eu.s3.amazonaws.com/9021def80b800977df59f791c651e…UXIHBOOVMGH5VA&Expires=1474733254&Signature=sqEzHm0SOwZSMD1Y8vcMTab9hY8%3D"},"flags":{"isProcessed":true,"isScrobbled":false,"isCorrectedByUser":false,"isLastfmValid":true,"isMarkedAsPlaying":false}}
controller.js:93 Tab 19: new track state: {"track":"Down In The Valley","artist":"The Head And The Heart","uniqueID":null,"duration":null,"currentTime":56,"isPlaying":true,"url":{"hash":"","search":"","pathname":"/my/songs","port":"","hostname":"music.amazon.de","host":"music.amazon.de","protocol":"https:","origin":"https://music.amazon.de","href":"https://music.amazon.de/my/songs","ancestorOrigins":{}},"trackArt":"https://album-art-storage-eu.s3.amazonaws.com/9021def80b800977df59f791c651e…UXIHBOOVMGH5VA&Expires=1474733254&Signature=sqEzHm0SOwZSMD1Y8vcMTab9hY8%3D"}
controller.js:101 Tab 19: new song detected: {"parsed":{"artist":"The Head And The Heart","track":"Down In The Valley","album":null,"uniqueID":null,"duration":null,"currentTime":56,"isPlaying":true,"trackArt":"https://album-art-storage-eu.s3.amazonaws.com/9021def80b800977df59f791c651e…UXIHBOOVMGH5VA&Expires=1474733254&Signature=sqEzHm0SOwZSMD1Y8vcMTab9hY8%3D","url":{"hash":"","search":"","pathname":"/my/songs","port":"","hostname":"music.amazon.de","host":"music.amazon.de","protocol":"https:","origin":"https://music.amazon.de","href":"https://music.amazon.de/my/songs","ancestorOrigins":{}}},"processed":{"artist":"The Head And The Heart","track":"Down In The Valley","album":null,"duration":null},"metadata":{"userloved":false,"startTimestamp":1474647130,"url":{"hash":"","search":"","pathname":"/my/songs","port":"","hostname":"music.amazon.de","host":"music.amazon.de","protocol":"https:","origin":"https://music.amazon.de","href":"https://music.amazon.de/my/songs","ancestorOrigins":{}},"connector":{"label":"Amazon","matches":["*://www.amazon.com/gp/dmusic/cloudplayer/*","*://www.amazon.de/gp/dmusic/cloudplayer/*","*://www.amazon.es/gp/dmusic/cloudplayer/*","*://www.amazon.co.uk/gp/dmusic/cloudplayer/*","*://music.amazon.com/*","*://music.amazon.de/*","*://music.amazon.es/*","*://music.amazon.co.uk/*"],"js":["connectors/v2/amazon.js"],"version":2}},"flags":{"isProcessed":false,"isScrobbled":false,"isCorrectedByUser":false,"isLastfmValid":null,"isMarkedAsPlaying":false}}
controller.js:150 Tab 19: song finished processing  {"parsed":{"artist":"The Head And The Heart","track":"Down In The Valley","album":null,"uniqueID":null,"duration":null,"currentTime":56,"isPlaying":true,"trackArt":"https://album-art-storage-eu.s3.amazonaws.com/9021def80b800977df59f791c651e…UXIHBOOVMGH5VA&Expires=1474733254&Signature=sqEzHm0SOwZSMD1Y8vcMTab9hY8%3D","url":{"hash":"","search":"","pathname":"/my/songs","port":"","hostname":"music.amazon.de","host":"music.amazon.de","protocol":"https:","origin":"https://music.amazon.de","href":"https://music.amazon.de/my/songs","ancestorOrigins":{}}},"processed":{"artist":"The Head and the Heart","track":"Down In The Valley","album":null,"duration":304},"metadata":{"userloved":false,"startTimestamp":1474647130,"url":{"hash":"","search":"","pathname":"/my/songs","port":"","hostname":"music.amazon.de","host":"music.amazon.de","protocol":"https:","origin":"https://music.amazon.de","href":"https://music.amazon.de/my/songs","ancestorOrigins":{}},"connector":{"label":"Amazon","matches":["*://www.amazon.com/gp/dmusic/cloudplayer/*","*://www.amazon.de/gp/dmusic/cloudplayer/*","*://www.amazon.es/gp/dmusic/cloudplayer/*","*://www.amazon.co.uk/gp/dmusic/cloudplayer/*","*://music.amazon.com/*","*://music.amazon.de/*","*://music.amazon.es/*","*://music.amazon.co.uk/*"],"js":["connectors/v2/amazon.js"],"version":2},"artistUrl":"https://www.last.fm/music/The+Head+and+the+Heart","trackUrl":"https://www.last.fm/music/The+Head+and+the+Heart/_/Down+In+The+Valley","artistThumbUrl":"https://album-art-storage-eu.s3.amazonaws.com/9021def80b800977df59f791c651e…UXIHBOOVMGH5VA&Expires=1474733254&Signature=sqEzHm0SOwZSMD1Y8vcMTab9hY8%3D"},"flags":{"isProcessed":true,"isScrobbled":false,"isCorrectedByUser":false,"isLastfmValid":true,"isMarkedAsPlaying":false}}

**Comment by Ausderfinsternis** [comment]
Sorry for the late reply. Scrobbling on YT was perfectly fine. But for me not even the first song after restart scrobbled. That issue somehow solved itself for me. didn't scrobble for a few days but works fine again now. I Will try to post logs if it occurs again.

**Comment by inverse** [comment]
Should we close this one too?
