### ISSUE TITLE
New Pandora = No Scrobbling

### ISSUE THREAD

**Issue by who1sJosh** [david-sabata/web-scrobbler#1068]
Pandora has changed the site or something because I am unable to scrobble songs. Please fix soon. TYSM

**Comment by alexesprit** [comment]
Strange, I see no changes of Pandora website. Scrobbling works fine too.

**Comment by dropdeadtired** [comment]
Pandora scrobbling doesn't work for me either since today.

**Comment by alexesprit** [comment]
I tested the extension on Chrome 53.0.2785.116m, works fine. Can you provide extension logs?

**Comment by alexesprit** [comment]
@who1sJosh @dropdeadtired could you guys please provide saved Pandora main page for inpections?
