### ISSUE TITLE
wrzuta.pl

### ISSUE THREAD

**Issue by mi8as** [david-sabata/web-scrobbler#1071]
Here https://chrome.google.com/webstore/detail/lastfm-scrobbler/hhinaapppaileiechjoiifaancjggfjm it is mentioned, that the site wrzuta.pl is allowed for scrobbling, but unfortunetely it isn't now. Is it possible to fix it?

**Comment by alexesprit** [comment]
Hi.

It's definitely can be fixed. Can you provide any example of URL with some music? I found only URLs like this http://www.wrzuta.pl/audio/najnowsze/disco_polo/odtworz but I can't play any song on these pages (possibly this is issue on my side, will try later on another PC). But I've almost fixed scrobbling for these URLs, though.

I also found URLs like this http://noname925.wrzuta.pl/audio/60e3sP4UTY0/thomas_gold_feat._bright_lights_-_believe but there's no music on that page.

**Comment by mi8as** [comment]
Hi,
thank you for reply.

Yesterday I've listened some playlists from there http://lalanablanalala91.wrzuta.pl/playlisty , for example http://lalanablanalala91.wrzuta.pl/playlista/5WQ44bqPAR0/napszyklat_-_np_2009 . What about them?

**Comment by alexesprit** [comment]
I fixed it in #1072.

If you don't want to wait until #1072 gets merged, you can download Web scrobbler from [my repo](https://github.com/alexesprit/web-scrobbler/tree/wrzuta-fix) and install as [unpacked extension](https://github.com/david-sabata/web-scrobbler#unpacked-extension).

**Comment by inverse** [comment]
Will close this once we have the release to cover :+1:
