### ISSUE TITLE
Connetor for driveplayer.com

### ISSUE THREAD

**Issue by saintego** [david-sabata/web-scrobbler#1082]
It would be great to support driveplayer.com. It's google drive music player which support id3 tags.

**Comment by saintego** [comment]
Hi
I cannot create pull request. This worked for me. Can you accpet it? 
Thanks
[driveplayer.com.zip](https://github.com/david-sabata/web-scrobbler/files/516358/driveplayer.com.zip)

**Comment by saintego** [comment]
@nicolasgarnier

**Comment by alexesprit** [comment]
Should be closed
