### ISSUE TITLE
Scrobbler and player for Tidido

### ISSUE THREAD

**Issue by bellamossa** [david-sabata/web-scrobbler#1089]
Good evening everyone,
can anyone please develop a simple plugin for any common desktop music app (like windows media player, for example), **able to play tracks from Tidido***\* while scrobbling them to LastFm?

Thanks a lot guys :)

Walter

**Comment by alexesprit** [comment]
How is this related to the extension?

**Comment by inverse** [comment]
As @alexesprit said I'm not sure how this fits with this extension.
