### ISSUE TITLE
SoundCloud Scrobbling

### ISSUE THREAD

**Issue by redelpedron** [david-sabata/web-scrobbler#1106]
I toggle the repeat playing track button but the add-on doesn't scrobble on repeat.

**Comment by alexesprit** [comment]
I have the same issue.

**Comment by f1u77y** [comment]
It doesn't get updated on progress.
I've probably fixed scrobbling on repeat this but extracting artist/title from that garbage has blown my mind

**Comment by alexesprit** [comment]
@f1u77y looks good, but you could use `Connector.getArtistTrack` function to get artist and track in one place.
Also, 
```js
return cleanArtistTrack({
	artist: split[0] || null,
	track: split.slice(1).join(artistTrackSep),
});
```
can produce an error, because `cleanArtistTrack` assumes artist is always string.

**Comment by f1u77y** [comment]
@alexesprit got it, fixed. 
(not sure if it will search for separator rightly with all the crap that is removed in `cleanArtistTrack`)
(also not sure about getting all info from this string; previous implementation used username in addition)
