### ISSUE TITLE
Vkontakte doesn't scrobble.

### ISSUE THREAD

**Issue by lauaviin** [david-sabata/web-scrobbler#1108]
Chrome Version 54.0.2840.71 m
Reauthing numerous times didn't fix VK but did fix di.fm and soundcloud's scrobbling.

**Comment by alexesprit** [comment]
It works for me. What am I doing wrong?

Also, [how to debug extensions.](https://github.com/david-sabata/web-scrobbler/wiki/How-to-debug-the-extension)

**Comment by lauaviin** [comment]
I'll look further into the debugging console this evening. Thanks for pointing out the wiki page. 
I can see the extension injecting scripts and calling resets after closing the tab but other than that there is nothing showing up.

**Comment by alexesprit** [comment]
Can you please check the latest version of the extension? You can install it as an unpacked extension: https://github.com/david-sabata/web-scrobbler#unpacked-extension

**Comment by lauaviin** [comment]
The latest version scrobbles just fine. Thanks for pointing out the link.
