### ISSUE TITLE
Amazon Echo Not Scrobbling 

### ISSUE THREAD

**Issue by hilgi** [david-sabata/web-scrobbler#1109]
I have the website open which shows the songs playing through Echo but the extension is still grayed out. http://alexa.amazon.com/spa/index.html#player 

Echo is shown as one currently supported, is there anything I need to do?

**Comment by alexesprit** [comment]
I cannot check scrobbling from Echo directly. 

Can you please add `*://alexa.amazon.com/spa/index.html#player`  as a custom pattern for Echo? You can do this by click on gear icon near 'Amazon Echo' item in the extension options:
![image](https://cloud.githubusercontent.com/assets/1119267/19831892/dcbacc0c-9e1d-11e6-9a46-31802695293f.png)
![image](https://cloud.githubusercontent.com/assets/1119267/19831899/fcce203e-9e1d-11e6-8df8-8194210d2716.png)

This action should fix Echo scrobbling.

**Comment by hilgi** [comment]
It worked when I added the whole thing http://alexa.amazon.com/spa/index.html#player

Thanks!

**Comment by alexesprit** [comment]
Glad to hear it's fixed for you!

**Comment by greedoe** [comment]
I can't actually get anything to happen when I click on the gear icon. I'm using the extension through v60 /64-bit of Chrome.
