### ISSUE TITLE
Vk does not scrobble

### ISSUE THREAD

**Issue by SketchTurnerrr** [david-sabata/web-scrobbler#1114]

**Comment by alexesprit** [comment]
It's known issue and will be fixed in next release.

**Comment by alexesprit** [comment]
Just forgot to say: you can install the latest verstion of Web scrobbler as [an unpacked extension](https://github.com/david-sabata/web-scrobbler#unpacked-extension) to scrobble VK tracks :)

**Comment by inverse** [comment]
Tagging as discussion for others to see until the new release is out.

**Comment by alexesprit** [comment]
@SketchTurnerrr please check out the new release -- it should scrobble tracks from VK.

**Comment by SketchTurnerrr** [comment]
Thx, it works.

**Comment by inverse** [comment]
Closing as resolved
