### ISSUE TITLE
Stripping garbage from track names

### ISSUE THREAD

**Issue by f1u77y** [david-sabata/web-scrobbler#1128]
Some internet services provide tracks with many garbage in the tags. This garbage seems to be at most common between services(for instance youtube and soundcloud connectors share (mostly) same function for stripping that garbage). I think it'd be better to implement one global anti-garbage function and put it to the core.

### Further discussion topics
1. ~~Can such function be incompatible to some services?~~
2. ~~If artist and title are in the same string(what a pain), is it better to remove such garbage before or after separating artist from title?~~
3. Should we provide ability to add more garabge-detecting regexes for users?
4. **UPD** Sometimes connector should be able to pass more than one variant of parsed {artist, track}(when artistTrack is ambigous, e.g. `"artist with- dashes -track title"` or some cases like username on soundcloud). last.fm should handle such cases better than we can do.

**Comment by alexesprit** [comment]
https://github.com/alexesprit/web-scrobbler/tree/metafilter

**Comment by inverse** [comment]
@alexesprit I think what you're doing is a good start. Perhaps opening up a PR on this topic to perhaps get some input from others... What do you think?

**Comment by alexesprit** [comment]
@inverse I think we should get rid of v1 connectors first.

**Comment by f1u77y** [comment]
Closing this because relevant PR merged

**Comment by alexesprit** [comment]
> Should we provide ability to add more garabge-detecting regexes for users?

It's supported already:
1. Connector developers can add new rules (regexes) to `Metadata.YoutubeTrackFilters` object to update `MetadataFilter.youtube` behaviour.
2. They also can write custom filter functions with usage of regexes.
