### ISSUE TITLE
Scrobbling doesn't work - internet radio RMF

### ISSUE THREAD

**Issue by InsaneLastFM** [david-sabata/web-scrobbler#1132]
Hi!
I have problem, when I'm listening music from internet radio RMF. In the case internet radio, e.g. http://www.rmfon.pl/play,46
it recognizes this site I think, because LastFM sign is red (see screenshot), but it behaves like no music was playing. Songs isn't shown on my Last.fm profile. I haven't changed anything on my computer and in the past it was working but now it isn't. One thing which was changed it's RMF site, but address is the same. Could you help me?

BR,
Insane_pl (my Last.fm username)

![rmf](https://cloud.githubusercontent.com/assets/23297497/20040167/da4db980-a452-11e6-9fed-72aa61f092f9.png)

![version](https://cloud.githubusercontent.com/assets/23297497/20040169/e05a3d26-a452-11e6-85ce-88dd5b944a5f.png)

**Comment by alexesprit** [comment]
Hi!

Can you please test the latest version? You can install it as [an unpacked extension](https://github.com/david-sabata/web-scrobbler#unpacked-extension). I've checked scrobbling from RMF right now, works fine on the latest version,

**Comment by InsaneLastFM** [comment]
Do you mean 1.58 version?

**Comment by alexesprit** [comment]
No, I mean the latest version from this repository, which is not released yet, but contains the RMF fix.

**Comment by InsaneLastFM** [comment]
Could you tell me step by step how to do it? I tried, but I think I did something wrong, because it still isn't working...

**Comment by alexesprit** [comment]
1. Download https://github.com/david-sabata/web-scrobbler/archive/master.zip and unpack it in to any place:
![image](https://cloud.githubusercontent.com/assets/1119267/20040683/b6fba022-a46c-11e6-8ece-68a3a36c678c.png)
2. Go to `chrome://extensions/` and enable developer mode:
![image](https://cloud.githubusercontent.com/assets/1119267/20040668/7be9a4e8-a46c-11e6-8c4a-77d31b7468c9.png)
3. Click on 'Load unpacked extension...' button and select the unpacked folder:
![image](https://cloud.githubusercontent.com/assets/1119267/20040673/9b0a47ce-a46c-11e6-8a97-3b3f3caddf89.png)

Don't forget to disable the extension from Web store first!

If you still cannot install it, just wait for next release. :)

**Comment by InsaneLastFM** [comment]
Thank you very much, Alex! It's working, but this extension needs to stay in developer mode to work. But plus is that it's working for all (I think) RMF station, not only for few (I had to enter path for each station earlier...). Thanks! And one more question (I'm wonder :) ) - when will be next release? ;)

Best regards from Poland :)
Insane_pl

**Comment by inverse** [comment]
Going to close this as fixed.

**Comment by alexesprit** [comment]
Good to hear it's working for you!

> when will be next release?

No one knows that :)

**Comment by inverse** [comment]
Actually I'll leave this open until the next release for reference. 

Perhaps we should turn your detailed instructions into a wiki page ;)

**Comment by alexesprit** [comment]
It's not mine - I took it from https://github.com/david-sabata/web-scrobbler/issues/1038#issuecomment-240474600 :D

But I agree it should be placed into a wiki.

**Comment by alexesprit** [comment]
@InsaneLastFM RMF scrobbling should works fine in recently released version. Can you please check that?

**Comment by InsaneLastFM** [comment]
Hi Alex! Do you mean 1.59? I will check :)

**Comment by InsaneLastFM** [comment]
Sooo, Dear Aleksey, I don't have good news. It's not working. I will test it precisely and I will write you list of things which are NOK (not OK) :) I need to compare 1.58 (from your link) and 1.59.

**Comment by InsaneLastFM** [comment]
OK, it's working. Just in the beginning I don't have this: 
![1](https://cloud.githubusercontent.com/assets/23297497/20246029/5ba7d690-a9ae-11e6-8503-5914c7cb5203.png)
... and I didn't see songs on my profile. Very slowly it regonized songs or didn't recognized.... but I turned on 1.58 and after 1.59 one more time and it is OK. It recognized songs, send information to my profile, I don't need enter path for each station separately... It's working fine :)

**Comment by alexesprit** [comment]
@InsaneLastFM could you please close the issue as resolved?

**Comment by InsaneLastFM** [comment]
Resolved :)
