### ISSUE TITLE
Indieshuffle scrobbling broken

### ISSUE THREAD

**Issue by nassia** [david-sabata/web-scrobbler#1135]
Looks like scrobbling for Indieshuffle.com is broken. The extension says "Play some music to get started" while it is in fact playing. Indieshuffle is checked in the options. Just thought I'd let you know.

**Comment by alexesprit** [comment]
This is known issue. Will be fixed in next release.

**Comment by alexesprit** [comment]
@nassia the new version is released. Can you please check if scrobbling works fine?

**Comment by nassia** [comment]
Hi Alexey! It works again for me. Thanks for fixing!
