### ISSUE TITLE
support for http://demiba.com/

### ISSUE THREAD

**Issue by alimoeeny** [david-sabata/web-scrobbler#115]
I was wondering if you can add support for http://demiba.com/
Or you can point me to what I need to do to, and I'll fork and make the changes and submit a pull request back.

**Comment by galeksandrp** [comment]
Site is nonexist, domain is expired.

**Comment by janbaykara** [comment]
Indeed, probably close this @david-sabata

**Comment by david-sabata** [comment]
Sry, overlooked
