### ISSUE TITLE
Support for RockRadio

### ISSUE THREAD

**Issue by aqzina** [david-sabata/web-scrobbler#1151]
Hi,

RockRadio is from the same network as JazzRadio, which is supported already by the extension. Could you also add the other sister sites as well?

http://www.classicalradio.com
http://www.radiotunes.com
http://www.rockradio.com

Thanks a lot!

**Comment by alexesprit** [comment]
We don't know how to scrobble the classical music properly: #857.

Also, RadioTunes is already supported, but I didn't know they all have the same website layout. Thanks for a hint!

**Comment by aqzina** [comment]
What about RockRadio then?

**Comment by alexesprit** [comment]
Proposed in #1155.

**Comment by inverse** [comment]
RockRadio will be in the next release :+1:
