### ISSUE TITLE
Vk.com: suddenly stops scrobbling

### ISSUE THREAD

**Issue by Silentor** [david-sabata/web-scrobbler#1162]
Hello! Today I saw thats scrobbling stop working on Vk.com. I'm using Google Chrome 54.0.2840.99 m.

**Comment by alexesprit** [comment]
It's because of internal VK changes. Will be fixed in next release.

You can install [this](https://github.com/alexesprit/web-scrobbler/archive/vk-fix.zip) version as a temporary solution.

**Comment by IRainman** [comment]
@alexesprit please update firefox version ;)

**Comment by alexesprit** [comment]
@IRainman updated.

**Comment by ironnerve** [comment]
When is the next release coming?
