### ISSUE TITLE
Enabling scrobbling on musicforprogramming.net

### ISSUE THREAD

**Issue by sergeychibunin** [david-sabata/web-scrobbler#1171]
Hello.
I guess many people listen this resource.

**Comment by inverse** [comment]
This would be a hard one to support since there is no clear indication when tracks change due to the nature of the mixes. If they provided this data it would be possible.

**Comment by f1u77y** [comment]
If last.fm api was availible directly from content scripts, we could fetch the song info(including duration) in some way but as for now I can suggest nothing

**Comment by sergeychibunin** [comment]
May be later this site change its structure. Thanks all.
