### ISSUE TITLE
Google Music November 2016 UI Update Broke Scrobbling

### ISSUE THREAD

**Issue by FunkeDope** [david-sabata/web-scrobbler#1172]
The new layout of Google Music appears to have broke something.

![image](https://cloud.githubusercontent.com/assets/1842453/20532912/afc481b8-b0a9-11e6-94ca-87f1a0debc88.png)

**Comment by alexesprit** [comment]
It's working for me now. Please provide us [the extension logs](https://github.com/david-sabata/web-scrobbler/wiki/How-to-debug-the-extension).

**Comment by alexesprit** [comment]
I accidentally found a way how to broke the Google Music scrobbling:
1. Open Google Music and play some song.
2. Refresh the current tab where actually Google Music is opened.
3. Play some music again (ooops, it doesn't work).

The console output of content scripts is:
```
Web Scrobbler: Connector.playerSelector is empty. The current connector is expected to manually detect state changes
starter.js:14 Web Scrobbler: Starter already loaded
```

**Comment by FunkeDope** [comment]
It does appear to be working for me now as well. I just cleared my cache.

**Comment by alexesprit** [comment]
> It does appear to be working for me now as well. I just cleared my cache.

So, the issue should be closed since it's resolved, right?
