### ISSUE TITLE
Just downloaded, won't work with iheartradio

### ISSUE THREAD

**Issue by oblivioushippie** [david-sabata/web-scrobbler#1179]
The extension is on and everything but won't scrobble. The message said to report it here.

**Comment by alexesprit** [comment]
[How to debug extensions.](https://github.com/david-sabata/web-scrobbler/wiki/How-to-debug-the-extension)

**Comment by alexesprit** [comment]
Also, 'Get stations' button on the main page doesn't work for me, so I cannot check if scrobbling is really broken.

**Comment by inverse** [comment]
Should be fixed in the next release :+1:
