### ISSUE TITLE
Authentication button doesn't do anything

### ISSUE THREAD

**Issue by daanddaan** [david-sabata/web-scrobbler#1182]
Can't connect it to my last.fm :( Sad

**Comment by alexesprit** [comment]
Works fine for me.

[How to debug extensions.](https://github.com/david-sabata/web-scrobbler/wiki/How-to-debug-the-extension)

**Comment by f1u77y** [comment]
Haven't you disabled notifications?

**Comment by alexesprit** [comment]
I see only two ways how to break notifications:
1. While using the extension on Opera and Win10, disable notifications in Win10 settings.
2. It's just Last.fm fault; it cannot get auth URL.

Switching notifications off in the extension settings doesn't disable auth notifications.

**Comment by daanddaan** [comment]
its fixed, thanks!

**Comment by alexesprit** [comment]
@daanddaan could you close the issue?
