### ISSUE TITLE
Slacker Scrobbling Issue

### ISSUE THREAD

**Issue by kmehlin** [david-sabata/web-scrobbler#1184]
Went back to listening to Slacker for the first time in a long time today. It seems like the extension isn't recognizing the Slacker page, just stays on the question mark.

**Comment by alexesprit** [comment]
Fixed the issue in https://github.com/alexesprit/web-scrobbler/tree/fix-slacker. Would be great if you check it.

**Comment by kmehlin** [comment]
Fixed. Many thanks!
