### ISSUE TITLE
mix-cloud beta dosen't scrobble

### ISSUE THREAD

**Issue by avgurf** [david-sabata/web-scrobbler#1190]
mix-cloud had started an open beta for their [new version](https://beta.mixcloud.com) the scrabbler seems to miss the playback

**Comment by alexesprit** [comment]
@avgurf the URL you provided redirects to mixcloud.com, not beta one. Is there something I should to do to get access to the beta version?

**Comment by avgurf** [comment]
you need to sign to it, It had appeared on my homepage. I guess you can contact support and ask for it, kinda strange they didn't provide a developer preview...

**Comment by inverse** [comment]
It's not available to me even when signed in.
