### ISSUE TITLE
YouTube and iTunes...

### ISSUE THREAD

**Issue by Angelfirenze01** [david-sabata/web-scrobbler#1192]
I've logged into two separate profiles and am still finding that my Last.fm account isn't scrobbling properly. Do I need to execute a new version?

**Comment by alexesprit** [comment]
[How to debug extensions.](https://github.com/david-sabata/web-scrobbler/wiki/How-to-debug-the-extension)

**Comment by HZNetworks** [comment]
YouTube is working for me
