### ISSUE TITLE
Issue with vk scrobbling

### ISSUE THREAD

**Issue by sigorilla** [david-sabata/web-scrobbler#1193]
I found js error in console when I play music on vk.com

Error is on [this line](https://github.com/david-sabata/web-scrobbler/blob/master/connectors/v2/vk.js#L47):

```
Uncaught TypeError: Cannot read property '3' of null
```

It seems that on [this line](https://github.com/david-sabata/web-scrobbler/blob/master/connectors/v2/vk.js#L35) should be `audio_v20_track` instead of `audio_v10_track`.

Proof:
![image](https://cloud.githubusercontent.com/assets/1208639/21041497/6d2b2e96-bdfc-11e6-92e5-b5fb4cf2afd9.png)

**Comment by alexesprit** [comment]
Hi!

It's already known issue, and it's fixed in #1164.
