### ISSUE TITLE
Temporarily disable scrobbling

### ISSUE THREAD

**Issue by santturin** [david-sabata/web-scrobbler#1196]
Hi,

I'm using Chrome 55.0.2883.87 and I am not able to temporarily disable scrobbling in youtube.
Clicking the scobbler icon just opens an infobox of the song. Am I doing something wrong or is this a bug?
![image](https://cloud.githubusercontent.com/assets/24542384/21134990/c81be4b0-c128-11e6-93b4-bd9895a963a2.png)

Santtu

**Comment by alexesprit** [comment]
It's by design. The old behaviour was used before that popup was implemented.

**Comment by santturin** [comment]
Well how do I temporarily disable scrobbling or is possible anymore?

**Comment by santturin** [comment]
Well how do I temporarily disable scrobbling or is possible anymore?

**Comment by alexesprit** [comment]
There's a list of all supported services in the extension preferences, where you can disable any service.

**Comment by santturin** [comment]
So this is not supported anymore?

![image](https://cloud.githubusercontent.com/assets/24542384/21137970/aad0e1f6-c134-11e6-81f7-2bd074aecce1.png)

**Comment by alexesprit** [comment]
Yes, you're right. This feature is not supported anymore.

**Comment by santturin** [comment]
That is a shame. It was very useful

**Comment by janbaykara** [comment]
I always planned to add this feature to #719. I might get round to it at some point, but if someone else wants to carry on the good work, go for it.

**Comment by alexesprit** [comment]
Now the extension allows to disable connectors via page action context menu.
