### ISSUE TITLE
Last fm

### ISSUE THREAD

**Issue by pink999** [david-sabata/web-scrobbler#1204]
How do we get a default image for artists (none @last fm) on Youtube & Soundcloud ? Great job otherwise, bandcamp scrobbling is flawless. Thx bri.

**Comment by inverse** [comment]
If I am not mistaken they are from musicbrainz or last.fm itself. I don't think we have configured the track art directly on those ones.

**Comment by pink999** [comment]
Thanks for the fast reply.

I thought such, so for unknown reasons they will not implement a default
image for tracks.

Have a great holiday everyone.

**Comment by pink999** [comment]
this beta is a huge disappointment for many of us)))). Have a great week !

You guys are swell :)
