### ISSUE TITLE
Duration priority

### ISSUE THREAD

**Issue by alexesprit** [david-sabata/web-scrobbler#1206]
Is there a reason to prefer processed duration (i.e. provided by Last.fm) to parsed one?

Some tracks have different versions, which have different durations, so Last.fm sometimes can return wrong result (see [this log](http://pastebin.com/xxtare3E) as an example).

**Comment by inverse** [comment]
@david-sabata might be able to shed some light on that. I can imagine if for whatever reason the connector failed to parse some duration it would fall back to last.fm.

**Comment by alexesprit** [comment]
> I can imagine if for whatever reason the connector failed to parse some duration it should fall back to last.fm.

Perhaps, I misunderstood you, but there's no fallback from parsed data to Last.fm one:
```js
/**
 * Returns song's processed or parsed duration in seconds
 */
song.getDuration = function() {
	return this.processed.duration || this.parsed.duration || null;
};
```

**Comment by david-sabata** [comment]
There could have been some historical reason for that, but it certainly makes more sense to prefer parsed duration

**Comment by alexesprit** [comment]
Priority is changed in 4dd0e6eb13e59379431706137a2408f40c3de72e.
