### ISSUE TITLE
Amazon Alexa not scrobbling albums

### ISSUE THREAD

**Issue by werewegian** [david-sabata/web-scrobbler#1208]
I'm using the UK version of Alexa and have added the pattern to the UK Amazon Echo page *://alexa.amazon.co.uk/spa/index.html#player but although the track and artist are scrobbling, the album isn't. Not a big issue but it means my recent album charts are emptying.

**Comment by werewegian** [comment]
I'm not too familiar but I inspected the element. The div is div.d-sub-text-2.d-truncate, the classname 
"d-sub-text-2 d-truncate" and the innerHTML contains the album name. Does that help?

**Comment by alexesprit** [comment]
I added album selector to Alexa connector. Can you please test it and say if it's helped or not? https://github.com/alexesprit/web-scrobbler/archive/alexa-album.zip
If yout don't know how to install extensions from zip file, please read [this howto](https://github.com/david-sabata/web-scrobbler#unpacked-extension).

**Comment by werewegian** [comment]
Took me a while to work it all out but the answer is yes, the album name is now associated with the scrobble. Thanks.

**Comment by alexesprit** [comment]
These changes will be available in the next release. Thanks for help!
