### ISSUE TITLE
iHeartRadio Connector not working custom station

### ISSUE THREAD

**Issue by andrewc2** [david-sabata/web-scrobbler#1211]
Tab 891: created controller for connector: {"label":"iHeartRadio","matches":["*://*.iheart.com/*"],"js":["connectors/v2/iheartradio.js"],"version":2}
4inject.js:121 -- subsequent ajax navigation, the scripts are already injected

I've also tried a live station and it's not scrobbling that either.

**Comment by andrewc2** [comment]
chrome.storage.local = {"Core":{"appVersion":"1.60.2"},"LastFM":{"sessionID":null,"token":null}}

I'm getting a storage error when I install the extension after disabling the main release.

Notification onClicked: 2d60b370-e5f4-47d6-8bcb-118aa6c68327
inject.js:79 -- loaded for the first time, injecting the scripts
inject.js:104 	injecting vendor/jquery-2.1.0.min.js
inject.js:104 	injecting vendor/underscore-min.js
inject.js:104 	injecting core/content/testReporter.js
inject.js:104 	injecting core/content/reactor.js
inject.js:104 	injecting core/content/filter.js
inject.js:104 	injecting core/content/connector.js
inject.js:104 	injecting connectors/v2/iheartradio.js
inject.js:104 	injecting core/content/starter.js
controller.js:329 Tab 526: created controller for connector: {"label":"iHeartRadio","matches":["*://*.iheart.com/*"],"js":["connectors/v2/iheartradio.js"],"version":2}

It's working for live stations now, but it isn't working for custom stations.

**Comment by alexesprit** [comment]
> I'm getting a storage error when I install the extension after disabling the main release.

What does 'storage error' mean? If you're talking about 'chrome.storage.local...` text, this is not an error.

> But, It's working for live stations now, but it isn't working for custom stations.

Ok, I'll look into that. I checked only live stations that were broken too for me.

**Comment by alexesprit** [comment]
@andrewc2 I didn't find custom station, but I noticed 'My Stations' (that propably are custom stations) and 'Artist Radio' are broken too. I fixed them, and now all stations and radio should work fine.

Could you check scrobbling again? The updated extension is available at the same URL.

**Comment by andrewc2** [comment]
Yeah that was what I meant by custom station!

Perfect, it's working! Thanks!

**Comment by alexesprit** [comment]
Thank you too!

Fixed in c96fb9472f9d73e2fb9716b0e93179dbdb8a965a and will be avaiilable in the next release.
