### ISSUE TITLE
RadioPlayer for non BBC stations

### ISSUE THREAD

**Issue by mvinaround** [david-sabata/web-scrobbler#1213]
Please add back the RadioPlayer sites like Heart and Kiss and others listed on http://www.radioplayer.co.uk/

**Comment by mvinaround** [comment]
possibly because "radioplayer.js' is now radioplayer.min.js

**Comment by inverse** [comment]
Correct me if I am wrong. Radioplayer just links to external sites for playing radio (in popup tabs). We would have to add support for these stations individually. 

What ones do you feel you're missing?

**Comment by mvinaround** [comment]
If it helps, I could make a list of URLs to most of the popular radio
player stations... Give me an example of the format I'm guessing JSON and I
can help you out

**Comment by inverse** [comment]
I think it's more we would have to implement one for each of the stations. What ones do you want implemented? 

Although from looking at the two you mentioned I am not sure how we would go about implementing connectors for them. They don't seem to show track data and thus not scrobblable

**Comment by mvinaround** [comment]
Sorry, been away for a while, Yeah the ones I listed above show it providing there's not a set dj on doing a show... for example Heart use a span with the class "song-text" to display the track playing... 

![image](https://cloud.githubusercontent.com/assets/9600680/24228118/062e1216-0f6a-11e7-9f30-071a1a4cdd24.png)
![image](https://cloud.githubusercontent.com/assets/9600680/24228134/2d60b0d2-0f6a-11e7-8112-e2c3976839c8.png)

**Comment by mvinaround** [comment]
Ok, so i pulled the source for this down and have managed to get it working for most of the radio player sites...

![image](https://cloud.githubusercontent.com/assets/9600680/24230128/49f24372-0f75-11e7-9742-8264a2c9179b.png)

**Comment by alexesprit** [comment]
Added in 9339f71b8ac37b02e80787aa64f5f1b1c1052e91.
