### ISSUE TITLE
Album and duration are never included in "updatenowplaying" request

### ISSUE THREAD

**Issue by namoscato** [david-sabata/web-scrobbler#1216]

**Comment by alexesprit** [comment]
I noticed that too.

Have you any information about how duration that specified in 'updateNowPlaying' request is used by Last.fm?

**Comment by namoscato** [comment]
@alexesprit, per their [documentation](http://www.last.fm/api/show/track.updateNowPlaying), it just the "length of the track in seconds" (as opposed to the current duration, for example).
