### ISSUE TITLE
Its not scrobbling anything on the youtube

### ISSUE THREAD

**Issue by sixledg3r** [david-sabata/web-scrobbler#1219]
![2017-01-09](https://cloud.githubusercontent.com/assets/25007551/21766928/7413ae26-d671-11e6-92e9-39ac5d3c3ba8.png)

**Comment by sixledg3r** [comment]
![2017-01-09 1](https://cloud.githubusercontent.com/assets/25007551/21766958/9ff1bef2-d671-11e6-88cc-240bb55da71d.png)

**Comment by sixledg3r** [comment]
anyways I would love to get help with this...because I feel like Im the only one with this problem

**Comment by alexesprit** [comment]
@sixledg3r

You're not only one who experiences this issue. I noticed some people also reported problems with Youtube scrobbling in Chrome Web Store comments.

To understand why it's broken, we need some logs. Here are steps how to get them:
1. Run Chrome, open Youtube and try to play some video.
2. Press Ctrl-Shift-I, then select 'Console' tab.
3. Copy all logs and paste on some pastebin service.
4. Get logs by using this howto: [How to debug extensions.](https://github.com/david-sabata/web-scrobbler/wiki/How-to-debug-the-extension)
5. Paste the second log too.

**Comment by sixledg3r** [comment]
![2017-01-10](https://cloud.githubusercontent.com/assets/25007551/21790882/916907fa-d6df-11e6-825b-5d8526a17ddd.png)

Im not sure what to do next thou...

**Comment by sixledg3r** [comment]
![2017-01-10 1](https://cloud.githubusercontent.com/assets/25007551/21790918/c60773ac-d6df-11e6-9ef2-e864b47a945a.png)

here one more

**Comment by alexesprit** [comment]
@sixledg3r  could you please install https://github.com/alexesprit/web-scrobbler/archive/youtube-fix.zip as an unpacked extension and check if it works?

If that updated extension doesn't work, could you install this one: https://github.com/david-sabata/web-scrobbler/archive/236b42c45a955018ae2cb038afff7372fe3bffae.zip?

**Comment by sixledg3r** [comment]
So I installed the first one and it didnt work, than I installed the second one, nothing changed...here you go...
![2017-01-10 2](https://cloud.githubusercontent.com/assets/25007551/21797607/50b1a808-d710-11e6-8600-5b813d48d0ae.png)
![2017-01-10 3](https://cloud.githubusercontent.com/assets/25007551/21797608/52c5b59e-d710-11e6-9431-36684df18505.png)

**Comment by alexesprit** [comment]
You're running them all at the same time. Please disable other extensions while testing each one.

**Comment by sixledg3r** [comment]
I actually tried at first run them one by one, but I thought that I did that wrong and I ran them all at once later, they didnt work the either way.
![lxtnc90 - imgur](https://cloud.githubusercontent.com/assets/25007551/21862467/a0092122-d839-11e6-98e6-274c9caaea26.png)

![vtw5vui - imgur](https://cloud.githubusercontent.com/assets/25007551/21862366/2c961e16-d839-11e6-866d-309eda87849a.png)

**Comment by sixledg3r** [comment]
btw I even installed a clean copy of Windows today, still nothing.

**Comment by alexesprit** [comment]
That's odd. Have you any installed extensions that affect Youtube website?

**Comment by sixledg3r** [comment]
only thing installed that affects Youtube is adblock, but I had no problems with it before...
since that "new Youtube" update came it stopped scrobbling.
I tried disabling all the extensions and still nothing.

**Comment by alexesprit** [comment]
What is the "new Youtube"?

**Comment by sixledg3r** [comment]
well I meant when the Youtube changed their interface and some other minor stuff

**Comment by alexesprit** [comment]
@sixledg3r do you know to how switch to that new interface?

**Comment by sixledg3r** [comment]
@alexesprit so I just logged out of my account on gmail and yt because I have messages on my other account and guess what?
It started scrobbling again, but as soon is a logged in to my primary account it stopped again.

**Comment by sixledg3r** [comment]
do you have any ideas what could be the problem?

**Comment by alexesprit** [comment]
@sixledg3r Looks like Youtube were turned on the new version of the website for your primary account.
I don't know how to fix the Youtube scrobbling if we don't know how to switch on the new version of the website by ourselves.

Could you provide a saved Youtube page (where are the 'new design' is), and I'll try to inspect it and fix the issue.

**Comment by sixledg3r** [comment]
Hi, again, I have been able to disable the new design after finding out that scrobbler works on my other accounts...and now by disabling it, the scrobbler started to work again...so I guess the new design really is the problem here.
btw here is the prt scr of the new design
http://imgur.com/a/V3A9G

**Comment by alexesprit** [comment]
@sixledg3r Unfortunately, screenshots have no information which can help to fix the scrobbling. That's why I asked for a saved page with video player (you still can do it if you're instresting in resolving the issue by pressing Ctrl+S and saving the page).

**Comment by sixledg3r** [comment]
I just found out that you can actually do it yourself by clicking "test new features" at bottom of the YT page...here is the screenshot, you can see it here http://imgur.com/a/oYHqA 
can i send you the saved page on your mail, it wont upload here... ( sorry I missread what you wrote before, so thats why I printscreened instead ).

**Comment by sixledg3r** [comment]
sorry I accidentally clicked "close the issue"...anyways will you give me your email so I can send you files there?

**Comment by alexesprit** [comment]
I enabled all features on the Youtube options page, still works.

My e-mail is displayed in my GitHub profile, Feel free to mail me a message.

**Comment by sixledg3r** [comment]
not the account features, but this features, it was enabled on my account by it self http://imgur.com/a/s6AFJ ...and I pressed "the escape" icon which was showed to me in the right bottom
corner of the YT page, and it said something like "bring the old youtube back". 
and now my scrobbler works again just fine :)

**Comment by sixledg3r** [comment]
btw I sent you the email...

**Comment by alexesprit** [comment]
@sixledg3r Could you test this version? https://github.com/alexesprit/web-scrobbler/archive/youtube-test.zip

I'm not sure if it works, but it should. (I also figured out why there were no Youtube logs in the console. Should be improved.).

**Comment by sixledg3r** [comment]
@alexesprit nah, this one also doesnt work with the new YT and it didnt even recognize the song on the old youtube...
anyways my problem is resolved for now, the first one (default from google chrome store ) works just fine with the old youtube...
you should do some testing with the new youtube though, cuz they might set it as default in the near future...
good luck and thanks for your time :)

**Comment by sixledg3r** [comment]
@alexesprit nah, this one also doesnt work with the new YT and it didnt even recognize the song on the old youtube...
anyways my problem is resolved for now, the first one (default from google chrome store ) works just fine with the old youtube...
you should do some testing with the new youtube though, cuz they might set it as default in the near future...
good luck and thanks for your time :)

**Comment by baowiak** [comment]
@sixledg3r - Hi, I've got the same issue as you, but no matter how hard I try, I cannot find the "escape button" you've mentioned. Could you be so kind and attach a screenshoot with the icon marked? (while being on youtube.com/testtube page). Thank you very much in advance!

**Comment by aphetica** [comment]
@baowiak The escape button is located on the bottom right of your youtube home page.

![youtubeexit](https://cloud.githubusercontent.com/assets/25377364/22355788/df3ed856-e3fa-11e6-8c9a-0251fc14b366.png)

**Comment by aphetica** [comment]
@alexesprit I am experiencing this issue also. Here are my logs. Let me know if you need anything else.

[http://pastebin.com/2KkfXVyG](url)
[http://pastebin.com/gtbwbHSW](url)

**Comment by sixledg3r** [comment]
sorry @baowiak  I was not online till now...ye just use the escape button as @aphetica showed in his/her printscreen...

**Comment by alexesprit** [comment]
@aphetica I need to know how to enable this new Youtube.

**Comment by baowiak** [comment]
@aphetica @sixledg3r  Thank you very much for your replies, however, my YT page just doesn't seem to have such icon. Guess I will simply wait for some scrobbler updates.

**Comment by sixledg3r** [comment]
@baowiak oh sorry man that it didnt work for you...
anyways @alexesprit I am not sure how you still dont know how to enable this new youtube feature, even thou I provided screenshots and instructions on how to enable it...
So here you go again, this time I marked it with red color where to click, I hope you will manage to solve it now.
At the bottom of the youtube tab click on "Test new features", new tab will open where you need to click on "Try new YouTube".
 Just follow the instructions and thats it.
![yt 1](https://cloud.githubusercontent.com/assets/25007551/22494164/7b902226-e835-11e6-9d6e-6cdc286e7334.png)
![yt 2](https://cloud.githubusercontent.com/assets/25007551/22494166/7f23945e-e835-11e6-9476-e0e361e0cdd8.png)

**Comment by alexesprit** [comment]
@sixledg3r I have no "A fresh new look for youtube.com" item on the page, that's why I didn't find how to enable the new layout.
