### ISSUE TITLE
Some titles on bandcamp cannot be scrobbled

### ISSUE THREAD

**Issue by JanePeppler** [david-sabata/web-scrobbler#1220]
Hello, new user here. I have a small record label and am trying to scrobble our releases. Some of them work  (for instance this one: https://mappamundi1.bandcamp.com/album/cabaret-warsaw-yiddish-polish-hits-of-the-1920s-1930s )
and some of them are greyed out
(for instance this one: http://skylark2.com/album/some-assembly-required)

can you tell me why? and how can I fix this? Thanks

**Comment by inverse** [comment]
The second link you provided is hosted on a custom domain and as such we cannot know if it's bandcamp or not. To work around this you can in the options configure this to work with custom domains.

@alexesprit Where do you think such documentation should live? IMHO should be in the extension options perhaps?

**Comment by JanePeppler** [comment]
Thanks for your answer! But I don't know where I should enter this information. I am finding this whole process mystifying. Thanks for any pointer how/where to proceed with this. By the way, many artists and labels have configured Bandcamp to use custom domain names so this would help a lot of us.

**Comment by JanePeppler** [comment]
wait, I found it. thanks.

**Comment by alexesprit** [comment]
@inverse yes, I think, the options page is a proper place to keep this documentation. This is a good idea, since that feature is not so obvious, especially for new users. Also, the configuration popup should contain some information about URL patterns (I'm not sure if it's neccessary).

**Comment by JanePeppler** [comment]
As the newbie in question, I say yes, information about URL patterns is helpful. I had to open notepad to copy your example character by character so I could paste it into the options box.

**Comment by alexesprit** [comment]
I guess the issue is resolved, right?
