### ISSUE TITLE
Custom URL patterns

### ISSUE THREAD

**Issue by alexesprit** [david-sabata/web-scrobbler#1222]
Should custom patterns *extend* default ones that are defined in `connectors.js`? 

In current implementation default patterns aren't used if at least one custom pattern is defined by user. I suppose it's made intentionally (and code comment proves that).

I don't use this feature but I was confusing when I tried to use it at first time. I mean if user wants to add a custom pattern to Bandcamp, for example, they should to define default Bandcamp URL patterns too; otherwise the extension won't scrobble tracks from bandcamp.com. That's not obvious behaviour and should be changed/documented/whatever.

I suggest two options:
1. Append custom patterns to default ones.
2. Leave all of it as is, but add default patterns to the configuration popup automatically.

I prefer the first one as the simplest way. The second option requires more changes.

**Comment by inverse** [comment]
IMHO they should extend the default options. Go with the first approach :+1:
