### ISSUE TITLE
Amazon Alexa scrobbling not working

### ISSUE THREAD

**Issue by RadianM** [david-sabata/web-scrobbler#1226]
EXPECTED: (R.e. issue #911)  install the web-scrobbler Chrome Extension from the Web Store and link to my Last.FM account. Browse to "http://alexa.amazon.co.uk/spa/index.html?#player" and have "Now Playing" content scrobble to last.fm

ACTUAL: The scrobbler icon remains greyed-out indicating that the web page isn't recognized.

Possibly related (?) the Spotify web player isn't scrobbling either - however the icon is red when on this page - but the message "Play some music to get started" appears when clicking it. Could it be the connector problem(s) are to do with different URL's for UK users?

TRIED: Re-activating last.fm, no dice. Youtube works fine though, so looked at console logs - only activity is seen while using YouTube.  No output for Spotify or Alexa. Looked at "Amazon Echo configuration" option, not exactly sure what is meant by URL pattern but added http://alexa.amazon.co.uk/spa/index.html?#player to no effect.

**Comment by alexesprit** [comment]
> Possibly related (?) the Spotify web player isn't scrobbling either - however the icon is red when on this page - but the message "Play some music to get started" appears when clicking it. Could it be the connector problem(s) are to do with different URL's for UK users?

No, it's not related to Spotify. Spotify scrobbling works fine for me, but some other people reported it doesn't work (see #1217, btw I posted a possible fix for Spotify in that thread).

> Looked at "Amazon Echo configuration" option, not exactly sure what is meant by URL pattern but added http://alexa.amazon.co.uk/spa/index.html?#player to no effect.

Try to add '*://alexa.amazon.co.uk/spa/index.html?player' (w/o quotes) as a custom pattern, it should help.
I tried to open URL you provided, and it redirect to another one which doesn't contain number sign.

**Comment by RadianM** [comment]
Thanks alexesprit, at least I now have Alxea scrobbling which was my main requirement because it's a great work-around for all kinds of Spotify Connect scrobbling issues at the moment.

I couldn't pinpoint exactly what made it work so I set up a whole new environment and last.fm test account...

- Step 1: After installing the chrome extension, linking to last.fm account, and rebooting PC - no connection when on the Alexa "Now Playing" page.
-  Step 2: added URL "http://alexa.amazon.co.uk/spa/index.html?#player" (without quotes) to Amazon Echo configuration. Connector now works.

Not sure why this worked second time around but it may be that I already had the "Now Playing" page open. I advise adding the URL with the Amazon web app closed. I also confirmed that removing the URL prevents the connection from working. Not understanding how this all works, I'm left wondering how the default code identifies the Alexa app. I'm assuming that in other territories the URL will be different.

**Comment by alexesprit** [comment]
@RadianM Glad to hear it's working for you!

Thanks for note about Alexa URL, I didn't know it can be different, but still valid. I extended the URL pattern in the code, so the connector will handle this URL without adding custom patterns.

P.S. If you're intresting in resolving Spotify issues, please visit #1217 issue. I create a test extension package, that should scrobble Spotify tracks, but no one confirmed the fix.

**Comment by greedoe** [comment]
do you need to have the player page open in a browser window for Alexa to scrobble? Seems a bit of a dodgy "workaround" if this is the case.
