### ISSUE TITLE
Amazon Echo not scrobbling album plays

### ISSUE THREAD

**Issue by RadianM** [david-sabata/web-scrobbler#1228]
EXPECTED: Amazon Echo can be asked to play a specific album on Spotify, so scrobbling should be the same as selecting the play widget in the Spotify app - which does add the album play to the last.fm library.

ACTUAL: Individual tracks are scrobbled but no album play is registered.

Possible BONUS: I bet this has been asked before, but if the first track is played, and all the subsequent tracks of an album follow on in sequence - could this also be scrobbled as an album play?

**Comment by alexesprit** [comment]
Unfortunately, I cannot fix this issue. Perhaps, @puthali (as a developer of the connector) could do something.

Btw, feel free to fix it by yourself and propose a PR.

**Comment by namoscato** [comment]
I think this was actually fixed with #1216, which is not released yet. This sort of behavior was what led me down that path. Last.fm does not actually have the concept of "album play", but the lack of album information on the initial "now playing" request prevented track scrobbles from being recorded correctly.

**Comment by RadianM** [comment]
OK, I downloaded from branch master and installed as an "unpacked extension". I'm now getting album plays scrobbled. And the connector picked up alexa.amazon.co.uk without me having to add a custom pattern as per #1226 Brilliant! 
I'd never paid much attention to scrobbling outside the Spotify desktotp client so hadn't really noticed how album scrobbles were counted.

**Comment by alexesprit** [comment]
@RadianM so, the issue is resolved, right?

**Comment by RadianM** [comment]
Yes thanks, I have closed it.
