### ISSUE TITLE
Request: support new Spotify web player

### ISSUE THREAD

**Issue by ftkftw** [david-sabata/web-scrobbler#1229]
Logged into Spotify web player after using the desktop app for a new days, turns out I have been "selected to test" the new web player UI at https://open.spotify.com:

<img width="1748" alt="new spotify ui" src="https://cloud.githubusercontent.com/assets/12530197/22163732/a6e4c1f4-df19-11e6-9314-60b411fca458.png">

**Comment by alexesprit** [comment]
So, how should I enable this new web player?

**Comment by alexesprit** [comment]
So, as I understood, this is just an UI for Spotify Desktop app, right? The Spotify app is able to scrobble tracks by itself. Is there a sense to make a connector for this web UI? Have you any use cases of this?

**Comment by youming-lin** [comment]
> So, as I understood, this is just an UI for Spotify Desktop app, right?
This is a new **web player UI**. I don't know if you have been selected for testing this new UI, but it looks like they are doing A/B testing on the new UI currently:
https://community.spotify.com/t5/Other-Partners-Windows-Phone-etc/New-Web-Player-is-garbage/td-p/1559947

Here is a longer thread: https://community.spotify.com/t5/forums/v3_1/forumtopicpage/board-id/001/page/1/thread-id/172874

>The Spotify app is able to scrobble tracks by itself. Is there a sense to make a connector for this web UI? Have you any use cases of this?
I'm not sure I understand your question. The existing, production-level Spotify web player UI at play.spotify.com also has a built-in scrobbler, yet this extension (which I'm extremely thankful for) also provides a connector for play.spotify.com.

In addition, I poked around my account settings in the new web UI and I have yet to find the option to link it with my lastfm account for scrobbling. It does not appear that the scrobbling feature has made it to the current version of the new UI: I don't know if they will include it in the final version if/when they release this to the general public.

**Comment by ftkftw** [comment]
Oops, sorry I posted with my other account I use for work :)
I'll just post it again with the account I used to start this thread for consistency.


> So, as I understood, this is just an UI for Spotify Desktop app, right?
This is a new **web player UI**. I don't know if you have been selected for testing this new UI, but it looks like they are doing A/B testing on the new UI currently:
https://community.spotify.com/t5/Other-Partners-Windows-Phone-etc/New-Web-Player-is-garbage/td-p/1559947

Here is a longer thread: https://community.spotify.com/t5/forums/v3_1/forumtopicpage/board-id/001/page/1/thread-id/172874

>The Spotify app is able to scrobble tracks by itself. Is there a sense to make a connector for this web UI? Have you any use cases of this?
I'm not sure I understand your question. The existing, production-level Spotify web player UI at play.spotify.com also has a built-in scrobbler, yet this extension (which I'm extremely thankful for) also provides a connector for play.spotify.com.

In addition, I poked around my account settings in the new web UI and I have yet to find the option to link it with my lastfm account for scrobbling. It does not appear that the scrobbling feature has made it to the current version of the new UI: I don't know if they will include it in the final version if/when they release this to the general public.

**Comment by alexesprit** [comment]
> This is a new web player UI. I don't know if you have been selected for testing this new UI, but it looks like they are doing A/B testing on the new UI currently

I didn't select anything, I just opened open.spotify.com and it asks to install desktop application. After installing and starting of it this website was just like web UI for desktop player. That means it doesn't play songs without desktop player. This website looks like on your screenshot, so I decided it's what are you talking about.

> I'm not sure I understand your question. The existing, production-level Spotify web player UI at play.spotify.com also has a built-in scrobbler, yet this extension (which I'm extremely thankful for) also provides a connector for play.spotify.com.

Seems like we're talking about different things. That question makes no sense, if open.spotify.com is web player, and not web UI.

Is anything I should to do to enable the new design?

**Comment by alexesprit** [comment]
Wow, it suddenly started to show me new web player on open.spotify.com.

**Comment by ftkftw** [comment]
I was about to reply, but I guess you found the answer to your question :)

I can take a crack at implementing this if you don't mind it taking some time as I'm new to developing extensions.

**Comment by alexesprit** [comment]
I added an experimental support of new website at https://github.com/alexesprit/web-scrobbler/archive/open-spotify.zip. Should work fine. Could you check that?

**Comment by ftkftw** [comment]
Testing it right now. It knows that a song is playing but is not able to figure out the song. Looks like `track.getInfo` is returning 400 Bad Request for some reason.

Ah I see. The `artist` and `track` query parameters are switched. Flip those two and it should be good.

**Comment by ftkftw** [comment]
I flipped the two selectors in your code and now it's working.

Thanks for the quick implementation!!!!

**Comment by alexesprit** [comment]
Thanks for note. I've already fixed that bug. I also fixed an issue when multiple artists were recognized incorrectly (e.g. 'Blood CommandSavant' instead of 'Blood Command, Savant').

I updated the 'open-spotify' branch; the update is available at the same URL.

**Comment by ftkftw** [comment]
:+1:

Looks good on my end. Looking forward to the next release!
