### ISSUE TITLE
Add Connector for Joy.fm

### ISSUE THREAD

**Issue by TheInfinit3** [david-sabata/web-scrobbler#1236]
I listen to Joy.fm and I am not sure if it possible to create a connector for it as it's a radio station. They do broadcast the author name and name of the song, so if it's possible, that would be great!

https://myradiomatic.com/player/joyfm/player.htm

Thanks!

**Comment by alexesprit** [comment]
Should be available in the next release. Check the extension from the latest master branch if you want to scrobble from Joy right now. :)

**Comment by TheInfinit3** [comment]
Thanks man!
