### ISSUE TITLE
Soundcloud Playlist (Scrobbling playlist name instead of the song Title)

### ISSUE THREAD

**Issue by redelpedron** [david-sabata/web-scrobbler#1238]
![soundcloud](https://cloud.githubusercontent.com/assets/5410887/22679475/82e81ef4-ed3d-11e6-9a34-62c8dbe204e1.png)

**Comment by alexesprit** [comment]
Could you provide a URL to that songs?

**Comment by redelpedron** [comment]
https://soundcloud.com/garoadmusic/sets/va-11-hall-a-prologue-ost

**Comment by inverse** [comment]
Strange - it's scrobbling for me fine with that URL. Well by fine I mean:


![image](https://cloud.githubusercontent.com/assets/713525/22691538/3bbaf026-ed3b-11e6-80c0-25111beab111.png)

**Comment by redelpedron** [comment]
My bad it seems that due to the length of the Album or Playlist name trimmed the entire track information.

Thanks
