### ISSUE TITLE
Youtube album scrobbling 

### ISSUE THREAD

**Issue by globularplains** [david-sabata/web-scrobbler#1239]
hey sorry but is there a feature in place which allows me to scrobble entire albums? as i'm sure you're aware there are many people who upload albums in their entirety to youtube with helpful timestamps in place and as an avid user of your app it annoys me I can only access one track from the possible over 10 song album.
thank you

### Steps to Reproduce (for bugs)

1.  
2.  
3.  

### Steps for resolving the issue

- [ ] Reauthenticate on Last.fm

- [ ] Try to use unpacked extension from latest master

- [ ] Check other issues for duplicates

### Environment

* Version used:
* Browser Name and version:

**Comment by alexesprit** [comment]
Duplicate #122.

There's #755, but it's too outdated.
