### ISSUE TITLE
Pandora.com has a new site layout, since reloading the new site scrobbling stopped working

### ISSUE THREAD

**Issue by ufjrhrjcicjfj** [david-sabata/web-scrobbler#1240]
### Expected Behavior
logging into pandora.com turns the AS symbol green, notifications are generated and last.fm records a scrobble for each song played (this worked yesterday)

### Current Behavior
logging onto pandora site the scrobbler recognizes pandora.com but doesn't turn green when music is playing and does not scrobble songs. no notifications are generated

### Possible Solution
 reason: pandora can't leave anything alone and changes things just to have something to do. 
 

### Steps to Reproduce (for bugs)

1.  Tab 17: created controller for connector: {"label":"Pandora","matches":["*://www.pandora.com/*"],"js":["connectors/v2/pandora.js"],"version":2}
2.  
3.  

### Steps for resolving the issue

- [ DONE ] Reauthenticate on Last.fm

- [ I HAVE NO IDEA HOW TO DO THIS] Try to use unpacked extension from latest master

- [CHECKED] Check other issues for duplicates

### Environment

* Version used:1.60.2
* Browser Name and version: CHROME 56.0.2924.87 (Official Build) (64-bit)

**Comment by alexesprit** [comment]
It's known issue and is already fixed. The update will be available in the next release.

P.S. You can use [this HOWTO](https://github.com/david-sabata/web-scrobbler#unpacked-extension) to install the extension from the latest master to make sure scrobbing works fine.

**Comment by ufjrhrjcicjfj** [comment]
alexesprit, thank you for the response, i'll try the howto i just saw this problem this morning.

**Comment by ufjrhrjcicjfj** [comment]
Working perfectly, thank you for your patience.

**Comment by Blasman** [comment]
I followed these instructions and it works now as well. I just wanted to say thanks!

**Comment by alexesprit** [comment]
I'd say the latest release from Chrome Web Store scrobbles Pandora fine.
