### ISSUE TITLE
Scrobbler doesn't detect replays on youtube

### ISSUE THREAD

**Issue by whatisthiswtf** [david-sabata/web-scrobbler#1241]
Just what the title says. When I click the play button, it doesn't scrobble the song again.
### Expected Behavior

It should scrobble the song again if at least the predefined threshold for a scrobble was reached without moving the play slider (I forget what it's called) or more simply if the play button was clicked again after the song ended. It can also check if the 'loop' option is checked which comes up if you right-click the player. This might change in the back-end if Google ends up deprecating flash from youtube (as they promised they will generally with Chrome this coming March I think)  

### Current Behavior

Song only scrobbles once unless the page is refreshed. Also, I'm not sure what the behavior is if an ad is played on first load, refresh, or simply re-play/loop.

### Possible Solution

See 'Expected Behavior'.

### Steps to Reproduce (for bugs)

See 'Current Behavior'.

### Context

See 'Current Behavior'.

### Environment

* Version used: 1.60.2
* Browser Name and version: Google Chrome Stable 56.0.2924.87 (64-bit) Debian Linux

**Comment by alexesprit** [comment]
@whatisthiswtf Thanks for reporting the issue!

Are you experiencing this issue all the time or just in certain cases? I noticed some time ago Youtube connector returns zero duration of now playing song in certain cases. This could break the repeat mechanism. 

I made the Youtube connector to return zero duration and reproduced the issue.

**Comment by whatisthiswtf** [comment]
@alexesprit You are right. I tried with another song and clicking on the play button, pressing the space bar with player active, and selecting loop all work fine.

**Comment by alexesprit** [comment]
@whatisthiswtf I added a temporary workaround in https://github.com/alexesprit/web-scrobbler/archive/youtube-repeat-fix.zip. Would be great if you test this version and confirm if the issue is fixed. 

If you don't know how to install extensions from a zip file, please use [this howto][1] to do that.

[1]: https://github.com/david-sabata/web-scrobbler#unpacked-extension

**Comment by alexesprit** [comment]
@whatisthiswtf I fixed this issue in the latest master. Now Web scrobbler should repeat all songs on Youtube. Please install the extension as unpacked one and confirm the fix.

**Comment by whatisthiswtf** [comment]
@alexesprit Nice! I'm testing it now. Update soon...

**Comment by whatisthiswtf** [comment]
@alexesprit The song scrobbles now on loop but sometimes doesn't scrobble on play or pressing the space-bar. 

I was also on my last.fm page at the same time and noticed that for the latter cases, sometimes the scrobbler would submit play data and sometimes it wouldn't. Or, that a previous scrobble would show up while I'm scrobbling the next play of the song. In total, I had played the song maybe 7 times but it's showed up only 5 times.

But, now the scrobbler is picking up multiple plays in general which is good.

**Comment by alexesprit** [comment]
@whatisthiswtf did you tested the extension from the master or from zip file?

**Comment by whatisthiswtf** [comment]
@alexesprit From the zip file.

**Comment by alexesprit** [comment]
@whatisthiswtf Please test the extension from the latest master, it's should scrobble repeated songs better.

**Comment by whatisthiswtf** [comment]
@alexesprit Ok I will report back in some time. Maybe a day or two.

**Comment by whatisthiswtf** [comment]
@alexesprit Everything seems to be working fine! :+1:

**Comment by alexesprit** [comment]
@whatisthiswtf Thanks for reporting! The next update from Chrome Web Store should scrobble repeats fine!
