### ISSUE TITLE
New Pandora.com Website Update Broke Scrobbling

### ISSUE THREAD

**Issue by Blasman** [david-sabata/web-scrobbler#1242]
The add-on has always worked for me on Pandora.com. However, Pandora just recently revamped their website. The add-on is no longer scrobbling from their website. I am using the latest Chrome browser Version 56.0.2924.87 (64-bit) on Windows 7. Last.fm Scrobbler 1.60.2.

**Comment by alexesprit** [comment]
This issue was submitted in #1194 and is already fixed.

**Comment by Blasman** [comment]
I should have specified the time frame of the issue. My mistake. It was working about 2-3 days ago. Pandora completely revamped their website only about two days ago. It has only been since then that tracks are no longer scrobbling.
