### ISSUE TITLE
Stopped with Aamazon

### ISSUE THREAD

**Issue by hilgi** [david-sabata/web-scrobbler#1243]
After I reauthorized it did work for a couple days, not it stopped again.

**Comment by alexesprit** [comment]
@hilgi [How to debug extensions.](https://github.com/david-sabata/web-scrobbler/wiki/How-to-debug-the-extension)

**Comment by hilgi** [comment]
chrome.storage.local = {"Core":{"appVersion":"1.61.0"},"LastFM":{"sessionID":null,"token":null}}
lastfm.js:97 getToken response: <?xml version="1.0" encoding="utf-8"?>
<lfm status="ok">
  <token>xxxxx1u9yeFalUZf5mgum18a-vC_waLy</token>
</lfm>

notifications.js:229 Notification onClicked: 0802a1df-5115-49fb-916a-5cf7535e133b
inject.js:33 -- loaded for the first time, injecting the scripts
inject.js:55 	injecting vendor/jquery-2.1.0.min.js
inject.js:55 	injecting vendor/underscore-min.js
inject.js:55 	injecting core/content/reactor.js
inject.js:55 	injecting core/content/filter.js
inject.js:55 	injecting core/content/connector.js
inject.js:33 -- loaded for the first time, injecting the scripts
inject.js:55 	injecting vendor/jquery-2.1.0.min.js
inject.js:55 	injecting connectors/v2/amazon.js
inject.js:55 	injecting vendor/underscore-min.js
inject.js:55 	injecting core/content/starter.js
inject.js:55 	injecting core/content/reactor.js
controller.js:333 Tab 4: created controller for connector: {"label":"Amazon","matches":["*://www.amazon.com/gp/dmusic/cloudplayer/*","*://www.amazon.de/gp/dmusic/cloudplayer/*","*://www.amazon.es/gp/dmusic/cloudplayer/*","*://www.amazon.co.uk/gp/dmusic/cloudplayer/*","*://www.amazon.co.jp/gp/dmusic/cloudplayer/*","*://music.amazon.com/*","*://music.amazon.de/*","*://music.amazon.es/*","*://music.amazon.co.uk/*","*://music.amazon.co.jp/*"],"js":["connectors/v2/amazon.js"],"version":2}
inject.js:55 	injecting core/content/filter.js
inject.js:55 	injecting core/content/connector.js
inject.js:55 	injecting connectors/v2/amazon.js
inject.js:55 	injecting core/content/starter.js
controller.js:333 Tab 4: created controller for connector: {"label":"Amazon","matches":["*://www.amazon.com/gp/dmusic/cloudplayer/*","*://www.amazon.de/gp/dmusic/cloudplayer/*","*://www.amazon.es/gp/dmusic/cloudplayer/*","*://www.amazon.co.uk/gp/dmusic/cloudplayer/*","*://www.amazon.co.jp/gp/dmusic/cloudplayer/*","*://music.amazon.com/*","*://music.amazon.de/*","*://music.amazon.es/*","*://music.amazon.co.uk/*","*://music.amazon.co.jp/*"],"js":["connectors/v2/amazon.js"],"version":2}
notifications.js:229 Notification onClicked: c19958ee-d120-4d5e-87fe-aeb985f38fdb
inject.js:33 -- loaded for the first time, injecting the scripts
inject.js:55 	injecting vendor/jquery-2.1.0.min.js
inject.js:55 	injecting vendor/underscore-min.js
inject.js:55 	injecting core/content/reactor.js
inject.js:55 	injecting core/content/filter.js
inject.js:55 	injecting core/content/connector.js
inject.js:55 	injecting connectors/v2/amazon.js
inject.js:55 	injecting core/content/starter.js
controller.js:333 Tab 4: created controller for connector: {"label":"Amazon","matches":["*://www.amazon.com/gp/dmusic/cloudplayer/*","*://www.amazon.de/gp/dmusic/cloudplayer/*","*://www.amazon.es/gp/dmusic/cloudplayer/*","*://www.amazon.co.uk/gp/dmusic/cloudplayer/*","*://www.amazon.co.jp/gp/dmusic/cloudplayer/*","*://music.amazon.com/*","*://music.amazon.de/*","*://music.amazon.es/*","*://music.amazon.co.uk/*","*://music.amazon.co.jp/*"],"js":["connectors/v2/amazon.js"],"version":2}
inject.js:68 -- subsequent ajax navigation, the scripts are already injected
inject.js:33 -- loaded for the first time, injecting the scripts
inject.js:55 	injecting vendor/jquery-2.1.0.min.js
inject.js:55 	injecting vendor/underscore-min.js
inject.js:55 	injecting core/content/reactor.js
inject.js:55 	injecting core/content/filter.js
inject.js:55 	injecting core/content/connector.js
inject.js:55 	injecting connectors/v2/amazon.js
inject.js:55 	injecting core/content/starter.js
inject.js:33 -- loaded for the first time, injecting the scripts
inject.js:55 	injecting vendor/jquery-2.1.0.min.js
controller.js:333 Tab 489: created controller for connector: {"label":"Amazon","matches":["*://www.amazon.com/gp/dmusic/cloudplayer/*","*://www.amazon.de/gp/dmusic/cloudplayer/*","*://www.amazon.es/gp/dmusic/cloudplayer/*","*://www.amazon.co.uk/gp/dmusic/cloudplayer/*","*://www.amazon.co.jp/gp/dmusic/cloudplayer/*","*://music.amazon.com/*","*://music.amazon.de/*","*://music.amazon.es/*","*://music.amazon.co.uk/*","*://music.amazon.co.jp/*"],"js":["connectors/v2/amazon.js"],"version":2}
inject.js:55 	injecting vendor/underscore-min.js
inject.js:55 	injecting core/content/reactor.js
inject.js:55 	injecting core/content/filter.js
inject.js:55 	injecting core/content/connector.js
inject.js:55 	injecting connectors/v2/amazon.js
inject.js:55 	injecting core/content/starter.js
controller.js:333 Tab 489: created controller for connector: {"label":"Amazon","matches":["*://www.amazon.com/gp/dmusic/cloudplayer/*","*://www.amazon.de/gp/dmusic/cloudplayer/*","*://www.amazon.es/gp/dmusic/cloudplayer/*","*://www.amazon.co.uk/gp/dmusic/cloudplayer/*","*://www.amazon.co.jp/gp/dmusic/cloudplayer/*","*://music.amazon.com/*","*://music.amazon.de/*","*://music.amazon.es/*","*://music.amazon.co.uk/*","*://music.amazon.co.jp/*"],"js":["connectors/v2/amazon.js"],"version":2}

**Comment by hilgi** [comment]
Is that what you need?

**Comment by alexesprit** [comment]
Yes. 

Unfortunately, I have no access to Amazon, so I can't fix the issue.

**Comment by hilgi** [comment]
Is there anything I can do?

**Comment by alexesprit** [comment]
@hilgi if you're familiar with JS and CSS, you can fix the connector by yourself.

Perhaps, @mft or @Paszt could fix that.

**Comment by hilgi** [comment]
I am not but if they need any info or help from me, I can try.

**Comment by Paszt** [comment]
It works for me. 
As always when submitting a bug, an explanation of what you did and what happened is always helpful. Did you press play? If so what happened? (what color icons, did they change, etc). What URL are you trying this from. etc...

**Comment by hilgi** [comment]
@Paszt Thanks. I go here https://music.amazon.com/my/songs?ie=UTF8&ref_=nav_shopall_webplayer 
click songs and then play. The scrobble icon just stays red.

**Comment by mft** [comment]
I can reproduce this.
When a track is played from "Songs", the album title is undefined, but is passed to a filter.
Then the filter excepting a string fails with
"Uncaught TypeError: Cannot read property 'replace' of undefined".

I think the expectation is that getAlbum returns always a string.

**Comment by alexesprit** [comment]
@mft Thanks for reply! I reproduced this issue too using synthetic function that returns undefined result.

All should be fine in the latest master. Could someone test it and confirm the issue is resolved?

**Comment by hilgi** [comment]
@alexesprit Does that mean it won't work until the new version is released?

**Comment by alexesprit** [comment]
@hilgi yes. You can install the fixed extension from the latest master, though.

**Comment by hilgi** [comment]
@alexesprit Thanks, is there a walkthrough on that?

**Comment by alexesprit** [comment]
Should work fine in v1.62.0.

**Comment by hilgi** [comment]
works, thanks!
