### ISSUE TITLE
Can't Scrobble with ViewTube

### ISSUE THREAD

**Issue by DuckFlagellant** [david-sabata/web-scrobbler#1250]
I recently installed the [ViewTube](https://github.com/sebaro/ViewTube) script via Tampermonkey on Chrome, and it seems the scrobbler extension is unable to recognize the ViewTube script since I can no longer scrobble on YouTube. The scrobbler extension had no problems recognizing YouTube videos before I installed ViewTube. Is there any way to fix this problem that doesn't involve uninstalling ViewTube? I'd like to continue using both ViewTube and the scrobbler if possible.

[Here's the log btw](http://pastebin.com/TGpJF1rg)

**Comment by alexesprit** [comment]
ViewTube uses another videoplayer, that's why the extension cannot recognize videos. Although, I can add support for the script with some limitations:
* Play/pause won't work;
* Replays won't work.

**Comment by DuckFlagellant** [comment]
Those limitations won't bother me, all I need is basic scrobbling. Thank you so much!

**Comment by alexesprit** [comment]
Should scrobble with installed ViewTube script in next release. Btw, you can install the extension from the latest master to get the update right now.

**Comment by DuckFlagellant** [comment]
I just tried the latest master with ViewTube and it's working great! Thank so much for taking the time to add support for it, I'm really liking your extension!
