### ISSUE TITLE
Idea: about the grey question mark icon in Google Play Music

### ISSUE THREAD

**Issue by plaxin** [david-sabata/web-scrobbler#1251]
### Grey question mark icon in Google Play Music
I think that this grey icon in Google Play Music inappropriate, as there are official names of the tracks and scrobbling the logic must go at once, without the confirmation of artist and title song.

With ❤️️ from 🇷🇺

**Comment by alexesprit** [comment]
The logic of song recognition is common for all connector. I don't think that separate logic for different connectors is a good idea.

As alternative, I'm planning to add new option; if this one is enabled, songs will be recognized by the extension even if they are unknown by Last.fm.

**Comment by plaxin** [comment]
good idea, look forward to, thanks
