### ISSUE TITLE
Move the get background-image Css image Url functionality to core + refactor the others

### ISSUE THREAD

**Issue by mrweiss** [david-sabata/web-scrobbler#1252]
Working on a connector and I need to extract an image URL from the background-image property - simple task.

Noticed there's existing code in other connectors as well (like mailrumusic.js and others) so I think the URL parsing logic and background-image selection could be moved to core so that all connectors can just specify the containing div selector and default filename if any.

Proposed:
Connector.trackArtDivSelector
 - if set, background-image will be checked, parsed etc.
 - add test so that connectors can't set both ArtDiv and ArtImage

OR (use existing)

Connector.trackArtImageSelector
 - if the selector doesn't return a valid 'img src..' it will try to parse the background-image property as per above

**Comment by alexesprit** [comment]
I'm working on `util` module that contains all utility functions currently placed in the `connector` module. This module already contains extracting function (I named it `extractUrlFromCssProperty`).

Usage:
```js
Connector.getTrackArt = function() {
	let backgroundImage = findIframeElement('.css').css('background-image');
	return Util.extractUrlFromCssProperty(backgroundImage);
};
```

> if the selector doesn't return a valid 'img src..' it will try to parse the background-image property as per above

I think that's better way than the first one, but `background` property should be parsed too.

I also pushed commits in a `util` branch, just for demonstration: https://github.com/alexesprit/web-scrobbler/tree/util.

**Comment by mrweiss** [comment]
yeah, Util class sounds like the correct place for that

agree, better to use one property and check all three scenarios (img src? background-image? background?)

**Comment by inverse** [comment]
I think having this logic wrapped in a Util would make the most sense. It would allow for much better test-ability too.

However don't let that hold you up with implementing a connector :+1:

**Comment by alexesprit** [comment]
@mrweiss I updated the branch, see https://github.com/alexesprit/web-scrobbler/commit/873312a2c9de6e0d51f5aab0af136ffd39d366da commit. Is anything should be added or changed?

> so that all connectors can just specify the containing div selector and default filename if any.

I also suggest to move check for default covertart to `connector` module. That means the base connector will have a function named `isTrackArtDefault` which takes track art URL as an agrument and return false result by default. This function can be overriden as in the following example:
```js
const DEFAULT_COVER = 'empty-cover.svg';

Connector.trackArtImageSelector = '.l-music__player__song__cover';

Connector.isTrackArtDefault = function(trackArtUrl) {
	return trackArtUrl.endsWith(DEFAULT_COVER);
};
```

Just compare this with current implementation:
```js
const DEFAULT_COVER = 'empty-cover.svg';

Connector.getTrackArt = function() {
	let backgroundImage = $('.l-music__player__song__cover')
		.css('background-image');
	let backgroundUrl = Util.extractUrlFromCssProperty(backgroundImage);
	if (backgroundUrl && backgroundUrl.endsWith(DEFAULT_COVER)) {
		return backgroundUrl;
	}

	return null;
};
```

The first one looks more compact. But I'm not sure about code readability. Is it looks more complicated?

What do you guys think about this approach?

**Comment by mrweiss** [comment]
@alexesprit the code looks good, that's how I'd write it :)

just one thought, if we're parsing the css background property as well, we might need to remove the start of word from the regex, according to the spec it is not guaranteed to ve 'url(..)' .. or maybe I'm just overcomplicating things :)

https://www.w3schools.com/cssref/css3_pr_background.asp

**Comment by alexesprit** [comment]
> just one thought, if we're parsing the css background property as well, we might need to remove the start of word from the regex, according to the spec it is not guaranteed to ve 'url(..)' .. or maybe I'm just overcomplicating things :)

Yep, I agree. Will update the code soon.

Btw, I have no plans to merge commits into the master branch right now, so for now you can just copypaste extracting code to connector you're working on.

**Comment by inverse** [comment]
The later looks easier to read in my opinion. It's less concise but it's clearer to follow.

**Comment by alexesprit** [comment]
Added in d3a109377e51cfa2eb9af3473a797fed64b83b40.
