### ISSUE TITLE
New Spotify web player has a new interface and no internal Last.fm scrobbling option anymore

### ISSUE THREAD

**Issue by hans-juergen** [david-sabata/web-scrobbler#1254]
This seems to be the new web player interface that Spotify is rolling out to all users at the moment:

![spotify_newwebplayer](https://cloud.githubusercontent.com/assets/4970867/23614190/6b46b148-0282-11e7-9d1e-e12037dac043.jpg)

There are no settings anymore, so you cannot add your Last.fm username and password anywhere. And the playbar is at the bottom now like in their desktop app, so your extension does not recognise the tracks. Users who already have this new interface and rely on it due to restrictions not allowing the installation of the desktop app cannot scrobble to Last.fm anymore.

**Comment by alexesprit** [comment]
We added support for new Spotify web player in v1.61.0.

I tested the connector yesterday, and it worked fine.

**Comment by hans-juergen** [comment]
Oops, I just noticed I had disabled the extension in Opera. It's scrobbling now like it should, great and sorry for that! ;-) Is it supposed to still work with the old interface as well, as I have read several reports recently that users suddenly have problems with scrobbling?

**Comment by alexesprit** [comment]
> Is it supposed to still work with the old interface as well, as I have read several reports recently that users suddenly have problems with scrobbling?

Yes, I haven't remove the old connector, and the extension should work with old web player as well (I don't know if it still accessible, though).

**Comment by hans-juergen** [comment]
I have just checked the old player URL in Opera and Chrome, and I still get the old interface there:

https://play.spotify.com/

The screenshot above was made while accessing https://open.spotify.com/, but I don't know if this works for everyone in every country with these browsers.

**Comment by alexesprit** [comment]
> I have just checked the old player URL in Opera and Chrome, and I still get the old interface there:
> https://play.spotify.com/

It redirects me to new website every time I click on URL. Looks like Spotify enable new version of their website eventually.

Anyway, I have no intention to remove the old connector, and I'll keep support for old website for some time. So I guess, the issue is resolved, right?

**Comment by hans-juergen** [comment]
I have checked that URL again with MS Edge, and it also shows me the old interface, so I guess Spotify has not established the redirect to open.spotify.com for all users yet. Anyhow, keeping support for it is a good idea, and the issue is resolved.
