### ISSUE TITLE
Make it possible to edit the values in the popup even though a match is found

### ISSUE THREAD

**Issue by mangomalte** [david-sabata/web-scrobbler#1257]
At times, an erroneous Artist and Track combination is found, and it's then impossible to change the values.

### Expected Behavior
I would like to have an edit button in the popup to use to go to the view where you fill in the artist and track information, if you know that the information is wrong.

### Current Behavior
Currently, there is only track information and functionality to love the track in the popup.

### Context
I've found this problem while listening to the following playlist on YouTube:
https://www.youtube.com/playlist?list=PL8BDEEE6C05DB6B28

**Comment by alexesprit** [comment]
It is possible to edit songs even if they're recognized by the extension (btw, you should check the extension from the latest master first), but new version isn't released yet.
