### ISSUE TITLE
Pandora not scrobbling anymore after changing to the new UI

### ISSUE THREAD

**Issue by aghiadyazji** [david-sabata/web-scrobbler#1261]
Pandora recently redesigned the website with a new UI, I think they have changed their APIs as well.
so the scrobbling is not working anymore.

**Comment by alexesprit** [comment]
Works fine for me with new UI.

[How to debug extensions.](https://github.com/david-sabata/web-scrobbler/wiki/How-to-debug-the-extension)

**Comment by alexesprit** [comment]
I suppose it's related to #1260. Could you please update to v1.62.1 and check scrobbling again?

**Comment by aghiadyazji** [comment]
Thanks @alexesprit for the quick response,
yeah you are right! It's working now :)
