### ISSUE TITLE
Could you add a connector for http://youtube-playlist-randomizer.valami.info

### ISSUE THREAD

**Issue by MedievalFluff** [david-sabata/web-scrobbler#1264]
I love the idea of the app, but i almost exclusively use this website to randomise my large 500+ song youtube playlist, and it would be great if you could add a connector for it!

(the reason i use this and not just randomise the youtube playlists is that youtube only randomises 100 videos ahead or behind the song you start from so more than half of my playlist would never get heard by me ;-P)

**Comment by alexesprit** [comment]
It's quite easy to add support for website, but the connector won't support play/pause.

**Comment by MedievalFluff** [comment]
that wouldnt be a problem for me, im not sure about other people who use it.
