### ISSUE TITLE
URL to GitHub releases instead of built-in changelog

### ISSUE THREAD

**Issue by alexesprit** [david-sabata/web-scrobbler#1266]
I realized that changelog that is on the options page is just a duplicate of release notes I write for every release. So, I think it's better to put URL named "Release notes" that leads to the release notes of current version to avoid duplicating of information.

On the other side, the "What's new" section with a single URL looks really odd, it's better to remove the section and place this URL to "About" section. But this doesn't looks good too:
![image](https://cloud.githubusercontent.com/assets/1119267/24305060/bc6c8982-10cc-11e7-896a-20d22f47aaa2.png)

Have anyone some thoughts on this?

**Comment by inverse** [comment]
Would you link to the releases page or an individual release? Duplicate content doesn't make sense IMHO and less maintenance is always good. Unless this could be automated ;)

**Comment by alexesprit** [comment]
> Would you link to the releases page or an individual release?

I want to place a link to release notes for currently installed version.

**Comment by inverse** [comment]
Are release URLs to a hash or a number?

**Comment by alexesprit** [comment]
I mean URLs like this one: https://github.com/david-sabata/web-scrobbler/releases/tag/v1.62.2
Current version can be obtained from manifest property.

**Comment by inverse** [comment]
That makes sense. I don't have a strong opinion either way. But less work is always a good thing :)
