### ISSUE TITLE
Last.fm extension doesn't scrobble

### ISSUE THREAD

**Issue by edgarsbu** [david-sabata/web-scrobbler#1267]
### Google Chrome Last.fm extension on Macbook doesn't scrobble Youtube tracks

Tab 130: scrobbling song Fais ft. Afrojack - Hey
https://ws.audioscrobbler.com/2.0/?method=auth.getsession&api_key=d9bb1870d…dXoK1A035xsM_7DEJXWmX&api_sig=d11bf23dc151f5fbedee3b4eb104089e&format=json Failed to load resource: the server responded with a status of 403 (Forbidden)
lastfm.js:175 auth.getSession failed: {"error":14,"message":"Unauthorized Token - This token has not been authorized"}
(anonymous) @ lastfm.js:175
lastfm.js:123 Failed to trade token for session - the token is probably not authorized
(anonymous) @ lastfm.js:123
controller.js:291 Tab 130: scrobbling failed

### Steps for resolving the issue

Restarting browser and removing and installing extention didn't help

When pressing reauthenticate, nothing happens 

### Environment

* Version used: 1.62.2
* Browser Name and version: Google Chrome, v. 56.0.2924.87 (64-bit)

**Comment by alexesprit** [comment]
Looks like you're reauthenticating while Chrome is in fullscreen mode. Try to press reauth button in windowed mode. That should help to resolve the issue.

This behaviour is fixed in latest master.
