### ISSUE TITLE
Spotify webplayer not scrobbling 

### ISSUE THREAD

**Issue by emwey** [david-sabata/web-scrobbler#1269]
Been trying the past few days and it's worked in the past but it's not working with scrobbling inside of Spotify's web player, any help?

**Comment by alexesprit** [comment]
I noticed that too and have fixed this issue in latest master. Please check out the changes and confirm if it works.

**Comment by emwey** [comment]
I just redownloaded through the Chrome store, still not working, am I missing something? Sorry, I'm new here.

**Comment by alexesprit** [comment]
Try to install the extension using this howto: https://github.com/david-sabata/web-scrobbler#unpacked-extension.

**Comment by emwey** [comment]
Yep, got it working! Thank you!
