### ISSUE TITLE
YouTube connector scrobbles video Ads

### ISSUE THREAD

**Issue by ali-essam** [david-sabata/web-scrobbler#1276]
![screenshot from 2017-04-09 01-14-40](https://cloud.githubusercontent.com/assets/5252681/24833490/9721f98c-1cca-11e7-9949-444b48920da7.png)

### Expected Behavior
Connector shouldn't scrobble video skippable Ads
### Current Behavior
Connector scrobbles video skippable Ads

### Steps to Reproduce
1. Open different YouTube music videos or refresh the same one till you get a video Ad
2. Scrobbler starts scrobbling the Ad (happens less if Music cat only is checked) then scrobbles the video once the ad finishes or skipped

### Steps for resolving the issue (kinda)
My guess is that the issue started in this commit 129664d as Ads use the `.ytp-title-link` too so it confuses the connector into thinking it's a valid playing track, on the other hand `getItemPropValue('name')` is not affected by the Ad. If the commit changes were reverted it will bring back the song reset issue again and the issue will still exist in fullscreen mode. The other solution would be to check if the current video is Ad or not, I noticed there's an element with class `videoAdUi` that only exists when the Skip Ad button is visible, so it can be used for checking.

If you can, please try to reproduce this issue and confirm whether my findings are correct or not.

**Comment by alexesprit** [comment]
@ali-essam thanks for reporting!

Can't find any videos with ads (I disabled everything that can block ads). Could you provide URL to any of these ones?

**Comment by alexesprit** [comment]
@ali-essam Could you check the extension and confirm if the issue is fixed? https://github.com/alexesprit/web-scrobbler/tree/youtube-skip-ads

**Comment by ali-essam** [comment]
@alexesprit It works great, it no longer scrobbles Ads.

For the first video (with Ad) when you load the page scrobbling starts after the Ad which is great; however for subsequent videos, if one of them has an Ad, it doesn't scrobble the Ad which is good, but there is just a very minor issue that it starts recognizing and scrobbling the song even before the Ad finishes and might finish scrobbling even before the song starts if the Ad is long or paused.
