### ISSUE TITLE
Spotify not scrobbling after an update

### ISSUE THREAD

**Issue by elctriqueooh** [david-sabata/web-scrobbler#1279]
after the launch of the new version of spotify web player, scrobbling has stopped

![screen](https://cloud.githubusercontent.com/assets/27276139/24901056/313286ea-1ea6-11e7-9fa3-4b9f56b9d170.jpg)

even thought the checks for spotify are ticked, nothing is being scrobbled, only the icon "lights up"

Tried deleting cookies, cache and reinstalling the app and re-authenticating it  in chrome, nada has helped. 

im using Chrome version 57.0.2987.133 (64-bit), tried it on a different computer, same issue.

**Comment by alexesprit** [comment]
Duplicate of #1270.
