### ISSUE TITLE
Opera 43 - Soundcloud Scrobbler error

### ISSUE THREAD

**Issue by mishalame** [david-sabata/web-scrobbler#1281]
![2](https://cloud.githubusercontent.com/assets/27344937/24952927/157a976c-1f82-11e7-9401-8494624eaf39.png)
![3](https://cloud.githubusercontent.com/assets/27344937/24952928/157af09a-1f82-11e7-92e8-dddcb7982ffc.png)
![4](https://cloud.githubusercontent.com/assets/27344937/24952930/157fae5a-1f82-11e7-9a1d-ba9096629240.png)
![5](https://cloud.githubusercontent.com/assets/27344937/24952929/157f3b0a-1f82-11e7-9512-42dfc74098d7.png)
![kj](https://cloud.githubusercontent.com/assets/27344937/24952931/158035dc-1f82-11e7-9ff6-901edb03542e.png)

Opera 43 - Soundcloud
So i have this error. What can i do to fix it ? re-authenticating doesn't help.

**Comment by alexesprit** [comment]
What happens when you press reauth button in the options page?

**Comment by mishalame** [comment]
Like...nothing. I just press it and that's all what happening..

**Comment by alexesprit** [comment]
Well, that's strange. I have Opera 44 installed on Win10 and reauth works fine. Could you reproduce this issue using Chrome?

Also, if you're using Win10 and have notifications disabled in the system preferences, the notification that is shown on reauth button click won't appear.

Could you also provide logs? Here are steps to get them:
1. Open the options page.
2. Click on reauth button.
3. Hit Ctrl-Shift-C key combination.
4. Select "Console" tab and copy logs.
5. Paste logs with any pastebin service and provide the URL.

**Comment by mishalame** [comment]
[chrome-extension://icjpieaianckgehnfpfpldhdjpnhmpbk/core/background/chromeStorage.js:108](url
![default](https://cloud.githubusercontent.com/assets/27344937/25042401/735820f8-2120-11e7-9d65-641c100d2259.png)
) chrome.storage.local.LastFM = {
  "sessionID": null,
  "sessionName": null,
  "token": "xxxxx029Ke6CiIYPN989Q9kTgK4wvlG9"
}
[chrome-extension://icjpieaianckgehnfpfpldhdjpnhmpbk/core/background/services/lastfm.js:99](url) getToken response: <?xml version="1.0" encoding="utf-8"?>
<lfm status="ok">
  <token>xxxxxSKvkWTLwOZpCBqx3uHa8IwpifZm</token>
</lfm>

[chrome-extension://icjpieaianckgehnfpfpldhdjpnhmpbk/core/background/services/lastfm.js:99](url) getToken response: <?xml version="1.0" encoding="utf-8"?>
<lfm status="ok">
  <token>xxxxxP5jGUgI46xwMfObRVTKooBGrPZP</token>
</lfm>

[chrome-extension://icjpieaianckgehnfpfpldhdjpnhmpbk/core/background/services/lastfm.js:99](url) getToken response: <?xml version="1.0" encoding="utf-8"?>
<lfm status="ok">
  <token>xxxxx1_s8akO2ul80jw8knZo6CtXeikO</token>
</lfm>

[chrome-extension://icjpieaianckgehnfpfpldhdjpnhmpbk/core/background/services/lastfm.js:99](url) getToken response: <?xml version="1.0" encoding="utf-8"?>
<lfm status="ok">
  <token>xxxxx4hcpTKDT9_DL4ZeAriovP_64mzO</token>
</lfm>

[chrome-extension://icjpieaianckgehnfpfpldhdjpnhmpbk/core/background/services/lastfm.js:99](url) getToken response: <?xml version="1.0" encoding="utf-8"?>
<lfm status="ok">
  <token>xxxxxYppKdLZVWd1GLsmmufboX8kYH66</token>
</lfm>

[chrome-extension://icjpieaianckgehnfpfpldhdjpnhmpbk/core/background/services/lastfm.js:99](url) getToken response: <?xml version="1.0" encoding="utf-8"?>
<lfm status="ok">
  <token>xxxxxoMk8y0clp475eea0ncGhb_AzAND</token>
</lfm>

chrome-extension://icjpieaianckgehnfpfpldhdjpnhmpbk/core/background/services/lastfm.js:99 getToken response: <?xml version="1.0" encoding="utf-8"?>
<lfm status="ok">
  <token>xxxxxgIftzTi6KSd7i08pZU_LB03-vwk</token>
</lfm>

[chrome-extension://icjpieaianckgehnfpfpldhdjpnhmpbk/core/background/services/lastfm.js:99](url) getToken response: <?xml version="1.0" encoding="utf-8"?>
<lfm status="ok">
  <token>xxxxxt7QHKvXiFUMzhC_LS0rhHzF52eP</token>
</lfm>


idk why but half of code disappearing when it comes to preview and comment

**Comment by alexesprit** [comment]
> and yes i disabled all notifications because system overheating my hard drive (win10)

That's why the nothing happens when you click on reauth button.

Unforturately, there's no way to detect if system notifications are disabled. The Chrome API implementation used in Opera behave like notifications are available. That's Opera issue.
