### ISSUE TITLE
Connector naming convention

### ISSUE THREAD

**Issue by alexesprit** [david-sabata/web-scrobbler#1282]
I noticed all connectors are named in a different way, and don't follow general rules. I propose a naming convention for connector filenames, which should help to keep the source code in the same style.

https://gist.github.com/alexesprit/f86391c1d72de44146b57e8acdddd6d6

Not sure if all the things are described clearly in the convention. Also, not sure if it's useful. Any feedback is welcome.

P.S. I know that some connectors don't match the rules mentioned in convention; they should be updated if the convention will be accepted.

**Comment by f1u77y** [comment]
I'd also suggest to include top-level domain if it's part of the service name(e.g. listen.moe)

**Comment by alexesprit** [comment]
@f1u77y yes, that makes a sense. I updated the document according your suggestion.

**Comment by inverse** [comment]
Conventions FTW - I think including the tld could be useful. Although how would this work for sites which use multiple? Can't think of any off the top of my head. They normally redirect to the `.com`.

**Comment by alexesprit** [comment]
> Although how would this work for sites which use multiple? Can't think of any off the top of my head. 

Yes, that's pretty rare case, but I read [this](https://github.com/david-sabata/web-scrobbler/pull/1234#issuecomment-288813475) recently comment and decided to mention such cases in the convention.

**Comment by inverse** [comment]
I'm all for this - what you documented seems good to me :+1: 

However what would the file name be for this

```
	{
		label: 'Wonder.fm',
		matches: ['*://wonder.fm/*', '*://white-label.fm/*', '*://primary.fm/*'],
		js: ['connectors/wonder.fm.js'],
	},
```

**Comment by alexesprit** [comment]
@inverse it should be called either "wonder.js" (their primary service) or "hydricmedia.js" (the company owns these service). The same story with "bemusic", "radiotunes" connectors and some others. That's one more case should be noted in the convention.

**Comment by alexesprit** [comment]
Added to "Connectors development" wiki page.
