### ISSUE TITLE
Asks me to Reauthenticate everytime

### ISSUE THREAD

**Issue by ErturkOzturk** [david-sabata/web-scrobbler#1283]
### Expected Behavior
I installed Chromium on Ubuntu. I reauthenticated. No need to do it again.

### Current Behavior
It's asking me to reauthenticate when I open browser.

### Steps to Reproduce (for bugs)

1.  Open browser
2.  Reauthenticate
3.  Close browser
4.  Return to no:1

### Environment

* Version used: 1.63.0
* Browser Name and version: Version 57.0.2987.98 Built on Ubuntu , running on Ubuntu 16.04 (64-bit)

**Comment by alexesprit** [comment]
Can't reproduce on Chrome 57.0.2987.133 running on Windows 10.

Could you provide logs? Here are steps to get them:

1. Open the options page.
2. Click on reauth button.
3. Hit Ctrl-Shift-C key combination.
4. Select "Console" tab and copy logs.
5. Paste logs with any pastebin service and provide the URL.

**Comment by ErturkOzturk** [comment]
I can't reproduce with Chrome on Windows 10 too.

`chromeStorage.js:108 chrome.storage.local.LastFM = {
  "sessionID": null,
  "sessionName": null,
  "token": "xxxxxR6Xgo_Yjsjfjp4C3KublIVowov7"
}
lastfm.js:99 getToken response: <?xml version="1.0" encoding="utf-8"?>
<lfm status="ok">
  <token>xxxxxZeYO7knwhgDU7IIJjRdQGZ9SjMG</token>
</lfm>`

**Comment by alexesprit** [comment]
I've tried to reproduce it on Ubuntu 16.04 with Chromium 57.0.2987.98, still works.

Could you also provide logs of background script? Just run Chromium, then wait until notification is shown, then copy logs and paste them here.

**Comment by ErturkOzturk** [comment]
I reinstalled Ubuntu for another problem.

This is the first time notification shows up: https://paste.ubuntu.com/24395236/ then I authenticated.

and this is after authenticated, restarted browser and click reauthenticate from options (automatic notification didn't show up): https://paste.ubuntu.com/24395270/

So it seems problem is gone, for now.

**Comment by ErturkOzturk** [comment]
Started again: https://paste.ubuntu.com/24403154/

**Comment by alexesprit** [comment]
@ErturkOzturk could you try to collect log using these steps from my comment? https://github.com/david-sabata/web-scrobbler/issues/981#issuecomment-238158879

The single log contain no useful information.

**Comment by ErturkOzturk** [comment]
https://paste.ubuntu.com/24408564/

**Comment by alexesprit** [comment]
@ErturkOzturk That's odd. Did you click on notification when you ran Chrome first time? I see no "Notification onClicked: 3279715f-a7b6-447e-9312-7c0d043359bd" in first part of the log.

**Comment by ErturkOzturk** [comment]
No, I didn't click on first time. I clicked on second time. Want me to paste the log in that way?

**Comment by alexesprit** [comment]
Yes, I need logs in the case when user reauthenticates via auth notification, then just restarts Chrome (as described in the comment in #981).

**Comment by Chronum94** [comment]
Can report that this occurs on Chrome/Win10 for me.

**Comment by alexesprit** [comment]
@Chronum94 https://github.com/david-sabata/web-scrobbler/issues/981#issuecomment-238158879

**Comment by ErturkOzturk** [comment]
https://paste.ubuntu.com/24421407/

The problem is: when I launch Chromium notification pops out. I click on notification and reauthenticate then restart chrome. After this everything is cool, no matter how many time I start Chrome. But another day, it's asking me to reauthenticate again.
