### ISSUE TITLE
Doesn't work on music.163.com

### ISSUE THREAD

**Issue by Kauxan** [david-sabata/web-scrobbler#1284]
First of all, thanks to all the contributors to this scrobbler. 

### Expected Behavior
Works fine...

### Current Behavior
It says that "This site is supported for scrobbling", but when the music is playing, the extension doesn't recognize it.

### Possible Solution
...I don't know

### Context
Well, this is the only way to scrobble songs from music.163.com. (Thanks again)

### Environment
Cent Browser and Vivaldi.

**Comment by alexesprit** [comment]
@Kauxan Thanks for reporting!

I fixed the issue, the scrobbling should work fine in the next release. Would be fine if you install the extension from the master branch and confirm if it's fixed.

**Comment by Kauxan** [comment]
Yes, it has been fixed. Thank you.
![tim 20170416181033](https://cloud.githubusercontent.com/assets/27534496/25070405/1471b098-22d0-11e7-8e40-67cd491bd693.png)
