### ISSUE TITLE
I played music on 163music but the extension did not recognize it

### ISSUE THREAD

**Issue by dwse** [david-sabata/web-scrobbler#1287]
### Steps to Reproduce (for bugs)

1.  
2.  
3.  

### Environment

* Version used: 1.63.0
* Browser Name and version: chrome 57.0.2987.133

**Comment by c-yau** [comment]
Same issue here. 

Steps to Reproduce:
1.Visit http://music.163.com
2.Click "play" and the scrobbler isn't working.

**Comment by alexesprit** [comment]
Duplicate of #1284.

**Comment by c-yau** [comment]
Tks. It's been fixed on master
