### ISSUE TITLE
Scrobbles always all YouTube videos on new experimental design

### ISSUE THREAD

**Issue by Vankog** [david-sabata/web-scrobbler#1288]
Even though I restricted scrobbling on YouTube only for the music category, every video is attempted to be scrobbled with the new experimental design (with night mode).

### Expected Behavior
Attempted scrobbling only of music videos, independent from the design.

### Current Behavior
Even though YouTube scrobbling is only allowed for music videos, it tries to scrobble all videos with the new YouTube design enabled.

### Possible Solution
Workaround: disable scrobbling or new design

### Steps to Reproduce (for bugs)
1. enable new YouTube design:  
1.1. go to youtube.com and open Chrome console (F12 and change to console tab)
1.2. enter following code, hit enter and reload:
`var cookieDate = new Date();
cookieDate.setFullYear(cookieDate.getFullYear( ) + 1);
document.cookie="VISITOR_INFO1_LIVE=fPQ4jCL6EiE; expires=" + cookieDate.toGMTString( ) + "; path=/";`
2. you can also change to night mode in the top right menu
3. set Last.fm Scrobbler settings:
x Use desktop notifications
x Unrecognized song notifications
x Use autocorrect (global)
x Force song recognition
x Disable Google Analytics

x Scrobble only Music category

### Context
Using the new YouTube design, which will probably be rolled out over the next months.

### Environment

* Version used: 1.63.0
* Browser Name and version: Chrome stable x64

**Comment by alexesprit** [comment]
Unfortunately, a category name is localized to several languages, and there's no metadata in the page source (like in current version of Youtube). That's why it's hard to implement support for this option in new design.

**Comment by Vankog** [comment]
I see, so basically we would have to include all localizations then?
Maybe some meta data will still be added back until the design goes live for all.

**Comment by alexesprit** [comment]
I'll try to look into that.

**Comment by alexesprit** [comment]
The category name is not accessible to connectors until the video description is expanded.

**Comment by Vankog** [comment]
Damn. :-/
Alright, I think we should not go ahead of ourselves. I suggest we wait until the design has an official release and check again. I think there will be several things that mjght change and maybe this gives a better opportunity to check for music. 
Maybe we could utilize some Google Music indicators in the page or the like.

**Comment by f1u77y** [comment]
We could get video category ID with YT api(the Music category is 10).

**Comment by alexesprit** [comment]
I thought about that. To use Youtube API we should implement custom state change function and check for track change to reduce Youtube API calls. This makes the connector more complex.

**Comment by f1u77y** [comment]
Somewhat easier solution is to use cache(that can be even page-local)

**Comment by Vankog** [comment]
Nice idea, but should we really expose the API key? Every guideline expresses it's concerns about this. 
However, the only option I see is to ask the user to put in a custom API key... :-/

**Comment by alexesprit** [comment]
@Vankog providing custom API keys is too hard for an usual user.

The previous v1 connector also was based on Youtube API. I think it's nothing wrong if we will keep the API key visible to all.
