### ISSUE TITLE
cannot scrobble 163 music

### ISSUE THREAD

**Issue by bjason** [david-sabata/web-scrobbler#1290]
### Environment

* Version used: 1.63.0
* Browser Name and version: Opera 44.0.2510.1218
(I know this is confusing that this extension doesn't mean to support Opera however I used another extension which allowed me to do so. And the web scrobble works fairly well in Spotify while cannot scrobble [163 music](music.163.com))

**Comment by alexesprit** [comment]
This is known issue and it's already fixed. You can install the extension as an unpacked one from master branch to get it worked right now.
