### ISSUE TITLE
Notifications only for unrecognized songs?

### ISSUE THREAD

**Issue by skjerns** [david-sabata/web-scrobbler#1291]
It would be cool to be able to disable notifications except for unrecognized songs.
Is that planned in the future?

**Comment by alexesprit** [comment]
@skjerns no, it isn't planned, but it's not hard to implement this feature if there's some reason for that.

**Comment by alexesprit** [comment]
@skjerns I've just found out this is possible to show only unrecognized notifications now. Just enable "Unrecognized song notifications" option, then disable "Use desktop notifications" one.

Actually, this is a but, and the extension isn't supposed to behave like that.

**Comment by skjerns** [comment]
great! it works :)

what a useful bug

**Comment by alexesprit** [comment]
I updated the code, and removed option dependency. The extension should allow to configure options separately now.
