### ISSUE TITLE
Pandora Mobile Solution

### ISSUE THREAD

**Issue by ssanders** [david-sabata/web-scrobbler#1295]
### Expected Behavior
No mobile apps can scrobble Pandora currently.
But a web-scrobbler could scrobble from a profile’s past activity.

### Current Behavior
Web-scrobbler only scrobbles tracks I play now.

### Context
I want to somehow scrobble from my Pandora mobile app.

**Comment by alexesprit** [comment]
This extension is designed to scrobble now playing songs. How should this feature work?

**Comment by alexesprit** [comment]
Closed as outdated.
