### ISSUE TITLE
Some service error has occurred

### ISSUE THREAD

**Issue by jeanloup** [david-sabata/web-scrobbler#1296]
The album I'm listening to doesn't submit its track details to last.fm, each track comes back with a ? in the browser extension icon and when submitting manually it fails with the error in the heading

### Expected Behavior

I expect the track to scrobble as expected even if the details are not in last.fm's database

### Current Behavior

The track is not scrobbled and triggers the "some service error has occurred" message. Re-authenticating doesn't help

### Steps to Reproduce (for bugs)

1.  
2.  
3.  

### Context

I just want my tracks to scrobble to my account

### Steps for resolving the issue

- [ ] Reauthenticate on Last.fm

- [ ] Try to use unpacked extension from latest master

- [ ] Check other issues for duplicates

### Environment

* Version used: 1.63
* Browser Name and version: Chrome 57.0.2987.133, Windows 7

**Comment by alexesprit** [comment]
[How to debug extensions.](https://github.com/david-sabata/web-scrobbler/wiki/How-to-debug-the-extension)

**Comment by alexesprit** [comment]
@jeanloup is this still an issue?

**Comment by jeanloup** [comment]
I'm not 100% sure but I think it worked fine last time I used it in that
confusion

**Comment by alexesprit** [comment]
@jeanloup ok, then I'm closing this. Please reopen the issue if the extension stops working.
