### ISSUE TITLE
Non-music video is scrobbled on Youtube after music video

### ISSUE THREAD

**Issue by f1u77y** [david-sabata/web-scrobbler#1299]
[This comment](https://github.com/david-sabata/web-scrobbler/pull/1298#issuecomment-298219084) fully describes the issue.

My suggestion is to change semantics of `Connector.isStageChangeAllowed()`. It should be more like `isScrobblingAllowed`. I think we don't need to change the function body in all connectors, just change its name and semantics.

**Comment by alexesprit** [comment]
I didn't change behaviour of the `isStateChangeAllowed` function, just added new one used by Youtube connector only.

https://github.com/alexesprit/web-scrobbler/tree/yt-reset-state
