### ISSUE TITLE
163 music doesn't scrobble now.

### ISSUE THREAD

**Issue by bluemelodypp** [david-sabata/web-scrobbler#1303]
http://music.163.com/#
this website can‘t be scrobbled now

**Comment by alexesprit** [comment]
Duplicate of #1284.

**Comment by bluemelodypp** [comment]
I reinstall the plugin but still not working.

**Comment by alexesprit** [comment]
It shouldn't work, because new version is not released. The issue is already reported and is fixed; that's why I closed it.

**Comment by bluemelodypp** [comment]
Thanks!!! 
BTW when will it release?
