### ISSUE TITLE
how to sign in?

### ISSUE THREAD

**Issue by isomorphisms** [david-sabata/web-scrobbler#1305]
### Expected Behavior

enter a username/pass, or at least check if I'm logged in

### Current Behavior

Options page doesn't ask for login

### Steps to Reproduce (for bugs)

1.  using chromium on ubuntu
2.  
3.  

### Context

actually scrobble

### Steps for resolving the issue

- [ ] Reauthenticate on Last.fm

- [ ] Try to use unpacked extension from latest master

- [ ] Check other issues for duplicates

### Environment

* Version used:
* Browser Name and version:

**Comment by alexesprit** [comment]
What does "Options page doesn't ask for login" mean? Have you tried to click on reauthenticate button?

https://www.youtube.com/watch?v=3GJjbJa6pK0 here is a tutorial how to start using the extension.
