### ISSUE TITLE
Issue with scrobbling from Napalm Records

### ISSUE THREAD

**Issue by RogerF81** [david-sabata/web-scrobbler#1311]
All in all the extension works, but it seems that it does not scrobble any video from [Napalm Records](https://www.youtube.com/channel/UCG7AaCh_CiG6pq_rRDNw72A). It only shows "Play some music to get started", though music actually is played. A few days ago, I'm quite sure it worked.

**Comment by alexesprit** [comment]
Can't reproduce.
![image](https://cloud.githubusercontent.com/assets/1119267/25932455/ebdd7704-3619-11e7-9782-b61cda8f18b6.png)

Make sure you have these options disabled:
![image](https://cloud.githubusercontent.com/assets/1119267/25932464/00c37fce-361a-11e7-891f-55b48c971ca0.png)

**Comment by alexesprit** [comment]
@RogerF81 are you still experiencing this issue?

**Comment by RogerF81** [comment]
I don't know what was wrong previously, but it seems to work again! :)
