### ISSUE TITLE
unable to re-authorize that the lastfm login window doesn't show up

### ISSUE THREAD

**Issue by bjason** [david-sabata/web-scrobbler#1312]
### Current Behavior

It went great in the past until yesterday, when I was listening to music in 163 music, and the app icon became yellow showing there's some error occurs and ask me to re-authorize in the option page. However when I clicked the button but there's nothing happened afterwards.
I noticed that in the extension page a error icon was shown next to the scrobbler. I clicked and this window poped out:

![alt](https://image.ibb.co/nK9WAk/Clipboard_image_2017_05_11_15_55_51.png)

I tried to re-install the extension (as I delete it in the browser and loaded again, I don't know whether that counts though), but not works.

### Environment

* Version used: 1.64.0
* Browser Name and version: Opera 44.0.2510.1449 (PGO)

**Comment by alexesprit** [comment]
What is OS name and version do you use?

**Comment by bjason** [comment]
It's Windows 10 Pro (1703)
OS version 15063.296 (I find this in about tab in setting, I'm not sure what that is though...)

**Comment by bjason** [comment]
And this problem occurs whichever supported website, not only the 163 music.

**Comment by alexesprit** [comment]
Check if you have system notifications enabled.

**Comment by alexesprit** [comment]
I update the extension and now it should open Last.fm page directly by clicking on reauth button. Could you install the extension from master branch and check how it works?

**Comment by bjason** [comment]
@alexesprit yeah, the newest version works just perfect! thank you!
