### ISSUE TITLE
not scrobbling from rockradio.com

### ISSUE THREAD

**Issue by hardkoren** [david-sabata/web-scrobbler#1314]
### Steps to Reproduce (for bugs)

1.  
2.  
3.  

### Steps for resolving the issue

- [ ] Reauthenticate on Last.fm

- [ ] Try to use unpacked extension from latest master

- [ ] Check other issues for duplicates

### Environment

* Version used:
* Browser Name and version:

**Comment by SeleniaIrisha** [comment]
Also does not work. Browser Chrome 58.0.3029.110 (64-bit). All the corrective actions performed does not help.
![qiy3hta-dj4](https://cloud.githubusercontent.com/assets/28702358/26049592/33de79b6-3964-11e7-997e-81f58c57f7a7.jpg)
