### ISSUE TITLE
please add a way to unscrobble current tracks from the popup

### ISSUE THREAD

**Issue by lukehunter2** [david-sabata/web-scrobbler#1315]
99% of titles on youtube have a - in them so it keeps adding random youtube videos and i have to go on lastfm to unscrobble them

**Comment by lukehunter2** [comment]
a 'disable on this page' button like with adblock would also work

**Comment by alexesprit** [comment]
An example of how this feature can be implemented:
![image](https://cloud.githubusercontent.com/assets/1119267/26176175/e9eb14ee-3b5d-11e7-9d91-879429d93c06.png)

This is how ignored songs look:
![image](https://cloud.githubusercontent.com/assets/1119267/26176218/0d60570e-3b5e-11e7-8c9a-ee0e0b1b2d19.png)

**Comment by inverse** [comment]
Should we maintain a cache of ignored pages? Could complicate things somewhat though I guess.

**Comment by alexesprit** [comment]
@inverse What is this cache for?

**Comment by lukehunter2** [comment]
is anyone working on this or should i learn javascript and see if i can do it

**Comment by alexesprit** [comment]
As you can see, I'm working on the feature, and it's almost done, but feel free to implement it by yourself.
