### ISSUE TITLE
Pandora Scrobbling not Listing album 

### ISSUE THREAD

**Issue by robotninek** [david-sabata/web-scrobbler#1316]
### Expected Behavior
It should scrobble the artist, the song title and the album.

### Current Behavior
It is only scrobbling the artist and the song title.

### Possible Solution
Make the album title automatically update like it did when it wasn't broken.

### Steps to Reproduce (for bugs)

1.  Play Song on pandora
2.  Press the toolbar button thing
3.  Edit and you can see the album is not listed

### Context
I am trying to use http://tapmusic.net but it uses the top albums on my last.fm page, but I cannot use it if i don't have any top albums. https://www.last.fm/user/BlacksmithMcae/library/albums?date_preset=LAST_30_DAYS

(the songs that are scrobbled are from itunes being scrobbled.

### Steps for resolving the issue

- [x] Reauthenticate on Last.fm

- [x] Try to use unpacked extension from latest master

- [x] Check other issues for duplicates

### Environment

* Version used: idk
* Browser Name and version: Google Chrome Latest Version

**Comment by alexesprit** [comment]
New Pandora website shows album information on the main page only. I'm not sure if it can be fixed on the extension side.
