### ISSUE TITLE
v1.64.0 YouTube Bug with Firefox 53.0.3 (32-bit)

### ISSUE THREAD

**Issue by DuckFlagellant** [david-sabata/web-scrobbler#1319]
I recently updated to v1.64.0 for Firefox 53.0.3 (32-bit), and now I'm unable to scrobble in Youtube. I've already reauthenticated last.fm numerous times, and I'm still unable to scrobble. Here's the log: https://pastebin.com/gRuUW6Vw

**Comment by alexesprit** [comment]
Yes, it's the same for me. I'll investigate this bug.

As a temporary workaround, you can disable these options:
![image](https://cloud.githubusercontent.com/assets/1119267/26278587/e9f14f80-3da6-11e7-98e6-1ccd368e2848.png)

**Comment by DuckFlagellant** [comment]
Okay, I just tried your suggested workaround, and now I can scrobble. Thanks very much, and I look forward to the bug being fixed!

**Comment by alexesprit** [comment]
@DuckFlagellant I changed some settings of Youtube API key, and now the extension should work even with enabled options. Could you check this and tell if it works?

**Comment by DuckFlagellant** [comment]
It's working now, thank you so much!
