### ISSUE TITLE
Scrobbles completely inaccurate for multiple services

### ISSUE THREAD

**Issue by StephenDonaldson** [david-sabata/web-scrobbler#1320]
### Expected Behavior
In a recent update Spotify, Soundcloud, and YouTube scrobbling all broke from what I can tell; when I check my scrobbles the information is incomplete or inaccurate; things don't contain album info anymore for one, which is a major issue for people trying to use their scrobbles to generate album boards to share.

### Current Behavior
Album tags in particular are missing for Spotify, Soundcloud, and YouTube causing things to only scrobble as tracks and frequently as incorrect tracks, even for services like Spotify, which should be giving proper data.

### Possible Solution
Either revert or check what information you're submitting when sending scrobbles to Last.FM as the information being sent is severely inaccurate that it negates scrobbling in the first place.

### Steps to Reproduce (for bugs)
Use extension. Use a service. Check Last.FM account. See that the albums tab has not increased whatsoever when using Spotify, Soundcloud, or YouTube, only the Tracks tab.

### Context
It's made scrobbling completely useless.

### Steps for resolving the issue
See above.

### Environment
* Version used: 1.65.0
* Browser Name and version: Chrome 58.0.3029.110

**Comment by alexesprit** [comment]
1. Youtube connector has never gathered album info, because there's no album info on the video page.
2. The same story with Spotify. The album info is not available in the player element.
3. Soundcloud connector should scrobble album, but I didn't check it.

I'm not sure [1] and [2] can be fixed. I'll look at Soundcloud connector later, perhaps, it's broken.

**Comment by f1u77y** [comment]
Spotify's target is music, so I think there should be info somewhere maybe not in the DOM but somewhere in scripts.

And we already fetch info from last.fm for checking info. Can we get album from there if the info from connector does not contain it?

**Comment by alexesprit** [comment]
Soundcloud also doesn't provide album info.

> Can we get album from there if the info from connector does not contain it?

Yes, we can, but it should be optional feature.

**Comment by StephenDonaldson** [comment]
> The same story with Spotify. The album info is not available in the player element.

This is false; before version 1.63.0 it automatically sent album information and scrobbled properly; with 1.63.0 it broke.

**Comment by alexesprit** [comment]
> This is false; before version 1.63.0 it automatically sent album information and scrobbled properly; with 1.63.0 it broke.

I've just scrobbled a track using v1.62.0, and the extension does not scrobble album too (and it shouldn't do that).

> The album info should automatically default to song title then so that some album info is being sent and not completely breaking the albums tab/ability to create collages.

I don't think it's a good solution.

**Comment by StephenDonaldson** [comment]
> I've just scrobbled a track using v1.62.0, and the extension does not scrobble album too (and it shouldn't do that).

That's because 1.62.0 is broken due to the changes Spotify pushed out.

**Comment by alexesprit** [comment]
Hmm... okay. Let's say it's "broken".

I think the issue can be resolved by getting the album info from Last.fm, but Last.fm doesn't always provide it.

**Comment by alexesprit** [comment]
> The option should still be offered because now this extension has absolutely no purpose for many.

I 'm just trying to understand why it becomes a problem now. The extension has about 50% of connectors which don't provide album information, but you're first one who said it's useless.

**Comment by StephenDonaldson** [comment]
> I 'm just trying to understand why it becomes a problem now. The extension has about 50% of connectors which don't provide album information, but you're first one who said it's useless.

Because you ignore all of the people posting comments on the extension's page itself and require them to come comment on friggin GitHub, which people aren't going to do. It's an issue since the main reason a lot of people use Last.FM in the first place is to generate album collages and when things aren't popping up as albums, it's pointless. The functionality worked before and does not now anymore, which means that it should be fixed so that those that did use the extension before could continue using it as they used to now.

**Comment by alexesprit** [comment]
> The functionality worked before and does not now anymore, which means that it should be fixed so that those that did use the extension before could continue using it as they used to now.

I can't fix it because I don't know what to fix. But pull requests contains fixes are always welcome.

**Comment by alexesprit** [comment]
> That's because 1.62.0 is broken due to the changes Spotify pushed out.

What about Youtube and Soundcloud? Will the v1.62.0 version scrobble albums for these websites?

**Comment by StephenDonaldson** [comment]
Went ahead and fixed this for Spotify and opened a pull request [here](https://github.com/david-sabata/web-scrobbler/pull/1322).
