### ISSUE TITLE
Broken extension in Firefox

### ISSUE THREAD

**Issue by brenoritvrezorkre** [david-sabata/web-scrobbler#1325]
Completely does not work. There are no notifications, authentication is impossible, when you try to open the settings, a non-existent address "moz-extension://3f74f045-475b-4185-a389-bd16e39636e0/options/options.html" is called.

The extension itself actually has a given name: "{799c0914-748b-41df-a25c-22d008f9e83f}.xpi". Not as above.

Version: 1.63.0.

Browser: Firefox 53.0.3.

OS: Windows 8.1.

**Comment by alexesprit** [comment]
How can I reproduce the issue? The extension works fine for me from AMO.

**Comment by brenoritvrezorkre** [comment]
I just install it using the AMO site / "about:addons" and get this result. Nothing more is required.

**Comment by alexesprit** [comment]
That's strange. I have no idea how to reproduce this issue.

**Comment by alexesprit** [comment]
Have you tried to remove the extension and install it again?

**Comment by brenoritvrezorkre** [comment]
Yes. The address has changed, but it is still incorrect.
Bad address: [screenshot](http://i.imgur.com/ZmtMRHV.png).
Real address: [screenshot](http://i.imgur.com/RWrcjVv.png).

**Comment by alexesprit** [comment]
Can you install the extension using new Firefox profile?

**Comment by brenoritvrezorkre** [comment]
The source of the problem is found. This extension is not compatible with RequestPolicy.

**Comment by alexesprit** [comment]
Do you mean the "RequestPolicy" extension for Firefox? I reproduced the issue after I installed that extension.

I also noticed other WebExtension become unusable too.

**Comment by alexesprit** [comment]
[This one](https://addons.mozilla.org/en-US/firefox/addon/requestpolicy-continued/) works fine with the WebExtensions.

**Comment by brenoritvrezorkre** [comment]
Yes, RequestPolicy for Firefox.

I've been using this extension for a long time, and it's really useful (even if it does not support the use of regular expressions), because it prevents unwanted requests from various web pages. I do not know what WebExtensions you mean, but personally, RequestPolicy did not work correctly only with this Scrobbler. Changing the RequestPolicy settings does not solve this problem.

**Comment by alexesprit** [comment]
[What is WebExtensions](https://developer.mozilla.org/en-US/Add-ons/WebExtensions). This extension is powered on this technology, that's why I mentioned WebExtensions.

I also have Feedly Notifier and Checker Plus for Gmail installed (they are WebExtensions too), and these extensions don't work if RequestPolicy is insalled.

This issue is fixed in RequestPolicyContinued project: https://github.com/RequestPolicyContinued/requestpolicy/issues/813.

**Comment by brenoritvrezorkre** [comment]
Yes, replacing the RequestPolicy with the RequestPolicyContinued really made this Scrobbler workable. Thank you.
