### ISSUE TITLE
Conflict with one more extension.

### ISSUE THREAD

**Issue by brenoritvrezorkre** [david-sabata/web-scrobbler#1326]
Random Agent Spoofer for Firefox.

The problem is that the Scrobbler does not perform the required (re-)authentication. Unchecking the flags in the 'Random Agent Spoofer' options does not help in resolving this conflict, either I incorrectly make adjustments to adapt R.A.S. to this Scrobbler.

Please see what things might contradict each other. Most likely, you know the list of technologies and techniques used by this Scrobbler, so it will be easier for you to answer this question.

Just in case, the situation with cookies should be okay, and it's not them who are to blame.

**Comment by alexesprit** [comment]
How exactly the extension does not perform the reauthentication? Is is showing an error message or is it do nothing? I've installed RAS and I can reauth w/o any problems.

**Comment by brenoritvrezorkre** [comment]
When installing the Scrobbler, there is no notification that I need to authenticate. In the settings, the reauthentication button does not work. This was tested in the profile with all other extensions disabled, and the correct operation of the Scrobbler stopped when the R.A.S. was enabled.

**Comment by alexesprit** [comment]
Can you add "ws.audioscrobbler.com" and "last.fm" URLs to RAS whitelist and reauth again?

**Comment by brenoritvrezorkre** [comment]
Nothing happens.

**Comment by alexesprit** [comment]
Can you post logs of options page? Here are steps to collect them:
1. Open options page.
2. Click on reauth button.
3. Hit "Ctrl+Shift+C" key combination, select "Console" tab and copy console logs.

**Comment by brenoritvrezorkre** [comment]
SecurityError: The operation is insecure.  config.js:41
	setupDefaultConfigValues moz-extension://81d88aec-a623-4d64-900c-3e0379a4f7e0/core/background/config.js:41:8
	<anonymous> moz-extension://81d88aec-a623-4d64-900c-3e0379a4f7e0/core/background/config.js:57:2
	execCb moz-extension://81d88aec-a623-4d64-900c-3e0379a4f7e0/vendor/require.js:1:12361
	check moz-extension://81d88aec-a623-4d64-900c-3e0379a4f7e0/vendor/require.js:1:6502
	enable moz-extension://81d88aec-a623-4d64-900c-3e0379a4f7e0/vendor/require.js:1:9041
	init moz-extension://81d88aec-a623-4d64-900c-3e0379a4f7e0/vendor/require.js:1:5605
	o moz-extension://81d88aec-a623-4d64-900c-3e0379a4f7e0/vendor/require.js:1:4173
	completeLoad moz-extension://81d88aec-a623-4d64-900c-3e0379a4f7e0/vendor/require.js:1:11612
	onScriptLoad moz-extension://81d88aec-a623-4d64-900c-3e0379a4f7e0/vendor/require.js:1:12516

Method document.createAttribute() is deprecated. To replace it, use the method element.setAttribute().  can.custom.js:1:6706

chrome.storage.local.LastFM = {
  "sessionID": "xxxxxcxAuFQ8imjmZxhqkZ5HHYm-T5Qw",
  "token": null,
  "sessionName": // my lastfm login
}  chromeStorage.js:108:4

**Comment by alexesprit** [comment]
Hmm, that's odd.

Can you install the extension from [this zip](https://github.com/alexesprit/web-scrobbler/archive/firefox-test.zip) as a temporary addon and reauth again?

**Comment by brenoritvrezorkre** [comment]
"This extension can not be established, since it appears to be damaged".

I tried to use the required formats ".xpi" and ".jar", install directly the source archive ".zip", zip-archive with the contents of the directory and so on, but the browser does not accept any of this. Please create a ready-to-install xpi-package.

**Comment by alexesprit** [comment]
You can install the extension by clicking on "Install temporary add-on" button on the "about:debugging#addons" page. Click on this button and select manifest.json file. The archive supposed to be extracted to some directory.

**Comment by brenoritvrezorkre** [comment]
```
SecurityError: The operation is insecure.  config.js:47
	setupDefaultConfigValues moz-extension://65148c87-45da-498d-9746-0f7c81ff7479/core/background/config.js:47:7
	<anonymous> moz-extension://65148c87-45da-498d-9746-0f7c81ff7479/core/background/config.js:81:1

Method document.createAttribute() is deprecated. To replace it, use the method element.setAttribute().  can.custom.js:376:24

SecurityError: The operation is insecure.  options.js:38
	<anonymous> moz-extension://65148c87-45da-498d-9746-0f7c81ff7479/options/options.js:38:4
	fire moz-extension://65148c87-45da-498d-9746-0f7c81ff7479/vendor/jquery.js:3047:10
	fireWith moz-extension://65148c87-45da-498d-9746-0f7c81ff7479/vendor/jquery.js:3159:7
	ready moz-extension://65148c87-45da-498d-9746-0f7c81ff7479/vendor/jquery.js:3365:3
	completed moz-extension://65148c87-45da-498d-9746-0f7c81ff7479/vendor/jquery.js:3380:2

```

**Comment by alexesprit** [comment]
Unfortunately, I have no idea why the extension does not work properly and how to fix it w/o disabling RAS.

**Comment by brenoritvrezorkre** [comment]
It's sad.
