### ISSUE TITLE
rockradio.com

### ISSUE THREAD

**Issue by SeleniaIrisha** [david-sabata/web-scrobbler#1328]
On the radio began to add to the title of the song name of the music style. Scroobler does not recognize

![default](https://user-images.githubusercontent.com/28702358/26868302-34f3d610-4b71-11e7-8104-2dcf1e808392.JPG)

**Comment by SeleniaIrisha** [comment]
![default](https://user-images.githubusercontent.com/28702358/26868373-7de75ec8-4b71-11e7-95de-592128266f21.JPG)

**Comment by Alex-Kho** [comment]
The same for https://www.radiotunes.com
![image](https://user-images.githubusercontent.com/5023703/26876577-8ef519f8-4b8f-11e7-91bf-9e53dcb5727f.png)

**Comment by SeleniaIrisha** [comment]
Probably all of their subsidiaries
![default](https://user-images.githubusercontent.com/28702358/26877085-757add76-4b91-11e7-9fa0-e923757a6471.JPG)

**Comment by alexesprit** [comment]
@SeleniaIrisha @Alex-Kho can you check the extension from this zip? https://github.com/alexesprit/web-scrobbler/archive/radiotunes-fix.zip

**Comment by rymarcode** [comment]
Yes, di.fm and others stations(radiotunes, rockradio) has changed their players from flash technology and direct streams. Also, they prepend station title to song title and its complicate extension to scrobbler.

I think, we just need add gsub function to scrobbler for cut out unnecessary text. I'll do pull request with this very soon

**Comment by alexesprit** [comment]
@rymarcode I have already fixed the issue and post URL to the fixed extension. I'm just waiting until someone confirms it's fixed.

**Comment by rymarcode** [comment]
@alexesprit okay. You can create pull request with fixed code
