### ISSUE TITLE
181.fm integration

### ISSUE THREAD

**Issue by crinabucur** [david-sabata/web-scrobbler#1329]
Hi,

Any chance of implementing the integration with the http://www.181.fm website?

Good job with the extension, thank you! (:

**Comment by alexesprit** [comment]
I'm not sure if it's possible. This website uses iframe which has different source, and this makes the scrobbling from this site impossible.

I tried to inject a script to read data from internal JS objects, but I had no luck.

**Comment by crinabucur** [comment]
That's a pity, I thought it was possible, especially since I saw a last.fm reference on their page. Thank you very much for trying, Alex! Hopefully they will change something in the future and it will be possible, as I really enjoy their radios and hate to see the scrobbles going to waste :)

**Comment by alexesprit** [comment]
I think it's possible to add support for scrobbing from pages like these ones: http://181fm.mystreamplayer.com/?autoplay=12 but users should open them manually.

**Comment by crinabucur** [comment]
Thank you. If the extension worked with this kind of hyperlink, I would gladly use it, instead of the conventional path.

**Comment by alexesprit** [comment]
Will be available in the next release.
