### ISSUE TITLE
Firefox crashes when trying to scrobble a youtube video

### ISSUE THREAD

**Issue by LaHaine** [david-sabata/web-scrobbler#1332]
### Current Behavior
Firefox always crashes after a few seconds of playing a youtube video. It doesn't crash after disabling the last.fm scrobbler.

### Steps to Reproduce (for bugs)
The video is this one: https://www.youtube.com/watch?v=ilfy5XjRl7Q&feature=em-subs_digest
Firefox is Firefox ESR 52.1.0 on Enterprise Linux 6.
Last.fm Web Scrobbler is 1.65.0

The error on the crash is this one:

1497422069136	addons.webextension.{799c0914-748b-41df-a25c-22d008f9e83f}	WARN	Loading extension '{799c0914-748b-41df-a25c-22d008f9e83f}': Reading manifest: Error processing page_action.chromeBroken: An unexpected property was found in the WebExtension manifest.
1497422069136	addons.webextension.{799c0914-748b-41df-a25c-22d008f9e83f}	WARN	Loading extension '{799c0914-748b-41df-a25c-22d008f9e83f}': Reading manifest: Error processing options_page: An unexpected property was found in the WebExtension manifest.
1497422069166	addons.webextension.{799c0914-748b-41df-a25c-22d008f9e83f}	WARN	Please specify whether you want browser_style or not in your page_action options.
process 18426: arguments to dbus_message_iter_append_fixed_array() were incorrect, assertion "n_elements <= DBUS_MAXIMUM_ARRAY_LENGTH / _dbus_type_get_alignment (element_type)" failed in file dbus-message.c line 2344.
This is normally a bug in some application using the D-Bus library.
  D-Bus not built with -rdynamic so unable to print a backtrace
Redirecting call to abort() to mozalloc_abort

[1]    18426 segmentation fault  firefox

**Comment by f1u77y** [comment]
Does not reproduce on my Nightly. That's Firefox bug, so it's better to report it to Mozilla but not here. 

Any bug in a new style Firefox extension (webextension) that makes the whole browser crash is most likely a Firefox bug because new API does not allow access to the browser internals.

**Comment by LaHaine** [comment]
It crashes right in the moment where the pop-up window would appear.

**Comment by f1u77y** [comment]
Okay, but that's a low level bug in Firefox (or maybe in the d-bus library). Try reproducing it on a new profile and reporting it to Mozilla.

**Comment by LaHaine** [comment]
OK, I have reported upstream: https://bugzilla.mozilla.org/show_bug.cgi?id=1372819
