### ISSUE TITLE
YouTube manually entered scrobbles are sometimes not remembered

### ISSUE THREAD

**Issue by kini** [david-sabata/web-scrobbler#1334]
Often I will play a YouTube video which web-scrobbler doesn't automatically recognize, so I click the gray question mark and enter the information, and the track successfully scrobbles.  But then when I play the video again, the gray question mark reappears and I have to enter the information again.  However this only happens on some videos.  On other videos, once I enter the information once, it seems to be remembered indefinitely.

### Expected Behavior
When I manually enter track/artist/album information about a YouTube video, it should be remembered if I play the video again in the future.

### Current Behavior
When I manually enter track/artist/album information about a YouTube video, for some videos it is remembered, and for other videos it is never remembered no matter how many times I enter the information.

### Steps to Reproduce (for bugs)
Example of a video for which I was able to add track/artist/album information and it was remembered indefinitely: [here](https://www.youtube.com/watch?v=p8na61sQO1k)

Examples of videos for which I added track/artist/album information but it the video is unrecognized again as soon as I reload the page: [here](https://www.youtube.com/watch?v=AhccsEK8S_Y), [here](https://www.youtube.com/watch?v=HAtotvbzgMM), [here](https://www.youtube.com/watch?v=ecJEECYUhYk)

### Context
The issue template tells me to say what I'm trying to accomplish.  Well, basically I often listen to the same song many times and I don't want to have to keep typing the same thing over and over again.

### Environment

* Version used: 1.66.0, though I've been seeing this in previous versions too.
* Browser Name and version: Chromium version 59.0.3071.86 (Developer Build) built on Debian 9.0, running on Debian 9.0 (64-bit)

**Comment by alexesprit** [comment]
Will be fixed in the next update.

**Comment by kini** [comment]
Wow, thanks for the EXTREMELY fast response! I should have reported this when I first saw it a couple weeks ago :)
