### ISSUE TITLE
Timestamp in now playing notifications

### ISSUE THREAD

**Issue by alexesprit** [david-sabata/web-scrobbler#1335]
Is there a reason to keep the timestamp in now playing notifications?
![image](https://user-images.githubusercontent.com/1119267/27262315-bc5ab364-545c-11e7-9477-107da4f071b4.png)
Chrome Notification Center is gone, therefore the notification is visible only when the track is playing. I can't imagine how the timestamp can be using in this case.

We could add an album title instead of that timestamp.

Ref #776.

**Comment by f1u77y** [comment]
> I can't imagine how the timestamp can be using in this case.

For watching current time?

Being more serious, I totally agree with you idea to show album instead.

**Comment by alexesprit** [comment]
Both album name and connector name don't look good when album name is long:
![image](https://user-images.githubusercontent.com/1119267/28498542-8a8ab87c-6fa8-11e7-959e-7f2b32fe705a.png)

So I think we can just get rid of the timestamp.
