### ISSUE TITLE
181.fm incorrect artist name

### ISSUE THREAD

**Issue by crinabucur** [david-sabata/web-scrobbler#1337]
Hi,

I want to report an issue regarding the newly integrated 181.fm radio ( http://181fm.mystreamplayer.com ).

It looks like for some tracks this website appends what seems to be the album / LP name after the artist name, separated through a slash character "**/**".

![image](https://user-images.githubusercontent.com/2715895/27385518-a7071f0c-569b-11e7-8205-4b373a505137.png)

Another thing is that if I try to fix this manually a bit later after the track has started playing, the Edit option is disabled and the tooltip says "Scrobbled tracks cannot be edited". I believe this is recent behaviour, as I remember fixing the scrobble info at any time in the past, even seconds before the track would end. Do you have any input on this behaviour of the latest version 1.66.0?

![image](https://user-images.githubusercontent.com/2715895/27385813-7d48c912-569c-11e7-8c9f-b18f85a65560.png)

Thank you!

**Comment by crinabucur** [comment]
I also added a snapshot of a situation with multiple slash characters. Not sure if you can find a solution for this though (perhaps just considering the first substring before the slash?), as it seems the radio website doesn't have its info straight.

![image](https://user-images.githubusercontent.com/2715895/27386904-df7f9b26-569f-11e7-8a35-8e93727d9088.png)

Thanks!

**Comment by alexesprit** [comment]
Hi Crina!

The extension should work fine after next update. I also added support for album info in the connector.

You can install the extension from the master branch to get update right now.
