### ISSUE TITLE
Pandora not scrobbling this morning

### ISSUE THREAD

**Issue by theregent1** [david-sabata/web-scrobbler#1339]
### Expected Behavior
pandora.com website stopped scrobbling this morning
no improvement

### Current Behavior
 red AS symbol in extensions says site should be scrobbling, but can't identify that the page is playing music

### Steps to Reproduce (for bugs)

1.  chrome.storage.local = {"Core":{"appVersion":"1.60.2"},"LastFM":{"sessionID":"xxxxx2S1kb5_eQcvZgVVg_dVwH0EALw3","sessionName":"theregent1","token":null}}
main.js:202 LastFM: Session ID xxxxx2S1kb5_eQcvZgVVg_dVwH0EALw3
inject.js:33 -- loaded for the first time, injecting the scripts
inject.js:58 	injecting vendor/jquery-2.1.0.min.js
inject.js:58 	injecting vendor/underscore-min.js
inject.js:58 	injecting core/content/testReporter.js
inject.js:58 	injecting core/content/reactor.js
inject.js:58 	injecting core/content/filter.js
inject.js:58 	injecting core/content/connector.js
inject.js:58 	injecting connectors/v2/pandora.js
inject.js:58 	injecting core/content/starter.js
controller.js:333 Tab 29: created controller for connector: {"label":"Pandora","matches":["*://www.pandora.com/*"],"js":["connectors/v2/pandora.js"],"version":2}
inject.js:71 -- subsequent ajax navigation, the scripts are already injected
2.  Web Scrobbler: Setting up observer
starter.js:52 Web Scrobbler: Player element (.region-bottomBar) was not found in the page.
(anonymous) @ starter.js:52
starter.js:89 Web Scrobbler: waiting for test capture to be configured
testReporter.js:57 Web Scrobbler: connector_injected undefined
3.  sucessfully reauthenticated several times.

### Steps for resolving the issue

- [X ] Reauthenticate on Last.fm

- [NOT SURE HOW TO DO THIS ] Try to use unpacked extension from latest master

- [HAVE'NT SEEN ANY YET ] Check other issues for duplicates

### Environment

* Version used:1.60.2 - TRIED 1.66.0 THIS MORNING - NO CHANGE
* Browser Name and version:CHROME

**Comment by alexesprit** [comment]
Will be fixed in the next update. You can install the extension from the master branch, if you want to get the update right now, though.

**Comment by theregent1** [comment]
master 1.66.0 unpacked extension from this morning works, thank you for the heads up
