### ISSUE TITLE
Pandora (Desktop) No Longer Scrobbles (chrome/pc)

### ISSUE THREAD

**Issue by HoustonHouston** [david-sabata/web-scrobbler#1340]
Title says it all. I've tried the following.
- re-authentication
- extension re-installation
- logout/login on last.fm 
- clear browser data

The extension will detect that pandora is supported but will never go green.

**Comment by alexesprit** [comment]
This is known issue and it was fixed. You can install the extension from the master branch, if you want to get the update right now.
