### ISSUE TITLE
Issue with gear icon configuration

### ISSUE THREAD

**Issue by greedoe** [david-sabata/web-scrobbler#1341]
### Expected Behavior
When I click the gear icon, a box should appear where I can add a customer configured URL.

### Current Behavior
When I click the gear icon, nothing happens.

### Steps to Reproduce (for bugs)

1.  Go to the Options page for the extension
2.  click on Options
3.  Scroll down to "supported websites" and click on the gear icon next to any website. 

### Context
I'm trying to configure my Amazon Echo to scrobble and can't adjust the URL for the Echo. 

### Steps for resolving the issue

- [x] Try to use unpacked extension from latest master

- [x] Check other issues for duplicates

### Environment

* Version used: Version 60.0.3112.40 (Official Build) beta (64-bit)
* Browser Name and version: Chrome

**Comment by greedoe** [comment]
Also having issues on v58 / 32bit Chrome.

**Comment by alexesprit** [comment]
Thanks for reporting the issue!

The issue should be fixed in the next update.
