### ISSUE TITLE
Multi-language support for extension

### ISSUE THREAD

**Issue by inverse** [david-sabata/web-scrobbler#1345]
Not sure how well the Firefox version will handle such things though.

- https://developer.chrome.com/webstore/i18n 
- https://developer.chrome.com/extensions/i18n

Init: https://github.com/david-sabata/web-scrobbler/compare/master...inverse:i18n?expand=1

**Comment by f1u77y** [comment]
Latest Firefox handles it fine. 
You could find relevant info at [MDN](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Chrome_incompatibilities)

**Comment by inverse** [comment]
Thinking about it more it feels like for a lot of the pages we should be using a templating library to make this easier to work with. so we can generate the strings with chrome.i18n.getMessage and passing them through. Any suggestions of a library to use?

**Comment by f1u77y** [comment]
We just use static pages, so won't something like this 
```js
$(function () {
	$('*').each(function () {
		if (this.prop('i18n-text')) {
			this.text(chrome.i18n.getMessage(this.prop('i18n-text')));
		}
	});
});
```
be enough?

**Comment by inverse** [comment]
What about placeholder? Where we concatenate? Also it's not just text we replace, we also update titles and placeholders

**Comment by marsjaninzmarsa** [comment]
> What about placeholders, e.g. where we build sentences up. Also what about title and placeholder attributes?

What's wrong with `i18n.getMessage()` second parametr?
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Internationalization

**Comment by inverse** [comment]
@marsjaninzmarsa what would you put here?

**Comment by marsjaninzmarsa** [comment]
@inverse any replaceable string part we need.

**Comment by alexesprit** [comment]
[Example of implementation](https://github.com/alexesprit/web-scrobbler/tree/i18n) and the [project page](https://www.transifex.com/web-scrobbler/web-scrobbler/) on Transifex. Probably missed some strings, please let me know if you find non-localized text (I know "Accounts" section is not localized yet).

@f1u77y any comments about RU localization?

**Comment by inverse** [comment]
Looks good :)

**Comment by marsjaninzmarsa** [comment]
I've requested Polish language.

**Comment by inverse** [comment]
Requested German :)

**Comment by inverse** [comment]
How does the process go for getting new strings translated going forward? or pulling them out of the tool? Let me know if you need me to review any documentation.

**Comment by alexesprit** [comment]
@inverse Translations can be downloaded or uploaded by using Transifex client. I pushed configuration file of Transifex client to `i18n` branch.

Optionally this can be automated by adding Grunt task executed before publishing new releases.

**Comment by alexesprit** [comment]
I also updated source locale and added missing strings. I didn't change source messages too much, but some of them look outdated a little. Changes are welcomed.

**Comment by alexesprit** [comment]
Merged i18n branch into master branch.

Currently, only RU locale is ready for use. Feel free to translate source strings to other locales.

**Comment by inverse** [comment]
:+1:

**Comment by marsjaninzmarsa** [comment]
Finished Polish and added Transifex link to wiki.
