### ISSUE TITLE
Ability to view list of saved edited tracks

### ISSUE THREAD

**Issue by fishstik** [david-sabata/web-scrobbler#1348]
I love the feature that saves edited track info and autofills it later. Very useful! Would like the ability to see (and maybe even edit?) a list of all my edited tracks. Could even just be a .txt file that could be opened from the Options page.

**Comment by alexesprit** [comment]
@fishstik In the next release you can view edited tracks. I don't think editing the data should be implemented; this action can be done using the now playing popup. Removing tracks is not supported too, but I think it's a good feature should be implemented (possibly, later).

**Comment by fishstik** [comment]
Awesome work, thanks!
