### ISSUE TITLE
Misleading YouTube option names

### ISSUE THREAD

**Issue by f1u77y** [david-sabata/web-scrobbler#1350]
If both options are disabled, we scrobble any category but user could misunderstand option titles (see [comments](https://github.com/david-sabata/web-scrobbler/issues/1349#issuecomment-312450318)). 

I'd like to suggest two options:
- One
  - Scrobble Music
  - Scrobble Entertainmaent
  - Scrobble other
- Two
  - Scrobble only these categories
    - Music
    - Entertainment
  - Scrobble all

**Comment by inverse** [comment]
Not a UX guy but I think Two would be a better fit, where the top two level are options and the categories checkboxes.
