### ISSUE TITLE
Soundcloud problem

### ISSUE THREAD

**Issue by marciof37** [david-sabata/web-scrobbler#1358]
The extension fails to scrobble soundcloud tracks with emojis in the title or artist name. Any time i try to play a song with an emoji in the title it fails to scrobble. Otherwise it works fine...
### Steps for resolving the issue

- [ ] Reauthenticate on Last.fm

- [ ] Try to use unpacked extension from latest master

- [ ] Check other issues for duplicates

### Environment

* Version used:
* Browser Name and version:

**Comment by alexesprit** [comment]
Have you an example of such tracks?

**Comment by LinkCable** [comment]
@alexesprit 

Just ran into this issue myself, here's a track with an artist who has emoji in their username: https://soundcloud.com/ntreboot/dreamy

**Comment by alexesprit** [comment]
Yes, I have the same issue. Trying to figure out how to fix it.

**Comment by alexesprit** [comment]
This issue is not related to Soundcloud connector.

I fixed it in the latest master. The new version of the extension should scrobble such songs correctly.
