### ISSUE TITLE
Scrobble stopped working for dubtrack.fm

### ISSUE THREAD

**Issue by cyancey76** [david-sabata/web-scrobbler#1361]
### Expected Behavior
Scrobbles have stopped working on dubtrack.fm since 7/20/17

### Current Behavior
Extension says "This site is not supported for scrobbling."

### Context
dubtrack dev says the site had some changes pushed on 7/20/17.

### Environment
* Browser Name and version: Chrome 59

**Comment by alexesprit** [comment]
Can't reproduce. Works fine for me. I don't listen to music on dubtrack, so I choosed a random room: https://www.dubtrack.fm/join/melharucos.

> Extension says "This site is not supported for scrobbling."

Where did you find this text?

**Comment by cyancey76** [comment]
It's an issue with another extension I use. I figured out that it only happens in this specific room because that extension has extra functionality there.
