### ISSUE TITLE
Scrobbles Spotify ads

### ISSUE THREAD

**Issue by jugdizh** [david-sabata/web-scrobbler#1365]
When listening to Spotify free version in a web browser with this Chrome extension enabled, the ads that come up in Spotify get picked up and scrobbled as though they were songs. Now my Last.fm page has things like "greatest hits ever - Listen now",  "Gordon's - Enter Now", and "ASICS - Learn More" showing as my most frequently played tracks.

Environment:
Last.fm Scrobbler 1.67.1
Chrome 56.0.2924.87 (64-bit)
CentOS Linux release 7.3.1611 (Core)

**Comment by alexesprit** [comment]
Tried to catch ads while listening to music on Spotify yesterday, had no luck (adblock is disabled, though). I use free version too. Is there a way to get ads?

**Comment by jugdizh** [comment]
Sure, here's how it happens in my experience:

1. Go to http://open.spotify.com (with Adbock disabled/paused)
2. Start listening to a playlist, for example Discover Weekly
3. After about 15-30 minutes of music the first ad will play.
Looking at my Last.fm history, it looks like the ads play about once every 10 songs or so, although I think they get more frequent the longer you have listened to Spotify continuously.

**Comment by alexesprit** [comment]
Fixed.
