### ISSUE TITLE
- Normally it would scrobble the track 'Uppermost - Passion' e.g., instead it doesn't even scrobble the site 'YouTube' overall. It doesn't recognize youtube for scrobbling. 

### ISSUE THREAD

**Issue by Aveefje** [david-sabata/web-scrobbler#1367]
### Expected behavior

It would scrobble the site YouTube.

All good.
### Current behavior

Now it doesn't scrobble at all. Particular problem occured while playing 'Uppermost - Passion', from then on it didn'"t scrobble anymore.

It should scrobble....
### Possible solution

Well , just update/fix? 

### Steps to reproduce (for bugs)

-playing 'Uppermost - Passion'
-check last.fm
-didn't see any scrobble
-check whether song was recognized by app
-app didn't recognize song
-check whether app recognizes others
-didn't recognize other either
-bug confirmed

1.  
2.  
3.  

### Context

Scrobbling.

### Steps for resolving the issue

- [ ] Reauthenticate on Last.fm

- [ ] Try to use unpacked extension from latest master

- [ ] Check other issues for duplicates

### Environment

* Version used:
* Browser name and version:

**Comment by Aveefje** [comment]
Fixed.

**Comment by alexesprit** [comment]
> Fixed.

What do you mean? Is it not an issue now?

**Comment by bertenvdb** [comment]
Had the same issue; suddenly no scrobbling of Youtube at all.

Reauthenticated on Last.fm and everything works as expected.

**Comment by alexesprit** [comment]
Closed as outdated.
