### ISSUE TITLE
the web scrobbler isn't working proprely (doesn't stop searching for a song)

### ISSUE THREAD

**Issue by NoFaced** [david-sabata/web-scrobbler#1368]
So uh I have been scrobbling my tracks exclusively with the web scrobbler and the web spotify player and I have come across a problem that started today. When a song is playing the button at the top right of the screen will show that it's searching for the song to scrobble. Thing is, it just keeps searching. Reloading the page only makes the button grey (signaling that the website I'm on does not support scrobbling), even though it worked flawlessly before. Deleting and reinstalling the extension works for a while and then it starts happening again. How can I fix this?

**Comment by alexesprit** [comment]
Can you reproduce the issue and provide the exension logs?
1. Start Chrome.
2. Reproduce the issue.
3. Grab logs and paste them.

[How to debug extensions.](https://github.com/david-sabata/web-scrobbler/wiki/How-to-debug-the-extension)

**Comment by alexesprit** [comment]
Closed as outdated.
