### ISSUE TITLE
Change project URL to add0n.com

### ISSUE THREAD

**Issue by marsjaninzmarsa** [david-sabata/web-scrobbler#1369]
Since Web Scrobbler is no longer Chrome-only extension, more appropriate than [Chrome Web Store](https://chrome.google.com/webstore/detail/lastfm-scrobbler/hhinaapppaileiechjoiifaancjggfjm) would be browser-agnostic [addon.com webpage](https://add0n.com/lastfm-scrobbler.html).

**Comment by alexesprit** [comment]
I cannot edit repository data, so I emailed David (the author of project and repo owner) and asked him to change URL.

**Comment by alexesprit** [comment]
Closed as resolved. Thanks to @david-sabata!
