### ISSUE TITLE
No scrobbling for retrowave.ru

### ISSUE THREAD

**Issue by kilometrix** [david-sabata/web-scrobbler#1371]
I can't scrobble music on retrowave.ru website.
Scrobbling enabled in settings. Extention icon is not active on retrowave.ru. Relogin did not help.

Google Chrome 60.0.3112.90, Windows 7.

**Comment by alexesprit** [comment]
Can't reproduce. Works fine for me.
[How to debug extensions.](https://github.com/david-sabata/web-scrobbler/wiki/How-to-debug-the-extension)

**Comment by alexesprit** [comment]
@kilometrix I've fixed two issues with Retrowave. Can you install the extension from latest master and tell if it works?

**Comment by kilometrix** [comment]
Sure, just tell me how to do it. Do I need to go to Chrome Market?

**Comment by alexesprit** [comment]
> 

No, just download https://github.com/david-sabata/web-scrobbler/archive/master.zip and install it using [this](https://github.com/david-sabata/web-scrobbler#unpacked-extension) instruction.

**Comment by kilometrix** [comment]
The extention works now.
But it's strange because the versions of extention from market and from latest master are both 1.68.0. Chrome updated the extention to 1.68.0 about 2 hours ago. Is that normal?

**Comment by alexesprit** [comment]
I don't change version during developing of the extension. I bump it before publish new version. So, yes, that's expected.

Thanks for reporting the issue! I'll publish hotfix to Chrome Web Store and AMO soon.

**Comment by kilometrix** [comment]
Thank you too, you do a great job.
