### ISSUE TITLE
Authentication Problem

### ISSUE THREAD

**Issue by sgsudhir** [david-sabata/web-scrobbler#1372]
### Steps to reproduce (for bugs)

1.  
2.  
3.  

### Steps for resolving the issue

- [x] Reauthenticate on Last.fm

- [ ] Try to use unpacked extension from latest master

- [ ] Check other issues for duplicates

### Environment

* Version used:
* Browser name and version:

**Comment by alexesprit** [comment]
Please describe the issue properly.

**Comment by alexesprit** [comment]
Closed as outdated.
