### ISSUE TITLE
Can this extension be used on chrome for iPhone?

### ISSUE THREAD

**Issue by jaruppert1** [david-sabata/web-scrobbler#1373]
### Steps to reproduce (for bugs)

1.  
2.  
3.  

### Steps for resolving the issue

- [ ] Reauthenticate on Last.fm

- [ ] Try to use unpacked extension from latest master

- [ ] Check other issues for duplicates

### Environment

* Version used:
* Browser name and version:

**Comment by marsjaninzmarsa** [comment]
Nope.
