### ISSUE TITLE
The pinguinradio.com scrobbler isn't working anymore

### ISSUE THREAD

**Issue by kaasplank** [david-sabata/web-scrobbler#1376]
The website got an update and I think it's behaving differently now, It doesn't detect songs to scrobble anymore.
I'm not a code expert so I'm sorry for my lack of understanding code and stuff.
the player: https://pinguinradio.com/player/pinguin-radio

**Comment by alexesprit** [comment]
Fixed in 78a560be36f06577d51d59c723eee92f0eb4f790.

**Comment by kaasplank** [comment]
You are amazing, thanks!
