### ISSUE TITLE
scrobbler does not remember edited tags w/ spotify web player

### ISSUE THREAD

**Issue by hlavkus** [david-sabata/web-scrobbler#1377]
when I edit a tag scrobbled from YOutube, the scrobbler remembers it an then always scrobbles the song with the tag the way I edited it
but it doesn't when scrobbling from spotify web player

**Comment by alexesprit** [comment]
This is expected behaviour. Some connectors such as Spotify connector don't provide song ID, and the extension saves edited data only if song ID is defined.

I plan on adding the calculated ID based on song data, if no one is defined. That should resolve the issue.
