### ISSUE TITLE
Playback detected — but no scrobbling — from app.plex.tv

### ISSUE THREAD

**Issue by bvanwesten** [david-sabata/web-scrobbler#1378]
When playing music from Plex remotely, [Last.fm Scrobbler detects that the tab is Plex but asks me to play some music to get started](http://imgur.com/EnAwPMP).

The domain I'm redirected to is http://app.plex.tv/web/app?secure=0#!

I'm using the latest versions of Chrome and web-scrobbler.

**Comment by alexesprit** [comment]
@bvanwesten did the extension work with Plex before or was it always be broken? I haven't use Plex before, but I've just installed Plex Server, and I confirm it's not working.

**Comment by bvanwesten** [comment]
@alexesprit The extension does work on my home computer when I can connect directly within the local network (i.e. http://192.168.X.XXX:XXXXX). I noticed the issue when I started listening to music at work. When I connect via http://plex.tv, I'm redirected to http://app.plex.tv/web/.

I did a little more testing once I got home. I'm able to get an HTTPS connection (https://app.plex.tv/web/app#) and it doesn't work either. Maybe app.plex.tv needs to be listed as a Plex domain?

**Comment by bvanwesten** [comment]
Here's the information from my Chrome console (connected to https://app.plex.tv/web/app#):

`-- loaded for the first time, injecting the scripts
inject.js:58 	injecting vendor/jquery.min.js
inject.js:58 	injecting core/content/reactor.js
inject.js:58 	injecting core/content/filter.js
inject.js:58 	injecting core/content/util.js
inject.js:58 	injecting core/content/connector.js
inject.js:58 	injecting connectors/plex.js
inject.js:58 	injecting core/content/starter.js
main.js:275 Tab 4: remove controller
controller.js:458 Tab 4: created controller for connector: {"label":"PLEX","matches":["*://*32400/web/*","*://plex.tv/web/*","*://*.plex.tv/web/*"],"js":["connectors/plex.js"]}
inject.js:34 -- loaded for the first time, injecting the scripts
inject.js:58 	injecting vendor/jquery.min.js
inject.js:58 	injecting core/content/reactor.js
inject.js:58 	injecting core/content/filter.js
inject.js:58 	injecting core/content/util.js
inject.js:58 	injecting core/content/connector.js
inject.js:58 	injecting connectors/plex.js
inject.js:58 	injecting core/content/starter.js
main.js:275 Tab 4: remove controller
controller.js:458 Tab 4: created controller for connector: {"label":"PLEX","matches":["*://*32400/web/*","*://plex.tv/web/*","*://*.plex.tv/web/*"],"js":["connectors/plex.js"]}`

**Comment by alexesprit** [comment]
@bvanwesten Looks like Plex uses two different user interfaces; that's why the extension doesn't recognize music which is being played on http://app.plex.tv/web/. Scrobbling using UI available on local address works fine for me too.

I'll try to add support for UI used on app.plex.tv, that should resolve the issue.

**Comment by alexesprit** [comment]
@bvanwesten I've updated Plex connector, everything works fine for me.

Could you install the extension from [this zip archive](https://github.com/alexesprit/web-scrobbler/archive/plex.zip) contains the update and confirm the issue is fixed?

**Comment by bvanwesten** [comment]
The updated version has successfully sent data to Last.fm!

**Comment by alexesprit** [comment]
@bvanwesten oops, that's not supposed to be.

I've updated the connector; now it's should take the proper song data. Can you download that zip file again and check these changes?

**Comment by bvanwesten** [comment]
@alexesprit The changes appear to be working. Thank you!
