### ISSUE TITLE
Spotity (Open) connector scrobbles multiple artists incorrectly

### ISSUE THREAD

**Issue by sk-zk** [david-sabata/web-scrobbler#1382]
The open.spotify.com connector scrobbles tracks with multiple artists differently from the apps with built-in Last.fm support, leading to a lot of artists with single digit listeners in my library.

### Expected behavior
An track with multiple artists, e.g. "_foo, bar_" scrobbles as "_foo_", like the official scrobbler.

### Current behavior
The track scrobbles as  "_foo, bar_". 

### Steps to reproduce (for bugs)
Scrobble any song with multiple artists listed, e.g. https://open.spotify.com/track/2sVRieO4jzGq6ZR5z9hlje

### Environment
* Version used: 1.68.1
* Browser name and version: Firefox 55.0.3 x64

**Comment by alexesprit** [comment]
Why do you think it's incorrectly?

**Comment by sk-zk** [comment]
None of Spotify's apps scrobble like this so I'd be getting a lot of duplicate tracks where the only listeners are people who use this app; e.g. [this](https://www.last.fm/music/The+Glitch+Mob,+Christopher+Willits/_/The+Clouds+Breathe+for+You+(Christopher+Willits+Remix)) instead of [this](https://www.last.fm/music/The+Glitch+Mob/_/The+Clouds+Breathe+for+You+(Christopher+Willits+Remix)).

It's also worth noting that the extra artists exist primarily to make it easier to search for music. For example, the track I've linked above is a remix, which in most cases means that the original artist remains in the artist field and the remixer is in the title. On Spotify, the remixer is also included in the artist tag so that all remixes by this person will be listed on their artist page.

**Comment by marsjaninzmarsa** [comment]
See also mopidy/mopidy#1389.

**Comment by weichslgartner** [comment]
Songs like https://open.spotify.com/track/1iO6RMfKFHNoS3GW3TfCqA don't scrobble at all. Last.fm uses only the first artist.
