### ISSUE TITLE
Bringing back support for Tunein.com after the layout change 

### ISSUE THREAD

**Issue by hdd007** [david-sabata/web-scrobbler#1384]
Tunein radio recently changed its user interface. The current Last.fm Scrobbler does not pick up the names of the songs and artists in the new Tunein interface.

### Expected behavior

Last.fm Scrobbler should be picking up the currently played song and artist on the radio that the user is currently listening to.

Some radios available would not provide the currently played track. The Last.fm Scrobbler should behave in the same manner as previously and for those instances not scrobble the track.
### Current behavior

Regardless of whether track information is provided in the new Tunein Radio interface, Last.fm Scrobbler  does not capture the song information.

When the information song information can be parsed to pick up the artist and song name the Last.fm Scrobbler should scrobble the he given song to the last.fm account configured.
### Possible solution

Tunein recently changed it's user interface/layout of the site.
The beta version had become live.
Last.fm Scrobller is able to properly parse the beta interface.
The Tunein connector should be set to match the Tunein-beta code.

### Steps to reproduce (for bugs)

1.  https://tunein.com/radio/Radio-Dismuke-s54028/
2.  https://beta.tunein.com/radio/Radio-Dismuke-s54028/
3.  

### Context

I am a dedicated Tunein Radio listener and chose Last.fm Scrobbler to capture the songs that I've listened to.

### Steps for resolving the issue

- [ ] Reauthenticate on Last.fm

- [ ] Try to use unpacked extension from latest master

- [ ] Check other issues for duplicates

### Environment

* Version used:
Latest Last.fm Scrobbler plugin version available on the Chrome market (1.68.1).
* Browser name and version:
Latest Chrome Stable Version. Version 60.0.3112.101 (Official Build) (64-bit)

**Comment by alexesprit** [comment]
Replaced by "TuneIn (Beta)" connector, thanks to @eugenesvk.

**Comment by hdd007** [comment]
@alexesprit / @inverse  Would you happen to know hen the  updated Last.fm Scrobbler version will be released that will replace  the old Tunin connector with TuneIn (Beta)?

Thanks!

**Comment by alexesprit** [comment]
@hdd007 we have no certain ETA.

You can download the extension from the master branch to scrobble from TuneIn until next version is released.

**Comment by hdd007** [comment]
@alexesprit Thanks! Enjoying the master branch code until the next official release!

Thanks!
