### ISSUE TITLE
Maybe a solution for avoid non-music Youtube scrobbles

### ISSUE THREAD

**Issue by felipemaciel** [david-sabata/web-scrobbler#1385]
There so many scrobbles that are non-music from Youtube. 

### Expected behavior
Scrobble just actually songs.

### Current behavior
For example that video "Simpsons Intro- Game of Thrones" was scrobbled, just because the hyphen. Any video with a hyphen in the middle is scrobbled.

### Possible solution
Add a option within extension settings that scrobble from Youtube just artists that have minimum 500 scrobbles in the artist page (or a configurable number).

### Steps to reproduce (for bugs)

1.  
2.  
3.  

### Steps for resolving the issue

- [ ] Reauthenticate on Last.fm

- [ ] Try to use unpacked extension from latest master

- [ ] Check other issues for duplicates

### Environment

* Version used:
* Browser name and version:

**Comment by alexesprit** [comment]
We have options to allow to scrobble videos from "Music" or "Entertainment" categories only.

> Add a option within extension settings that scrobble from Youtube just artists that have minimum 500 scrobbles in the artist page (or a configurable number).

This is a hacky way, and it doesn't resolve the issue.
