### ISSUE TITLE
Scrobbler doesn't works for the albums

### ISSUE THREAD

**Issue by ascerrillo** [david-sabata/web-scrobbler#1386]
It works perfect. From youtube, deezer, spotify (open), and so on. But i noticed something, the scrobbles for the album doesn't work. I mean if i listen a whole album, the scrobble of the artist and the songs are there, but not the album ones... Could this be fixed? I know i can added manually, but  i do not wanna do this anytime.
Besides this, the add-on is perfect! Thanks a lot

Thanks!

**Comment by alexesprit** [comment]
Some websites don't provide album title, so there's no way to get album info of now playing song.

In next update the extension will automatically retrieve album title from Last.fm.

**Comment by ascerrillo** [comment]
Thanks a lot! it was weird, i guess deezer provided it, but i think not. Anyway, amazing job and many thanks!

**Comment by ascerrillo** [comment]
Also happened with spotify, but anyway, i am glad to hear that this will be fixed in next extension
