### ISSUE TITLE
Since yesterday scrobbler doesent scrobble mixcloud sets. Even the ones that used to work. 

### ISSUE THREAD

**Issue by protoplazmik** [david-sabata/web-scrobbler#1388]
for example: https://www.mixcloud.com/DreamScenes/dreamscenes-30-april-2017/
I tried to reinstall and reaunthenticate. Its happening in every browser.
Please does anybody know what to do?

**Comment by inverse** [comment]
That URL works for me. Hmm anyone else able to reproduce the issue? Which version you running?

**Comment by protoplazmik** [comment]
Its version: 1.68.1
thx for feedback.

**Comment by inverse** [comment]
Same version as here :(

**Comment by alexesprit** [comment]
Doesn't work for me too.

**Comment by alexesprit** [comment]
@protoplazmik can you install the extension from this zip and confirm it's working for you? https://github.com/alexesprit/web-scrobbler/archive/mixcloud-fix.zip

@inverse can you check this zip too?

**Comment by protoplazmik** [comment]
@alexesprit  it works! huge thx :)

**Comment by Kyrremann** [comment]
This patch worked for me too.

**Comment by Gezzaia** [comment]
Patch didn't work for me. :(

**Comment by Gezzaia** [comment]
Ok, back after one day. The scrobbling is erratic. Today the script scrobbled 10 songs and stopped two hours ago, despite listening to the same station on Mixcloud, which has its songs tagged correctly.

**Comment by alexesprit** [comment]
@Gezzaia Looks like they made some internal changes that broke the Mixcloud connector.

**Comment by alexesprit** [comment]
I've fixed Mixcloud connector again. You can install it from master branch until new version is released. Can someone test changes and tell me if everything is ok?

**Comment by Gezzaia** [comment]
Sorry, hasn't worked for me.

**Comment by alexesprit** [comment]
@Gezzaia [How to debug extensions.](https://github.com/david-sabata/web-scrobbler/wiki/How-to-debug-the-extension)

**Comment by Gezzaia** [comment]
Ok, will try that, but can't right now. Sometime tomorrow.

Thanks for your efforts.

**Comment by Gezzaia** [comment]
https://pastebin.mozilla.org/9032075

I hope I did that correctly.

**Comment by inverse** [comment]
Looks like an authentication issue.

Have you tried authenticating with last.fm again in the options?

**Comment by Gezzaia** [comment]
Sure, whenever I reloaded the script and also in between. Now I
authenticated again and nothing has changed.

**Comment by alexesprit** [comment]
@Gezzaia https://github.com/david-sabata/web-scrobbler/wiki/How-to-debug-the-extension#logs-of-content-scripts

**Comment by Gezzaia** [comment]
My new desktop arrived. The problem was on my sons' laptop which I temporarily used. Right now it's working OK on the new PC.

**Comment by Gezzaia** [comment]
Ok, I'm really sorry for coming back to this. I think I will just give up and live with it. But I thought you might want to have this final update.

The new desktop also only scrobbled for a few songs. (Using your debugged master branch link, reauthenticated on last.fm). Here's the log:

https://pastebin.mozilla.org/9032375

**Comment by alexesprit** [comment]
I see no songs are scrobbled, but you said a few songs were scrobbled.

**Comment by alexesprit** [comment]
Also, what happens when songs are not scrobbled? Are they marked as now playing (green note icon) or scrobbled (green tick icon) or unrecognized (gray question icon)?

**Comment by Gezzaia** [comment]
I might have been mistaken. It showed at least the first one as scrobbling but when I check my last.fm profile now I don't see it.

At all the subsequent songs I had/have the same situation. The extension logo is just sitting there (red), saying "This site is supported for scrobbling" when I hover over it; sending me to github through "Is it already playing?"

**Comment by alexesprit** [comment]
@Gezzaia it's stopped working for me too. I fixed Mixcloud connector again for me, can you redownload it, install and test changes?

**Comment by Kyrremann** [comment]
I did a quick test now with Mixcloud, and it now correctly recognise songs.
But, Mixcloud have added a buy link that messes up the recognise of songs.
"Ian Boddy, Erik Wollo  — Buy" should have been "Ian Boddy, Erik Wollo".

**Comment by Gezzaia** [comment]
Downloaded and reauthenticated. The connector works, but observed the same as @Kyrremann 
I had to erase "- Buy" manually and it scrobbled correctly. Though not all songs have this "buy" addendum.

**Comment by alexesprit** [comment]
Fixed again. Now the extension ignores "Buy" label, and I believe the issue is fully resolved.
