### ISSUE TITLE
scrobbler chokes on smart quotes

### ISSUE THREAD

**Issue by ronech** [david-sabata/web-scrobbler#1392]
### Steps to reproduce (for bugs)

1.  Listen to http://www.npr.org/2017/09/05/547854997/first-listen-husker-du-savage-young-du
2.  Songs with a ' (e.g. "Can't See You Anymore") cause the scrobbler to choke with "This song is not recognized"; if you go into the editor, the title is truncated at the apostrophe (e.g., "Can")

### Steps for resolving the issue

- [x] Reauthenticate on Last.fm

- [ ] Try to use unpacked extension from latest master

- [x] Check other issues for duplicates

### Environment

* Version used: 1.68.1
* Browser name and version: macOS 10.12.6 - Chrome Version 60.0.3112.113 (Official Build) (64-bit)

**Comment by alexesprit** [comment]
Thanks for reporting the issue!

Should work fine in the next update; you can install the extesion from the master branch to get it worked until new version is published.

**Comment by ronech** [comment]
Thanks!
