### ISSUE TITLE
Slow down in scrobbling

### ISSUE THREAD

**Issue by inverse** [david-sabata/web-scrobbler#1402]
Since version 2 I've noticed the scrobbling pipeline has slowed down significantly. Did you ever notice this @alexesprit 

I believe it's from the Libre.fm changes that cause a 522 timeout on their servers ( I'm not authenticated ).

## Update

Could be that I'm not able to access libre.fm atm in which case we might want to add sensible timeouts to certain aspects. Opinions?

**Comment by alexesprit** [comment]
Yes, it's same for me. This happens because of Libre.fm is down now. I partially fixed this issue by adding timeouts for all network requests (15 sec).

If it won't be resolved until tomorrow, I'll exclude Libre.fm from the list of track info providers and will publish a patch update.

**Comment by inverse** [comment]
Glad we caught this early on :+1: Always the fun part of relying on 3rd parties.
