### ISSUE TITLE
YT - Music-only scrobbling broken since v. 2.0.0

### ISSUE THREAD

**Issue by Vankog** [david-sabata/web-scrobbler#1403]
### Expected behavior
"Scrobble videos from "Music" category" in Youtube should only scrobble this category. (in conjunction with the "Entertainment" category option)

### Current behavior
It scrobbles other videos as well

### Possible solution
none

### Steps to reproduce (for bugs)
1. enable Options -> Youtube -> "Scrobble videos from "Music" category"
2. enable YouTube scrobbler
3. go to a video in non-Music category. 
e.g. "Gaming": https://www.youtube.com/watch?v=zJm0AKZzlQY
e.g. no category: https://www.youtube.com/watch?v=JdG__35gaR0
4. Scrobbler tries to recognize the title

### Context
- Chrome 61.0.3163.91 (Official Build) (64-bit)
- Last.fm Scrobbler v. 2.0.0

### Steps for resolving the issue
none

**Comment by alexesprit** [comment]
Thanks for reporting!

I've already fixed this issue. I'll publish a new patch update tomorrow.

**Comment by Vankog** [comment]
That's what I figured, when I saw all the commits after the release. ^^

**Comment by Vankog** [comment]
Alright, works fine! 👍
