### ISSUE TITLE
Loose custom settings

### ISSUE THREAD

**Issue by travispaul** [david-sabata/web-scrobbler#1409]
Every so often I notice the extension scrobbling somewhere that I have disabled (I typically notice it on Youtube, where I don't want to scrobble). After checking the options I realize they are ALL enabled, despite only enabling 2 (Google Play Music and Bandcamp).

### Expected behavior
My custom settings should never be cleared. 

### Current behavior
This is possibly happening during either an extension or chrome update. None of my other extensions seem to exhibit this behavior.

### Steps to reproduce (for bugs)
I have not attempted to reproduce. I've only noticed it happening about 3 times over the past few months.

### Context
I don't want to scrobble everywhere.

### Steps for resolving the issue

- [ ] Reauthenticate on Last.fm

- [ ] Try to use unpacked extension from latest master

- [x] Check other issues for duplicates

### Environment

* Version used: 2.0.1
* Browser name and version:  Chrome (macOS Sierra) 61.0.3163.91

**Comment by alexesprit** [comment]
We keep all settings in sync storage since v2.0.0; possibly, this can be related to the issue.

**Comment by inverse** [comment]
Do you think there is a bug between version upgrades?

**Comment by travispaul** [comment]
Could this be caused by signing into Chrome on another system? Perhaps the default settings (all sites enabled) are overwriting my sync settings and then getting pushed to the browser I use most often.

**Comment by alexesprit** [comment]
@travispaul it could, but it shouldn't, because data from server has higher priority.

**Comment by alexesprit** [comment]
@travispaul I'll publish new release in an hour. Could you check if settings are missing after update?

**Comment by travispaul** [comment]
@alexesprit will do!

**Comment by travispaul** [comment]
My settings have persisted after the latest update. Closing this as I'm unable to reproduce. 
Thanks for looking into it.
