### ISSUE TITLE
SiriusXM Online Streaming connector request

### ISSUE THREAD

**Issue by andrewc2** [david-sabata/web-scrobbler#1414]
Does anyone else have SiriusXM that would be willing to look into creating a connector for it?

https://player.siriusxm.com/

```html
<h1 class="np-track-artist" ng-class="{'pdt-navbar-open':vm.navbar.isOpen &amp;&amp; !vm.noAlbumArt}" style="">Cheat Codes <!----><span class="artist-track-separator" aria-hidden="true" ng-if="vm.track.artistName.length > 0 &amp;&amp; vm.track.trackName.length > 0">-</span><!----> No Promises (f. Demi Lovato)</h1>
```

This seems to be the code for the artist / track. 

I'm not really familiar with javascript but I'm happy to provide information from the player and test the connector if someone else doesn't have SiriusXM

**Comment by andrewc2** [comment]
```js
'use strict';

Connector.playerSelector = '#player';

Connector.artistTrackSelector = '.np-track-artist';

Connector.playButtonSelector = '.play';
```

I thought it would be like this, but it isn't scrobbling, is there some kind of debug method?

**Comment by inverse** [comment]
You can view the logging information from the background page. See https://github.com/david-sabata/web-scrobbler/wiki/How-to-debug-the-extension

**Comment by andrewc2** [comment]
Ah, well it's not throwing any errors, so I guess it's just not the right elements.

**Comment by marsjaninzmarsa** [comment]
@andrewc2:
1. `Connector.playButtonSelector = '.play .RegularPlay01';` rather than above, containing `.play` element is always visible.
2. Have you registered your connector in `core/connectors.js`?
3. No errors, or no info in console at all? Correctly registered connector should generate bunch of debug info in logs (indicating matched URL, injected scripts, detected player state etc)...

**Comment by andrewc2** [comment]
1. Ooh okay I'll try that.
2. I think so, the icon shows up saying "this site is supported for scrobbling"
3. I see the connector get loaded but nothing more. It made me think my connector code was just that far off.

**Comment by andrewc2** [comment]
Thanks to everyone's help this is now a working connector! I've opened a pull request with the implementation.
