### ISSUE TITLE
service error 

### ISSUE THREAD

**Issue by laufun** [david-sabata/web-scrobbler#1416]
''Some service error was occurred

Looks like something went wrong while scrobbling the music. Please open options page and try to reauthenticate with services. If reauthentication doesn't help, and you still see this message, please create a new issue at the GitHub project page.''

I already tried reautheticating...

**Comment by alexesprit** [comment]
[How to debug extensions.](https://github.com/david-sabata/web-scrobbler/wiki/How-to-debug-the-extension)
