### ISSUE TITLE
Saving edited album info in new "Edited Tracks" tab

### ISSUE THREAD

**Issue by hans-juergen** [david-sabata/web-scrobbler#1418]
I just noticed that the new version saves edited tracks under a new tab in the options which is great. But it seems that it actually only saves edited track info, not edited album info, as I have edited some albums recently to test that new feature, but could not find them in the new tab. It would be nice to have all edited album infos saved as well, as they will come up quite often and would not have to be edited manually the next time.

**Comment by alexesprit** [comment]
The extension is already saves album info (at least it supposed to save).

Also I can't understand what you mean by "new tab".

**Comment by hans-juergen** [comment]
Here is a copy of my Edited Tracks:

> Tito & Tarantula — In My Car - Live 2008 Bonn
> David Bowie — Ziggy Stardust - Live
> Tito & Tarantula — End of Everything - Live 2008 Bonn

For example I edited the David Bowie scrobble by adding the missing album info ("A Reality Tour"), but this is not saved here. With "new tab" I just meant the new option to view the saved edited tracks.

**Comment by alexesprit** [comment]
The album info is actually saved in the storage, but it isn't displayed in the modal window (the one you called "new tab").

**Comment by marsjaninzmarsa** [comment]
> it isn't displayed in the modal window

…and should be.

**Comment by alexesprit** [comment]
@marsjaninzmarsa Probably. Have you any thoughts on where exactly to place album info?

**Comment by marsjaninzmarsa** [comment]
@alexesprit album thumbnail with album name on hover would be perfect, but AFAIK it would require more data stored per item. I must look into code, but caching Last API response data for track in storage may not be as bad idea…?

**Comment by alexesprit** [comment]
> album name on hover would be perfect

@marsjaninzmarsa it doesn't look hard to implement this feature, but album thumbnail is overkill.

**Comment by alexesprit** [comment]
@marsjaninzmarsa @hans-juergen is it fine?
![image](https://user-images.githubusercontent.com/1119267/31306817-45e6fd7c-ab60-11e7-90e4-5d1ec4728d67.png)

The tip is not displayed if no album title is saved.

**Comment by marsjaninzmarsa** [comment]
Good enough. :wink:

**Comment by hans-juergen** [comment]
OK, it would be a confirmation that the added album info has indeed been saved. And edited tracks will be automatically scrobbled next time like they are saved in this window, right?

Using the new version of the extension I also noticed that sometimes scrobbles are duplicated for no apparent reason. I tried to find out why, but can only guess: maybe this only happens with long tracks over 8 minutes, and/or it happens when another track cannot be scrobbled at all, so the duplicate would be some kind of a placeholder for the missing scrobble?

**Comment by marsjaninzmarsa** [comment]
> Using the new version of the extension I also noticed that sometimes scrobbles are duplicated for no apparent reason. I tried to find out why, but can only guess: maybe this only happens with long tracks over 8 minutes, and/or it happens when another track cannot be scrobbled at all, so the duplicate would be some kind of a placeholder for the missing scrobble?

Are you sure that there are separate scrobbles and no "Now listening" information displayed concurrently with proper scrobble?

**Comment by hans-juergen** [comment]
Yes, I have checked the duplicates in my recent tracks list and deleted them there. I will keep an eye on it how often this happens and with which tracks. I am using the extension in Opera 48 stable version on Windows 10, by the way.

**Comment by alexesprit** [comment]
> OK, it would be a confirmation that the added album info has indeed been saved. And edited tracks will be automatically scrobbled next time like they are saved in this window, right?

No, I just added a tooltip that contains album title. And yes, tracks that are saved in local cache will be scrobbled with data (including album title) from the cache.

>  I tried to find out why, but can only guess: maybe this only happens with long tracks over 8 minutes, and/or it happens when another track cannot be scrobbled at all, so the duplicate would be some kind of a placeholder for the missing scrobble?

You are probably right, this happens with long tracks. Anyway, it's another issue to discuss.

**Comment by hans-juergen** [comment]
OK, should I open a new issue and copy my report there, or can you split this thread?
