### ISSUE TITLE
Scrobbler scrobbles only 1st song (WFMU)

### ISSUE THREAD

**Issue by surfinzap** [david-sabata/web-scrobbler#1420]
Player URL: [WFMU](https://wfmu.org/audioplayer/?p=http://stream0.wfmu.org/freeform-128k&t=Duane%20Train&song=%22Gimme%20that%20Sammich%22%20by%20Charles%20Wright&currentStream=WFMU%20Live%20Stream)

### Expected behavior
* Given you open [WFMU](https://wfmu.org/audioplayer/?p=http://stream0.wfmu.org/freeform-128k&t=Duane%20Train&song=%22Gimme%20that%20Sammich%22%20by%20Charles%20Wright&currentStream=WFMU%20Live%20Stream) player 
* And the player scrobbles artist / title of the current track 
* When the new song starts 
* Then it gets scrobbled as well

### Current behavior
* Given you open [WFMU](https://wfmu.org/audioplayer/?p=http://stream0.wfmu.org/freeform-128k&t=Duane%20Train&song=%22Gimme%20that%20Sammich%22%20by%20Charles%20Wright&currentStream=WFMU%20Live%20Stream) player 
* And the player scrobbles artist / title of the current track 
* But when the new song starts 
* Then it isn't scrobbled 

### Context
* When I open a dev tools, there is one event "connector_state_changed" shown after player starts for the first time. However as the radio goes on and songs change, the event "connector_state_changed" is not fired anymore
* I'm not sure whether this is the issue of scrobbler or WFMU connector
* If it's an issue with a WFMU connector, I would be glad for any help pointing out the problem so I can fix it, since I did it (i.e. if there is a similar connector/radio I could learn the implementation)

### Environment
* Version used: latest master branch (Oct 4th, 2017)
* Browser name and version: Google Chrome Version 63.0.3231.0 (Official Build) canary (64-bit)

**Comment by alexesprit** [comment]
I suppose this happens because of wrong player selector. Can you change it to `.audioplayer` and test the connector?

**Comment by surfinzap** [comment]
@alexesprit I'll test it out and let you know.

**Comment by surfinzap** [comment]
That does it. I've already sent pull request in the [following commit](https://github.com/david-sabata/web-scrobbler/pull/1434/commits/8e6988ed6bb80aafd21277163671503266b64b0d). Thanks for the help!
