### ISSUE TITLE
Missing extension icon in Toolbar Firefox Beta & Nightly (57 & 58)

### ISSUE THREAD

**Issue by scheinercc** [david-sabata/web-scrobbler#1423]
The extension installed without a problem except of the missing extension icon and the corresponding functionality. The initial notification appeared, adding last.fm worked liked a charm and it is scrobbling like champion. 
I installed it quickly in Chrome to see the "install-flow" and the icon. Works fine there.

### Expected behavior
The extension icon appears in Firefox's Toolbar during or after the installation

### Current behavior
The extension icon is missing in the Toolbar after the installation

### Steps to reproduce (for bugs)
1.  Download https://nightly.mozilla.org
2.  Install WS extension
3.  Confirm prompts during installation

### Context
Quick temporary disabling of the extension via the Toolbar icon not possible

### Environment

* Version used: 2.0.1
* Browser name and version: Firefox Nightly 58.0a1 (2017-10-06); Firefox Developer Edition 57.0b6

**Comment by alexesprit** [comment]
Firefox hides page action icons while page navigation, and I'm not sure if it's on the extension side. Btw, the icon is displayed all the time on several sites (e.g. Google Play Music) and becomes hidded while navigation on other ones (Spotify). Don't know why it behaves differently.

**Comment by scheinercc** [comment]
Thanks @alexesprit - Found it! 

<img width="237" alt="image" src="https://user-images.githubusercontent.com/817856/31304380-b04a9600-ab6b-11e7-812b-87a9ebbb30cc.png">

... in all it's glory
<img width="367" alt="image" src="https://user-images.githubusercontent.com/817856/31304460-de1bd21e-ab6c-11e7-9643-be7d76e21ca7.png">


It's the first time I encounter a "page action icon" and was expecting a "normal"(?) extension icon. As you might know Youtube only displayed it after a track started playing. 

If there is no easy way for you to display it at least ones with explanation during the installation, this might be something worth to file a bug over at bugzilla for I'd say.
It might also be an idea to change the FAQ answer a little as it is not in the "extension bar"
> You can do that by right-clicking on the extension icon in the extension bar.

Would it be possible to maybe add a screenshot like mine (just better ;) ) there?

**Comment by alexesprit** [comment]
> It might also be an idea to change the FAQ answer a little as it is not in the "extension bar"

Yes, you're right. There's already fix for this (see #1412 for details), which is merged.

> Would it be possible to maybe add a screenshot like mine (just better ;) ) there?

That makes sense. Thanks for the suggestion!

**Comment by scheinercc** [comment]
@alexesprit FYI, I also filled a bug. Feel free to follow it or comment https://bugzilla.mozilla.org/show_bug.cgi?id=1406604

**Comment by alexesprit** [comment]
I submitted [another issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1406765).

**Comment by scheinercc** [comment]
Cool, I simply linked them for now. Lets hope someone has time soon to check them out and then we see how the two tasks might interact with each other.

**Comment by scheinercc** [comment]
Hey Alex,

Do you reckon it would be possible to have a grey/disabled icon on unsupported pages?

Currently unsupported page:
<img width="128" alt="image" src="https://user-images.githubusercontent.com/817856/32322859-15498238-c01a-11e7-9799-0d9bf5139549.png">

Supported page:
<img width="119" alt="image" src="https://user-images.githubusercontent.com/817856/32322871-212de698-c01a-11e7-9802-a77195ef17d9.png">

**Comment by alexesprit** [comment]
Hey @scheinercc

Gray icon is already used for disabled websites. I think using the same icon for unsupported sites might be confusing. But I like the idea to add an icon to unsupported pages. We could also have a popup with an URL to GitHub Issues, where users can request new connectors.

**Comment by scheinercc** [comment]
Update: there is now a default extension icon since today (58.0a1) instead of nothing 
<img width="120" alt="image" src="https://user-images.githubusercontent.com/817856/32375055-5fd8cfc2-c0f4-11e7-9b1d-d66bcd8c0b6e.png">

**Comment by alexesprit** [comment]
@scheinercc I added a new icon for unsupported pages:
![image](https://user-images.githubusercontent.com/1119267/32411988-feb47874-c1fa-11e7-819e-f75a0265ca1c.png)

The extension now uses `chrome.browserAction` instead of `chrome.pageAction`, since the first one is recommended, when an extension uses icons for all websites. Intrestingly, the browser action has the same issue as the page action — it hides after AJAX navigation (btw, I added a workaround for that issue).

**Comment by scheinercc** [comment]
Ah, cool. Ok. I guess I will see this change coming through with the next plugin update? I guess we close this bug then :)

**Comment by alexesprit** [comment]
Interestingly that FF57 released today displays a browser action (page action) icon correctly even w/o workaround I added in 56ee903b527081043dc0be2f7052be49e98dd034. But there's another minor bug related to browser action icon I'll probably fix in next patch update.

FF58 and FF59 still hide the icon while navigation, though.

**Comment by scheinercc** [comment]
Thanks for the update, Alex.
