### ISSUE TITLE
Unable to get auth URL for Last.fm on second machine

### ISSUE THREAD

**Issue by lidel** [david-sabata/web-scrobbler#1427]
### Expected behavior

User should be able to use extension on multiple machines with settings synced via Firefox Sync.

### Current behavior / Replication steps
0. I've got Firefox Sync set up on my two machines
1. I've set up the web-scrobbler add-on on one machine, got auth token from last.fm, everything works as expected. Songs get scrobbled 👌 
3. I've installed the web-scrobbler add-on on another machine. 
    - I noticed that my custom settings were synced via Firefox Sync (eg. scrobbling was enabled only on Google Music, Youtube was disabled), but I was logged out of Last.fm
    - When I tried to log-in to Last.fm I got this error on the Browser Console:
       > ![2017-10-08-161224_674x151_scrot](https://user-images.githubusercontent.com/157609/31317671-797066fc-ac45-11e7-833b-4d484ec335b9.png)

   At the first glance it looks like the use case of syncing settings does not work correctly. Would be great if someone is able to reproduce, to eliminate the possibility of issue being on my end.

### Environment

* Version used: 2.0.1
* Browser name and version: Firefox 56

**Comment by alexesprit** [comment]
The extension does not sync auth settings.

**Comment by lidel** [comment]
Ok, then we probably have a bug/misconfiguration  that prevents me from logging-in to Last.fm.
I've created a new Firefox profile _without sync_ on the same box and it works fine (I was able to log-in).
Is there anything I could set/check to provide more debugging information?

**Comment by alexesprit** [comment]
Users reported certain extensions can block Web Scrobbler, e.g. uMatrix. Have you any extension installed which could block network requests?

**Comment by lidel** [comment]
Ah, it was indeed due to uMatrix! Thank you for mentioning it.

I was using a "stable" release of uMatrix. 
After I've updated it to the latest developer version (1.0.1rc4), the issue is gone.
Now I can use both web-scrobbler and uMatrix.

Thanks again, closing as solved.
