### ISSUE TITLE
Chrome extension average update ETA?

### ISSUE THREAD

**Issue by Ma5onic** [david-sabata/web-scrobbler#1436]
How long do you guys usually wait to update extension? Is there a to-do list? 
I would love to help out!

**Comment by alexesprit** [comment]
There's no certain ETA since it's an open-source project, and we contribute to when we have some time. It's usually about a month between minor updates (they contain a lot of changes, though!).

We also have no todo list, but you can view all open issues to find something you could improve.

**Comment by bykidi** [comment]
Additional wiki & how to compile and test on your own would be nice addition
(firefox user)

**Comment by alexesprit** [comment]
https://github.com/david-sabata/web-scrobbler/wiki/Setup-development-environment

Haven't describe how to install the extension from sources (Firefox). If it's needed, I'll make a new howto page soon.

**Comment by bykidi** [comment]
That's enough, thank you!
