### ISSUE TITLE
Plex Scrobbling not working

### ISSUE THREAD

**Issue by calvinc64** [david-sabata/web-scrobbler#1442]
### Expected behavior
I've activated Scrobbling for PLEX on the Plugin settings... but nothing happens.
And this Problem is present on app.plex.tv and on the local server IP.

### Current behavior
Maybe there is a Problem with the Regex... because the Title is shown in the Browser-Tab!
If so you may can help me... maybe I can fix it by my self with some help.

### Possible solution
Maybe it will help when the Regex of the Plex detection will be overdone some time soon...

### Steps to reproduce (for bugs)
Can't really reproduce this... but 
![image](https://user-images.githubusercontent.com/5560381/31842058-a4dda498-b5ec-11e7-8f88-4b5d22757e37.png)
will maybe describe it better....

### Environment

Browser Version: Chrome: Version 61.0.3163.100 (Offizieller Build) (64-Bit)
Plex-Server: Version 1.9.2.4285 (Running on a Freenas Jail)
Web-Scrobbler: 2.1.0

**Comment by xyauhideto** [comment]
I made some changes that might help:
- add a a new match pattern `*://*.plex.tv/desktop*`
- detect the player type by a selector rather than the `url`

You could try the branch following the [unpacked-extension](/david-sabata/web-scrobbler#unpacked-extension) instruction to check if it works.
