### ISSUE TITLE
Random cover art

### ISSUE THREAD

**Issue by OwnageIsMagic** [david-sabata/web-scrobbler#1443]
![image](https://user-images.githubusercontent.com/10534634/31845107-454cf1ae-b606-11e7-94ee-1ac7eba5d5c9.png)
[last.fm cover](https://www.last.fm/music/%D0%BC%D0%BE%D0%BD%D0%B5%D1%82%D0%BE%D1%87%D0%BA%D0%B0/_/%D0%9F%D1%80%D0%B0%D0%B7%D0%B4%D0%BD%D0%B8%D0%BA+%D0%9A%D0%BE%D0%BD%D1%82%D1%80%D0%BD%D0%B0%D1%81%D0%B8%D0%BB%D0%B8%D1%8F) is empty 

### Environment

* Version used: 2.1.0
* Browser name and version: FF 57.0b9 (64-bit)

**Comment by alexesprit** [comment]
The extension downloads cover arts from CoverArtArchive, if Last.fm returns nothing. But CoverArtArchive sometimes returns wrong cover arts.
