### ISSUE TITLE
Connection Request: scrobble from ccmixter.org

### ISSUE THREAD

**Issue by douglasawh** [david-sabata/web-scrobbler#1445]
I'd like to be able to scrobble from http://ccmixter.org/

### Expected behavior

Just an additional site request

### Current behavior

It just doesn't do it right now.

### Context

When i got to a page such http://ccmixter.org/people/Reiswerk I'd like to be able to scrobble those tracks.
There are also pages like http://ccmixter.org/view/media/remix/picks that have a slightly different format

**Comment by alexesprit** [comment]
The extension now supports ccMixter scrobbling, thanks to @xyauhideto.
