### ISSUE TITLE
Handle Gaana songs with no artist information

### ISSUE THREAD

**Issue by dufferzafar** [david-sabata/web-scrobbler#1450]
Song URL: https://gaana.com/song/chalti-hai-kya-9-se-12

### Expected behavior
Detect that the music is playing and notify that some information couldn't be identified.

### Current behavior
No music is detected to be playing

### Possible solution
I think we should assume that artist info might be missing while writing the code.

### Steps to reproduce (for bugs)
Visit above URL; scrobbler can't detect music playing.

### Context
Just trying to play a song.

**Comment by alexesprit** [comment]
Can't reproduce. Please make sure you're using v2.1.0 version.
![Imgur](https://i.imgur.com/v1CPIKD.png)

**Comment by dufferzafar** [comment]
Yeah, I am not able to reproduce it from the song page.

But @alexesprit try this: https://gaana.com/search/9%20se%2012

Playing the song from here, does not trigger last.fm scrobbling. 

![image](https://user-images.githubusercontent.com/1449512/31886456-f80043c0-b811-11e7-9817-b146bd4a9fce.png)

**Comment by alexesprit** [comment]
Works fine too.

**Comment by alexesprit** [comment]
@dufferzafar I also noticed player bar looks differently on our screenshots:
![image](https://user-images.githubusercontent.com/1119267/31898958-1cb9bc1c-b823-11e7-9698-882ef002d4a7.png)

**Comment by alexesprit** [comment]
@dufferzafar I reproduced this issue on Firefox.

Unfortunately, I have no idea how to resolve it. Gaana connector is tricky and gets artist name via HTTP request using album URL. But by unknown reason this URL is missing in Firefox.
