### ISSUE TITLE
Anghami scrobbling issues

### ISSUE THREAD

**Issue by vixenoshia** [david-sabata/web-scrobbler#1452]
So far i had problems with these 2 albums:
 https://www.anghami.com/album/1684878
https://www.anghami.com/album/2769851

### Expected behavior

It should scrobble them to last.fm but it doesn't

### Current behavior
I notice the last.fm scrobble extension icon keeps flickering from the search icon to the "it has been scrobbled" green icon.

### Context
i am no coder or understand how these work so idk

**Comment by vixenoshia** [comment]
why closed?

**Comment by alexesprit** [comment]
Because this issue is fixed.

**Comment by Korina34** [comment]
This is still an issue so why is it closed?

**Comment by alexesprit** [comment]
New version which will be released soon works fine with Anghami.
