### ISSUE TITLE
Old firefox/palemoon support

### ISSUE THREAD

**Issue by lazyest** [david-sabata/web-scrobbler#1457]
There still a number of old FF versions working for some reasons and also palemoon browser mostly being FF 27 or something, with old-fashioned interface and lower resources consuming. Maybe its possible to do some scrobbler version, working with it?

**Comment by alexesprit** [comment]
This extension is powered by WebExtensions, which isn't supported by Palemoon and older Firefox versions. To add support for these browsers we should totally rewrite the exension.

**Comment by lazyest** [comment]
that's an answer I was afraid to receive. Ok, sad but true but someone had to ask anyway ;-)
