### ISSUE TITLE
Option that divide track name by "-" and fill inputs right

### ISSUE THREAD

**Issue by ershovdev** [david-sabata/web-scrobbler#1463]
There are a lot of tracks in SC with name of the track like "sb who load that track" - "real track author - real track name" (e.g. "House" - "Lana Del Rey - Summertime Sadness") and that why after scrobbling on last.fm there are wrong author and name in tracks. 

so it could be cool feature - option that allow to divide track name "real track author - real track name" by "-", fill all inputs respectively and then send to last.fm right track info.

**Comment by alexesprit** [comment]
Could you provide an URL to a such track?

**Comment by ershovdev** [comment]
https://soundcloud.com/tsimashei/max-sajnev-remix
https://soundcloud.com/kharcho/s3yljrq6e93q
https://soundcloud.com/godxtsar/last-disco

then i scrobbling, last.fm could get author names like "xXx_MusicLover_xXx", so recommendations, statistic and all that things work wrong.

there are almost every second track with name like this. however, sometimes track could be published from official account with real author name, so in your code it could be test like if "-" not isset then get author from author field, if isset then get author before "-" in track name field.

**Comment by alexesprit** [comment]
Fixed in e86b9ed7d47987499a3bb96ff0e98eb0407d6a26.

**Comment by alexesprit** [comment]
Also made some other fixes, and now the extension should recognize tracks like [this](https://soundcloud.com/monetochkamusic/zwnb46e0ea5l) correctly too.

**Comment by ershovdev** [comment]
yep, now works fine. thank you so much for the attention to that problem. strange, that nobody didn't tell about that earlier.
