### ISSUE TITLE
Add support for gimmeradio.com

### ISSUE THREAD

**Issue by Sh4gr4th** [david-sabata/web-scrobbler#1464]
Gimmeradio is a online music station with real DJs.  
Since "Mr. Trash Metal himself" Dave Mustaine is going to have a weekly 2h show on it, starting @ 11/09/2017 I stumbled upon this website and was wondering if they could be added since I am definitely going to listen to them more often. 
Maybe there are more users who would like to see it added?

**Comment by Daimonion1980** [comment]
Yes, scrobbling support for gimmeradio would be awesome. I heard so many new songs and bands and would love them to be seen on my scrobbles.

**Comment by alexesprit** [comment]
@Sh4gr4th @Daimonion1980 This website uses obfuscacted class names, and I'm not sure they're the same for all users. Could you check the extension from this zip: https://github.com/alexesprit/web-scrobbler/archive/feature/gimmeradio.zip and tell if scrobbling from Gimme Radio works or not?

**Comment by Sh4gr4th** [comment]
@alexesprit 
It seems to work just fine for me. Notification popped up and last.fm shows "is scrobbling".  Great! 👍 Thank you so much!

**Comment by alexesprit** [comment]
@Sh4gr4th Thanks! I'll push these changes to master branch, so scrobbling from Gimme Radio will be available in the next release.
