### ISSUE TITLE
Failing to recognize album

### ISSUE THREAD

**Issue by OwnageIsMagic** [david-sabata/web-scrobbler#1469]
It fetches cover and insert track info but doesn't auto scroble
![image](https://user-images.githubusercontent.com/10534634/32503250-cd94ab8e-c3ed-11e7-9c2a-f598a849ee60.png)
https://www.last.fm/music/Popeda/Atlas+Stands
https://musicbrainz.org/release/3d3a0ec0-2957-43df-a0a4-1dcc04a7f78a

**Comment by alexesprit** [comment]
This track is not known by Last.fm, that's why it wasn't scrobbled.

**Comment by OwnageIsMagic** [comment]
https://www.last.fm/music/Popeda/Atlas+Stands/Atlas+Stands
Scrobbles
574

**Comment by OwnageIsMagic** [comment]
ok i get it
last.fm uses wrong band name ( Popeda instead of Pobeda )

**Comment by OwnageIsMagic** [comment]
but it scrobbles as popeda 
Can I disable auto corrections?

**Comment by alexesprit** [comment]
No, there's no a such feature.
But you can force scrobbling of unknown songs (if they're really unknown).

**Comment by OwnageIsMagic** [comment]
Can you add button to temporary disable scrobbling from current page? I don't want to scrobble tracks with bogus metadata and skipping 7 tracks seems tedious

**Comment by alexesprit** [comment]
We have an option to disable scrobbling for a tab (until it's closed). Is this acceptable for you?

**Comment by OwnageIsMagic** [comment]
Yes, this is what I mean

**Comment by OwnageIsMagic** [comment]
btw, user menu isn't recreated after icon reappears (#1455)
![image](https://user-images.githubusercontent.com/10534634/32510483-cc51b992-c401-11e7-8693-a342eeca7f81.png)

**Comment by alexesprit** [comment]
Ok, will look into that.

**Comment by OwnageIsMagic** [comment]
since FF 58 https://github.com/david-sabata/web-scrobbler/issues/1469#issuecomment-342575563 no longer problem
![image](https://user-images.githubusercontent.com/10534634/32547451-712a68e2-c493-11e7-8f49-ba31fdc97d0c.png)

**Comment by alexesprit** [comment]
![image](https://user-images.githubusercontent.com/1119267/32691124-46182b0c-c714-11e7-80d8-427208686258.png)
Next version now uses a browser action icon which is visible all the time along with the context menu.
