### ISSUE TITLE
Trim spaces

### ISSUE THREAD

**Issue by OwnageIsMagic** [david-sabata/web-scrobbler#1470]
I'm deleting ` (Remastered 2007)`
And if I left space it can't guess album name
![image](https://user-images.githubusercontent.com/10534634/32508801-90cd34aa-c3fc-11e7-955e-1f4c2f139ae5.png)

**Comment by alexesprit** [comment]
Aah, yes, missed that. Will fix it in a couple of days.

Btw, we have sort of "Remastered" filter which removes "Remastered"-like labels. How do you think, is it worth applying this filter to VK connector? I don't listen to VK music too much, so I don't know how many remastered tracks they contain.

**Comment by OwnageIsMagic** [comment]
I only encounter Remastered label on Blind Guardian songs
Also search shows that there is only 250k tracks
![image](https://user-images.githubusercontent.com/10534634/32509565-b46065b6-c3fe-11e7-9dd6-38daa37c874f.png)
