### ISSUE TITLE
mixcloud not scrobbling. tried restart, and disconnected/reconnected connector but no songs are being scrobbled from mixcloud.

### ISSUE THREAD

**Issue by rudegirlb** [david-sabata/web-scrobbler#1473]
### Steps to reproduce (for bugs)

1.  
2.  
3.  

### Steps for resolving the issue

- [ ] Reauthenticate on Last.fm

- [ ] Try to use unpacked extension from latest master

- [ ] Check other issues for duplicates

### Environment

* Version used:
* Browser name and version:

**Comment by alexesprit** [comment]
Can't reproduce:
![image](https://user-images.githubusercontent.com/1119267/32691066-69598cb0-c713-11e7-8869-c38197e7c779.png)

**Comment by kustek** [comment]
Confirm can't scrobble.

**Comment by alexesprit** [comment]
[How to debug the extension.][1]

[1]: https://github.com/david-sabata/web-scrobbler/wiki/How-to-debug-the-extension

**Comment by BenTen** [comment]
hello,
For me too, it doesn't work.
I used **Firefox ESR** 52.5.2 64 bit.
Is it compatible with this version of Firefox?

**Comment by bykidi** [comment]
@BenTen it is 'should' or 'may' work, but use latest stable Firefox Quantom, because it is based on web-extensions (which this addon for sure was made for)

**Comment by OwnageIsMagic** [comment]
@bykidi Quantum
ESR have webext support under flag
But this ext won't work https://github.com/web-scrobbler/web-scrobbler/issues/1538#issuecomment-352815907
