### ISSUE TITLE
Plex Scrobbling Not Working

### ISSUE THREAD

**Issue by rastating** [david-sabata/web-scrobbler#1477]
Plex is detected, but no scrobbling occurs - upon inspection of the connector file (`connectors/plex.js`), and cross comparison with the markup on the page, it looks like the class names have changed.

The current selectors are as follows:

```javascript
function setupRemoteUI() {
	Connector.playerSelector = '[class^=MiniPlayerContainer-miniPlayer]';

	Connector.artistSelector = `${Connector.playerSelector} [class*=MetadataPosterTitle-title] > a:nth-child(1)`;

	Connector.trackSelector = `${Connector.playerSelector} [class*=titlesContainer] > a`;

	Connector.albumSelector = `${Connector.playerSelector} [class*=MetadataPosterTitle-title] > a:nth-child(3)`;

	Connector.playButtonSelector = `${Connector.playerSelector} [class^=plex-icon-player-play]`;

	Connector.timeInfoSelector = `${Connector.playerSelector} [class^=DurationRemaining-container]`;
}
```

Looking at the markup though on a local Plex installation, the classes are the same, but with a unique identifier appended to the class name, every time a song change occurs, e.g.:

```html
<span class=" MetadataPosterTitle-title-3tU5F MetadataPosterTitle-isSecondary-2VUxY  ">
```

## Possible Solution
If wildcards can be implemented, then this should be resolvable I believe, by just appending `-*` to the end of the class names.

## Environment Details
Plex version: **3.23.1**

**Comment by rastating** [comment]
Upon further reading - it looks like the `class*=` indicates to the browser to find classes that contain the value, so the code is already doing what I suggested. So, not too sure what possible solution is 😢

**Comment by alexesprit** [comment]
Yes, @xyauhideto made some changes in PLEX connector recently.

**Comment by alexesprit** [comment]
@rastating could you check the updated extension (v2.2.0)?

**Comment by rastating** [comment]
@alexesprit - just tested both FireFox and Chrome extensions, it now detects the songs being played :) I have found another [minor] issue, but it is different to this one, so I'll open it in a new issue as to not mix the two!
