### ISSUE TITLE
The disappearing icon

### ISSUE THREAD

**Issue by Rostov84** [david-sabata/web-scrobbler#1483]
After update to version 2.2.0, the extension icon disappears during scrobbling. The problem is with Windows 7 Home Premium (x64) & Firefox 56.0.2 (x64)

**Comment by Rostov84** [comment]
Also, the songs are scrobbled correctly, but I can not verify that title and artist informations are displayed correctly.

**Comment by alexesprit** [comment]
@Rostov84 could you record a screencast with this issue being reproduced?

Could you also check if icon is displayed all the time on FF57?

**Comment by Rostov84** [comment]
Here is a recording from Firefox 56.0.2:

[https://www.4shared.com/s/f5C0qn_muei](url)

The icon disappears after entering YouTube.

In the evening I will check if the problem is also in FF 57.

**Comment by alexesprit** [comment]
I can't download from 4shared, but if you mean this (see screenshot below) I reproduced it too.
![image](https://user-images.githubusercontent.com/1119267/32852376-bed5f7cc-ca48-11e7-9a7b-12978b94d3c8.png)

FF57 works fine.

**Comment by Rostov84** [comment]
Yes, I meant exactly what you showed on screenshot. Will it be fixed?

I can't update Firefox to version 57 because it doesn't support the extensions I use.

**Comment by IRainman** [comment]
@Rostov84 I think that it is not necessary. You just have to wait until the icon is replaced in the extension.

**Comment by Rostov84** [comment]
@IRainman, if only I knew where these icons found and how to do it, I could do it myself.

**Comment by OwnageIsMagic** [comment]
@Rostov84 If you do this you will no longer be able to receive auto updates

**Comment by Rostov84** [comment]
@OwnageIsMagic, OK, now I understand. So I just have to wait. Thanks!

**Comment by Rostov84** [comment]
@alexesprit when can we expect a bug fix?
