### ISSUE TITLE
Short songs not scrobbling

### ISSUE THREAD

**Issue by rastating** [david-sabata/web-scrobbler#1485]
When listening to a short song (i.e. 30-45 seconds long), it is detected and last.fm will indicate it is currently being scrobbled, but at the end of the song, it seemingly never "finalises" that, and doesn't record it.

### Steps to reproduce (for bugs)
1. Play a song that is short, such as https://www.last.fm/music/NOFX/_/I+Wanna+Be+an+Alcoholic
2. Watch progress on last.fm profile page

### Environment
* Version used: **2.2.0**
* Browser name and version: **Google Chrome 62.0.3202.89 x64 (Linux) and FireFox 56.0 x64 (Linux)**
* Connector used: **Plex**

**Comment by alexesprit** [comment]
According to Last.fm guidelines scrobblers should scrobble tracks with 30 or more seconds only.

Is a some purpose to scrobble such short tracks?

**Comment by inverse** [comment]
As per the Last.fm Scrobbling Guidelines

>  The track must be longer than 30 seconds.
And the track has been played for at least half its duration, or for 4 minutes (whichever occurs earlier.)

See: https://www.last.fm/api/scrobbling

@alexesprit is this an edge case we have on the 30 sec bounds?

**Comment by rastating** [comment]
I had a feeling Last.fm may have had rulings on it, to try and reduce things being spammed (makes sense, given there can't be many songs out there that are so short). Thought I'd raise the issue just in case it was something no one was aware of though :smile:

**Comment by alexesprit** [comment]
@rastating I've updated scrobbling algorithm and now the extension should scrobble 30-45 sec tracks fine. I didn't change length limitation.
