### ISSUE TITLE
VK.com in latest version not working properly

### ISSUE THREAD

**Issue by IRainman** [david-sabata/web-scrobbler#1486]
I am trying to scrobble track on my music page  https://vk.com/audios3735913 , and only one track is scrobbling now. After I reload the page is other one track is scrobbling. 

* Version used: 2.2.0
* Browser name and version: 56.0.2 32 bit on Windows 7 SP1 64bit.

P.S. I am not sure, probably it is not an issue with extension.

**Comment by inverse** [comment]
It's working here for me on `2.2.0`.

**Comment by OwnageIsMagic** [comment]
See also https://github.com/david-sabata/web-scrobbler/issues/1455

**Comment by alexesprit** [comment]
I reproduced this one on FF57. Closing this in favor of #1455.
