### ISSUE TITLE
last fm will not scrobble from chrome today

### ISSUE THREAD

**Issue by dumluk2002** [david-sabata/web-scrobbler#1488]
### Steps to reproduce (for bugs)

1.
2.
3.

### Steps for resolving the issue

- [ ] Reauthenticate on Last.fm

- [ ] Try to use unpacked extension from latest master

- [ ] Check other issues for duplicates

### Environment

* Version used:
* Browser name and version:

**Comment by inverse** [comment]
We need more context to be able to solve this one.

**Comment by dumluk2002** [comment]
When I play pandora on Google Chrome, it wont scrobble.  the message says scrobbler does not support that website

**Comment by inverse** [comment]
I'm unable to access Pandora from here so am unable to verify.

**Comment by leoos** [comment]
I'm using Google Play Music on the below version of Chrome on MacOS 10.13.1
Version 62.0.3202.94 (Official Build) (64-bit)

I am also getting a message saying This website is not supported from Last.fm Scrobbler.

I'm pretty sure this is related to this new version of Google Chrome.

I had no problems scrobbling from Chromium on Linux Mint 18.2 yesterday.
I don't have the version of that browser to hand as I am not at that machine today.

**Comment by xyauhideto** [comment]
Both sites (Pandora through VPN) worked fine with the version 2.2.0 on Win10, Chrome Canary 64.0.3269.0 64 bit in my tests.

**Comment by leoos** [comment]
Scrobbling working ok on Google Play  Music on below version of Chrome on Mac OS 10.13.1 
Version 60.0.3112.78 (Official Build) (64-bit)

The Chromium version I'm running which works on Linux Mint 18.2 is as below
Version 62.0.3202.75 (Official Build) Built on Ubuntu , running on LinuxMint 18.2 (64-bit)

**Comment by alexesprit** [comment]
@dumluk2002 [How to debug the extension.][1]

[1]: https://github.com/david-sabata/web-scrobbler/wiki/How-to-debug-the-extension
