### ISSUE TITLE
Youtube.com 

### ISSUE THREAD

**Issue by robiannelli** [david-sabata/web-scrobbler#1489]
### Steps to reproduce (for bugs)

1.
2.
3.

### Steps for resolving the issue

- [ ] Reauthenticate on Last.fm

- [ ] Try to use unpacked extension from latest master

- [ ] Check other issues for duplicates

### Environment

* Version used:
* Browser name and version:

**Comment by alexesprit** [comment]
Can you describe the issue more clear?

**Comment by CalidrisO** [comment]
YouTube will not scobble while being watched on Chrome.  I get the message that "The connector code for this specific website needs to be updated."  How do I do this?

**Comment by alexesprit** [comment]
[How to debug the extension.][1]

[1]: https://github.com/david-sabata/web-scrobbler/wiki/How-to-debug-the-extension
