### ISSUE TITLE
Layout problem with long titles

### ISSUE THREAD

**Issue by OwnageIsMagic** [david-sabata/web-scrobbler#1490]
![image](https://user-images.githubusercontent.com/10534634/32862908-b32dff6a-ca6a-11e7-93d9-8304778bb7e4.png)
ff 58

**Comment by alexesprit** [comment]
I can fix it by two following ways:
![image](https://user-images.githubusercontent.com/1119267/32979363-e5e3fa62-cc64-11e7-9956-6e1e617b788e.png)
or
![image](https://user-images.githubusercontent.com/1119267/32979370-1043541a-cc65-11e7-923c-573feab2816a.png)

Chrome ignores popup height and resizes the popup, so long tracks are displayed like on first pic.

**Comment by inverse** [comment]
I would be happy with either. I'm favoring more the first one as it shows it all, although could look really funky when things get parsed wrong.
