### ISSUE TITLE
hghghghgh

### ISSUE THREAD

**Issue by Emkunov** [david-sabata/web-scrobbler#1499]
### Steps to reproduce (for bugs)

1.
2.
3.

### Steps for resolving the issue

- [ ] Reauthenticate on Last.fm

- [ ] Try to use unpacked extension from latest master

- [ ] Check other issues for duplicates

### Environment

* Version used:
* Browser name and version:

**Comment by inverse** [comment]
Not sure exactly what you're saying is up? We should close this one.
