### ISSUE TITLE
Connector injects to site even if disabled

### ISSUE THREAD

**Issue by OwnageIsMagic** [david-sabata/web-scrobbler#1501]
`vk.com` as usual
![image](https://user-images.githubusercontent.com/10534634/32998264-a97fac64-cdaa-11e7-97fe-388830102827.png)
Refreshed page 2 times

**Comment by alexesprit** [comment]
Yes, this is expected. This way is used to turn on/off connectors w/o refreshing tabs.

**Comment by OwnageIsMagic** [comment]
Then if it always connected add option to turn it on on youtube even if video isn't in music/ent category?

**Comment by alexesprit** [comment]
I'm not sure I understand you right, but this is already implemented.
![image](https://user-images.githubusercontent.com/1119267/32999040-cf6474cc-cdb0-11e7-950f-c1545ef3bc4f.png)
Is this what you are looking for?

**Comment by OwnageIsMagic** [comment]
Yeah, but when this checks are enabled I can't scrobble from any other category

**Comment by alexesprit** [comment]
You should disable these checkboxes to scrobble from ALL categories. It's written below these options.

Note that you should reload a tab with Youtube to make sure changes are applied.

**Comment by OwnageIsMagic** [comment]
I'm seeking for more fluent way to change this options

**Comment by alexesprit** [comment]
> And when they are disabled it keeps scrobbling TED lectures and etc

Sorry, the extension has no mind to detect is it really music video or not.

Anyway, it's not related to this non-issue.

**Comment by OwnageIsMagic** [comment]
for now I must open addon settings turn 2 checks
then refresh yt page with vid to scrobble if  it in non music category
I suggesting you to add this checks to popup

**Comment by alexesprit** [comment]
I suggest to use [Gitter](https://gitter.im/david-sabata/web-scrobbler) instead of discussing non-related things in issues.
