### ISSUE TITLE
Oibaf Music

### ISSUE THREAD

**Issue by fabiojacobp** [david-sabata/web-scrobbler#1518]
### Steps to reproduce (for bugs)

1.
2.
3.

### Steps for resolving the issue

- [ ] Reauthenticate on Last.fm

- [ ] Try to use unpacked extension from latest master

- [ ] Check other issues for duplicates

### Environment

* Version used:
* Browser name and version:

**Comment by alexesprit** [comment]
What is this?

**Comment by bykidi** [comment]
spam bots being broken because of... i don't know... i think that the default issue description somehow mess up with them
