### ISSUE TITLE
New bandcamp adress doesn't work

### ISSUE THREAD

**Issue by jajard** [david-sabata/web-scrobbler#1530]
my english is very bad, sorry...

new bandcamp adress doesn't work with firefox and chrome (lastest version explorer and scrobbler plugin)

an exemple : http://opaltapes.com/
before adress was http://opaltapes.bandcamp.com/

**Comment by OwnageIsMagic** [comment]
https://github.com/david-sabata/web-scrobbler/wiki/Custom-URL-patterns

**Comment by jajard** [comment]
*://opaltapes.com/*

thank you
