### ISSUE TITLE
Running `grunt` ends up with `SyntaxError`

### ISSUE THREAD

**Issue by balaziks** [david-sabata/web-scrobbler#1531]
I followed the instructions from the [Setup development enviroment](https://github.com/david-sabata/web-scrobbler/wiki/Setup-development-environment) wiki page as follows.

```> git clone https://github.com/david-sabata/web-scrobbler.git
> cd web-scrobbler
> npm install
> sudo npm install -g grunt-cli # had to with sudo
> grunt compile:chrome
```

Last command errors with

```
Loading "Gruntfile.js" tasks...ERROR
>> SyntaxError: Unexpected token ...
Warning: Task "compile:chrome" not found. Use --force to continue.

Aborted due to warnings.
```

All previous commands succeed with no problem.

I am not at all fluent in JS and I just wanted to patch together a simple connector for a site I listen music from.

Thanks for this great extension!

**Comment by alexesprit** [comment]
Make sure you have Node.js v6.0.0 or greater.
