### ISSUE TITLE
YT playlist not scrobbling

### ISSUE THREAD

**Issue by OwnageIsMagic** [david-sabata/web-scrobbler#1536]
https://www.youtube.com/watch?v=p9BoEuwuzIk&list=PLgAQes15lM1NSkDXTnvA6zeubQ94b3CTi
![image](https://user-images.githubusercontent.com/10534634/33970920-c7f93298-e086-11e7-8a70-537e6a1182f7.png)

**Comment by Nordblum** [comment]
![image](https://user-images.githubusercontent.com/10522412/34007888-7cdf1a00-e114-11e7-88ce-e6ef6099a411.png)
Works for me on Chrome 63.

**Comment by OwnageIsMagic** [comment]
category problems
