### ISSUE TITLE
Unrecognized Songs...Copy/Paste issues

### ISSUE THREAD

**Issue by MscTch** [david-sabata/web-scrobbler#160]
When there is an unrecognized song and you desire to copy&paste the artist and title, there is a big problem.  Which ever one you copy and paste first, the box closes when you try to copy the second item.  Once you go to the next item you are wanting to copy&paste, it closes it out.  Therefore you can only copy and paste ONE item and then you MUST type in the second item.  I don't mind having to fill in unrecognized but it would be extremely helpful to copy&paste BOTH items (artist & title) rather than just one.  If the box would just stay open until I hit submit so that I could copy&paste the second item, that would be fantastic.

**Comment by ex47** [comment]
This should be closed.
