### ISSUE TITLE
Use rich notifications

### ISSUE THREAD

**Issue by david-sabata** [david-sabata/web-scrobbler#180]
see
http://chrome.blogspot.cz/2013/05/richer-notifications-coming-to-chrome.html

could feature "Love this song", "Dont scrobble this song" and other

**Comment by janbaykara** [comment]
**Love/unlove mechanic** discussed further in #598. I think the rest of these ideas ("remove scrobble" / "remove from library") could be something to think about as a continuation of #719 (popup) efforts.

Cover art is now included in notifications ( Discussed in #580, achieved in 85c3629bb6af66cae3969ba9edb3e5c33417f908 - [specific line](https://github.com/david-sabata/web-scrobbler/commit/85c3629bb6af66cae3969ba9edb3e5c33417f908#diff-c8b7c308d45b9a10f85757c1b60d8643R58) ).

@david-sabata Can probably close this one.

**Comment by david-sabata** [comment]
( @janbaykara thanks for cleanup tips ^_^ )
