### ISSUE TITLE
Not valid - Adding tracks to last.fm

### ISSUE THREAD

**Issue by ghost** [david-sabata/web-scrobbler#185]
Everytime I use omnibox to enter a song still not existing on last.fm, I get the "Not valid" message.

It would be great if we could scrobble songs for the first time to last.fm even when the scrobbler doesn't recognize it. 

Examples:
http://www.youtube.com/watch?v=t6MIE5hrZFk
http://www.youtube.com/watch?v=4_F7EgrmAdU

**Comment by alexesprit** [comment]
Since the extension can save and load edited track info, this issue is resolved. Plus, we have an option to force scrobbling of unknown tracks.
