### ISSUE TITLE
Introduce new icon for validation-in-process

### ISSUE THREAD

**Issue by david-sabata** [david-sabata/web-scrobbler#197]
So we know that a connector is working fine and it's just validation taking so long

**Comment by janbaykara** [comment]
@david-sabata Were you thinking a 'scanning/searching...' kind of icon? 

E.g. ![](http://www.b2bsymposium.com/assets/Images/product-images/icons/binoculars-icon.png)

**Comment by david-sabata** [comment]
@janbaykara not bad ... but it should be in the same style as whatever results from #650

**Comment by janbaykara** [comment]
@david-sabata purely a google search for illustration. I completely agree.
