### ISSUE TITLE
Opera 15 - sometimes Scrobbler stops scrobbling for no reason

### ISSUE THREAD

**Issue by dzek69** [david-sabata/web-scrobbler#205]
As reported on your last.fm - there are some troubles with either scrobbler or Opera support. I was listening to Google Music, when i discovered the icon no longer goes green - it just says "The site is supported for scrobbling". When I clicked it - I could only disable srobbling. Changing icon status became slower with everyclick (i could click on it 10 times, then 5 secs later it quickly changed it's status 10 times). No extensive CPU use or anything though. Youtube scrobbling also didn't work. I tried everything: refreshing page, restarting Opera - no luck. I decided to reinstall extension - but because of Opera servers being down for several hours - I couldn't. Today it was working again. I decided to try it with Jango. But the icon is "The site is supported for scrobbling" when playing. I noticed my last Google Music scrobble isn't on my profile, but when started to play another song - it's working anyway.

I have NO IDEA how to reproduce this. If your extension save some logs (or I can enable some debug mode) - tell me how.

**Comment by janbaykara** [comment]
@david-sabata Can probably close, due to age of bug report.

**Comment by david-sabata** [comment]
Well, Opera => #503
