### ISSUE TITLE
Temporarily Enable feature

### ISSUE THREAD

**Issue by EnviousElitist** [david-sabata/web-scrobbler#275]
Perhaps not a common use case, but would it be possible to have a temporarily scrobble function?  That is, if a site like youtube is disabled in the options, I would like to scrobble the times I actually play music through youtube and click on the icon in the omnibox.

**Comment by janbaykara** [comment]
Here's a thought. What if the 'site disabled' option simply disables SCROBBLING (i.e. data transmit), but doesn't disable connector functionality.

Well, then:
````
if (site.disabled) { 
    $forceScrobble.btn.onClick( LastFM.scrobble );
} 
```

**Comment by alexesprit** [comment]
As a solution I can suggest to disable all connectors and enable them by right-clicking on the icon in the extensions bar.
![image](https://user-images.githubusercontent.com/1119267/27262819-48d26530-5467-11e7-97c6-e3bd845cb025.png)
