### ISSUE TITLE
Plugin-like Modular Structure

### ISSUE THREAD

**Issue by lacivert** [david-sabata/web-scrobbler#283]
(This may be what you want to make, @david-sabata ,  at the end) 

As there are many connectors, if there is a way to make connectors like plug-ins, then people can plug and use them without depending any other connectors.

Is there a chance to do that? If you want to use amazon connector, then let someone make it and use it. Not necessary to think much about them in this repository as it is a "plugin" only, this can be some kind of an API so people can write and use their own connectors.

**Comment by janbaykara** [comment]
@david-sabata Can close.
