### ISSUE TITLE
Transfer Thumbs Up (Pandora) to Love (Last.fm)

### ISSUE THREAD

**Issue by redbassett** [david-sabata/web-scrobbler#299]
I'd like (love?) to see the option to sync thumbed up tracks in Pandora as loved tracks on Last.fm, and maybe the ability to removed thumbed down tracks from Last.fm library.  Maybe the same with services such as Grooveshark and Youtube as well?

**Comment by redbassett** [comment]
Requesting this issue be closed!

**Comment by david-sabata** [comment]
You can close it yourself, you know

**Comment by redbassett** [comment]
Was I tired enough to not notice that?

Thanks ;)
