### ISSUE TITLE
Songza not scrobbling - potentially when tab is not active

### ISSUE THREAD

**Issue by lazarescu** [david-sabata/web-scrobbler#301]
The little button is there, saying that the site is supported for scrobbling but nothing appears to be happening. Is this because the tab is not the one I have active? I have re-authenticated my account to no avail.

Thanks.

**Comment by janbaykara** [comment]
@lazarescu Is this working now?

**Comment by lazarescu** [comment]
Yes, it has been working for a long time, sorry, I should have closed this!
