### ISSUE TITLE
Double injection

### ISSUE THREAD

**Issue by cenobitedk** [david-sabata/web-scrobbler#342]
Some pages triggers double (or even triple) injection under some circumstances.
Looking through the issues this specific issue concerns at least Youtube (https://github.com/david-sabata/Chrome-Last.fm-Scrobbler/issues/262), Soundcloud (https://github.com/david-sabata/Chrome-Last.fm-Scrobbler/issues/286#issuecomment-36185247), Pitchfork (https://github.com/david-sabata/Chrome-Last.fm-Scrobbler/issues/337), Google Music (https://github.com/david-sabata/Chrome-Last.fm-Scrobbler/issues/286) and Pandora (https://github.com/david-sabata/Chrome-Last.fm-Scrobbler/issues/278).

I'm not sure what causes the problem but I know Soundcloud triggers DOM ready twice (and probably "unload" too) and the mechanism provided (https://github.com/david-sabata/Chrome-Last.fm-Scrobbler/issues/278#issuecomment-33730917) to detect whether the content script is loaded is not able to respond quickly enough.

When loading a new tab with a soundcloud page the script seems to work fine, but when you hit reload the console of the background script looks like this:
![screen shot 2014-03-29 at 00 49 16](https://cloud.githubusercontent.com/assets/1397207/2556541/2573e5fe-b6d7-11e3-978d-6c5a1136f5f5.png)
This is tested with version 1.33 and clearly indicates that the content script is loaded twice - due to missing response from the "ping" message.

I hope @david-sabata have some ideas concerning this issue. In any way I'd love to get some ideas on the table. :-)

**Comment by inverse** [comment]
We could probably close this now. It's almost 3 years old.

**Comment by alexesprit** [comment]
> We could probably close this now. It's almost 3 years old.

Is this issue resolved? I didn't notice multiple injection, except the case I described in #1175.
