### ISSUE TITLE
problem with absolute radio UK

### ISSUE THREAD

**Issue by arriver** [david-sabata/web-scrobbler#343]
When listen http://player.absoluteradio.co.uk/ - plugin submit track-artist instead of artist-track

**Comment by alexesprit** [comment]
Well, I accidentally remove RadioPlayer support, which covers mentioned music service (see #1133 discussion); the issue makes no sense now.

As @inverse said before, we always can return the RadioPlayer support, so you can request adding support for Absolute Radio UK by opening new issue.
