### ISSUE TITLE
Scrobbles not being stored because of Notifications errors

### ISSUE THREAD

**Issue by probedb** [david-sabata/web-scrobbler#344]
I had my work machine rebuilt and have reinstalled Chrome and the plugin.

Using either Amazon Cloud player or Google Play I'm having the same issue as before.

last.fm is showing the currently playing track but it's not storing them.

I haven't had any popup asking for permissions for the plugin yet.

Any thoughts on how to debug this?

Thanks,
Paul.

**Comment by janbaykara** [comment]
From what I can tell, notifications & scrobbling do not seem to be interdependent anymore? In which case this can close.

**Comment by david-sabata** [comment]
Should be true. Outdated anyway.
