### ISSUE TITLE
What do we do about songs scrobled with incorrect info?

### ISSUE THREAD

**Issue by Ratizi** [david-sabata/web-scrobbler#371]
For example, https://www.youtube.com/watch?v=UoK8DaJRDaM
This is scrobled in my library as きゃりーぱみゅぱみゅ – "CANDY CANDY , Kyary Pamyu Pamyu - CANDY CANDY"
When it should simply be きゃりーぱみゅぱみゅ – "CANDY CANDY"
or Kyary Pamyu Pamyu - "CANDY CANDY"
In the current system, there's no way to fix titles showing up incorrectly.

**Comment by rlenders** [comment]
I referenced this issue on another issue but I might as well reference [that issue](https://github.com/david-sabata/web-scrobbler/issues/619) here.
