### ISSUE TITLE
Consecutive authorization requests

### ISSUE THREAD

**Issue by wieczorek1990** [david-sabata/web-scrobbler#458]
Somehow every now and then the program asks for last.fm authorization and I wasn't deleting any caches.

**Comment by david-sabata** [comment]
It's been some time since I changed the credentials storage. Is anyone still experiencing this issue?

**Comment by hugovk** [comment]
Just retested, it's now working for me on Mac with YouTube. Thanks!

**Comment by hugovk** [comment]
But on Windows 7 I still get the popup asking to authorise every time I start Chrome.

**Comment by david-sabata** [comment]
@hugovk Do you have the last version? Can you please send some logs (on pastebin or something like that)?

**Comment by hugovk** [comment]
@david-sabata I just deleted the extension from Chrome, then added it again from the store, and it's now working on Windows 7. Thanks!

**Comment by david-sabata** [comment]
@hugovk Glad to hear that. Any chance you noticed what version did you have? Is it possible that you haven't used that Win7 pc for a while and the extension was few versions old?

**Comment by hugovk** [comment]
@david-sabata I think it was the same version as that in the store. I've been using this Win7 PC almost daily.

**Comment by flopflip21** [comment]
Same issue on Chrome 40 on OS X 10.9.5 I just installed the extension today

**Comment by VesNL** [comment]
Still having this issue after uninstalling it a while ago. 

Getting this on my OSX 10.10, Windows 7 32b, Win 10 Preview and Chrome OS. All running Chrome in beta channel.

**Comment by HEdingfield** [comment]
Been getting an authentication request every time I start my computer since the release.

**Comment by inverse** [comment]
Strange :/ @david-sabata would providing logs be beneficial with resolving this?

**Comment by HEdingfield** [comment]
I haven't had this issue in a couple weeks now. For reference though, these were the errors I was getting before:

**Warnings:**
lastfm.js:93 Failed to trade token for session - the token is probably not authorized
lastfm.js:52 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.
core/background/services/lastfm.js:93 Failed to trade token for session - the token is probably not authorized

**Errors:**
Unchecked runtime.lastError while running pageAction.hide: No tab with id: 525.
    at injectCb (chrome-extension://hhinaapppaileiechjoiifaancjggfjm/core/background/main.js:54:23)
    at onPatternsReady (chrome-extension://hhinaapppaileiechjoiifaancjggfjm/core/background/inject.js:168:5)
    at Object.callback (chrome-extension://hhinaapppaileiechjoiifaancjggfjm/core/background/chromeStorage.js:28:6)

**Comment by david-sabata** [comment]
@HEdingfield is scrobbling working fine? Because according to those warnings it shouldn't be

**Comment by HEdingfield** [comment]
@david-sabata yes, it's working fine now, but back when I was having those warnings it wasn't. I think I resolved it by uninstalling and reinstalling.

**Comment by alexesprit** [comment]
Closed due to changes of auth process.
