### ISSUE TITLE
Notifications are not clearing from Chrome notifications taskbar icon

### ISSUE THREAD

**Issue by ghost** [david-sabata/web-scrobbler#467]
Windows 8.1 64-bit
Google Chrome 37.0.2062.124 m (64-bit)
Last.fm Scrobbler 1.40

Recently (past week or so), desktop notifications have stopped automatically clearing from the Chrome notification queue (the bell icon in the Windows taskbar).

![screenshot 17](https://cloud.githubusercontent.com/assets/694485/4429232/e9d441e0-45df-11e4-9d1c-2f49261446db.png)

**Comment by ex47** [comment]
Seems like it is no longer the issue. Should be closed.

[Google removes Chrome's notification center because nobody used it](http://www.theverge.com/2015/12/1/9833006/google-chrome-notification-center-removed)
