### ISSUE TITLE
Support for Nokia Mix Radio?

### ISSUE THREAD

**Issue by hans-juergen** [david-sabata/web-scrobbler#476]
Hi, usually Nokia Mix Radio is available on Nokia/Microsoft Windows mobile phones, but they also have a web site which offers free mixes in your browser: http://www.mixrad.io/ Is it possible and/or difficult to create a connector for this?

**Comment by bes-internal** [comment]
I did not find any player on the site

**Comment by galeksandrp** [comment]
Already here #571

**Comment by ex47** [comment]
Should be closed as the site is dead.
