### ISSUE TITLE
Changes on Myspace

### ISSUE THREAD

**Issue by hans-juergen** [david-sabata/web-scrobbler#487]
Hi, it seems that Myspace has changed the way its player works again. When choosing a radio station, you will also get videos now, even from YouTube which are not scrobbled. When playing one of your own mixes (= playlists) with audio-only content, they are not scrobbled either. I still use v1.38 for Opera 25 on Windows XP.

**Comment by janbaykara** [comment]
@david-sabata close? The Opera extension is dead. Long live the extension!

**Comment by david-sabata** [comment]
Yes. If there are still some issues, they should be in separate reports.
