### ISSUE TITLE
New feature request: Option to add the current scrobble to last.fm favorites.

### ISSUE THREAD

**Issue by TheMicronaut** [david-sabata/web-scrobbler#495]
Last.fm provides API for adding a scrobbled song to the list of favorites. I guess it would not be that hard to add this option in this great gadget. A possible idea for implementation would be to add it as a new option 'Add to fav' in the context menu of the scrobbling icon that appears upon right click.

**Comment by david-sabata** [comment]
I'll assume you were talking about "love" feature, which is implemented in #702
