### ISSUE TITLE
I have to re-authorize last.fm scrobbler every time I restart my browser

### ISSUE THREAD

**Issue by motocharlie** [david-sabata/web-scrobbler#496]
I didn't used to have to do this. It might have to do with synching chrome / chromium over many different computers, installations, etc. 

I reinstall ubuntu-based linux distros quite often, or run from a live usb rather often as well. I also dual-booted with windows 7 a lot. I've seen this issue across all of them. 

Anything that I can do in particular to help with this?

**Comment by toekneebullard** [comment]
I tried the reinstall yesterday, but this morning it asked me to authorize once again. 

Might it have anything to do with using two separate Chrome profiles? I switch back and forth between the two quite often during my day.

**Comment by BenjaminHCCarr** [comment]
@david-sabata I'll try to debug log based on what you linked, I commented in one of the other threads. It is on every browser start across Chrome, Canary, and Chromium.
