### ISSUE TITLE
Feature Request: Custom URL and TheMusicNinja Support

### ISSUE THREAD

**Issue by ShahmanTeh** [david-sabata/web-scrobbler#499]
Hi, I definitely love the applet so far. so here are some request from me, a fan~

- Support for TheMusicNinja (http://www.themusicninja.com/) radio/player.
- A custom URL parameter to scrobble. maybe there is another unsupported site like TMJ that need some love? I would be neat!

Cheers,
S.T

**Comment by bes-internal** [comment]
#688 waiting for the next release
