### ISSUE TITLE
play.google.com/music doesn't seem to work.

### ISSUE THREAD

**Issue by DawTaylor** [david-sabata/web-scrobbler#527]
Trying to scrobble activity from Google Play Music but it doesn't works.

Are there any specific setting I should change in order to get it to work?

**Comment by BalooUriza** [comment]
Also getting some inconsistency with Google Play; about 80% of the time it's not scrobbling, usually have to reauth 10-12+ times before it works.

**Comment by inverse** [comment]
@BalooUriza have you tried re-installing the extension?

**Comment by david-sabata** [comment]
Seems to work for me. What are the symptoms? Is there the icon in the browser address bar?

Does reauthing really work? It shouldn't make much difference.

Can you [post some logs](https://github.com/david-sabata/web-scrobbler/wiki/How-to-debug-the-extension)?

**Comment by DawTaylor** [comment]
Thanks for your time.

Reauth about 8 times and now it show a lastfm icon on the address bar. However the music wasn't scrobbled to my profile.

Logs. http://pastebin.com/dfuGSUk8

**Comment by BlakeIsBlake** [comment]
Had this issue, reauthing seemed to fix it.

**Comment by DawTaylor** [comment]
Unfortunately it didn't help me through.

**Comment by jaapz** [comment]
I have the same problem, reauthing does not work. Do have the image in the address bar, but no actual scrobble.

**Comment by tellarin** [comment]
Having a similar problem over here. Most recent Chrome build. It stops scrobbling intermittently not very often.

When it happens, the red icon is shown. Reloading the Google Music a couple times (<5) usually works. Otherwise, re-auth and re-launch browser works.

**Comment by NAUSHNIK52** [comment]
Works OK for me. Chrome Beta.

**Comment by ottomatias** [comment]
I have this issue too since few weeks. Youtube scrobbles fine but Google Music doesn't. Reauth doesn't help but reloading a couple of times seems to.

**Comment by Konc** [comment]
Didn't work for me initially, but after a couple of reloads it started working.

**Comment by donalhunt** [comment]
Also have the same issue. logs at http://pastebin.com/0KE8JNYu

**Comment by Yakovko** [comment]
Have the same issue - looks like the web service is unavailable or API has changed. Logs: http://pastebin.com/5eCpVX6U

**Comment by tschieggm** [comment]
I also consistently have this issue with google play music.

**Comment by inverse** [comment]
related to #657

**Comment by david-sabata** [comment]
Anyone still experiencing this issue?

**Comment by janbaykara** [comment]
@david-sabata Perhaps something to put to bed?

**Comment by galeksandrp** [comment]
Scrobbling is not starting when Play Music opened via ajax hyperlink on Google Play.

> cast sender errors in #664 means that opened site tried to connect chrome cast extension.

**Comment by daiyiwhale** [comment]
Also not working for me!

**Comment by tellarin** [comment]
I'm having this problem again. Now on Goolge Music and Youtube on Chorme on Windows 10.
Chrome on Windows 8.1 works fine in the same websites.

**Comment by inverse** [comment]
Is this still an issue? one year on?

**Comment by alexesprit** [comment]
I think all Google Play Music issues should be closed by following reasons:
1. There's no certain steps to reproduce in that issues.
2. #1176 is merged.

**Comment by alexesprit** [comment]
Closed as outdated.
