### ISSUE TITLE
problems with deezer 

### ISSUE THREAD

**Issue by mi8as** [david-sabata/web-scrobbler#536]
hi, I've got problems with scrobbling from deezer, last.fm scrobbler doesn't recognize any song/track. When used in other services (for ex. youtube) everything seems ok.

**Comment by kevinsilva** [comment]
"Last.fm scrobbler for web " does'nt work for deezer. +1

**Comment by mi8as** [comment]
It used to work. :) But no problem for me now, cause I haven't recognized that deezer has an option for scrobbling. :+1:

**Comment by NAUSHNIK52** [comment]
But it scrobbles every song at start. When you just skipping songs their scrobble anyway.

**Comment by NAUSHNIK52** [comment]
I made a pull that fixes Deezer scrobbling.
