### ISSUE TITLE
Please scrobble the music at ektoplazm.com

### ISSUE THREAD

**Issue by w-sky** [david-sabata/web-scrobbler#540]
Would be great if scrobbling would work for Ektoplazm. They have terabytes of (electronic) music, free to play in the browser.
http://www.ektoplazm.com/free-music

**Comment by inverse** [comment]
Not sure if it's possible. The music is being played through a flash mp3 player which doesn't look like any of the DOM state gets updated.

**Comment by bslotems** [comment]
I've created a connector for ektoplazm: https://github.com/david-sabata/web-scrobbler/pull/588/

**Comment by bslote** [comment]
I've created a connector for ektoplazm: https://github.com/david-sabata/web-scrobbler/pull/588
