### ISSUE TITLE
Deezer not work

### ISSUE THREAD

**Issue by NAUSHNIK52** [david-sabata/web-scrobbler#541]
Last.FM Scrobbler can't recognize Deezer song (I think this error appeared about two weeks ago) and suggest to enter name.
![image](https://cloud.githubusercontent.com/assets/4209275/6314614/dba53efe-b9f6-11e4-99e4-fbe8025bbbb8.png)

**Comment by david-sabata** [comment]
Can someone else confirm this? I just played few random tracks and all were recognized just fine.

@NAUSHNIK52 some tracks are not recognized by L.FM, because their database is never complete. Can you post a link to track that is causing problems?

**Comment by NAUSHNIK52** [comment]
@david-sabata All tracks cause problem. My deezer.js fixed scrobbling for me.

**Comment by david-sabata** [comment]
I am on beta too. Is it possible that Deezer has some new UI that is open for some users only? Or maybe difference based on country?

**Comment by NAUSHNIK52** [comment]
@david-sabata Oh, looks like it is. I am just changed language to English and my fix won't work anymore.

**Comment by david-sabata** [comment]
That's interesting. Can you somehow detect language and make your fix active for RU only?

**Comment by NAUSHNIK52** [comment]
@david-sabata I think I can't. I don't know JS very well (making fix for me took about 2 hours).
Maybe I am try later. I don't think Russian is one language with this problem.

**Comment by david-sabata** [comment]
I understand, but I don't want to apply a change that breaks something that previously worked. I'll note this to the PR. Maybe someone will show up and make the fix language-dependent.

**Comment by inverse** [comment]
The HTML tag binds the language attribute. Could use that to hook in a fix on a per language basis.

**Comment by inverse** [comment]
should be fixed in next release
