### ISSUE TITLE
Please add support for the new Beatport beta

### ISSUE THREAD

**Issue by steven2358** [david-sabata/web-scrobbler#542]
From the email they sent me yesterday:
> Take a first look at our new streaming service.
> Stream unlimited electronic music, for free.
> FEATURES
> -Listen to millions of tracks and mixes with free, unlimited streaming.
> -Easily purchase any track you stream at the new music store, Beatport Pro.
> -Discover festivals and shows from around the world.
> -Connect to new music, artists, and labels through curated playlists and charts.

The experience is very much like Soundcloud, and it would be a nice addition given their huge catalogue and userbase.

**Comment by bes-internal** [comment]
#686 waiting for the next release
