### ISSUE TITLE
Scrobbling from spotify for chromebook not working

### ISSUE THREAD

**Issue by blackadders** [david-sabata/web-scrobbler#543]
Scrobbling was working OK last week.
For the last few days, it hasn't. I've reinstalled both Spotify and last.fm scrobbler and reconnected to last.fm but still getting no response. I've also cleared all my browsing data.
Any idea? 
Thanks

**Comment by vinimk** [comment]
Isn't working for me neither, it says in the navigation bar that "This site is supported for scrobbling" but never actually scrobbles

**Comment by blackadders** [comment]
I've found a way to get it working.
Click on the preferences icon at the bottom of spotify page.
Where it says Scrobble to last.fmConnectd as xxxxxx (disconnect) click on disconnect.
Then click on connect. This takes you to last.fm log on page. Sign in to last.fm. This takes you to spotify web player page within last.fm. Click on yes,allow access.
Have to do this each time login to spotify.
Each tune is then scrobbled after it's played for 40 seconds. Nothing shows up on spotify.
Not elegant, but it's worked 100% for last week.

**Comment by SamZR** [comment]
I'm having this issue as well. Spotify's built-in scrobbler isn't working on the web interface and neither is this extension's. The workaround above doesn't help me, either.
