### ISSUE TITLE
Soundcloud scrobble not working

### ISSUE THREAD

**Issue by llisama** [david-sabata/web-scrobbler#546]
Hasn't worked for me for quite some time now. Wasn't sure if it was just me or overall. I've re-authenticated etc. can't seem to find the problem.

cheers

**Comment by inverse** [comment]
Should be fixed with #545 - You could try it out and see if you are comfortable with running unpacked extensions + git.

**Comment by munframed** [comment]
Same problem here. It shows it scrobblable, but doesn't scrobble. No problem with lots of other websites like youtube, google music player, or even tunein, but with Soundcloud, yes. Please fix it :/

**Comment by inverse** [comment]
It's fixed. Just needs to be merged and released.

**Comment by munframed** [comment]
You mean it's fixed but hasn't released yet? When should I expect it then? Thanks for your answer btw.

**Comment by inverse** [comment]
@munframed  - It's been merged - should be in the next release.

**Comment by david-sabata** [comment]
Bad news - SC seems to be broken again. I was just checking before release... :(

**Comment by munframed** [comment]
:( thanks for your efforts I do appreciate it. Keep me posted please :)

**Comment by inverse** [comment]
It's like cat and mouse :(

**Comment by Yoshi8765** [comment]
Not working for me yet again. :-1:

**Comment by apaulvs** [comment]
Hey, I don't know the status on this issue but as of the past few weeks, Soundcloud hasn't been scrobbling for me either at all. The extension doesn't even seem to be running on the website. :/

**Comment by llisama** [comment]
Anything here? Soundscloud has just never worked for me. I'm running the unpacked version...

**Comment by david-sabata** [comment]
@llisama can you post an example url of what you cannot scrobble? Also please try using regular package. A lot of changes were done for SC in last two releases.

For me the SC scrobbling seems to be working fine now.

**Comment by nicoletheghoul** [comment]
not working again :/
