### ISSUE TITLE
Noon Pacific

### ISSUE THREAD

**Issue by Rusty87** [david-sabata/web-scrobbler#551]
Hello,
If you find the time, and the inclination, could you please add scrobbling functionality to http://www.noonpacific.com/? It is a great service - they publish an ad-free playlist every Monday, plus provide access to previous playlists. I read your FAQs, and this is a 'probably not', but it can't hurt to ask, right? =)

Thank you in advance,
Rusty

**Comment by david-sabata** [comment]
Resolved by #558
