### ISSUE TITLE
FEATURE idea: Click on "error - check status.last.fm..." actually opens status.last.fm

### ISSUE THREAD

**Issue by dotWee** [david-sabata/web-scrobbler#553]

**Comment by janbaykara** [comment]
+1 :+1: Presumably for the notification?

**Comment by alexesprit** [comment]
That notification was gone when v1 core was removed.

Atm, the error notification is shown only when authentication with Lasf.fm is failed (was added in 5879dce9818ab4c3d66ac1e9c453bc35733bae89). Clicking on this notification opens Last.fm status page.
