### ISSUE TITLE
Album title url with '-' is scrobbled as '%E2%80%8B-%E2%80%8B' (Bandcamp)

### ISSUE THREAD

**Issue by bobcanthelpyou** [david-sabata/web-scrobbler#554]
I scrobbled an EP on Bandcamp
````
http://knudt.bandcamp.com/album/this-is-my-world-turned-upside-down
````
and the url of the scrobbled album title looks like:
````
http://www.last.fm/music/Knudt/This+is+my+world+turned+upside%E2%80%8B-%E2%80%8Bdown
````
I would expect the following 
````
http://www.last.fm/music/Knudt/This+is+my+world+turned+upside-down
````
What could be the reason for these additional '%E2%80%8B'?

**Comment by inverse** [comment]
@david-sabata I can pick this up.

**Comment by inverse** [comment]
The reason is that the album title that is being captured from the BC page has `&#8203;` wrapped to each side of the dash. Which happens to be the [zero width space character][0]. This is then being URL encoded hense the format you are seeing. 

I'm not seeing an issue with this when scrobbling though.

```
BandCampScrobbler: scrobbling - Artist: Knudt; Album:  This is my world turned upside​-​down; Track: These Days; duration: 177
```

[0]: http://www.fileformat.info/info/unicode/char/200b/index.htm

**Comment by bobcanthelpyou** [comment]
The album title is shown correctly (e.g. i could check my Lastfm library page) 
````
http://www.last.fm/user/{{yourUsername}}/library/music/Knudt
````
The album is shown as 'This is my world turned upside​-​down' but the link to the library album page looks like
````
http://www.last.fm/user/{{yourUsername}}/library/music/Knudt/This+is+my+world+turned+upside%E2%80%8B-%E2%80%8Bdown
````
And the 'Go to album page' link address looks similar 

When i mouse over the album link address with Firefox the characters are shown as '%u200B-%u200B'

These characters are only shown when i access my Lastfm Libary with Firefox, Chrome does not show the characters in the url (but you could see them e.g. in the HTML source code of the scrobbled album page e.g. the 'link rel="alternate"'-tags). The characters appear there, too, but their are not displayed / not visible.

You could make the hidden characters visible with Chrome if you copy the scrobbled album page address from the address bar or from a link and paste them i your text editor or to the comments here.

**Comment by david-sabata** [comment]
Ehm, I'm not sure I understand the bug here. Does the track scrobble correctly (including album info)?
I don't think the connector adds some extra chars and if those spaces really are in the album title, we pass them on to the L.FM.

**Comment by bobcanthelpyou** [comment]
@david-sabata The scrobbled album name doesn't match the correct album on Lastfm. Could you scrobble a song of the album on Bandcamp and look at your lastfm library and copy & paste the url to the album here? The link to the scobbled name could be found at:

```
http://www.last.fm/user/{yourLastFMname}/library/music/Knudt
```

**Comment by bobcanthelpyou** [comment]
The extra chars are on the Bandcamp page at several places:
```
<h2 class="trackTitle" itemprop="name">
            This is my world turned upside&#8203;-&#8203;down
</h2>
```
These special chars appear at all albums with a '-' between letters or other chars at Bandcamp and should be removed before the title is scrobbled

**Comment by inverse** [comment]
I've created a PR for this and it strips out the zero width chars and scrobbles correctly.

**Comment by david-sabata** [comment]
Thanks @inverse!
