### ISSUE TITLE
Support for Samsung Milk web

### ISSUE THREAD

**Issue by SubbyDew** [david-sabata/web-scrobbler#555]
Now that Samsung Milk is available through any browser, it would be good to get it supported.
I don't personally use it as I have no samsung devices and was just trying it out on the web to see if it is any good.
http://milk.samsung.com/

**Comment by artlung** [comment]
/* depends on jQuery */
    /* information about currently playing track is in the
       highest z-index .famous-surface element */
    var highestIndex = -100;
    $('.famous-surface').each(function(){
    	var zIndex = parseInt($(this).css('z-index'), 10);
    	if (zIndex > highestIndex) {
    		highestIndex = zIndex;
    	}
    });
    // once you have the highest z-index for .famous-surface elems:
    var activeFamousSurface = $('.famous-surface[style*="z-index: ' + highestIndex + '"]');
    
    // then you can get Song Title and Artist Name
    var songTitle = activeFamousSurface.find('.track-info:first h1').text();
    var artistName =  activeFamousSurface.find('.track-info:first h2').text();
    
    // whether the player is playing is here
    var isPlaying? = $('.actions li.playing.active').length > 0;
    
    // I don't see a way to get track length or current track position

**Comment by mvinaround** [comment]
Samsung Milk has closed now.
