### ISSUE TITLE
Correcting titles doesn't work in vk.com.

### ISSUE THREAD

**Issue by yvm** [david-sabata/web-scrobbler#559]
Click on icon with "?" mark, write in two fields, click "submit" - no effect.
Tested with "Per Kristian Risvik – Suspense (Doom E1M5)" audio file.

**Comment by bedefaced** [comment]
I think your song did not scrobbled because there is no track with this artist-track name on the last.fm service. Correction function in this popup is for *correction* only, not for adding to last.fm database. See #452.
