### ISSUE TITLE
Another Deezer issue

### ISSUE THREAD

**Issue by NAUSHNIK52** [david-sabata/web-scrobbler#560]
Hello. I just want to share about Deezer issue. Scrobbler works OK, but I hate this issue.
Every little change at Deezer page starts song scrobbling over. Like, if I'm change volume from 50% to 51%, open a side menu, open another Deezer page - scrobble start over. HTML code not changes. Is it possible to fix it?
P.S. This is issue persist in all languages for me.
Sorry for my bad English, I hope you understand what I mean.

**Comment by inverse** [comment]
This is really an issue. The scrobbler works by listening to DOM changes on the title tag.

Below is an example of the problem.

![bug](https://cloud.githubusercontent.com/assets/713525/6777189/6fc2a1f0-d147-11e4-9090-3a0a7fd8ccf3.gif)

Wouldn't a better solution to be to either check to see if this matched track matches what already is playing (checking duration to allow for replays of the same song).

or listening to events being triggered directly from `dzPlayer`.

**Comment by NAUSHNIK52** [comment]
@inverse I am just edited the deezer.js

    else if ($('.player .control-pause').size() > 0) {
		
		if ($('.progress-time').text() == '00:00') {
		
            return {
                track: $('.player-track-title').text(),
                artist: $('.player-track-artist').text().replace($('.player-track-artist').children().first().text(), '').trim().replace(/,$/, ''),
                duration: parseDuration($('.player-progress .progress-length').text())
            }
		}	
    }

It is works. But I am just learning the coding and maybe you or someone another find a better way to fix the issue.

**Comment by inverse** [comment]
I see - so your going to only return when the track time text looks reset. I'm not sure if this is the best thing to do since it may not always be correct. Also you may want to enable strict matching using triple equals (`===`).

I'm trying to modify the scrobbler to use the `dzPlayer` object and hook into the Event subscriber mechanism but I'm struggling to find out when this is bound to the page. 

@david-sabata is it bad to do something such as:

```JS
    function bindPlayer() {

        if (dzPlayer === null) {
            window.setTimeout(bindPlayer, 1000);
            return;
        }


     // Register events here

 
    }
```

**Comment by david-sabata** [comment]
@inverse It aint pretty, but it's acceptable if you do this just to initially find the player :)

**Comment by inverse** [comment]
should be fixed in next release
