### ISSUE TITLE
Google Play Music

### ISSUE THREAD

**Issue by cbrowne91** [david-sabata/web-scrobbler#561]
The Google Play music streaming site registers as supported in the toolbar, however does not seem to scrobble. This was working fine until around 23rd March, so there may be a change to the website preventing scrobbling from working?

**Comment by dfacoet** [comment]
It works for me, v 1.44 and Chrome 41.0.2272.101 (64-bit) on CentOS 7.

**Comment by harpingon** [comment]
Not working for me on play music, v1.44 on Chrome 41.0.2272.101 m (64-bit), Windows 8.1

**Comment by cbrowne91** [comment]
This is now working for me again, though spontaneously will stop working.

I have found closing and reopening chrome fixes the problem. v1.44 on Chrome 41.0.2272.101 m (64-bit), Windows 8.1

**Comment by harpingon** [comment]
Hm. I went to Play Music right after a reboot. Still though, I'll retry next time I close the browser.

**Comment by david-sabata** [comment]
I've just checked and it seems to work for me. Could be a cache issue. Google Music is JS-heavy app and I'm sure they update it quite often.

Closing for now, hope it will keep working
