### ISSUE TITLE
Digitally Imported not scrobbling

### ISSUE THREAD

**Issue by dfacoet** [david-sabata/web-scrobbler#562]
Scrobbling does not seem to work for me on di.fm radio.
I am using v 1.44 and Chrome 41.0.2272.101 (64-bit) on CentOS 7.
I get the "this site is supported for scrobbling" icon, but it does not seem to recognize that the radio is streaming.

**Comment by boniverski** [comment]
It doesn't work for me, too.

**Comment by brycied00d** [comment]
I'm not sure whether you'd prefer a new issue or if I should reopen this recent old issue. Version 1.46 is not working with di.fm once again. Same symptoms as the initial issue - extension reports the site is supported, but no songs are being scrobbled.

I've confirmed in Chrome Inspector that elements used by connectors/difm.js#L88 are filled with the relevant artist/track names. I see no errors in the console from web-scrobbler.

**Comment by dfacoet** [comment]
It does not work again for me either, 1.47 on Chrome 42.0.2311.152 (64-bit).

**Comment by brycied00d** [comment]
As of today, it seems to be scrobbling just fine. Extension version 1.47, Chrome 43.0.2357.65 beta (64-bit).

**Comment by dfacoet** [comment]
Once again scrobbling from di.fm does not work for me with the same symptoms, on version 1.53.
Radiotunes is supposed to be very similar and works fine, with the v2 connector.
