### ISSUE TITLE
web-scrobbler doesn't scrobble songs at odnoklassniki.ru

### ISSUE THREAD

**Issue by d0ppe1ganger** [david-sabata/web-scrobbler#568]
Hi David!

Tried to set up web-scrobbler for my father and found that it doesn't scrobble songs at odnoklassniki.ru which is my dad's favorite social network. At the same time it scrobbles songs at youtube etc so it works but not at odnoklassniki.ru

btw they changed url from odnoklassniki.ru to ok.ru and every time you type odnoklassniki.ru in address bar it redirects you to ok.ru - maybe this is the reason for this bug.

Could you please find some time for late night programming and fix it )

**Comment by david-sabata** [comment]
@d0ppe1ganger Hi, I added the new url. Hopefully it will work. If not, feel free to reopen this issue :)

**Comment by Pastafarianist** [comment]
David, looks like it's not working.

There's another issue referencing the same problem at https://github.com/david-sabata/web-scrobbler/issues/667, which also provides a solution. Could you take a look?

**Comment by bes-internal** [comment]
I can't confirm this. I just checked on the 1.49 release, and everything worked

**Comment by Pastafarianist** [comment]
I am using 1.50, fresh from Web Store. I have also disabled all sites except for Odnoklassniki, Vk, Youtube and the two Yandex services in the settings. Nothing scrobbles on Last.fm, I am getting no "now playing" notifications and no errors show up in the console.
