### ISSUE TITLE
web scrobbler doesn't scrobble Album when using music.xbox.com

### ISSUE THREAD

**Issue by Machiventa** [david-sabata/web-scrobbler#576]
The web scrobbler scrobbles artist and song title, but not the album when using music.xbox.com. For instance if you go to your charts on last.fm and choose albums in the last 7 days it doesn't show any.

**Comment by Machiventa** [comment]
It looks like this scrobbler doesn't pull album title from the Spotify web client either. So I'm assuming it just doesn't scrobble album titles of any web player? If not I'll just use a different scrobbler.

**Comment by artlung** [comment]
@Machiventa scrobbling of the Album title is dependent on the connector including where to look for it. If you could provide help identifying where that title appears consistently you can help get it into the code. I don't have either xbox or spotify accounts or I'd try to help.

**Comment by Machiventa** [comment]
@artlung thanks for the reply. I don't have any coding skills so I have no idea how to help with this. 
If there's an easy way to tell me where to look I'll be glad to help with this. I use Chrome for both services. I believe both services released their API for devs but I don't know if that would help. 

But both Xbox Music (via OneDrive) and Spotify have free accounts. Spotify has a free tier where you either create an account or sign up with Facebook. And Xbox Music lets you stream your own music for free when you register an account through their One Drive cloud storage service.

**Comment by inverse** [comment]
t looks like the Xbox connector is scrobbling the album name, if the matcher finds something.

`var albumValue = $("div#player .playerNowPlayingMetadata .secondaryMetadata>a:last-child").text().trim();`

Perhaps it's this which isn't working. I've not got an account so am unable to verify this trhough. Looking at the connector makes me feel it'll be a good candidate to upgrade to the V2 connector model.

**Comment by Machiventa** [comment]
Thank @inverse - how do I upgrade it to v2?

**Comment by Machiventa** [comment]
Would really love to scrobble albums. Can anyone help?

**Comment by david-sabata** [comment]
@Machiventa take a look at files in `/connectors/v2`. It's totally simple. You just specify selectors for track name, artist, album and so on.

**Comment by Machiventa** [comment]
Where do I look and how do I specify selectors? I'm have no experience with coding.

**Comment by janbaykara** [comment]
@Machiventa 'selectors' refer to CSS selectors, that point to specific HTML elements.

Here's an introductory guide: http://www.sitepoint.com/web-foundations/introduction-css-selectors/

If you rightclick and 'inspect element', you'll find a panel with the HTML code of the page, and you can deduce the selectors required to reference specific HTML elements like the track artist, etc.

**Comment by david-sabata** [comment]
Should be fixed by #775
