### ISSUE TITLE
"Listening now" behaving strangely

### ISSUE THREAD

**Issue by j3mdamas** [david-sabata/web-scrobbler#577]
I noticed the following behaviour when scrobbling from Spotify: when any song starts, after a few seconds, it appears on Last.fm with the "Listening now" sign, and remains there for about 20-30 seconds, after which it disappears, only to appear later as "Just listened" (after the scrobble), but the "Listening now" never comes back until the next song starts, and the behaviour repeats.

From what I recall, the "Listening now" should remain while the song is being played, and when it scrobbles, a "second entry" shows beneath with the "Just listened", which remains after the song stops or changes. Or did this behaviour change?

I'll try later with the "Last.fm scrobbler for Windows", to see if this behaviour also happens.

**Comment by janbaykara** [comment]
@j3mdamas is this still an issue?

**Comment by j3mdamas** [comment]
I just checked. Now there's the new last.fm beta page. The recent tracks do not seem to refresh itself, but used some hard refreshes.

RIght now, the 20-30 seconds issue does not occur. The song scrobbles at about the same time the web-scrobbler does. But after it does, the "Listening Now" disappears nonetheless, which was not the usual behaviour, but maybe it is now? I don't know.

**Comment by inverse** [comment]
@j3mdamas closing as I believe this is a non-issue anymore

**Comment by j3mdamas** [comment]
I haven't been paying attention to my scrobbles lately. yes, better to close, if no one else notices it.
