### ISSUE TITLE
Paused music on vk.com still scrobbling

### ISSUE THREAD

**Issue by RadikMusabirov** [david-sabata/web-scrobbler#578]
When i paused music on vk. com it's still scrobbling. On last.fm it's look like
![screenshot_3](https://cloud.githubusercontent.com/assets/12019447/7219753/bcff0942-e6b7-11e4-8985-def9299ce0cf.png)
![screenshot_4](https://cloud.githubusercontent.com/assets/12019447/7219754/beead1aa-e6b7-11e4-8ffb-8dfa851e1eda.png)

My profile on last.fm for details - http://www.lastfm.ru/user/M0safiR/tracks

**Comment by inverse** [comment]
Could be related to #409

**Comment by ex47** [comment]
This should be closed. Fixed long time ago #416
