### ISSUE TITLE
Single song from Bandcamp is not scrobbled to Lastfm

### ISSUE THREAD

**Issue by bobcanthelpyou** [david-sabata/web-scrobbler#582]
I tried to scrobble the 5 tracks EP Sunwards by Trapped In Cold Season http://trappedincoldseason.bandcamp.com/album/sunwards the songs 1,2,3 and 4 are scrobbled correctly but not the last song "Song7 (What's Left of Us)"

The song is detected correctly 

```
BandCampScrobbler: scrobbling - Artist: Trapped In Cold Season; Album:  Sunwards; Track: Song7 (What's Left of Us); duration: 356
```

Also the scrobbler says: "Song has been scrobbled", but the song does not show up scrobbled on my profile or at the song page Lastfm 
http://www.last.fm/music/Trapped+in+cold+season/SUNWARDS/Song7+%28What%27s+Left+of+Us%29

What could be wrong?

**Comment by alexesprit** [comment]
The song is ignored by Last.fm for some reason. I tried to scrobble it using [Open Web Scrobbler](http://ows.elamperti.com/), but had no luck with this. So I believe it's not the extension issue.
