### ISSUE TITLE
YouTube scrobbles as youtube.com/devicesupport

### ISSUE THREAD

**Issue by maxdaniel98** [david-sabata/web-scrobbler#593]
When using YouTube, web-scrobbler scrobbles as youtube.com/devicesupport.

**Comment by inverse** [comment]
dupe of #590

**Comment by MansourMans** [comment]
On youtube it scrobbles track as  <youtube.com/devicesupport> and artist as <http>
![snap](https://cloud.githubusercontent.com/assets/12377342/7552839/df54f7c0-f6d6-11e4-9aa5-cbdb12782fa3.JPG)
