### ISSUE TITLE
Showing the source you're scrobbling in Last.fm

### ISSUE THREAD

**Issue by ryanbr** [david-sabata/web-scrobbler#606]
Is it possible to have it "Scrobble from the <Source>", say "Scrobbling from Google Music" within Last.fm. Or have an option for it?

**Comment by inverse** [comment]
From my understanding this isn't possible. This information is populated by last.fm from the information provided when setting up the application and associated with the API.

**Comment by janbaykara** [comment]
This could be possible, by hijacking one of two Last.fm features:

* **Tagging** the track with 'Scrobbled from 8Tracks'

http://www.last.fm/api/show/track.addTags

* Add the track to a **playlist**, like 'Scrobbled from 8Tracks'

http://www.last.fm/api/show/playlist.addTrack and http://www.last.fm/api/show/playlist.create

**Comment by inverse** [comment]
But how would that impact this:

![image](https://cloud.githubusercontent.com/assets/713525/7669986/83cf8108-fc90-11e4-9105-db59a9a2762c.png)

This is my understanding what @ryanbr  is talking about.

**Comment by janbaykara** [comment]
Oh I see; I hadn't realised that was a thing already.

**Comment by david-sabata** [comment]
@inverse is right. The app name is there to tell you which one is currently active, in case you use multiple scrobbling apps. In case of wrong data you know which one sent them
