### ISSUE TITLE
Amazon Music (in Germany) struggles playing in Opera 29

### ISSUE THREAD

**Issue by MartinL0815** [david-sabata/web-scrobbler#611]
Using Opera 29 I continued using the web scrobbler.

While in Google Chrome nothing strange happens, now in Opera playing music from the amazon.de cloud player struggles very often:

1. Sometimes the player stopps visually, but the track continues to play and can only be stopped by reloading the page.
2. Often the scrobbler does not recognize the played track.
3. Entering the data for not recognized tracks results often in "not valid" message in the input dialog. Sometimes deleting text in parenthesis or brackets helps to let the scrobbler accept the input. 

I know the first point could be an issue to be reported to Amazon, but ... it seems to be a problem while using the web scrobbler.

Belonging to my configuration - I disabled most supported web services, but those I use, like soundcloud and amazon.

**Comment by david-sabata** [comment]
Sorry to say, but Opera is no longer updated or supported --> see #503 
You can still continue using it, but it will be without any support and on your own risk.

**Comment by MartinL0815** [comment]
Thanks David for this information!

May I ask why Opera isn't sorted anymore?

Thanks in advance!

Martin5

------- Original message -------

**Comment by david-sabata** [comment]
You haven't read #503, have you :)
