### ISSUE TITLE
Scrobbling not working for Spotify web player

### ISSUE THREAD

**Issue by DrCron** [david-sabata/web-scrobbler#612]
Hi,

I downloaded this extension to scrobble songs from the Spotify web player (since its own scrobbler doesn't seem to work with LastFM) but it's not working. I tried with Youtube too and it worked ok, but it's not recognizing the songs being played in Spotify Web Player.

Thanks.

**Comment by inverse** [comment]
@DrCron going to close this should be resolved now.
