### ISSUE TITLE
music.163.com: cannot scrobble songs with white space in the title/artist

### ISSUE THREAD

**Issue by ftkftw** [david-sabata/web-scrobbler#614]
First of all, a big thanks to everyone who contributed to this plugin.

Lately I started using netease, but I noticed that the method.getInfo request returns 400 Bad Request if the song title has white space in it. I did some more checking and it appears to be an encoding issue; for music.163.com, white spaces in title are encoded to %C2%A0, which is the non-breaking space in UTF-8. This causes the getInfo API call to return 400. However, the exact same method.getInfo call returns 200 OK if I replace all %C2%A0 with %20 in the Request URL.

Is it a simple fix to swap all non-breaking spaces with regular spaces before UTF-8 encode? I'm new to Github and Chrome extension development but I'm willing to get my feet wet by testing a fix.

**Comment by inverse** [comment]
Have you got an example URL which is showing the problem?

**Comment by ftkftw** [comment]
Do you mean the Request URL for the method.getInfo call?

Here is one:
https://ws.audioscrobbler.com/2.0/?method=track.getinfo&autocorrect=1&artist=interior%20palette%20toeshoes&track=traffic%C2%A0jam

I've removed my api_key for security reasons. The request returns

<lfm status="failed">
<error code="6">Track not found</error>
</lfm>

If I change the %C2%A0 in the track query string to %20, such as:
https://ws.audioscrobbler.com/2.0/?method=track.getinfo&autocorrect=1&artist=interior%20palette%20toeshoes&track=traffic%20jam

then it returns

<lfm status="ok">
<track>
<id>82084417</id>
<name>Traffic Jam</name>
<mbid/>
<url>
http://www.last.fm/music/interior+palette+toeshoes/_/Traffic+Jam
</url>
<duration>617000</duration>
<streamable fulltrack="0">0</streamable>
<listeners>163</listeners>
<playcount>520</playcount>
<artist>
<name>interior palette toeshoes</name>
<mbid/>
<url>http://www.last.fm/music/interior+palette+toeshoes</url>
</artist>
<toptags></toptags>
</track>
</lfm>

The song is here:
http://music.163.com/#/song?id=748718

The white space issue does appear in this example to only affect the track string, and not the artist string. I am using Chrome on OSX. IIRC I ran into non-scrobbling issue for netease on Chrome on Windows 7 as well, though I didn't check if it was the same white space issue.

**Comment by rkne** [comment]
Any word on how progress on this is going? I've just run into the same problem and it looks like your findings are all sound.

**Comment by ftkftw** [comment]
Looks like the issue was fixed by fakelbst in
https://github.com/david-sabata/web-scrobbler/commit/6c7ab508ea43d92ef249189b408292bb96b5c22a
by replacing char code 160 with regular space.

Thank you fakelbst!!!
