### ISSUE TITLE
Youtube  - not working at all.

### ISSUE THREAD

**Issue by Eroticus** [david-sabata/web-scrobbler#617]
Cloud you fix it =] ?

Thanks...

![1](https://cloud.githubusercontent.com/assets/12580518/7786700/47303f1a-01e7-11e5-96d5-cc5f7e99fc50.png)
![2](https://cloud.githubusercontent.com/assets/12580518/7786701/47309f00-01e7-11e5-963e-54f1958316f4.png)

**Comment by inverse** [comment]
Opera isn't supported anymore. This issue will not be fixable.
