### ISSUE TITLE
Opera 2x extension database has obsolete version of scrobbler

### ISSUE THREAD

**Issue by Dwarden** [david-sabata/web-scrobbler#618]
The version of this scrobbler is obsolete on Opera's extension website
https://addons.opera.com/en/extensions/details/lastfm-scrobbler-2/?display=en

so unless user know how 'use' chrome extension 
then they locked into that old one with e.g. last.fm vs youtube bug

thanks in advance for updating the Opera one

note: i know about the compatibility issues you had in past 
(reason you stopped update the Opera version)

but atm. there were several majors bugs which actually cause troubles to 'normal unaware user'
so update would be really welcome, another option is to de-list the Opera version / mark as obsolete

p.s. 1.47 version of Chrome extension seems to work fine on Opera 29.0.1795+

**Comment by david-sabata** [comment]
Actually I was thinking about deleting the extension completely from the Opera store. I'm not aware of some "obsolete" flag and have no intentions to post any more updates.

**Comment by Eroticus** [comment]
1.47 not working for me ... only if set song / title manual =[

**Comment by david-sabata** [comment]
The Opera extension is deleted from the store now. Sorry for inconvenience. Details at #503
