### ISSUE TITLE
Editing scrobbled songs

### ISSUE THREAD

**Issue by torava** [david-sabata/web-scrobbler#619]
Scrobbler's UI is too limited. You can manually edit song to be scrobbled only if scrobbler doesn't recognize it. Usually it thinks it does and too often results are garbage like Stevie Wonder - I Wish (Live in London 1995). Then I have to go remove the entry and scrobble it manually. I think user should be able to correct it straightly from the interface to Stevie Wonder - I Wish. YouTube video titles are seldom in a correct form. You could even add a feature which links corrections to YouTube video links if they got enough support.

**Comment by rlenders** [comment]
I came here to suggest this too. Most of the times, songs from movies and games don't have the composer's name in the title. (And sometimes not even in the description!) Instead, the title usually is "%GAME/MOVIE NAME% - %SONG NAME%". I wish I could correct this directly.
