### ISSUE TITLE
Spotify overhaul ruined music recognition

### ISSUE THREAD

**Issue by swablueme** [david-sabata/web-scrobbler#620]
<img src=http://i.imgur.com/eBwGykf.png=>
<img src="http://i.imgur.com/30f0sQo.png">
Google chrome Version 43.0.2357.81 m using the webplayer. It was working fine yesterday and I was receiving notifs/scrobbling for each song played.

**Comment by david-sabata** [comment]
Spotify seems to be rolling out some changes based on geographic regions. Should be fixed by #623 for now, but there may be some other issues until Spotify finishes the process
