### ISSUE TITLE
Build passing?

### ISSUE THREAD

**Issue by hughrawlinson** [david-sabata/web-scrobbler#625]
What build? There's no `test` directory in the repository, and the badge in the readme links to an image of the badge, not to any CI service as you'd usually expect. What exactly is the badge intended to indicate?

**Comment by janbaykara** [comment]
http://travis-ci.org/david-sabata/web-scrobbler/builds/

**Comment by david-sabata** [comment]
It's for lint and syntax checking, which is useful to see if pull requests keep the code clean.
There are currently no automated tests.

**Comment by david-sabata** [comment]
Closed by #626
