### ISSUE TITLE
Scrobble bug in Youtube

### ISSUE THREAD

**Issue by dungahk** [david-sabata/web-scrobbler#627]
The extension is scrobbling "https – youtube.com/devicesupport" for all the songs I listen to in Youtube.

**Comment by inverse** [comment]
I don't think this is an issue any more. What version of the extension are you running?

**Comment by pink999** [comment]
it is an issue for playlist, constant refreshing, myspace has stopped working, last staff are of no help

**Comment by david-sabata** [comment]
I use playlists a lot and haven't observed this problem.

Can you please send a version of the extension and some more info about how you open the playlist and what you click for the bug to reporduce?

**Comment by janbaykara** [comment]
@david-sabata I think this longstanding issue was crushed a while back.

For history's sake, though, this bug resulted in some hilarious mass mis-scrobbling: http://www.last.fm/music/https

![screenshot 2015-09-09 11 44 32](https://cloud.githubusercontent.com/assets/237556/9759882/3afaed2a-56e8-11e5-9f9b-3be70b164ef0.png)

Also: http://www.last.fm/music/https/_/youtube.com%2Fdevicesupport
![screenshot 2015-09-09 11 45 26](https://cloud.githubusercontent.com/assets/237556/9759890/4e4c0a58-56e8-11e5-9329-c745dc658f55.png)

**Comment by david-sabata** [comment]
:smile:

**Comment by pink999** [comment]
thanks !!!! it was lost in spam, Don't get much on G-mail.😂
