### ISSUE TITLE
Double scrobbling on Mixcloud

### ISSUE THREAD

**Issue by dukedave** [david-sabata/web-scrobbler#630]
Mixcloud [supports scrobbling natively](http://blog.mixcloud.com/2014/12/03/mixcloud-tips-5-social-media-connections/), but #358 added it to web-scrobbler as well.
If you have both, everything gets double scrobbled :unamused: 

I'm not sure how best to handle this?
Perhaps we could detect if native scrobbling is set up; is there a precedent for such a feature in any other connectors?

**Comment by inverse** [comment]
Alternatively disable web-scobbler from the options ;)

**Comment by janbaykara** [comment]
The same can be said of 8tracks and IndieShuffle. Wondering if, down the line, we should implement a little prompt that asks whether you want to disable scrobbling for site X, because site X has native scrobbling.

**Comment by david-sabata** [comment]
We can have a notification with button to disable the connector on a single click.

The tricky part is figuring out whether or not the user has native scrobbling enabled. We need that information on every page that is supported for scrobbling. Also it may be based on user's settings for given service and it does sound a little like privacy invasion when we would read the settings, even only to check for scrobbling.

Another way would be some flag for connector, that the page may have native scrobbling, which would make notification show up on each visit until the user decides if he wants to disable the connector or keep it. (With that the notification would have two buttons.)

What do you think?

**Comment by janbaykara** [comment]
I agree that it might be a bit intrusive to actively gauge whether the user is logged in/natively scrobbling or not.

I'd just have a notification that says something like:
> ThisSite.com users can directly scrobble songs to Last.fm, without the Last.fm extension
> [ Alright, disable extension on ThisSite.com ] or [ Nevermind, carry on scrobbling via extension ]

**Comment by janbaykara** [comment]
Sites that definitely have scrobbling:
* 8tracks
* IndieShuffle
* MixCloud
* Spotify

**Comment by fedorg** [comment]
I never remember to turn off scrobbling for Spotify until it's too late. And above all, there are two connectors enabled by default, neither of which I need.
I think it'd be fine to ask once to _disable_ scrobbling the site on the first play. Maybe even check if the song is already playing on lastfm (after several seconds) and only then show the notification. Kinda hacky, but most people won't play the same song twice on the first visit, I guess. If the user ignores the message, just keep scrobbling and remind him after a while (probably on next launch or so).

**Comment by Paszt** [comment]
"I never remember to turn off scrobbling for Spotify until it's too late." - You should disable the Spotify connector in options.

**Comment by dukedave** [comment]
I'm with @fedorg's view on this, specifically the 'ask once' one sites with native scrobbling part.

@Paszt I think the point is that (at least @fedorg and myself) are arguing is that:
One tends to only realize they need to disable the connector, when they see duplicate scrobbles in their Last.fm library. At this time it's "too late" in the sense that the user must then go and manually delete the duplicate scrobbles.

**Comment by david-sabata** [comment]
I'm still not sure if the case is as strong as you say. If you _always_ remember after it's too late, then you realize that you were double-scrobbling, but didn't disable the connector, so it happens again the next time, right? 

I think the easiest thing we can do is some flag on connectors definitions and then that notification @janbaykara was talking about. But still, the default state should be enabled for all connectors.

**Comment by inverse** [comment]
@david-sabata I agree with you on the flag on the connector def to state the ones which have native scrobbling and push a notification on the first time visiting. @janbaykara are you working on this?

**Comment by janbaykara** [comment]
@inverse Nope, entirely forgot!

**Comment by alexesprit** [comment]
Closed in favor of #1375.
