### ISSUE TITLE
Add more sited (audiosplitter.fm)?

### ISSUE THREAD

**Issue by linnhansen** [david-sabata/web-scrobbler#631]
Hi! Do you have any plans to add more sites? Could audiosplitter.fm be a part of that plan?

Best regards

**Comment by inverse** [comment]
It's possible - someone just has to implement it! Are you familiar with JS?

**Comment by linnhansen** [comment]
No, I''m not. :(

2015-06-16 19:35 GMT+02:00 Malachi Soord <notifications@github.com>:

**Comment by david-sabata** [comment]
Closed by #652
