### ISSUE TITLE
Youtube doesn't scrobble

### ISSUE THREAD

**Issue by AltarBeastiful** [david-sabata/web-scrobbler#634]
The icon is showing but no scrobble.

Checked the code at youtube.js:l190 a request is sent to get the video data, it seems to never return. I don't even see it in the network tab, or in the blocked request in the console. No logs either.

Anyone else has this problem? 

Chromium 43.0.2357.65 (64-bit), OpenSUSE 13.2

**Comment by AltarBeastiful** [comment]
Checked the api and v2 is deprecated. We might want to switch to v3. Although I'm not sure if that's the problem here.

To test the v3 api : [api playground](https://developers.google.com/youtube/v3/docs/videos/list#try-it)

we should replace the current URL by something like : 
https://www.googleapis.com/youtube/v3/videos?part=snippet&id=9d8SzG4FPyM&key={YOUR_API_KEY}

**Comment by pink999** [comment]
please listen - most people see all these fixes they do not understand including myself, So staff at last LM act like "whatever" then they locked this out saying "fixed" it not fixed and yes people are that foolish - so when they realize, hey? locked out of support - see fix or fixed, perhaps Chrome can help? There is some great material on the tube for now and you can listen to "chart" music anywhere - no one even wants to log in here, thanks if you at least read this.

**Comment by pink999** [comment]
pretty all is down, bandcamp works, vk is ify - well thats the new improved last fm I guess

**Comment by AltarBeastiful** [comment]
Waiting for #635 to be merged.

**Comment by pink999** [comment]
thanks

**Comment by westyFM** [comment]
I am having the same problem, works every where but youtube

**Comment by pink999** [comment]
this how lost fm handles the issue, it keeps switching this comment back and forth from web support to client support and "their" answer is really a question (like that is anything new) - - http://www.last.fm/forum/21713/_/2251091, no cloud, no you tube, deductive reasoning = more to the problem that any so-called expert is letting anyone know or no one knows what they are doing (then there are the rumors).

**Comment by AltarBeastiful** [comment]
Fixed by #635. It will work when a new version of the extension is released.

**Comment by westyFM** [comment]
mine still isnt working

**Comment by pink999** [comment]
Remy/ westyFM;


I will write this, there is a pattern that starts right around that time
period of article (sometime in late 2013 there was a legal merger) I
thought I deleted it – it’s May 21, 2013 -- that was a handshake merger,
but from Muzu to Spotify integration/ including scrobbling (ironically, May
20 something this year – new page with more integration) - conflicts
started.


Honestly it doesn’t matter what I think.It is a shame that you guys are so
committed to doing this, vk is back up though, bandcamp works.


Thanks though, Bri

**Comment by inverse** [comment]
@david-sabata hasn't made a release yet which includes the fixes. But expect one soon I am sure. He is probably either super busy or working on some crazy new stuff for the extension!

**Comment by pink999** [comment]
"crazy new stuff for the extension" that is what I was trying to write lol
cool :p thx

**Comment by david-sabata** [comment]
Well, not so much crazy new stuff will be in the release... at least not in the core :-P

**Comment by pink999** [comment]
YaY ! it works :-)
