### ISSUE TITLE
chorus support

### ISSUE THREAD

**Issue by simba83** [david-sabata/web-scrobbler#636]
It would be nice to get chorus for kodi (former xbmc) support in this add-on.

https://github.com/jez500/chorus

**Comment by inverse** [comment]
This looks like it'll be hard to add support directly as I am guessing this is hosted on your home network. Perhaps having the option for adding such 'self hosted' connectors is a good move though. We already have the mechanisms in place to handle this it's just a case of hooking it all up in the options via configuration.

**Comment by simba83** [comment]
That's true this runs on a hosted home network. There are even a chorus2 in development atm, 
I have no problems to setup this in a config menu. 
Thanks for taking this further.

**Comment by janbaykara** [comment]
I feel like it might be better to just add native Last.fm scrobbling to that application?

**Comment by inverse** [comment]
https://github.com/jez500/chorus/issues/85 - they have already an open ticket for this

**Comment by galeksandrp** [comment]
Temporary you can use https://github.com/galeksandrp/web-scrobbler/tree/chorus branch. If you browser and kodi installed from different machines, set chorus url on `connectors/v2/chorus.js`.
