### ISSUE TITLE
Pandora scrobbling is broken

### ISSUE THREAD

**Issue by draaglom** [david-sabata/web-scrobbler#637]
The extension emits a single console.log at startup:

```
Web Scrobbler: Setting up observer
```

and the green 'scrobbling' icon displays; however, nothing is actually scrobbled.

Examining the background page, I'm seeing 403 errors when the extension tries to POST to `ws.audioscrobbler.com`; re-authenticating with last.fm doesn't seem to fix them.

Edit: Re-authenticating again and then restarting Chrome seems to have fixed the issue.

**Comment by inverse** [comment]
The console.log doesn't highlight a problem with the scrobbler. Are you able to check the extensions console?

1. navigate to `chrome://extensions/` 
2. Find web-scrobbler and click on `background page`
3. Clear the log that is shown then revisit pandora and provide a dump of the output.


@david-sabata  perhaps we should update the debug wiki as it's a bit out of date. I'll create a ticket for it and someone or I could pick this up :+1:

**Comment by draaglom** [comment]
@inverse I edited my message above -- restarting chrome after re-authenticating with last.fm fixed the issue (and it hasn't recurred since then).

So if there is an issue, it's not with pandora so much as last.fm re-authentication not working without restarting Chrome. 

I would suggest we close this, since I have no idea how to reproduce the re-authentication problem.

**Comment by david-sabata** [comment]
Weird. There may be some issue with authentication indeen. I tried to investigate, but wasn't able to reproduce the issue in my environment.

@inverse please do :)

**Comment by DaaOtt** [comment]
I'm getting this too.

**Comment by Paszt** [comment]
@DaaOtt: please follow the instructions outlined by Inverse above about how to debug and then share your results here.

**Comment by DaaOtt** [comment]
```
Tab 307: received empty state - resetting
-- loaded for the first time, injecting the scripts
	injecting vendor/jquery-2.1.0.min.js
	injecting vendor/underscore-min.js
	injecting core/content/reactor.js
	injecting core/content/connector.js
	injecting connectors/v2/pandora.js
	injecting core/content/starter.js
Tab 307: created controller for connector: {"label":"Pandora","matches":["*://www.pandora.com/*"],"js":["connectors/v2/pandora.js"],"version":2}
-- subsequent ajax navigation, the scripts are already injected
Tab 307: new track state: {"track":"Ruffneck","artist":"Navigator & Freestylers","album":"An England Story - From Dancehall To Grime - 25 Years Of Music In The Uk 1983-2008","uniqueID":null,"duration":425,"currentTime":0,"isPlaying":true,"trackArt":null}
Tab 307: new song detected: {"parsed":{"artist":"Navigator & Freestylers","track":"Ruffneck","album":"An England Story - From Dancehall To Grime - 25 Years Of Music In The Uk 1983-2008","uniqueID":null,"duration":425,"currentTime":null,"isPlaying":true,"trackArt":false},"processed":{"artist":"Navigator & Freestylers","track":"Ruffneck","album":"An England Story - From Dancehall To Grime - 25 Years Of Music In The Uk 1983-2008","duration":425},"metadata":{"userloved":false,"startTimestamp":1440830118},"flags":{"isProcessed":false,"isScrobbled":false,"isCorrectedByUser":false,"isLastfmValid":null,"isMarkedAsPlaying":false}}
GET https://ws.audioscrobbler.com/2.0/?method=auth.getsession&api_key=d9bb1870d…32205afd508239ea7447d&api_sig=8f3c53331fcdce3077c343b77f4c4b96&format=json 403 (Forbidden)
auth.getSession failed: Forbidden, error
```

**Comment by Paszt** [comment]
lol, you're also getting an authentication error. As draaglom said, re-authenticating should fix your problem.  Have you tried to re-authenticate? If not, open your chrome extensions page (one method it to put chrome://extensions/ in your address bar and press enter); find "Last.fm Scrobbler" and click options; on the options page, open Options; scroll down to the bottom of the supported websites list and click the "Re-authenticate with Last.fm" button.

**Comment by DaaOtt** [comment]
Things shouldn't just silently fail. It needs to notify you if there's a
problem.

**Comment by janbaykara** [comment]
> Things shouldn't just silently fail. It needs to notify you if there's a problem.

You're right, of course. We can launch a re-auth notification at `auth.getSession failed: Forbidden, error`. I'll post a PR for this later this weekend if someone doesn't get to it before me.
