### ISSUE TITLE
Update debug wiki

### ISSUE THREAD

**Issue by inverse** [david-sabata/web-scrobbler#639]
The wiki could do with a bit of work as it's not been updated since 2013 by which time the way to get to the debug information has changed.

Perhaps including screenshots for illustrative purposes would be useful.

This will aid in the error reports that people are submitting so we can help them get to the information required that'll help us understand the problem. Especially with geo-location services.

**Comment by inverse** [comment]
Done :dancer:

**Comment by david-sabata** [comment]
Nice, thanks!

**Comment by inverse** [comment]
Didn't even know I could modify it... Thought It would have just created a PR.

**Comment by david-sabata** [comment]
Surprised me too :smile:
