### ISSUE TITLE
user

### ISSUE THREAD

**Issue by pink999** [david-sabata/web-scrobbler#641]

**Comment by inverse** [comment]
Did you check the post date on this article?

**Comment by david-sabata** [comment]
What's this?

**Comment by inverse** [comment]
It had a link to an article from 2013 about LFM and videos  - Close this :+1:

**Comment by pink999** [comment]
I pulled that after some people got in trouble bring it up in form, but
this was stating that on Jan 14? 2014 there where problems scrobbling, but
I again pulled that - so post must stick, what I close remains open?

whatever the case there is no communication, staff or whatever you want to
them are rude, not trying to make this work, but what do I know other than
I closed the issue nearly 3 hours ago - I am sorry for wanting to work
collectively and can not.

one other thing you should tell people that their issue/posts remain I got
3 message 1 hour. 50 mns, and 40 mins - burn me at the cross

okay good luck

**Comment by inverse** [comment]
@pink999 I'm sorry - I don't follow? I didn't mean to cause offence. 

What exactly is the issue you are facing?

**Comment by pink999** [comment]
did I cuss you out, if not, no offense then ;p sorry late with this it "here" I do remember you, hey geek is right word for guy and gals that dig doing what you guys do right? 

I do have an issue with lost fm (yes lost), nothing anyone can do about that, but the youtube isn't well (I have you right?) I posted, that has been my issues in past, not with you guys, you actually were very helpful, but the spot-mods as I call them think we are all developers? I guess because they are not, tell us to go fix their problems.

so people are complaining again, but afraid of you wild and crazy guys I guess, so I was thinking its connecting the spotify with last fm = messing connection up, but strangely everything else seems to be working, so I noticed no one left a message and posted, plus I missed you guys , you are buying this right cause I mean it you get stuff done.

if you offended me, I would have said something, k ~ bri :)

did you just call me dizzy? thanks my best friends say that lol

**Comment by janbaykara** [comment]
I'm enjoying this immensely.

**Comment by bes-internal** [comment]
I parse: our web-scrobbler not working, and @david-sabata somewhere resting and does not want to help a ~cute~ girl

**Comment by pink999** [comment]
Think of it for world peace and other cool stuff x

**Comment by pink999** [comment]
wake him up and tell him I fixed it - but really it appears to be trying to
work,

Pom Poms and cheering helped ----- "Goooo You Tube!"

"cute" plz - cool

West Coast strut that’s sweet as molasses

Knock you out with my cheap sunglasses


If you fixed it ~ thanks, but I think the cheerleading chants worked lol


See then  watch this neat stuff and store it - you can send to exel, but
you knew that , Have a great weekend x


https://www.youtube.com/watch?v=inavKm9r9cw

**Comment by Yoshi8765** [comment]
I can't tell if this Bri person is an especially entertaining troll or a legitimate girl.

**Comment by david-sabata** [comment]
Either way, half of it I don't understand and half of it is really funny 😁

**Comment by pink999** [comment]
le tracker pour YouTube semble fonctionner, understand, you need to see my
papers?

a Troll? The Bridge Creatures? ever seen Troll Hunter?

Really now Troll - that is below belt  you rather have someone that's
"bitch, bitch, blah, blah,yada?"
Way ahead of you, you'd turn them off - correct (?).
okay it is settled, maybe its working on its own?

but perhaps if you would be so kind, maybe a look at it and you get another
surprise (geeks go figure?)

https://www.youtube.com/watch?v=WhGFwk58h34 (Run!) Great sub-titles!
lol my sister watches this stuff,
zombies are the fad in BC too, the ones that are cannibals, vampires are
cool <3

Really this is the problem with the world -- no fun, all tense over what?
Tight undies?
blame it Canada; Thank you.

**Comment by pink999** [comment]
https://www.youtube.com/watch?v=WhGFwk58h34

**Comment by janbaykara** [comment]
This issue needs to remain permanently open.

**Comment by pink999** [comment]
got it, the e-mails before your had virused or something, norton
caught shut dow, rebooted, locked, rebooted, running slow like dail up
days, full scan was full of threats?

so I am good, gone.

**Comment by pink999** [comment]
Similarity to suspicious messages cautions were on it, locked my system,
received 2
sad shit
