### ISSUE TITLE
Soundcloud scrobbling broken (again)

### ISSUE THREAD

**Issue by jdb8** [david-sabata/web-scrobbler#643]
#633 seemed to fix it, but now I'm getting `Cannot scrobble. Please report at https://github.com/david-sabata/web-scrobbler/issues` in the console.

Using v1.48 from the chrome store.

**Comment by joshkaplan** [comment]
Might be worth referencing this, their soundcloud scrobbling works: https://github.com/msfeldstein/chrome-media-keys

**Comment by inverse** [comment]
@joshkaplan  I think what they do is control the player which binds to DOM elements. We could do that with this scrobbler but binding to the event bus feels more pragmatic in this instance. The changes that are in PR #648  will make this a lot more robust @Paszt is doing some good work with bringing all the scrobblers to v2 as well!

**Comment by maegentae** [comment]
Soundcloud is not scrobbbling again.
