### ISSUE TITLE
Scrobbling does not work on Youtube

### ISSUE THREAD

**Issue by fabiolamzwave** [david-sabata/web-scrobbler#644]
The app doesn't work weeks ago. Even though the plug is active and the button appears on, it does not connect to my lastfm account.

**Comment by inverse** [comment]
Can you provide:

- A URL which has the problem
- Debug logs (see the wiki) 
- Information regarding the version of the extension you are running?


We recently fixed this issue, perhaps you just need to update your extension to `1.4.8`

**Comment by fabiolamzwave** [comment]
https://www.youtube.com/watch?v=DE09lbqVPb8&list=PL9PphsKbpuIXObVrL3s09tm336bJyGyZY&index=9 

What do you mean by debug logs? I've tried to look for it but i have no idea.

I installed the latest available version (i think its 1.48)

**Comment by fabiolamzwave** [comment]
It is fixed! I don't know how...

**Comment by AltarBeastiful** [comment]
Works also for me.
Maybe the request sent to youtube API's took some more time than expected. 

@david-sabata Close?
