### ISSUE TITLE
Using sync storage

### ISSUE THREAD

**Issue by inverse** [david-sabata/web-scrobbler#647]
What is your opinion on using chrome's sync storage to persist config settings to the cloud so that they can be shared between installs linked to account? 

docu: https://developer.chrome.com/extensions/storage

**Comment by janbaykara** [comment]
+1

**Comment by AltarBeastiful** [comment]
+1, love this as you can pop a new install of chromium and get your setup working instantly!

Would it be used for the account connection as well?

**Comment by inverse** [comment]
Account connection wouldn't be a wise thing IMO but syncing everything else would be a good move!

**Comment by inverse** [comment]
@david-sabata what is your stance on this? Is this something that you think should be included? Or should we leave the storage to local only?

**Comment by david-sabata** [comment]
I poked around this a little when I was switching storage from `localStorage` to "extension storage" (it's probably not a real term, but it is somehow different from classic `localStorage` which was used before).

From what I remember there were some limitations, but probably nothing critical. We don't store much data yet. Also I'm not sure about the security, but it would be super nice if we could sync the tokens too. Because besides that there isn't much configuration that needs to be stored. Currently we store tokens to some internal storage and I'd say that the cloud storage would work and be secured quite the same.

It would be cool to sync also manually entered track info some day, but we may hit the limit with that.

**Comment by marsjaninzmarsa** [comment]
> Also I'm not sure about the security, but it would be super nice if we could sync the tokens too.

[Unfortunately](https://developer.chrome.com/extensions/storage#using-sync):
> Confidential user information should not be stored! The storage area isn't encrypted.

**Comment by alexesprit** [comment]
Currently we have the following storages:
* `Connectors` for connectors options;
* `customPatterns` for user-defined URL patterns;
* `Options` for the extension options;
* `LocalCache` for edited song metadata;
* `Core` for core data;
* storages for each scrobbling service (Last.fm and Libre.fm).

Althought all these local storages can be quite easily transformed into sync ones, there're some reasons to keep some of them as local ones.

I suggest to make first three storages as sync.

`LocalCache` storage is supposed to have a lot of data, while sync storages have some limits. 

`Core` storage contains app version and notification flags. Propably, it makes a sense to sync these flags; to achieve this we can split `Core` storage into several ones.

Last.fm and Libre.fm storages should be stored locally.

**Comment by inverse** [comment]
@alexesprit what does core contain? by notification flags do you mean whether to display the notifications? 

I agree `LocaleCache`  could become problematic. We could plan some larger storage migration strategy such as export/import or even cloud handling in future iterations.

**Comment by alexesprit** [comment]
@inverse core storage contains the extension version (not used now, but could be used for specific migration process) and notification flags (don't know how to call them properly). These flags used to prevent displaying notable changes several times:
https://github.com/david-sabata/web-scrobbler/blob/cf0d8b8455ef1ca45043190e2890f9d106a2c1b9/core/background/main.js#L330-L350

I updated this code a little (reverted `true` and `false` meaning), but the idea is still the same.

**Comment by inverse** [comment]
Nice - I haven't seen this code for a while - It looks a lot nicer with the new ES touches :) 

That makes sense.
