### ISSUE TITLE
New Icon suggestions

### ISSUE THREAD

**Issue by Paszt** [david-sabata/web-scrobbler#650]
Here are some flat icon suggestion I was playing around with.  The current one is a bit smaller than all my other extension icons.

![chrome-web-scrobbler_128-icons](https://cloud.githubusercontent.com/assets/1742693/8368842/d78989a4-1b7d-11e5-8b37-35775f81ca01.png)

Let me know if there's interest.

**Comment by inverse** [comment]
These are yummy!

**Comment by janbaykara** [comment]
I quite like the simplicity of 2 and 5, although using an unmodified version of the last.fm logo might miscommunicate what the scrobbler is, and who it's made by.

I like the concept of 7, though I think it may not work well at small icon sizes. Could we try that without the blue square in the centre, @Paszt ?

**Comment by Paszt** [comment]
![chrome-web-scrobbler_128-icons](https://cloud.githubusercontent.com/assets/1742693/8501851/7e8cf002-2177-11e5-8552-282f7c3f18fd.png)?

**Comment by lacivert** [comment]
vote for 6 and/or 7

**Comment by inverse** [comment]
I really like 2 and my partner likes 5.

**Comment by NAUSHNIK52** [comment]
2 or 7

**Comment by david-sabata** [comment]
Nice work :)

I'd prefer flat design. Also I'd like to keep the icon informative. Basically this should be the "startup" version, where no music is playing, but there should also be versions for "some music is playing" and "unrecognized track".

I probably like 7 the best, but I'm not sure how it would look in the address bar. The decorative border may take up some useful space.

What do you think?

**Comment by Paszt** [comment]
I meant those above as the large 128px icon that's named icon128.png, though I did mess around with the smaller flat icons too.  Here's they are:  
    
![web-scrobbler_icons](https://cloud.githubusercontent.com/assets/1742693/8768955/f1ab0512-2e5e-11e5-8a68-f4cbc716587f.png)
    
Unfortunately the 7 from above doesn't scale down very well as you suggested.

**Comment by inverse** [comment]
Awesome work @Paszt I'm really digging number 1 and 2, although 2 is still my favourite! :+1:

**Comment by david-sabata** [comment]
My choices would be
* a3
* b - nothing; the cross icon turned out to be historical
* c2
* e - some flat tick on green background in the spirit of the row number 2
* g2, but maybe with white text color?

Also I'm considering removing states "d" and "f". I'd use the logo on gray (or maybe black?) background for scrobbling disabled by user.

What do you think?

**Comment by Paszt** [comment]
I've recently had a computer malfunction and I'm in the middle of backing-up and reinstalling everything. I can probably have a PR created in a day or two.  I'll just include the smaller icons unless you'd like to include a larger one too.

**Comment by david-sabata** [comment]
No rush ;-)

I think small icons are fine except for logo. I'm thinking about updating it in the extension store too, so a large one would be useful too.

**Comment by janbaykara** [comment]
@Paszt poke! If only as a reminder, and because I'm really keen to see what comes of this :)

**Comment by Paszt** [comment]
Still having computer issues.  I can install Linux but not Windows. I think I'll just suck it up and learn how to use Inkscape in lieu of Illustrator.  For the large icon (used in the store and chrome://extensions) is 7 (from original post) the preferred @david-sabata ?  I think I have a handle on the small icons, I'm trying to clean up the duplicates and remove the ones not used.  For #197 I'm trying to do an animated icon if it's not too busy looking.

**Comment by david-sabata** [comment]
Yes, I think 7 is still preferred. It's still Chrome only, so I guess the outline is ok. If we ever move to other browsers, we can do customized one.

Also for #197 I'm not sure about animated icons. They can be done, but it's hacking the pageAction APIs by quickly changing the icons :smile: 
It would probably break our popup (which is recreated each time the icon changes) and be just low-fps slideshow :-/
