### ISSUE TITLE
Request to enable scrobbling for Saavn.com

### ISSUE THREAD

**Issue by ag1410** [david-sabata/web-scrobbler#656]
Hi David,

Thanks for the great app. Is it possible to enable scrobbling for the music website Saavn.com?

**Comment by galeksandrp** [comment]
Looks like not possible because Artist name not shown in player.

**Comment by mayank127** [comment]
This could be done by querying song page and getting the artist name. 

https://github.com/mayank127/web-scrobbler/blob/master/connectors/v2/saavn.js
