### ISSUE TITLE
Google Play Music not working anymore

### ISSUE THREAD

**Issue by G4Zz0L1** [david-sabata/web-scrobbler#657]
Google Music is not working anymore, for the last 2 weeks. I already try to reinstall the plugin, and to wipe and reinstall Chrome. Actually I've Chrome Dev, maybe it can cause problem? (But I don't find anything similar)

**Comment by nickvanhoog** [comment]
I am seeing this as well.

**Comment by G4Zz0L1** [comment]
But not today? I don't know how to check if is the plugin or other things...

**Comment by AltarBeastiful** [comment]
Same here. I got this error in the console : 
```
googlemusic.js:5 Uncaught ReferenceError: Connector is not defined
```

I could only reproduce it once. After reload scrobbling worked fine.

**Comment by G4Zz0L1** [comment]
Altready tried to reload, nothing appeared in my console. I don't have any other extension, so I don't think it's related to any conflict within Chrome.

**Comment by AltarBeastiful** [comment]
Got a bit further. It works fine if go directly to my music library through this url :  https://play.google.com/music/listen

But if I go through https://play.google.com/, then click "Music", then "My Music", scrobbling is broken and I get those in the console: 
```
web-scrobbler/core/content/starter.js:52 Web Scrobbler: Connector.playerSelector is empty. The current connector is expected to manually detect state changes
web-scrobbler/core/content/starter.js:58 Uncaught ReferenceError: $ is not defined
web-scrobbler/core/content/starter.js:14 starter already loaded
```

Can you reproduce this behavior on your side?

**Comment by G4Zz0L1** [comment]
I usually go through that url but I don't receive any message. After the last attempt on reistalling the plugin the indicator at the top has changed to green and the track is recognised, but Last.fm doesn't see me playing anything.

**Comment by G4Zz0L1** [comment]
I've tried to fresh install Chrome and the plugin, another time: the only thing on my console are the xhr request of play music and nothing else.

**Comment by G4Zz0L1** [comment]
Woo! It's working again now. After last reinstall (and directory wiping) is working, but last.fm recognise my track only after it ended, not like before. I'll watch this in the next couple of days, and if it stop working I'll let you know.

**Comment by nickvanhoog** [comment]
Page refresh worked for me, but that is a terrible workaround. Requiring 2x the page load for each thing I want to scrobble breaks its usability.

**Comment by G4Zz0L1** [comment]
Have you already tried to reinstall chrome (wiping the chrome folder) and reinstall everything?

**Comment by AltarBeastiful** [comment]
After further debugging it seems that the scripts are injected twice.  

Background page log when I access from https://play.google.com/ : 
```
-- loaded for the first time, injecting the scripts
inject.js:107 	injecting vendor/jquery-2.1.0.min.js
inject.js:107 	injecting vendor/underscore-min.js
inject.js:79 -- loaded for the first time, injecting the scripts
inject.js:107 	injecting vendor/jquery-2.1.0.min.js
inject.js:107 	injecting core/content/reactor.js
inject.js:107 	injecting vendor/underscore-min.js
inject.js:107 	injecting core/content/connector.js
inject.js:107 	injecting core/content/reactor.js
inject.js:107 	injecting connectors/v2/googlemusic.js
inject.js:107 	injecting core/content/connector.js
inject.js:107 	injecting core/content/starter.js
inject.js:107 	injecting connectors/v2/googlemusic.js
controller.js:311 Tab 3030: created controller for connector: {"label":"Google Play Music","matches":["*://play.google.com/music/*"],"js":["connectors/v2/googlemusic.js"],"version":2}
inject.js:107 	injecting core/content/starter.js
controller.js:311 Tab 3030: created controller for connector: {"label":"Google Play Music","matches":["*://play.google.com/music/*"],"js":["connectors/v2/googlemusic.js"],"version":2}
inject.js:120 -- subsequent ajax navigation, the scripts are already injected
```
Then the scrobble doesn't work and the log off the page is : 
```
web-scrobbler/core/content/starter.js:52 Web Scrobbler: Connector.playerSelector is empty. The current connector is expected to manually detect state changes
web-scrobbler/core/content/starter.js:14 starter already loaded
```

If I access through https://play.google.com/music/listen?u=0#/now scrobble works and script are only injected once: 
```
inject.js:79 -- loaded for the first time, injecting the scripts
inject.js:107 	injecting vendor/jquery-2.1.0.min.js
inject.js:107 	injecting vendor/underscore-min.js
inject.js:107 	injecting core/content/reactor.js
inject.js:107 	injecting core/content/connector.js
inject.js:107 	injecting connectors/v2/googlemusic.js
inject.js:107 	injecting core/content/starter.js
controller.js:311 Tab 3099: created controller for connector: {"label":"Google Play Music","matches":["*://play.google.com/music/*"],"js":["connectors/v2/googlemusic.js"],"version":2}
```

Could this be caused by a double injection? I'm not sure how the Connector could get set to null.
Where could I start the debug of the injection process?

**Comment by david-sabata** [comment]
I dug into this and it seems that Google Music is doing some navigation magic. 0b53de1 should fix it so please wait until it is released and check if the problem persists.
