### ISSUE TITLE
Apple Beats1 radio in a web player

### ISSUE THREAD

**Issue by hans-juergen** [david-sabata/web-scrobbler#659]
Someone created a free webplayer for Apple's Beats1 radio station: http://beats1.tk/ Works for me in Firefox 39 on Windows 7 now. Doesn't scrobble yet, but maybe you can create a connector for it?

**Comment by inverse** [comment]
Unable to use the site here. Perhaps geo-locked. tk domains always feel spammy.

**Comment by david-sabata** [comment]
Not sure what the site is supposed to show. I see only few labels and big white space in the middle.

**Comment by Paszt** [comment]
It's a page with an iframe containing a flash flowplayer.  Most likely geo-locked as inverse said.  There's no way that I can see to get the song metadata.  I don't think a connector can be made for this website.

**Comment by galeksandrp** [comment]
Theoretically info can be grabbed from https://twitter.com/Beats1Plays with Twitter Streaming API (but keep in mind that stream have delay), but it is not a task of this extension.

**Comment by hans-juergen** [comment]
Interesting Twitter link, thank you. Universal Scrobbler might be able to use it in automated way perhaps, or listeners scrobble the tracks manually with it if they do not use Apple Music.

**Comment by alexesprit** [comment]
The requested service is not available for a long time, so I'll close it. Feel free to reopen the issue if that service will be available again.
