### ISSUE TITLE
Not scrobbling from youtube

### ISSUE THREAD

**Issue by problems666** [david-sabata/web-scrobbler#660]
Everytime I play something on youtube the red icon on the top right hand corner appears and it says this website is supported for scrobbling but it never scrobbles. in other websites the icon turns to green and start scrobbling but in youtube this just doesnt happen

**Comment by ODyckhoff** [comment]
I have this issue too. Tried turning off AdBlock just in case that was getting in the way, no dice.

**Comment by Paszt** [comment]
See here for instructions how to debug: https://github.com/david-sabata/web-scrobbler/wiki/How-to-debug-the-extension

**Comment by timtoo** [comment]
In the console log I'm seeing "reset called"  soon after what appears to be a successful call to ws.audioscrobbler.com and then a "nowPlaying Object" message, like this...

> L.FM response to https://ws.audioscrobbler.com/2.0/?method=track.getinfo&autocorrect=0&artis…ndrew%20Wyatt%2C%20Brian%20Wilson&api_key=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx : success
> [XML omitted]
> nowPlaying Object
> reset called

**Comment by david-sabata** [comment]
@timtoo that may be the problem. How do you play the music? Is it playlist, autoplay or are you just clicking tracks manually?

**Comment by pink999** [comment]
its off and on? playlist, manually - the same - bandcamp is down also - it looks like a ok - but you get this message see last fm status where it says everything id fine and dandy no issues since july 1 ?

**Comment by janbaykara** [comment]
Hopefully #752 will fix this?

**Comment by alexesprit** [comment]
This issue is related to v1 Youtube connector which was replaced by v2 implementation a long time ago.
