### ISSUE TITLE
Adress Bar Icon Gone

### ISSUE THREAD

**Issue by Galusa** [david-sabata/web-scrobbler#663]
I don't know what happened but although the scrobbling works, the adress bar icon which appears on the supported sites doesn't show up in the last few days or weeks. The small pop-up window appears on the down-right of the screen as usual showing the artist and song name and the songs are scrobbled OK to Last.fm, but I can't stop unwanted scrobbling without the icon. So, it keeps scrobbling unrelated Youtube video names which i'll have to delete manually from Last.fm site. I didn't change any settings or install another add-on. I was and still using Chrome Canary.

**Comment by david-sabata** [comment]
Chrome Canary is changing very fast and it's possible that something about the address bar icons have changed. Something like this happened before - they make changes back and forth and often they revert the problematic changes or maintain backward compatibility some other way. There's not much we can do about it.

I use Chrome Beta and when some breaking change reaches beta, I'll update the extension. Canary is just too experimental to be supported, sorry.

**Comment by Galusa** [comment]
It has come back today without my interference. Thank you anyway.
