### ISSUE TITLE
Don't work for odnoklassniki.ru

### ISSUE THREAD

**Issue by roamn** [david-sabata/web-scrobbler#667]
Fixed connector.
https://drive.google.com/file/d/0B4053IkN6QcnWllTRTFKM2QtbVU/view?usp=sharing
- change selectors;

Thaks for app.

**Comment by inverse** [comment]
Hey! First up thanks for wanting to contribute to this project.

The usual route for getting changes accepted is via the pull request (PR) route. See https://help.github.com/articles/using-pull-requests/ for more information.

The main steps are:

1. Forking this repo
2. Creating a new branch
3. Apply your changes into that branch
4. Create a PR from the branch to this repo.

Do you feel comfortable enough setting this up?
