### ISSUE TITLE
Support for TIDAL + WiMP stopped working

### ISSUE THREAD

**Issue by olekasper** [david-sabata/web-scrobbler#671]
Hi,

Support in TIDAL (listen.tidalhifi.com) and its Norwegian counter part WiMP (play.wimpmusic.com) has stopped working for me. (Yet it works on e.g. bandcamp.com.)

Let me know if I can do anything in way of debugging (or fix something at my end?).

(Even though TIDAL's Web and desktop players (just a Chromium wrapper, really) natively support scrobbling, it is *extremely* unreliable (it "disconnects" from last.fm all the time, without warning - leaving entire sessions unscrobbled).)

**Comment by Paszt** [comment]
Looks like they're redirecting from listen.tidalhifi.com to listen.tidal.com, so that would be a quick fix.  But I don't see any previous code for WiMP - did it use to work?

**Comment by olekasper** [comment]
Might be my bad recollection, originating form the fact that TIDAL is the "internationalised" version of WiMP. But looking at the connector code for TIDAL, it just might work without much effort, as they are basically different skins for the same service.

(WiMP will probably be completely rebranded to TIDAL in the future, so there might not be any reason to add it to connectors.js.)

**Comment by david-sabata** [comment]
I added the redirect url to matcher, which should help.

As for WiMP please start a new separate issue for it ;)
