### ISSUE TITLE
Add support for lyricstraining.com

### ISSUE THREAD

**Issue by Arthaey** [david-sabata/web-scrobbler#672]
I use lyricstraining.com to practice foreign languages. It would be nice if I could scrobble the songs I listen to there.

**Comment by Arthaey** [comment]
I'm trying to write the connector myself. However, lyricstraining's player is an iframe with a Youtube video, which means I'm getting "cross-origin frame" errors.

Are there other connectors that successfully work when the player is just an embedded Youtube video? Or are there other workarounds for scrobbling the song, if not?

**Comment by david-sabata** [comment]
Hi @Arthaey! I'm not sure if scrobbling embedded YouTube videos is possible. I never had the time to dig into it, but there is definitely a cross-origin access, which is usually a problem (at least for us, generally that's for users' security).

**Comment by Arthaey** [comment]
That's what I was afraid of.

Would you accept a connector that merely tracked that, say, 1 minute had passed before scrobbling? Or allowing the user to manually scrobble by clicking "yes, the song is done" from a popup?

**Comment by david-sabata** [comment]
That doesn't sound very usable. 
The idea of this extension is that is just works out-of-box, without any user actions other than logging in.

**Comment by Arthaey** [comment]
Working on a simple timer would still "just work", it's just not as accurate as checking how long the player has played.
