### ISSUE TITLE
1.48 >>> 1.49

### ISSUE THREAD

**Issue by laurencebarnes505** [david-sabata/web-scrobbler#673]
1.48 worked without problems, but since 1.49 the songs aren't scrobbled or only partly scrobbled. I've downloaded many times the older version, but Google update the extension after about few hours again automatically.

**Comment by Paszt** [comment]
I just tried it on several sites and had no issues.  What website is not working for you?  You can also get more info by following this guide: https://github.com/david-sabata/web-scrobbler/wiki/How-to-debug-the-extension

**Comment by laurencebarnes505** [comment]
I'm using XBOX Music, Bandcamp and YouTube.

**Comment by david-sabata** [comment]
What exactly are the symptoms?
Can you post logs? https://github.com/david-sabata/web-scrobbler/wiki/How-to-debug-the-extension

**Comment by laurencebarnes505** [comment]
https://drive.google.com/file/d/0B2FXK0rhSzpAT1h3SlNodHhzSlE/view?usp=sharing

**Comment by laurencebarnes505** [comment]
Microsoft rebrands Xbox Music to Groove and Grove won't be scrobbled.

**Comment by galeksandrp** [comment]
related #681 and #677

**Comment by david-sabata** [comment]
Alright, I'll close this. @laurencebarnes505 please check if the issue persists on version 1.51 and if so, reopen this issue and post some more info.
