### ISSUE TITLE
Bandcamp assuming "various artists" incorrectly

### ISSUE THREAD

**Issue by tyrust** [david-sabata/web-scrobbler#676]
Hello,

First off thanks for the extension, it works for me pretty much all the time.

Now for my issue.  I'm listening to Lil Ugly Mane's [Third Side of Tape](https://liluglymane.bandcamp.com/album/third-side-of-tape).  Each track is being scrobbled with artist="SIDE {ONE,TWO,THREE}", track="{A,B}".  I took a look at the code see that it is because `artistIsVarious` [assumes that](https://github.com/david-sabata/web-scrobbler/blob/master/connectors/v2/bandcamp.js#L39-49) because all the tracks have dashes that the left side of the dash is the artist and the right is the track.  This would be an acceptable misunderstanding, except for the fact that `getArtist` does, in fact, return the artist "Lil Ugly Mane".  

So, in `getArtistTrack`, the correct value returned by `getArtist` is [being clobbered](https://github.com/david-sabata/web-scrobbler/blob/master/connectors/v2/bandcamp.js#L63-L67) because `artistIsVarious` is returning the wrong value.

I'm happy to write the fix myself, but I wanted to ask you: have you ever seen a time where the artist is Various, but `$('span[itemprop=byArtist]').text()` is something besides "Various"?  Like, in the [example you give](http://tigersmilkrecords.bandcamp.com/album/peru-maravilloso-vintage-latin-tropical-cumbia), `getArtist` will return "Various Artists", yielding the hyphen/vertical bar check in `artistIsVarious` unnecessary.

Thanks for your work on this.  Please let me know if I can clarify anything for you.

-Tyrus

**Comment by inverse** [comment]
I can name [one][0] example off the top of my head which doesn't use Various or any other variation of the regex we use. What is your proposed solution for resolving this?

[0]: https://touched.bandcamp.com/album/touched-two-the-remixes

**Comment by tyrust** [comment]
>I can name one example off the top of my head which doesn't use Various or any other variation of the regex we use.

Darn that is really too bad.  Looks like there will have to be cases that are scrobbled incorrectly.

>What is your proposed solution for resolving this?

Since we cannot get everything right, it's going to be a matter of deciding what is "least bad".  On one hand, it would be more correct if producers properly set the album artist to "Various".  However, like in the example you gave, it does make sense from the producer's perspective to put their name as the artist of a collection.  Thus, the hack of checking for dashes and pipes.

The best decision for this extension would be the one that gets the most things correct, but I don't have the data to know what this decision should be.  This isn't my code, the decision is up to you guys.

**Comment by tyrust** [comment]
A friend of my has thought of at least a small fix.  In the [check for dashes and bars](https://github.com/david-sabata/web-scrobbler/blob/master/connectors/v2/bandcamp.js#L44), it should probably actually check for a dash or bar surrounded by spaces (i.e. `/ [\||-] /`.  This way if an artist happens to use hyphenated words in all of their tracks, it won't be mistaken for a Various Artists album.

**Comment by inverse** [comment]
Yeah - It's going to be really tough to get everything to scrobble correctly, especially in instances like these. 

Perhaps something that could work in your example would to when checking that all tracks are dashed to then check that the artists are different? What do you think? 

Your suggestion could also work and I think that would be a sufficient solution :+1: we should opt for that. @Paszt you have an opinion?

> This isn't my code, the decision is up to you guys.

Also don't feel like you can't add to the code, it's an open source project after all :smile:  But @david-sabata  has the final say in the end :wink:

**Comment by david-sabata** [comment]
Surrounding separators with spaces sounds like a reasonable low-effort solution. Assuming that mix tracks will be always labeled with separator with spaces :-P

Feel free to create fix and open PR.
