### ISSUE TITLE
Xbox Music name and URL change - not scrobbling now

### ISSUE THREAD

**Issue by Machiventa** [david-sabata/web-scrobbler#677]
Today Microsoft updated their Xbox Music web player to a different URL and now the scrobbler isn't working. 
Will there be a fix in the works?

**Comment by artlung** [comment]
@Machiventa Looks like the new url is https://music.microsoft.com -- I have not used this service -- has the interface also undergone a revamp?

**Comment by hans-juergen** [comment]
The new name for Xbox Music is Groove now, but the GUI and player looks the same, except that it used white background now.

**Comment by electricduck** [comment]
Yeah, it is pretty much the same as the old Xbox Music, except with a reskin
![](http://z54314.bsx.fr/~/ducky/onedrive/screenies/%CE%A8200/Windows-6.1.7601.Pro/0963.png)

**Comment by Machiventa** [comment]
Any chance the developer of this plugin can update it? It's been two weeks of no scrobbling. 

Apparently the app didn't scrobble albums (when it was working before the name change) and the dev finally chimed in months later telling me it's an easy fix and for me to just do it myself. I get the feeling he doesn't care too much about updating it. Maybe I'm misreading the situation, but I sure would like to scrobble albums from Groove. I would definitely donate some funds if that would help! :)

**Comment by artlung** [comment]
@Machiventa I've created a pull request for this, I hope it's as simple as it seems.
cc: @david-sabata

**Comment by Machiventa** [comment]
Thanks artlung! Just found scroblr works for Groove so I'm good now!!

**Comment by david-sabata** [comment]
Resolved with #681
