### ISSUE TITLE
Connector request: dashradio.com

### ISSUE THREAD

**Issue by yac00b** [david-sabata/web-scrobbler#692]
I recently started listening to Dash Radio, but unfortunately they do not offer Last.fm scrobbling. Would it be possible to create a connector for their website. It would be awesome.

**Comment by bes-internal** [comment]
#693 waiting for the next release

**Comment by yac00b** [comment]
Awesome, great news, thanks!

**Comment by yac00b** [comment]
When will this be available in Chrome extension?
