### ISSUE TITLE
Connector request: radio.yandex.ru

### ISSUE THREAD

**Issue by TimO-n** [david-sabata/web-scrobbler#694]
I recently started listening to Radio Yandex, but unfortunately they do not offer Last.fm scrobbling. Would it be possible to create a connector for their website. It would be awesome. URL: https://radio.yandex.ru/

**Comment by roamn** [comment]
Yandex support lastfm in profile settings, you can link this service to yandex.
And scrobble yandex music and radio.

**Comment by roamn** [comment]
Screenshot of settings page: http://i.imgur.com/avW71tJ.png

**Comment by bes-internal** [comment]
Connector already in Version: 1.50 (d9e152783) at chrome web store.

**Comment by david-sabata** [comment]
Is the Radio Yandex working using this extension working or not?
Using internal L.FM connection is not a real solution for us :)

**Comment by TimO-n** [comment]
@david-sabata Yandex advertising inserts and extension stop reading after headers songs

**Comment by galeksandrp** [comment]
Don't see any advertising even without AdBlock. It works for me.

We need to split artist names from 'Nancy Sinatra, Billy Strange' and catch first.

**Comment by bes-internal** [comment]
@TimO-n can you copy page source with advertising? What we want:
1. on page with adv
2. right click on page on any empty place
3. above in code find root container <div class="page-root">
4. right click on it and "edit as html"
5. select and copy all (ctrl+a, ctrl+c) in textarea

**Comment by TimO-n** [comment]
now in extension have problem with scrobbling. Beta LastFM can't authenticate with new service api

**Comment by bes-internal** [comment]
we only need the code page, the extension does not matter here

**Comment by 1v** [comment]
Connecting account here https://music.yandex.ru/settings working fine on https://radio.yandex.ru/.

**Comment by alexesprit** [comment]
The extension works fine with YandexRadio now.
