### ISSUE TITLE
Travis CI test env is running on legacy infrastructure

### ISSUE THREAD

**Issue by janbaykara** [david-sabata/web-scrobbler#703]
@david-sabata A notice appears on un-finished CI tests for this repo:

> This job is running on legacy infrastructure

[Apparently it's pretty easy to upgrade, and it makes tests faster amongst other things](http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade#How-can-I-use-container-based-infrastructure%3F).

**Comment by galeksandrp** [comment]
Pretty easy to upgrade, but you don't make a PR :smile: 

#704 fixes it, `.travis.yml` is simple, so I hope that don't break something.
