### ISSUE TITLE
Switch IRC for gitter

### ISSUE THREAD

**Issue by inverse** [david-sabata/web-scrobbler#711]
I think we should switch IRC for [gitter](https://gitter.im) as it plays really nicely with github and will allow us to discuss easier. What do you think?

**Comment by janbaykara** [comment]
:+1: Keen.

**Comment by galeksandrp** [comment]
:+1:, because gitter have https://irc.gitter.im anyway

**Comment by inverse** [comment]
Ahaha I didn't realise that! The best of both worlds :dancer:

**Comment by david-sabata** [comment]
:tada: https://gitter.im/david-sabata/web-scrobbler

**Comment by david-sabata** [comment]
https://github.com/david-sabata/web-scrobbler/commit/ca1a57f689dbe3c2f30167cda46f015b1bc9956e
