### ISSUE TITLE
Auth error 1.51

### ISSUE THREAD

**Issue by bes-internal** [david-sabata/web-scrobbler#713]
was trying to authenticate several times, restart browser, but every time I get this error
![](http://internal.by/i/20150824-012542.png)
full url from screenshot: https://ws.audioscrobbler.com/2.0/?method=auth.getsession&api_key=d9bb1870d3269646f740544d9def2c95&token=68a15342e47a0bdd36ae9fb3085f4035&api_sig=5b078f4651d962adfb21e5dc28610960&format=json

**Comment by daberkow** [comment]
@janbaykara fixed it with that branch after a re-auth
