### ISSUE TITLE
Support for Jazzandrain

### ISSUE THREAD

**Issue by boky8** [david-sabata/web-scrobbler#725]
Hi,

please add support for:
- http://www.jazzandrain.com/
- http://relaxingbeats.com/
- http://epicmusictime.com/
- http://www.christmasholidaymusic.com/

(All share the same backend server, all seem to be using Soundclould as a backend).

Thanks.

**Comment by galeksandrp** [comment]
http://www.christmasholidaymusic.com/ -> http://holidaychristmasmusic.com/

**Comment by david-sabata** [comment]
Closed by #726
