### ISSUE TITLE
Jamendo

### ISSUE THREAD

**Issue by FraYoshi** [david-sabata/web-scrobbler#727]
![jamendo issue](https://cloud.githubusercontent.com/assets/14005514/9532398/c3e7204a-4d0b-11e5-987b-91e8be5cd85d.PNG)
Music is playing but not on scrobbling.. since all day long

**Comment by signaleleven** [comment]
Jamendo had, since this issue was opened, a substantial overhaul of the interface. The connector must be updated.

**Comment by alexesprit** [comment]
See #873. Works fine for me.
