### ISSUE TITLE
Scrobbling has stopped after new lastfm update.

### ISSUE THREAD

**Issue by iamrazor** [david-sabata/web-scrobbler#739]
Also scrobbler dissapeared from Opera apps store.

**Comment by pink999** [comment]
completely stopped - no nothing but tampermonkey (tube), no answers, a lot of complaints?

**Comment by fedorg** [comment]
Did you try reauthenticating with last.fm?

**Comment by iamrazor** [comment]
Yes i tried. Few times. Still no scrobbling.

**Comment by fedorg** [comment]
@iamrazor This is weird, people have reported issues with lastfm itself, but I never had any. Could you show us the background page logs?

**Comment by david-sabata** [comment]
The scrobbler was intentionally taken down from the Opera store. It's because Opera is no longer supported. For more info see #503 

Do I get it right that you're still using Opera? The extension is no longer updated and probably not working there.

**Comment by pink999** [comment]
All is working great (Opera is overrated :) I know you peeps are busy, the big question everyone has is exporting listened to tracks From L-FM, seems people don't like Libre? 

I have never have tried it, someone had a site that put all scrobbling history into zip files, opens in excel, but read only, so an easier question is do any other media player (other than Spot) support export/import function without major glitches, no biggie a yes or no in a few week would be cool, I hope is okay to post a question here, its not an issue for me.
Thanks David & others, you are a great service

**Comment by david-sabata** [comment]
@pink999 Import/export will probably not be implemented, as it goes too far from this extension's core features and main purpose.
If you're talking about Libre.fm, then we already have PR for that - #756

**Comment by pink999** [comment]
I think I'll give a try or likely, its getting funky, mean, I honestly
think a merge with bandcamp would be perfect, that is just me,
But; either way Thank you so much David!

Hey if you like rock and fun which you do - this rocks,
so funny and big names

- https://www.youtube.com/watch?v=vc5PMA6poio
