### ISSUE TITLE
Xiami problem

### ISSUE THREAD

**Issue by MomoMars** [david-sabata/web-scrobbler#740]
Not scrobbling from xiami, help please!

**Comment by Muonik** [comment]
Same problem ಥ_ಥ

**Comment by inverse** [comment]
Is this still an issue?

**Comment by Muonik** [comment]
yeah

**Comment by alexesprit** [comment]
Xiami scrobbling works fine for me (e.g. from here http://www.xiami.com/play?ids=/song/playlist/id/1020552829/type/1#loaded).

[How to debug extensions.](https://github.com/david-sabata/web-scrobbler/wiki/How-to-debug-the-extension)

**Comment by alexesprit** [comment]
Closed as outdated.
