### ISSUE TITLE
trance.fm

### ISSUE THREAD

**Issue by sergeychibunin** [david-sabata/web-scrobbler#750]
Hello.
Add the trance.fm to scrobbler, please.
Thanks.

**Comment by inverse** [comment]
The site uses a flash player. Not sure if we can support this one I'm afraid.

**Comment by janbaykara** [comment]
@inverse @sergeychibunin without looking at the site, it might still be possible to intercept API calls via 
`chrome.webRequest.onCompleted.addListener()`.

E.g. https://github.com/janbaykara/Yammer-Desktop-Notifications/blob/master/lib/background.detectors.js#L12-L36

**Comment by ex47** [comment]
Should be closed as the site is dead.
