### ISSUE TITLE
Chrome 46-beta does not scrobble and re-auth

### ISSUE THREAD

**Issue by Ky6uk** [david-sabata/web-scrobbler#753]
I tried to scrobble from Google Music and VK on the last extension from store (1.52) and does not happens anything. Chrome 45-beta.

Re-authenticate button doesn't work too.

**Comment by fedorg** [comment]
Is the scrobbling enabled? The icon in the adress bar should be red as well.
If this checks out, you can upload a screenshot of the background page console to help investigate.

**Comment by Ky6uk** [comment]
After re-auth I have getToken response (chrome console):
```xml
<lfm status="ok">
  <token>70d77e14997a9fc1f75978ce00000000</token>
</lfm>
```

and 403 on the scrobble try
```
Request URL: https://ws.audioscrobbler.com/2.0/?method=auth.getsession&api_key=d9bb1870d3269646f740544d9def2c95&token=70d77e14997a9fc1f75978ce00000000&api_sig=0bf40a0f44a3e763020199eb00000000&format=json
Request Method: GET
Status Code: 403 Forbidden
```

I think this is lastfm issue?

**Comment by Ky6uk** [comment]
Ya. Error code 14 — "This token has not been authorized". This is strange.

**Comment by d3m3vilurr** [comment]
I have same problem. I think, it is [lastfm issue](http://www.last.fm/group/Last.fm+Web+Services/forum/21604/_/2277427).

anyway I try to change mobile api, and console logs look like work.
```
	function tradeTokenForSession(token, cb) {
		var params = {
			method: 'auth.getMobileSession',
			api_key: apiKey,
			username: 'LASTFM_USERID',
			password: 'LASTFM_PASSWORD'
		};
		var apiSig = generateSign(params);
		$.post(apiUrl + '?format=json&api_sig=' + apiSig, params)
			.done(function(response) {
				if ((response.error && response.error > 0) || !response.session) {
					console.log('auth.getSession response: ' + JSON.stringify(response));
					cb(null);
				} else {
					cb(response.session);
				}
			})
			.fail(function(jqxhr, textStatus, error) {
				console.error('auth.getSession failed: ' + error + ', ' + textStatus);
			});
	}
```
but recent track page still not update.(I think, it also last.fm issue)

**Comment by david-sabata** [comment]
@Ky6uk are you still getting these errors?

I had to reauth today, having the same error as reported. But once I got a new token and authorized it, everything works fine.

Possibly some temporary L.FM issue

**Comment by david-sabata** [comment]
also Chrome beta channel should be on 46 now, so update and try it again please

**Comment by Ky6uk** [comment]
Problem still here.

**Comment by wxl** [comment]
Just upgraded to 47.0.2526.27-1 (on Ubuntu 14.04 fwiw) with 1.53 of web-scrobbler and all is well and good. Wasn't behaving on 46, despite re-authing. Actually didn't on 47 either, at first, but when I re-authed again, all was well. That being said, if there's a bug, I suspect the issue lies, as @david-sabata said, in a temporary issue.

**Comment by wxl** [comment]
47.0.2526.58-1 and 1.54. Had to re-auth again to get Bandcamp to work. It seems to me it's kind of a bug that one can clearly see the 403 errors and yet the notifications seem to suggest all is well and good. So you don't notice unless you check.

**Comment by Ky6uk** [comment]
47.0.2526.73 beta-m (64-bit) confirmed to work after clean installation of that extension.

**Comment by ex47** [comment]
Should be closed. (outdated)
