### ISSUE TITLE
Youtube 'page' change scrobble error

### ISSUE THREAD

**Issue by janbaykara** [david-sabata/web-scrobbler#757]
When the playing Youtube video changes, or navigation occurs, the extension sometimes hangs up in the backend. I imagine this has something to do with capturing the HTML5 history state of the page, but it means that often a silent error prevents scrobbling, fixable only by a page refresh (that the user probably wouldn't expect to have to do.)

 ````
2015-09-04 13:38:43.323 main.js:97 
    Missing controller for tab 476 (should only happen for legacy connector)

2015-09-04 13:38:43.324 @ extensions::uncaught_exception_handler:8
    Error in event handler for runtime.onMessage: TypeError: Cannot read property 'onStateChanged' of undefined
        at chrome-extension://achhfabcnpilepjnpedafpakffnfpple/core/background/main.js:145:9handler
````

![screenshot 2015-09-04 14 06 19](https://cloud.githubusercontent.com/assets/237556/9684248/31c02186-530e-11e5-9f21-69639420a0b7.png)

**Comment by david-sabata** [comment]
I am getting a lot of these too. Using Chrome beta, currently 45. How about you?

**Comment by david-sabata** [comment]
Also noticed the page action icon disappears and the connector doesn't stay in place.

Youtube probably hacks the history api even better than we do :-P

**Comment by janbaykara** [comment]
Believe I'm just using standard Chrome distro, Version 45.0.2454.85 (64-bit)

**Comment by fedorg** [comment]
I believe I have found a reproducible way of crashing the controller:
1. Play youtube video
2. Search something
