### ISSUE TITLE
Re-categorise on Chrome Store, from 'Fun' to 'Entertainment: Music & Radio'

### ISSUE THREAD

**Issue by janbaykara** [david-sabata/web-scrobbler#767]
#### Currently: 
<img width="330" alt="screen shot 2015-09-06 at 10 00 13" src="https://cloud.githubusercontent.com/assets/237556/9703512/4313bfda-547e-11e5-9a16-19cdcb9b5d5b.png">

#### New category might make more sense: 
<img width="312" alt="screen shot 2015-09-06 at 09 59 27" src="https://cloud.githubusercontent.com/assets/237556/9703513/4541e890-547e-11e5-9abd-698793f41c1c.png">

**Comment by artlung** [comment]
+1

**Comment by david-sabata** [comment]
Where's that screenshot from? I only see like 10 base categories in the extension settings. Totally different from these on the screenshot

**Comment by janbaykara** [comment]
@david-sabata These are from the chrome store user view: https://chrome.google.com/webstore/category/apps

<img width="416" alt="screen shot 2015-09-06 at 22 34 24" src="https://cloud.githubusercontent.com/assets/237556/9706747/7c8ce016-54e7-11e5-8c16-ec9e205e9c79.png">

**Comment by janbaykara** [comment]
...

Right, ignore me. I've fundamentally mistaken Chrome Store "apps" for "extensions", which have different categories entirely.
