### ISSUE TITLE
bop.fm artist name fix

### ISSUE THREAD

**Issue by abelas** [david-sabata/web-scrobbler#769]
Currently the Artist selection includes whitespace that bop.fm adds to the current artist.

![capture](https://cloud.githubusercontent.com/assets/2183467/9723029/576efe3a-557e-11e5-935b-e74cdcf227dc.PNG)

I made a very inelegant fix that uses the 'data-event-label' attribute from the same anchor tag as the original and lets the auto correct fix the capitalization.

(replaces Connector.artistSelector)

```javascript
Connector.getArtist = function () {
	return $('.current-song-section .song-info .artist a:first').attr('data-event-label');
}
```

**Comment by abelas** [comment]
Realized it only works if there is one word in the attribute. Updated to remove hyphen, but still this isn't the best way to do this. I don't know jQuery.

```javascript
Connector.getArtist = function () {
	var artist = $('.current-song-section .song-info .artist a:first').attr('data-event-label');
	artist = artist.replace(/-/g, ' ');
	return artist;
}
```

**Comment by galeksandrp** [comment]
It's not jQuery, it's javascript that have 100500 functions that does same things.

Anyway, it fail on Ne-Yo as expected.

Sometime `@bes-internal` said me, that there are `trim()` in javascript, it does the trick.

**Comment by abelas** [comment]
Thank you so much! That makes a lot more sense. What does "|| null" do here?

**Comment by janbaykara** [comment]
@abelas getArtist() will return `null` if there is no valid text to return. `text || null` is a shorthand for that, where `||` means "or".

**Comment by abelas** [comment]
@janbaykara I see. So the solution is really as simple as using the core connector getArtist function and adding trim(). I had tried something similar to this but it kept giving me [object Object] or a blank field. I see my mistake now. Thank you for your help!
