### ISSUE TITLE
New default cover art image

### ISSUE THREAD

**Issue by janbaykara** [david-sabata/web-scrobbler#777]
![screenshot 2015-09-10 14 38 27](https://cloud.githubusercontent.com/assets/237556/9789742/d514c93a-57c9-11e5-89ff-fb0bafa3abb7.png)
1. The top one is the current extension art fallback, and is no longer used on the Last.fm site
2. The middle and bottom ones are both used in the Last.fm redesign ( [here](http://img2-ak.lst.fm/i/u/174s/c6f59c1e5e7240a4c0d427abd71f3dbb.png) & [here](http://img2-ak.lst.fm/i/u/174s/4128a6eb29f94943c9d206c08e625904.png) )

Thoughts on whether/which way to proceed?

**Comment by david-sabata** [comment]
I like the note :-)

**Comment by inverse** [comment]
Bottom one looks better ;)

**Comment by deansheather** [comment]
+1 for bottom cover art image. I think it looks better than the top and middle ones.

**Comment by ex47** [comment]
Relevant?

**Comment by alexesprit** [comment]
Added "note" icon.
