### ISSUE TITLE
Bandcamp scrobbling not working

### ISSUE THREAD

**Issue by w-sky** [david-sabata/web-scrobbler#783]
Hi there,

I've been playing some music on bandcamp.com lately and it does not get scrobbled, though the red scrobbling icon is shown. When I click on it, I always see the "Play some music to get started" message. But it is already playing of course.

For example: http://kelpe.bandcamp.com/album/the-curved-line

Browser: Google Chrome Version 45.0.2454.85 (Linux)
Scrobbler: Last.fm scrobbler 1.52

**Comment by janbaykara** [comment]
May be fixed by changes in #785

**Comment by w-sky** [comment]
Great :) can the Autocorrect feature help with this?

**Comment by tdhooper** [comment]
The plugin works for me on that page.

#785 fixes various artist album scrobbling.

**Comment by david-sabata** [comment]
Just tried after merging #785 and it seems to be scrobbling fine. @w-sky please wait for 1.53 release and reopen this issue if your problem persists
