### ISSUE TITLE
Add an automatic scrobbling feature to new unrecognized tracks

### ISSUE THREAD

**Issue by evrial** [david-sabata/web-scrobbler#786]
Majority of my music from soundcloud feed is unrecognized, so it would be handy to skip the dialog.

**Comment by dgw** [comment]
Is this why I often get the gray ? button and have to confirm the song title and artist before it'll scrobble? I'm seeing the behavior in Plex.

**Comment by evrial** [comment]
still up

**Comment by jaccarmac** [comment]
Specifically, I find this to be a problem when I'm working. I don't have the energy to check every song for scrobblability, but also want to be able to go back and see my listening history in Last.fm.

**Comment by evrial** [comment]
Exactly. 106 open issues here, so I had no good use and removed the extension. Sadly Last.fm is slowly dying.

**Comment by inverse** [comment]
You could always help out and contribute :wink:

**Comment by dgw** [comment]
It's unreasonable to assume that everyone commenting on an issue has the necessary time and/or expertise to submit a pull request.

**Comment by inverse** [comment]
Ok
