### ISSUE TITLE
Pandora

### ISSUE THREAD

**Issue by 10-14** [david-sabata/web-scrobbler#787]
Scrobbling for Pandora has been working for the past few days...until today. The scrobbler does not recognize any music playing. What can I do? Disabling and re-enabling didn't do anything.

**Comment by TRManderson** [comment]
I too am having this issue.

**Comment by Paszt** [comment]
Just tested and I can scrobble with no problem.  See this link for information how to debug: https://github.com/david-sabata/web-scrobbler/wiki/How-to-debug-the-extension 
  
If you see authorization type errors, you can try to re-authorize the extension in the extension's options page.

**Comment by JamesG3D** [comment]
![image](https://cloud.githubusercontent.com/assets/8207645/11016640/35445b76-85ed-11e5-8a12-fdf292295389.png)

Doesn't seem to be even attempting to do the connector thing.

**Comment by Paszt** [comment]
@JamesG3D 

The screenshot you posted is from pandora.com console instead of the extension's background page.  The link in my message above shows how to debug the extension. I have no issues with scrobbling from pandora.

**Comment by inverse** [comment]
Closing as non-issue
