### ISSUE TITLE
Click icon to disable scrobbling gone

### ISSUE THREAD

**Issue by fishstik** [david-sabata/web-scrobbler#795]
After 1.51 with the "_Added popup with song info - just click the icon in address bar (v2 only)_" feature, I can no longer quickly disable (and re-enable) scrobbling by clicking on the icon (song info popup appears instead). I used it a lot to quickly disable if an incorrect title or non-song is to be scrobbled. Any plans to bring this back?

**Comment by fedorg** [comment]
Yes :)

**Comment by jason404** [comment]
I've been looking forward to having the ability to enable and disable coming back.  Also, when the magnifying glass icon comes up, for 'lookup', it doesn't seem to do anything and it is not possible to edit titles at all.

I suppose you must know this, but...

**Comment by dreambrother** [comment]
+1

**Comment by jason404** [comment]
I was using my old laptop.  Chrome isn't signed into my Google account, so it still has old extensions.  I found that the old version of web-scrobbler works fine.  

Is there a way to revert to the old extension version on my signed-in Chrome installations?  The current version seems to have a lot of stuff broken.

**Comment by inverse** [comment]
You could run an unpacked build against a tagged version. 

As for the icon being gone I know chrome have changed a lot the way icons etc are with the beta builds. Could it be related to this?

**Comment by fishstik** [comment]
No, this was before that. This issue came when notifications contents were updated in 1.51. Looks like the next iteration of notifications will add the functionality though. As to when it'll be released...

**Comment by inverse** [comment]
Closing as old
