### ISSUE TITLE
Sound Cloud connector not working

### ISSUE THREAD

**Issue by langri-sha** [david-sabata/web-scrobbler#799]
Stopped working as of today. Here's what I'm getting at the console:

```
Web Scrobbler: Connector.playerSelector is empty. The current connector is expected to manually
detect state changes
```

**Comment by inverse** [comment]
Check the extension log too. The SC connector doesn't use the playerSelector so this is why this is being thrown. 

It's working here! Most likely it'll be that it's unable to find the track on last.fm and thus is not valid. Could be related to API changes - see #785

**Comment by langri-sha** [comment]
I've looked at the logs at the extension. 

First had `403 Forbidden` responses when getting my session data errors, even though I've re-authenticated recently, but the extension seemed to be happy and otherwise caught tracks from the SC player.

Right, one re-auth later, I am getting `400 Bad Request` responses for the following request:

```
https://ws.audioscrobbler.com/2.0/?method=track.getinfo&autocorrect=0&username=malkron&artist=FLOOR%20BABA&track=a%20woe%20like%20whoa&api_key=${api_key}
```

And now everything seems to be working fine! Thanks @inverse for pointing me in the right direction.
