### ISSUE TITLE
Support for Cubic.fm

### ISSUE THREAD

**Issue by lef-est** [david-sabata/web-scrobbler#801]
Will you please add support for Cubic.fm?
It's an aggregator for Soundcloud, Beatport, Youtube etc. (https://cubic.fm/integrations)

**Comment by inverse** [comment]
I've requested an invite, will see what I can do when I get it. 

.. .alternatively if you're feeling adventurous you could take a look at one of the v2 connectors and adapt it to the site :wink:

**Comment by lef-est** [comment]
Oops sorry this is my invite code!
https://cubic.fm/?ref=producthunt&i=H1i4Fv72Gg sorry forgot about that.

**Comment by inverse** [comment]
:+1: cheers! Ill work on this for you

**Comment by lef-est** [comment]
Thank you! :)
