### ISSUE TITLE
Spotify isn't scrobbling on Chrome 43.0.2357.134 (64-bit), Mac 10.10.4 13 inch Macbook pro

### ISSUE THREAD

**Issue by jranks123** [david-sabata/web-scrobbler#804]

**Comment by david-sabata** [comment]
Can you please post version of the extension and details of your issue?
Screen size of your Macbook isn't really relevant :-P

**Comment by asmisha** [comment]
Version 1.54, chrome 46.0.2490.86 (64-bit), mac 10.11.1
Can't reauthenticate on the options page - clicking on the button does nothing
on vk.com the icon is always "ready to scrobble", on youtube it always "searching for the song"
Ready to provide any other useful information

**Comment by alexesprit** [comment]
I'm closing this issue because looks like new Spotify player is default for most users; the issue is not related to current web player.
