### ISSUE TITLE
Scrobble search never completes (Windows 10, chrome Version 46.0.2490.71 m)

### ISSUE THREAD

**Issue by wmvoje** [david-sabata/web-scrobbler#806]
![capture](https://cloud.githubusercontent.com/assets/5429461/10464470/b7d466ac-719e-11e5-827d-2b73790991f5.PNG)

This app searches indefinitely for the track in the Laft.fm database. I can confirm that this happening for both youtube and google play music.

**Comment by Paszt** [comment]
I just had this issue.  Re-authenticating from the extension's options fixed it for me.

**Comment by wmvoje** [comment]
@Paszt This worked perfectly. Thanks for the tip. I'm going to close this issue then.
