### ISSUE TITLE
PageAction icon mismatch

### ISSUE THREAD

**Issue by fedorg** [david-sabata/web-scrobbler#808]
![icon_diff](https://cloud.githubusercontent.com/assets/4352852/10488820/2e01ee1c-72a3-11e5-8a4e-e8877f233868.png)
Version 1.53

**Comment by Paszt** [comment]
I purposely didn't update the V1 icons.  This gives you a visual indication of which version the connector is and the V1 connectors will be phased out shortly.

**Comment by janbaykara** [comment]
Good idea.
