### ISSUE TITLE
Retina pageAction icons are pixelly

### ISSUE THREAD

**Issue by janbaykara** [david-sabata/web-scrobbler#811]
Fussy, minor issue, but on my retina screen the icons look pixelly, like so:

<img width="76" alt="screen shot 2015-10-17 at 10 53 54" src="https://cloud.githubusercontent.com/assets/237556/10558144/6cd237e8-74bd-11e5-8fd4-b81440b8e848.png">

Could fix this by providing double-resolution icon files. @Paszt, thoughts?

**Comment by david-sabata** [comment]
It looks that pageAction API already supports multiple icon resolutions - https://developer.chrome.com/extensions/pageAction#method-setIcon

**Comment by Paszt** [comment]
Please test #813 as I don't have a device that supports double scale.

**Comment by janbaykara** [comment]
<img width="141" alt="screenshot 2015-10-18 17 54 55" src="https://github-cloud.s3.amazonaws.com/assets/237556/10565149/885c6fe2-75c1-11e5-9054-02b86f906ad7.png">

#813 - It's... it's beautiful :+1:
