### ISSUE TITLE
VK.com is not scrobling in 46.0.2490.71 m

### ISSUE THREAD

**Issue by IRainman** [david-sabata/web-scrobbler#812]
Hello! The site vk.com skrobling not working. The problem is that the plugin does not see the playback track.

I tested on the following URL:

https://vk.com/wall-35486626_305177

https://vk.com/wall-10839812_371448

https://vk.com/wall-10839812_371464

https://vk.com/wall-35486626_305201

https://vk.com/audios3735913

**Comment by IRainman** [comment]
I remove and reinstall the extension after that did reauthentication - did not help

**Comment by david-sabata** [comment]
Already fixed in #809 which will be released soon

**Comment by IRainman** [comment]
Thx! 
P.S. I apologize for the carelessness :-[
