### ISSUE TITLE
bandzone.cz scrobbling is not working

### ISSUE THREAD

**Issue by pvlkohout** [david-sabata/web-scrobbler#819]
When I play the song on the bandzone.cz it says 
"Play some music to get started
Is it already playing?"
When I choose some unknown band, which is not probably in database, it displays "?" icon and when I select the right name of song I also get the "Play some music to get started
Is it already playing?"

I think, there is some problem in detecting that song is playing...
btw. on youtube and other it works well...

![2unknownsong](https://cloud.githubusercontent.com/assets/15219025/10617675/f599813e-776b-11e5-8b74-e73ae2f9a2a2.png)
![3than](https://cloud.githubusercontent.com/assets/15219025/10617676/f59b4546-776b-11e5-9536-8867138e583f.png)
![1notscrobbling](https://cloud.githubusercontent.com/assets/15219025/10617677/f5a8885a-776b-11e5-8853-c8e125044b7e.png)

**Comment by alexesprit** [comment]
I fixed this issue in #915.
