### ISSUE TITLE
vk.com scrobbling is not working

### ISSUE THREAD

**Issue by uberstein** [david-sabata/web-scrobbler#820]
![dd dd](https://cloud.githubusercontent.com/assets/15245313/10661422/92b6d534-78b6-11e5-9205-4d0f79201474.png)
![dd](https://cloud.githubusercontent.com/assets/15245313/10661423/92b7c6ba-78b6-11e5-89b6-f743f8788877.png)

vk.com scrobbling is not working but plugin icon up still showing "this site is supported for scrobbling" and this icon have old design from previous versions

**Comment by leeheecherry** [comment]
Same for me

**Comment by dreambrother** [comment]
+1

**Comment by kizhaeff** [comment]
Sorry,scrobbler not working ):

**Comment by mikdmgo** [comment]
Probably already fixed. Waiting for next release ;) See https://github.com/david-sabata/web-scrobbler/pull/809

**Comment by Loki29A** [comment]
Same

**Comment by IRainman** [comment]
+1 - not working :( v1.54 ... It ruined a good extension for a few weeks and try every time - nothing.

**Comment by Paszt** [comment]
As always when reporting software bugs, just saying "it's not working" doesn't give enough information to help. 

https://github.com/david-sabata/web-scrobbler/wiki/How-to-debug-the-extension

**Comment by IRainman** [comment]
Thank you! It helped to see in the console that gives life ws.audioscrobbler.com 403 error. Opening the attached link json remarks with an expired token authentication.I realized that only need to make reauthentication on last.fm.

I beg developers to add an explicit error message for this case for now it seems that the plugin does not recognize the track playing on the page, and the matter is in the connector to the service, not the authorization. Thank you again!
