### ISSUE TITLE
Extension not working with Google Play Music?

### ISSUE THREAD

**Issue by thexenographer** [david-sabata/web-scrobbler#822]
Using Chrome version 46.0.2490.80 on Windows 7. The icon appears, but the extension doesn't seem to recognize that I'm playing music. Tried reauthenticating and reinstalling, but to no avail. I've tried YouTube, Spotify, 8tracks, Bandcamp, and Amazon Cloud Player and they all work fine, it seems to be just Google Play Music that's the problem. Let me know if you need any more information.

**Comment by kleak1m** [comment]
It isn't working for me either. Chrome v. 46.0.2490.80 on Windows 8. The icon appears in red color and doesn't change to green as it usually does.
![chrome-extension](https://cloud.githubusercontent.com/assets/15271941/10707464/5e988b8c-79b8-11e5-9851-5a45dae97e65.png)

**Comment by LordCatzorz** [comment]
Same for me. 
Version 46.0.2490.80 m (64-bit) on Windows 8.1
To fix it, I have to reload the page.
Could it be some kind of race condition?

**Comment by githoober** [comment]
Same here.

**Comment by thexenographer** [comment]
Now the icon is turning green and recognizing the songs I play, but they still don't appear on my last.fm profile at all.
