### ISSUE TITLE
Extension not working with latest Plex version

### ISSUE THREAD

**Issue by romainbriand** [david-sabata/web-scrobbler#823]
Hi,

The extension is not working anymore with Plex. It seems this issue came with the last Plex update.

Technical information:
- Plex Media Server 0.9.12.13 (on Ubuntu Trusty)
- Chrome 46.0.2490.80

Let me know if you need further information.

Thanks!

**Comment by robinrossow** [comment]
Hey, 

I've had the same problem but managed to fix it by doing some debugging. Here is how to get it to scrobble again:

1. Download the latest version from github
2. **Reauthenticate with last.fm!**
3. Done!

I hope this will work for you as well.

**Comment by romainbriand** [comment]
Thank you so much @robinrossow! It works :)
