### ISSUE TITLE
Re-auth through browser notification (not bug, but feature)

### ISSUE THREAD

**Issue by alexandr-selezniov** [david-sabata/web-scrobbler#827]
I'm not sure if ut is a proper place to post my issue, but I looked through google store comments with all "nothing works" and decided to report.
#### **tl;dr:** re-authentication is done through notification, which I disabled the first day after installing extension (popups with song name are annoying). So I simply didn't see notification with new token request.

---

Some time ago scrobbling for vk.com got broken, but I came to finding a solution only yesterday.
- I pressed "re-auth" button several times and didn't see effect. I looked through all the settings on last.fm in search for some request. Console wrote 403 err code and "Invalid token" if I open a link from log.
- I reinstalled extension but it didn't fix anything.
- Then I installed another one and it opened auth link. I tried to replace api key and decided to refresh it.
- That's how I pressed "re-auth" with default notification settings and at last saw the one from your extension.
### **Now all works well, but i have a request.**

---

Could you implement separate disabling for song info notifications
or
different mechanism for re-authentication, that wouldn't use notifications?

**Comment by david-sabata** [comment]
Hi @alexandr-selezniov, there is already a checkbox "enable desktop notifications". Have you tried that?
It should disable all music related notifications, but you will still be able to use notification for authentication. Unfortunately when you disable notifications for the whole extension right in Chrome, we cannot bypass that (which is totally right).

Safe solution would probably be detecting that notifications are not available and opening the pop-up right away (we already have the detection in `background/notifications`)
