### ISSUE TITLE
Another Chrome music-related plugin

### ISSUE THREAD

**Issue by beshur** [david-sabata/web-scrobbler#828]
Hi.

Really a fan of this extension.
My friends and I are developing a Chrome extension that allows to control music playback in browser.
Really simple. Think it can be related https://github.com/StoPlay/stoplay-ext/

Maybe some tweet exchange?
Our audience is much smaller, but anyway.

**Comment by david-sabata** [comment]
Hi @beshur!

The playback control via extension is already one of our feature requests AFAIK. But it's not really a priority right now, so don't worry ;-))

Your extension looks interesting and I think our users could benefit from it, so I'm open to some retweeting and stuff. PM me at twitter.com/web_scrobbler and we'll see :)

**Comment by beshur** [comment]
Happy New Year!

I followed you from my personal and extension accounts, almost ready for exchange (except can't send you a DM).

**Comment by david-sabata** [comment]
DMs should work now :)

**Comment by inverse** [comment]
Personally I don't think playback controls should be part of the extension. But that's my 2c.

I use [StreamKeys][0] for that ;D

[0]: http://www.streamkeys.com/

**Comment by david-sabata** [comment]
Looks exactly like the extension from @beshur, only with more supported sites :stuck_out_tongue:
