### ISSUE TITLE
Custom blacklist

### ISSUE THREAD

**Issue by david-sabata** [david-sabata/web-scrobbler#83]
Make option to make a black list of words so much more songs will be identified.
I'm talking about abillity to let words like "-lyrics", "-live *" ("-" all the text before it is vissible for scrobbler, and "*" is opposite) , "-cover" be invissible for scrobbler.

(via L.FM private message by n3L1)

**Comment by janbaykara** [comment]
Can close; this is accomplished on a connector level. E.g. https://github.com/david-sabata/web-scrobbler/blob/cb11bddbf46476b2bda379bcbdcb30eb5e03da59/connectors/v2/youtube.js#L62-L84

**Comment by janbaykara** [comment]
@david-sabata Can close; this is accomplished on a connector level. E.g. https://github.com/david-sabata/web-scrobbler/blob/cb11bddbf46476b2bda379bcbdcb30eb5e03da59/connectors/v2/youtube.js#L62-L84
