### ISSUE TITLE
Plex support appears broken - never "activates" the extension

### ISSUE THREAD

**Issue by nicholashead** [david-sabata/web-scrobbler#839]
When using Plex, I'm on a URL beginning with `https://app.plex.tv/` - and I never see the scrobbler icon appear in my chrome URL bar, so I don't believe it's getting "activated".

I may try and look into the Github source and try and figure this out on my own. But just wanted to get an issue filed in case anyone else has run into it. Thanks!

**Comment by mdomi** [comment]
I can confirm the behavior as well - I'm seeing in error in the console logs in the Plex connector indicating the the jQuery reference it's looking for isn't available - I'll open a pull request to avoid assuming jQuery is present.

**Comment by nicholashead** [comment]
@mdomi my pull request seems to fix the issue; i'm not seeing a jQuery error in my console as far as I know?

**Comment by mdomi** [comment]
@nicholashead is #840 the one you're referring to? I added a wildcard in my settings and even though it activated, it never picked up any songs playing. The jQuery error may be something else, but I'll keep digging into my case.

**Comment by nicholashead** [comment]
@mdomi yep, #840 is the build i have running locally and it's working for me. any other chrome extensions you have installed that might be causing conflicts?

**Comment by mdomi** [comment]
@nicholashead that's definitely a possibility, although I'm not sure where I'd begin to look. Would it be a bad idea to rewrite the portions of the Plex connector that depend on jQuery such that they use native DOM access code? From the looks of the code, it should just be a couple of selections and event handlers.
