### ISSUE TITLE
error with the plugin and some sound

### ISSUE THREAD

**Issue by djconnexion** [david-sabata/web-scrobbler#842]
hello,
when i use your plugin and see wath tey do iin back ground i see this : 
GET https://ws.audioscrobbler.com/2.0/?method=auth.getsession&api_key=d9bb1870d…a6f5138ffb36adbcccd0a&api_sig=ff9743459b277a20025e20e9364799d9&format=json 403 (Forbidden)l.cors.a.crossDomain.send @ jquery-2.1.0.min.js:4o.extend.ajax @ jquery-2.1.0.min.js:4o.(anonymous function) @ jquery-2.1.0.min.js:4o.extend.getJSON @ jquery-2.1.0.min.js:4tradeTokenForSession @ lastfm.js:135(anonymous function) @ lastfm.js:91(anonymous function) @ chromeStorage.js:26target.(anonymous function) @ extensions::SafeBuiltins:19safeCallbackApply @ extensions::sendRequest:21handleResponse @ extensions::sendRequest:72
lastfm.js:145 auth.getSession failed: Forbidden, error

ithink this why some song are not scrobble.
i test this with soundcloud

**Comment by david-sabata** [comment]
You need to re-authenticate with Last.fm, do that either by clicking the button in the extension's options page or reinstall the extension completely
