### ISSUE TITLE
Scrobbler Not Getting Track Information

### ISSUE THREAD

**Issue by kmehlin** [david-sabata/web-scrobbler#843]
Seemed like it was working earlier today judging by my track list at last.fm, but now it just sits at the magnifying glass icon in the address bar with the pop up "Looking up" whatever the track name is. Tried it at both Slacker and Google Music.
![scrobbler](https://cloud.githubusercontent.com/assets/1565086/11406750/010bc1e4-937d-11e5-9bbd-f88963b5c448.png)

**Comment by PiotrDabr** [comment]
I have the same problem. Tried on Bandcamp and Youtube.

**Comment by dpzmick** [comment]
Same problem here as well. What the method for getting any sort of logs to assist in debugging?

**Comment by Paszt** [comment]
[How to debug the extension](https://github.com/david-sabata/web-scrobbler/wiki/How-to-debug-the-extension)

**Comment by Pimorez** [comment]
403 forbidden errors in my logs.
The URL it points to shows me the following: 
{"error":4,"message":"Invalid authentication token supplied"}

In short, songs are being recognized but they cannot be scrobbled (Soundcloud).

At the same time the console throws me the same error for Youtube except that the scrobbling does work.

**Comment by Paszt** [comment]
Try the Re-authenticate with Last.fm button in the extension's options.

**Comment by Pimorez** [comment]
Thanks, fixed it. The scrobbler has been working pretty bad for a while now. I've tried re-authenticating before but I guess it hasn't been working for me. The re-authentication button did not bring me to the Last.FM page before, it did now :) (That's the reason I hadn't tried it today)
