### ISSUE TITLE
Zvooq.com scrobbling out of service

### ISSUE THREAD

**Issue by staleo** [david-sabata/web-scrobbler#844]
That seems Zvooq.com tracks are not being scrobbled. Not sure if it ever worked, but for now, it's definitely not working.

The icon in the address bar seems like it's just nothing to scrobble.

![2015-12-05 19-02-24](https://cloud.githubusercontent.com/assets/1087531/11608732/ca986000-9b82-11e5-99ea-a8d133917754.png)

**Comment by alexesprit** [comment]
Web scrobbler doesn't scrobble tracks from zvooq.com, but it does from zvooq.ru.
If you want to scrobble zvooq.com tracks you should manually add URL pattern to zvooq.com in extension settings.

**Comment by staleo** [comment]
alexesprit, Jesus Christ, thanks A LOT for a tip!
