### ISSUE TITLE
Extension's mini-icon remove option

### ISSUE THREAD

**Issue by SaintGerasim** [david-sabata/web-scrobbler#849]
<p>Can you make option to remove extensions mini-icon in address bar please? <br>It really annoys me.</p>

**Comment by ex47** [comment]
I think it is no longer the case, is it? The only icon can be hidden inside "hamburger" now.
![screenshot_10](https://cloud.githubusercontent.com/assets/2480069/17521391/d5eec498-5e5b-11e6-98ac-da78cfe5eee3.png)
