### ISSUE TITLE
Re-auth with Last.fm not working

### ISSUE THREAD

**Issue by rlevarski** [david-sabata/web-scrobbler#850]
tl;dr It suddenly stopped getting track names (searches for <Artist> - null; I have to add everything manually). I tried to re-auth and it won't open the dialog to do so.

(I'm using Google Music Play.)

**Comment by inverse** [comment]
Anyone use google music to verify? Potentially related to #843?

**Comment by rlevarski** [comment]
Okay so, I tried reinstalling the extension for the last time and also cleared some of the Chromes browsing data, cleared Java stuffs (because why not). Re-authenticated (this works, yay!) and it seemingly worked... for one song. At least, it detects the track name, but doesn't scrobble.

So ya, close, but no cigar.
