### ISSUE TITLE
Track title no longer detected in Google Play Music

### ISSUE THREAD

**Issue by TRManderson** [david-sabata/web-scrobbler#852]
The scrobbler is correctly detecting the artist of tracks in Google Play Music, but the songs titles themselves are being detected as "null" currently. This happens in multiple different scrobblers so it's likely a change on Google Music's end screwing you over.

**Comment by sierratango88** [comment]
Confirming the issue as well.

Console:
Tab 546: song finished processing  {"parsed":{"artist":"Steve Jablonsky","track":null,"album":"Transformers: Age of Extinction (Music from the Motion Picture)","uniqueID":null,"duration":null,"currentTime":56,"isPlaying":true,"trackArt":false,"url"...

**Comment by MathieuLLF** [comment]
It's happening for me as well.

**Comment by TRManderson** [comment]
Both #848 and #851 fix this issue. I'm currently using #851 locally to fix the issue, working solidly.

**Comment by jag426** [comment]
Same here.

**Comment by sierratango88** [comment]
Thanks TRManderson, that did the trick.

Anyone who wants to know where to make the change can find the specific file here:
...\AppData\Local\Google\Chrome\User Data\Default\Extensions\hhinaapppaileiechjoiifaancjggfjm\1.54_0\connectors\v2\googlemusic.js

**Comment by dtw85** [comment]
Hi. Im having the same issue. Im looking at the solution posted by TRManderson above but honestly have no idea what Im looking at. Could somebody possibly explain what to do here? I would appreciate it

**Comment by inverse** [comment]
You need to download and load an unpacked version for now (see readme). Until David merges #848 and creates a new release.

**Comment by Kail0** [comment]
**TRManderson**
Thanks, that worked for me, as well.

**Comment by w4** [comment]
cd ~/Library/Application\ Support/Google/Chrome/Default/Extensions/hhinaapppaileiechjoiifaancjggfjm/1.54_0
    wget https://patch-diff.githubusercontent.com/raw/david-sabata/web-scrobbler/pull/848.patch
    patch < 848.patch
