### ISSUE TITLE
New source: classicalradio.com

### ISSUE THREAD

**Issue by Ky6uk** [david-sabata/web-scrobbler#857]
New music service by radiotunes.

**Comment by 102** [comment]
I can't find anything about proper classical music:
* should composer name be interpreted as artist?
* in this case, should we just drop performers, conductors, etc info?

**Comment by 102** [comment]
I've started to implement this 102/web-scrobbler@876707f0675520d571f4963d1c256fbd4bc05b75

**Comment by Ky6uk** [comment]
It's just should be available for detecting by last.fm I think.

**Comment by Paszt** [comment]
@Ky6uk: last.fm uses musicbrainz as one of their data sources, that's why 102 posted the link to the musicbrainz styleguide. But classicalmusic.com doesn't follow the same naming that is outlined in the style guide, so it's going to be hit or miss whether the song is recognized by last.fm.

**Comment by Ky6uk** [comment]
Hmm yep, you're right. I tried to find some random tracks. It's looks impossible to describing on last.fm.  But tracks have composer name, performer name and songname.

**Comment by 102** [comment]
@Ky6uk @Paszt 
may be we can just create something like {'shortname': 'fullname'} object?
e.g.
```
  {
    'F.J. Haydn': 'Franz Joseph Haydn',
    'W.A. Mozart': 'Wolfgang Amadeus Mozart',
    ..
  }
``` 
Later we'll just take full composer name from this object?

**Comment by alexesprit** [comment]
ClassicalRadio support was implemented in https://github.com/david-sabata/web-scrobbler/commit/9dd193886310a4f5099917a6f1cbd0a67c693832, but that implementation doesn't filter the artist field.
