### ISSUE TITLE
Don't working on Yandex.Radio

### ISSUE THREAD

**Issue by anton0kurilov** [david-sabata/web-scrobbler#859]
On Yandex.Radio not scrobble tracks, but there is an icon in the status bar.

**Comment by inverse** [comment]
unable to verify as not in Russia (geo-locked it seems)

**Comment by alexesprit** [comment]
Tried to test scrobbling on Yandex.Radio. It works but a bit buggy.
It works (for me) if you open radio station directly, e.g. [this one](https://radio.yandex.ru/genre/rock).
When you select radio station on [this page](https://radio.yandex.ru/) scrobbling doesn't work until you refresh the station page.

**Comment by anton0kurilov** [comment]
Yes, now works, thank you.
