### ISSUE TITLE
Cannot connect on OSX

### ISSUE THREAD

**Issue by lamons** [david-sabata/web-scrobbler#860]
Nothing happens when click the re-authenticat button or the 'please connect' notification. (El Capitan 10.11.2, Chrome 47.0.2526.106 (64-bit))

**Comment by inverse** [comment]
No new tab in Chrome directing to last.fm?

**Comment by lamons** [comment]
It just definitely nothing happened.
```
chrome.storage.local = {"Core":{"appVersion":"1.54"},"LastFM":{"sessionID":null,"token":"xxxxx4fb0d2000769a5b23a4153c31e9"}}
https://ws.audioscrobbler.com/2.0/?method=auth.getsession&api_key=d9bb1870d…000769a5b23a4153c31e9&api_sig=237604a6cfa6595704a43993b5d7ffdf&format=json Failed to load resource: the server responded with a status of 403 (Forbidden)
lastfm.js:145 auth.getSession failed: Forbidden, error(anonymous function) @ lastfm.js:145
```
These are what in the log page. Seems like network problem, but other computers have no problem using the extension using same WIFI.

**Comment by inverse** [comment]
Strange. Looks like it's an issue with the token that the extension has. Could you try removing the extension and installing again. Perhaps we need to be smarter about such situations and clear the cached token in such instances.

**Comment by lamons** [comment]
I have reinstalled the extension, same thing happened and the log changed to
```
chrome.storage.local = {"Core":{"appVersion":"1.54"},"LastFM":{"sessionID":null,"token":null}}
lastfm.js:52 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.
lastfm.js:56 getToken response: <?xml version="1.0" encoding="utf-8"?>
<lfm status="ok">
  <token>50ff262c23b9852bd595c0279c6e23eb</token>
</lfm>
```

**Comment by inverse** [comment]
Interesting - that looks more valid. The deprecated message is more of a warning which I don't think is much of an issue due to the way we use it.

What does the log look like when you visit a valid site and try playing a track?

**Comment by lamons** [comment]
I tried xiami.com, the log file became much longer so I attached it below. There was a 'looking up' symbol appears on the address bar, but nothing happens when I clicked on it.

[hhinaapppaileiechjoiifaancjggfjm-1450977881665.log.txt](https://github.com/david-sabata/web-scrobbler/files/71852/hhinaapppaileiechjoiifaancjggfjm-1450977881665.log.txt)

**Comment by sigorilla** [comment]
I have the same [issue](https://github.com/david-sabata/web-scrobbler/issues/860#issuecomment-166606709).

**Comment by twof** [comment]
I'm also experiencing this issue and have been for a while. I'll grab logs if they're needed. I'm on the latest Chrome version and I reinstalled the extension.

**Comment by alexesprit** [comment]
Chrome doesn't show notifications when it in fullscreen mode. You should quit this mode, then reauthenticate using the button on the extension options page.

It's possibly to do not show notification and to force open tab directly on MacOS; is it right solution of the problem?

**Comment by alexesprit** [comment]
Closed as outdated.
