### ISSUE TITLE
Google Play Music: Cant' get track name

### ISSUE THREAD

**Issue by idrumgood** [david-sabata/web-scrobbler#861]
The jQuery selector seems correct, but all my tracks are returning as null. Looking in the debug console:

`Tab 40: new song detected: {"parsed":{"artist":"The Bronx","track":null,"album":"The Bronx (IV)","uniqueID":null,"duration":null,"currentTime":1,"isPlaying":false,"trackArt":false,"url": [...]`

**Comment by kmehlin** [comment]
Same here, for the past couple of days. Slacker seems to work so I'm assuming something went funny on the Google end.

**Comment by idrumgood** [comment]
Ah, you know what it is, Google Music isn't using the updated connector js. When I check which googlemusic.js gets injected into the page, it doesn't have the new function to get the track.

**Comment by kmehlin** [comment]
@idrumgood: Any chance you can walk me through how to do that???? I'm just a graphics guy...code scares me!

**Comment by idrumgood** [comment]
Not sure exactly how you have to submit extension updates to the chrome store, but I'm guessing this is because the updates to the Google Play Music connector were made but there was not an update to the manifest.json version number so the update isn't picked up.

You can get around this by manually editting the googlemusic.js folder located here:

`~/Library/Application Support/Google/Chrome/Default/Extensions/hhinaapppaileiechjoiifaancjggfjm/1.54_0/connectors/v2`

Your extension name may be different, you just have to try all the ridiculously named files until you find the scrobbler one. Just drop in [this file](https://raw.githubusercontent.com/david-sabata/web-scrobbler/master/connectors/v2/googlemusic.js) and replace the existing one. That will get you the updates.

**Comment by kmehlin** [comment]
@idrumgood: You are a genius. Thank you!

**Comment by TylerJane** [comment]
I'm still having this issue with google music. Track is "null" and I cannot edit. Tried reinstalling plugin, tried modifying the connector via idrumgood's advice above, tried removing other extensions that might interfere, etc. Still "null" and doesn't let me edit. I don't know what else to try.

**Comment by idrumgood** [comment]
After you modified the connector, did you reload google music? Really it's a hack and we just need the extension to be updated in the chrome store.

**Comment by TylerJane** [comment]
I restarted chrome altogether; that should've done the trick, yes? Is there some straightforward way for me to see whether or not the connector is actually being used? (and thanks for the reply)

**Comment by idrumgood** [comment]
If you're familiar with web inspector, you can right click anywhere on the
google music page and select 'Inspect Element'. From there, click the
'Sources' tab at the top to view all the javascript loaded into the page.
Use cmd+P to bring up a file search dialog, and type in 'googlemusic', this
will let you view the connector googlemusic.js file that is being loaded.
You can check to see if it has the updates for the getTrack() function, or
if it's still using the old one. If it's using the old one, then you didn't
successfully replace that connector file in your extensions folder.

**Comment by TylerJane** [comment]
Thanks! It's still using the old one. The connector I modified is in ~/1.45_0/connectors/v2, but that seems to be an old version number. I can't seem to find the 1.54 folder, but it's got to be somewhere. I'll see if I can figure it out from here, thanks for the help!
