### ISSUE TITLE
YouTube scrobbler doesn't work on fullscreen playlist

### ISSUE THREAD

**Issue by ali-essam** [david-sabata/web-scrobbler#865]
- Open a YouTube mix playlist for example
- Play first song and maximize to fullscreen
  The scrobbler only scrobbles the first song and doesn't detect/scrobble other songs unless the window is minimized again.

Chrome v47.0.2526.106 m

**Comment by muratoflu** [comment]
Does not work on https://www.youtube.com/watch?v=N2V9v7tvyKg as an example, and asks me to enter song details upon clicking address bar icon. Thanks.

**Comment by ali-essam** [comment]
@muratoflu I think this is unrelated to this issue. I guess this is because the scrobbler is unable to confirm artist/song name from YouTube video title "*New Electro & House 2015 Best of Party Mashup, Bootleg, Remix Dance Mix*"

**Comment by alexesprit** [comment]
@ali-essam now the extension should scrobble fine in fullscreen mode.
