### ISSUE TITLE
dubtrack.fm no longer works at all

### ISSUE THREAD

**Issue by wilsonbiggs** [david-sabata/web-scrobbler#866]
basically what the title says. nothing scrobbles from dubtrack.fm.

**Comment by inverse** [comment]
Looks like it's working through testing here. https://www.dubtrack.fm/join/nightblue3

**Comment by david-sabata** [comment]
Seems to be working for me too

**Comment by alexesprit** [comment]
I have the same issue.
It works randomly; sometimes scrobbling works, sometimes does not.
Looking into dev console helps me to find reason why it's broken:
```
Web Scrobbler: Setting up observer
Web Scrobbler: Player element (.infoContainer) was not found in the page.
```
Changing `Connector.playerSelector` to `#player-controller` possibly solves the issue.

**Comment by qaisjp** [comment]
Doesn't work for me. I'm using DubX though, does this matter?

**Comment by Botanistt** [comment]
same
