### ISSUE TITLE
[Noon Pacific] scrobbler doesn't work

### ISSUE THREAD

**Issue by ennuiso** [david-sabata/web-scrobbler#867]
Hello, guys!

Please check this issue and fix if it's possible.

Thanks.

p.s. [Noon Pacific](http://noonpacific.com/).

**Comment by alexesprit** [comment]
Yep, seems like it's broken due to code changes in Noon Pacific. I tried to fix it in #869.

**Comment by ennuiso** [comment]
Yes, perfect!

Супер, спасибо большое.
