### ISSUE TITLE
Can't authenticate extension with last.fm in Opera on Windows 10

### ISSUE THREAD

**Issue by andis-sprinkis** [david-sabata/web-scrobbler#870]
Clicking "Re-authenticate with last.fm" opens system notification, but clicking on the notification leads to nothing. Also, I can't find any signs of the extension as a connected app in last.fm settings.

Opera 34.0.2036.41 Stable on Windows 10 Pro. Things used to work fine on the Windows 7 installation I manually upgraded from the same day.

**Comment by inverse** [comment]
Unless you have experience or want to learn about the Opera extension API it probably doesn't work. Unfortunately the extension hasn't been tested/maintained on Opera for quite some time.

**Comment by andis-sprinkis** [comment]
That's sad. It has worked on Opera fine all this time even untested.
Noticed that another scrobbling extension (unfortunately one I don't like so much) from Chrome store authenticates with last.fm fine on my setup. Difference that it doesn't ask to click on a notification message to do so but does it through through link in extension icon's pop-over.

**Comment by inverse** [comment]
See #503 for more info

I'm not sure how much has changed since then. Perhaps they have caught up with the chrome API, however some might be broken. Perhaps one day we might want to think about making vendor specific extensions. [WebExtensions][0] could make this a bit easier in the long run.

[0]: https://developer.mozilla.org/en-US/Add-ons/WebExtensions

**Comment by david-sabata** [comment]
Everything important is indeed stated in #503. I know Opera keeps improving their extension APIs, but it's just too difficult for us to maintain the compatibility. Therefore Opera is not supported, but I'm definitely not against compatibility contributions (as long as they don't limit Chrome features) or even  some kind of Opera forks of the extension.
