### ISSUE TITLE
LAST.FM Scrobbler no longer working with Google Music

### ISSUE THREAD

**Issue by dbibby88** [david-sabata/web-scrobbler#876]
The last fm scrobbler is no longer working whilst using Chrome and Google Play Music. It was scrobbling fine before Christmas, but now no songs scrobble to my profile. I have listened to two albums today and only one song has scrobbled. I have tried playing the same song again and it didn't scrobble a second time. 

I have tried disabling and enabling the plug in. I have also tried completely deleting the plugin and installing it again. When playing any songs a spy glass (magnifying glass?) appears in the chrome address bar, this has only happened since I deleted the plugin and reinstalled it. 
Before I did this, a green tick was appearing in the address bar, but the songs still werent scrobbling.

**Comment by inverse** [comment]
Are you able to provide us with an error log? There are instructions on how to do it on the wiki.

**Comment by dbibby88** [comment]
![screen shot 2016-01-05 at 16 24 49](https://cloud.githubusercontent.com/assets/16561462/12120388/a5fd15b6-b3c8-11e5-8cef-143a6fd81704.png)

**Comment by dbibby88** [comment]
is this right?

**Comment by gordonbondon** [comment]
I can confirm having the same issue on Chrome 47.0.2526.106 64bit/Windows 10 64 bit. I've got the same error as @dbibby88 when playing first track on Google Play page and error from attached screenshot when track is changed.
![image](https://cloud.githubusercontent.com/assets/9439689/12121639/efbedea8-b3de-11e5-928b-e78e7bd6fa65.png)

**Comment by dbibby88** [comment]
do you think its due to the lastfm website being in a new beta?

**Comment by Paszt** [comment]
Last.fm has been in beta for many months.  You both need to Re-authenticate with Last.fm using the button found in the extension's options.

**Comment by dbibby88** [comment]
Still isn't working. They have changed some of the website recently because the scrobble page is terrible now. Ive been listening to music all day and this is all I have. 

![screen shot 2016-01-05 at 17 54 28](https://cloud.githubusercontent.com/assets/16561462/12122810/4267d9f2-b3d5-11e5-98d3-0e0028e79c3a.png)

**Comment by alexesprit** [comment]
> When playing any songs a spy glass (magnifying glass?) appears in the chrome address bar

It often means that you need to reauthenticate with Last.fm by using the button in Web scrobbler settings. And error log you provided proves this fact.

Unfortunately, Web scrobbler doesn't notify user about "broken" authentication (403 errors while scrobbling, the magnifier icon etc).

It's also quite easy to check if you need to do reauthentication. Just try scrobble music from another services, e.g. YouTube. If symptoms will be the same (like mentioned above 403 error), it's authentication problem. If not, so, the extension is really broken.

P.S. I have tested scrobbling on Google Play Music before sending this post. It works fine for me.

**Comment by dbibby88** [comment]
It looks like its starting to work again? It's missed a few songs but a few have gone. I'll try the reauthenticate thing again tomorrow. Thanks for all the help.

![screen shot 2016-01-05 at 21 15 32](https://cloud.githubusercontent.com/assets/16561462/12127830/61092714-b3f1-11e5-8a23-4c623ebc3f84.png)

**Comment by kokoon** [comment]
> It often means that you need to reauthenticate with Last.fm by using the button in Web scrobbler settings. And error log you provided proves this fact.
This. I kinda gave up on the extension working for Google Play Music, but re-authenticating just fixed it for me. Thanks!
