### ISSUE TITLE
Not scrobbling on Tradiio 

### ISSUE THREAD

**Issue by frekoutfil** [david-sabata/web-scrobbler#877]
I have not seen my tracks on last.fm for tradiio.com. I know they mentioned that they just updated the website to be more user-friendly. I wonder if that is what changed that is making it not work. I thought it did before. 

Please review.

Thanks,

**Comment by alexesprit** [comment]
@frekoutfil Tradiio scrobbling was fixed in latest release. Did you check it?

**Comment by frekoutfil** [comment]
Thank you. Yes, it is working.

Phil

On Thu, Jan 14, 2016 at 7:17 AM, Alexey <notifications@github.com> wrote:

> @frekoutfil <https://github.com/frekoutfil> Tradiio scrobbling was fixed
> in latest release. Did you check it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/david-sabata/web-scrobbler/issues/877#issuecomment-171655007>
> .
>



-- 
Phil Scoville, M.S.
Licensed Marriage and Family Therapist
AAMFT Clinical Fellow and Utah Clinical Supervisor
Clinical Director and Owner - Center for Couples and Families

o: 801-709-1785
e: philscoville@gmail.com

*Locations*
   *American Fork*     americanforkfamilies.com
*   Provo                     *provofamilies.com
<http://provofamilies.com/>
*   Spanish Fork*        spanishforkfamilies.com
<http://paysonfamilies.com/>

___________________

                                     utvalleywellness.com
____________________
CONFIDENTIALITY NOTICE:  Electronic Mail is not secure, may not be read
daily, and should not be used for urgent or sensitive issues.  The
information in this message and any attached files might contain
confidential information protected by federal and state law and may be
legally privileged.  The information is intended solely for the
individual(s) or entities originally named as addressees; access to this
message by anyone else is unauthorized.  Any disclosure, copying, or
distribution of information, or any action or omission taken by
unauthorized individuals or entities in reliance on it, is prohibited and
may be unlawful and subject to civil or criminal penalties.  If this
message reached you in error, please destroy this message and any attached
files.
