### ISSUE TITLE
Not scrobbling on SomaFM

### ISSUE THREAD

**Issue by alexandru-pinzaru** [david-sabata/web-scrobbler#879]
Wen I play any station I get the message:
"Play some music to get started
Is it already playing?"
and the lastFM red icon, not the "?" gray one.

Pls help, thanks a bunch!

**Comment by inverse** [comment]
Hmm #874  might fix this for you. Are you able to run unpacked extensions? It worked for me. Would be good to have someone else verify this.

**Comment by alexesprit** [comment]
@inverse it works fine with your fix.

**Comment by alexandru-pinzaru** [comment]
I never tried unpacked, only from the Web store. Thanks for helping me, I  will try the unpacked

**Comment by alexandru-pinzaru** [comment]
@inverse it worked, thx allot!

**Comment by david-sabata** [comment]
Fixed by #874
