### ISSUE TITLE
[Noon Pacific] Can't scrobble from NP Collections

### ISSUE THREAD

**Issue by ennuiso** [david-sabata/web-scrobbler#882]
Hey there!

NP connector doesn't work for "Collections". Please check and fix if it's possible.

Thank you. 

P.S. [NP ► Collections](http://noonpacific.com/collections/).

**Comment by ennuiso** [comment]
@inverse, your fix is good, but not for all collections (only for first four in [the list](http://noonpacific.com/collections/)). Obviously, other collections had developed in other way.

**Comment by inverse** [comment]
Ahh didn't see that! I don't use the site :whale:  I'll see what I can do to update

**Comment by ennuiso** [comment]
@inverse, yeap, here: [1](http://noonpacific.com/wishyouwerehere/), [2](http://noonpacific.com/coachella/), [3](http://noonpacific.com/spacejams/) and [4](http://noonpacific.com/midnight/). Thank you for your enthusiasm.

**Comment by inverse** [comment]
Yeah - looks like we will have to handle the various ways in which the artist - track are encoded too. Someone else can pick up the branch if they want to continue fixing it.

**Comment by inverse** [comment]
Will be in the next release thanks to @alexesprit :)
