### ISSUE TITLE
Spotify web player is not scrobbing

### ISSUE THREAD

**Issue by DJAlik** [david-sabata/web-scrobbler#889]
https://play.spotify.com

**Comment by Paszt** [comment]
It's working for me.  

To get more information about likely problems: [How to debug the extension](https://github.com/david-sabata/web-scrobbler/wiki/How-to-debug-the-extension)

**Comment by goldswimmerb** [comment]
It very rarely scobbles for me.

**Comment by hector** [comment]
+1 Does not work for me either

**Comment by tropicoo** [comment]
+1, this need to be fixed

**Comment by alexesprit** [comment]
I listen to music with Sprotify and scrobbling works well (and right now too). Maybe you have authentication problems? And it will be good if you provide Web scrobbler logs.

**Comment by hector** [comment]
I don't know if there have been any changes on the extension, but today it is working fine for me.
I would also like to point out that if you go to the Spotify Web preferences there is the option to scrobble to Last.fm. Actually, I have this preference activated together with the web-scrobbler enabled and songs get correctly scrobbled only once.

**Comment by david-sabata** [comment]
There's been no changes for quite a while. Spotify is scrobbling fine for me using just the extension, not the built-in scrobbling

**Comment by ama4tf** [comment]
I'm seeing scrobbling issues too. Let me know how to provide logs and I can do so. It recognizes it can scrobble on the site, however despite music is playing, no scrobbling

**Comment by Paszt** [comment]
@ama4tf, that information has already been posted in this very thread.

**Comment by ex47** [comment]
It works fine for me.
![screenshot_7](https://cloud.githubusercontent.com/assets/2480069/17180569/99174760-5425-11e6-83f6-6ec64812968b.png)

**Comment by alexesprit** [comment]
I'm closing this issue because looks like new Spotify player is default for most users; the issue is not related to current web player.
