### ISSUE TITLE
Amazon scrobbling seems to work, but no scrobbles are listed by LastFM

### ISSUE THREAD

**Issue by MartinL0815** [david-sabata/web-scrobbler#890]
I use Last FM Scrobbler with the lastest Google Chrome and Amazon.de.

The icons of the extension tell me, that scrobbling should work, but non of my played and seemingly successfully scrobbled tracks is listed in my LastFM library.

What's broken this time (at LastFM)?

Best regards,

Martin

**Comment by MartinL0815** [comment]
BTW "loving" a track does not seem to work, too!

**Comment by Paszt** [comment]
It's quote possibly a problem with Last.fm authentication.  You can try to re-authenticate using the “Re-authenticate with Last.fm” button in the extension options.  If that doesn't work, you can find the steps to check the logs here: [How to debug the extension](https://github.com/david-sabata/web-scrobbler/wiki/How-to-debug-the-extension)

**Comment by MartinL0815** [comment]
Thanks for your suggestion to re-authorize!
Scrobbler is back to work again!

Does scrobbler not show API errors, especially those related to authorization or is the Last.FM API screwed? (I suspect Last.FM).

Cheers,

Martin

**Comment by Paszt** [comment]
As you've noticed, the extension doesn't currently detect or display errors.  That is something that should be looked into though.

Glad you got it working.
