### ISSUE TITLE
Can’t scrobble certain songs？

### ISSUE THREAD

**Issue by EdwardRech** [david-sabata/web-scrobbler#891]
While trying to scrobble a certain song [https://www.youtube.com/watch?v=2I25AFSBm2g], for which I had to input data, I got an error.

This one, to be specific: http://i.imgur.com/Zmx59h4.png

How to reproduce the bug: go to the song

Input the data:

Artist: サカナクション
Track: 夜の踊り子

**Comment by alexesprit** [comment]
The possible solution is to disable the `Scrobble only Music category` option in extension preferences. This video is not in Music category and won't be scrobbled if that option is enabled.

**Comment by david-sabata** [comment]
@EdwardRech can you confirm that you do *not* have `Scrobble only Music category` enabled?

**Comment by EdwardRech** [comment]
Forgot to mention - the solution worked.
