### ISSUE TITLE
Scrobble not Scrobbling

### ISSUE THREAD

**Issue by Tsvet** [david-sabata/web-scrobbler#893]
Just noticed that my Scrobbler is not Scrobbling at all.
Tested with Pandora and Youtube.
Removed and Reinstalled, same issue.
Removed, cleared Chrome cached, killed Chrome, reinstalled Scrobbler, logged at Last.Fm, tried to Scrobble: Still same issue.

`Tab 314: state update: only currentTime has changed
controller.js:48 Tab 314: received empty state - resetting
inject.js:79 -- loaded for the first time, injecting the scripts
inject.js:107   injecting vendor/jquery-2.1.0.min.js
inject.js:107   injecting vendor/underscore-min.js
inject.js:107   injecting core/content/reactor.js
inject.js:107   injecting core/content/connector.js
inject.js:107   injecting connectors/v2/youtube.js
inject.js:107   injecting core/content/starter.js
controller.js:324 Tab 314: created controller for connector: {"label":"YouTube","matches":["*://www.youtube.com/*"],"js":["connectors/v2/youtube.js"],"version":2}
controller.js:92 Tab 314: new track state: {"track":"Toxic","artist":"Alex & Sierra","album":null,"uniqueID":"w9JDrf1QBO4","duration":411,"currentTime":1,"isPlaying":true,"url":{"hash":"","search":"?v=w9JDrf1QBO4","pathname":"/watch","port":"","hostname":"www.youtube.com","host":"www.youtube.com","protocol":"https:","origin":"https://www.youtube.com","href":"https://www.youtube.com/watch?v=w9JDrf1QBO4","ancestorOrigins":{}},"trackArt":null}
controller.js:100 Tab 314: new song detected: {"parsed":{"artist":"Alex & Sierra","track":"Toxic","album":null,"uniqueID":"w9JDrf1QBO4","duration":411,"currentTime":1,"isPlaying":true,"trackArt":false,"url":{"hash":"","search":"?v=w9JDrf1QBO4","pathname":"/watch","port":"","hostname":"www.youtube.com","host":"www.youtube.com","protocol":"https:","origin":"https://www.youtube.com","href":"https://www.youtube.com/watch?v=w9JDrf1QBO4","ancestorOrigins":{}}},"processed":{"artist":"Alex & Sierra","track":"Toxic","album":null,"duration":411},"metadata":{"userloved":false,"startTimestamp":1454613168,"url":{"hash":"","search":"?v=w9JDrf1QBO4","pathname":"/watch","port":"","hostname":"www.youtube.com","host":"www.youtube.com","protocol":"https:","origin":"https://www.youtube.com","href":"https://www.youtube.com/watch?v=w9JDrf1QBO4","ancestorOrigins":{}},"connector":{"label":"YouTube","matches":["*://www.youtube.com/*"],"js":["connectors/v2/youtube.js"],"version":2}},"flags":{"isProcessed":false,"isScrobbled":false,"isCorrectedByUser":false,"isLastfmValid":null,"isMarkedAsPlaying":false}}
jquery-2.1.0.min.js:4 GET https://ws.audioscrobbler.com/2.0/?method=auth.getsession&api_key=d9bb1870d…775be95346dad0d31c808&api_sig=39a5852a424de05c9472646b20e946d6&format=json 403 (Forbidden)l.cors.a.crossDomain.send @ jquery-2.1.0.min.js:4o.extend.ajax @ jquery-2.1.0.min.js:4o.(anonymous function) @ jquery-2.1.0.min.js:4o.extend.getJSON @ jquery-2.1.0.min.js:4tradeTokenForSession @ lastfm.js:135(anonymous function) @ lastfm.js:91(anonymous function) @ chromeStorage.js:26target.(anonymous function) @ extensions::SafeBuiltins:19safeCallbackApply @ extensions::sendRequest:21handleResponse @ extensions::sendRequest:72
lastfm.js:145 auth.getSession failed: Forbidden, error`

**Comment by EdwardRech** [comment]
This is interesting since the extension itself works for me usually. What video you getting this on?

**Comment by Tsvet** [comment]
Every single video @ youtube and song @ Pandora.

The one used to create the log above was:
https://www.youtube.com/watch?v=w9JDrf1QBO4

**Comment by Tsvet** [comment]
Tried both on Linux [Fedora 23] and Windows 10.

**Comment by Paszt** [comment]
Your log is truncated, there's not enough info to figure out the problem.  More info such as the state of the icons would help also.

**Comment by llisama** [comment]
any luck here? same issue. my last fm wasn't even scrobbling through spotify though (even though it was all connected the same) so I wasn't sure what the issue with. logged out, reinstalled spotify, last. fm and last.fm scobbler.

it seems to now be scrobbling from spotify, although days are missing...
youtube/soundcloud etc... doesn't seem to be working at all. 

i also can't ceem to 'reauthenticate' on the extensions 'options' section. nothing happens when i click on it. 

any suggestions?

**Comment by alexesprit** [comment]
Can you provide extension logs?

**Comment by dfacoet** [comment]
Same issue here on CentOS (Youtube, Google Play, Soundcloud, di.fm)
> More info such as the state of the icons would help also
The icon changes to green and I get the notification, but it does not actually scrobble.

**Comment by spudart** [comment]
Not scrobbling Soundcloud.

**Comment by Paszt** [comment]
Why do people keep posting useless comments?  As stated above several times, logs are needed to help fix your issues.

**Comment by alexesprit** [comment]
Closes as outdated.
