### ISSUE TITLE
Scrobble not scrobbling on Google Play Music - Chrome

### ISSUE THREAD

**Issue by albajene** [david-sabata/web-scrobbler#896]
Hi,

Google Play Music recently changed its look and seems like it does not support scrobbling now with this extension. Running on Win 10, Chrome 48.0.2564.109 m.

Any settings I can tune to make it work or needs to be checked internally?

Thanks!

**Comment by alexesprit** [comment]
Hi!

I've tried to test scrobbling from Google Play Music, it works fine.

First of all, we need console logs. See [here](https://github.com/david-sabata/web-scrobbler/wiki/How-to-debug-the-extension) for details.

It's possible you have authorization problem (a lot of `403 Forbidden` errors in your logs). In this case it's enough to do reauthentication using the button in extension preferences.

**Comment by cookies4breakfast** [comment]
I'm having the same problem, running Win 7, Chrome version: 48.0.2564.116

**Comment by hnprashanth** [comment]
I had the same issue, went through console as suggested by @alexesprit and I did see 403 errors as expected. Re-authenticating Las.fm fixed the issue.

**Comment by tellarin** [comment]
I'm getting:

Unchecked runtime.lastError while running tabs.executeScript: Cannot access contents of the page. Extension manifest must request permission to access the respective host.
    at injectWorker (chrome-extension://hhinaapppaileiechjoiifaancjggfjm/core/background/inject.js:108:19)
    at chrome-extension://hhinaapppaileiechjoiifaancjggfjm/core/background/inject.js:116:5reportIfUnchecked @ extensions::lastError:133handleResponse @ extensions::sendRequest:78
inject.js:107 	injecting core/content/reactor.js

I'm on win10, Chrome 48.0.2564.116 m.

**Comment by tellarin** [comment]
And the re-authenticate button doesn't seem to do anything anymore. How can I manually re-authenticate? The new last.fm website is so crappy there isn't an option I can find to list my authorized apps/extensions. :-/

**Comment by retroelectric** [comment]
![image](https://cloud.githubusercontent.com/assets/16373241/13835182/66322746-ec30-11e5-935e-911cb4746f07.png)

I think my last.fm account is logged in but t his appears to show it not recognizing that a song is being played.

**Comment by vitriolix** [comment]
I had this issue and reauthenticating fixed it for me

**Comment by tellarin** [comment]
Now a song being played is recognized, but the actual scrobble never happens.

**Comment by alexesprit** [comment]
@tellarin have you tried to reauthenticate with Last.fm?

**Comment by emiliewebb** [comment]
Hi,
I'm experiencing the same problem. It works on my Google account at work which use the same version of Windows 10.
I don't undersatnd.
That's what console says in red background color
Unchecked runtime.lastError while running pageAction.hide: No tab with id: 78.
    at injectCb (chrome-extension://hhinaapppaileiechjoiifaancjggfjm/core/background/main.js:54:23)
    at onPatternsReady (chrome-extension://hhinaapppaileiechjoiifaancjggfjm/core/background/inject.js:168:5)
    at null.callback (chrome-extension://hhinaapppaileiechjoiifaancjggfjm/core/background/chromeStorage.js:28:6)

**Comment by alexesprit** [comment]
@emiliewebb There's no useful info in that logs. Try to listen to the music, collect the extension logs and send them here again.

**Comment by alexesprit** [comment]
Hi guys. Is the latest release works fine with Google Music?

**Comment by alexesprit** [comment]
Closed as outdated.

**Comment by elachim** [comment]
Hi,

i still have to re-authenticating my last.fm account everytime i open google music in new tab.

Is there any fix for that?

Thanks!

**Comment by alexesprit** [comment]
@elachim Hi!

No, there's no fix for that. We discuss this in #981; you can find all information we need to fix the issue in that thread.
