### ISSUE TITLE
Doesn't work with dubtrack

### ISSUE THREAD

**Issue by Botanistt** [david-sabata/web-scrobbler#897]
Just installed scrobbler and it's not working with dubtrack.
what a shame

**Comment by alexesprit** [comment]
I tried to fix dubtrack in my fork, It's would be great if you tested it: https://github.com/alexesprit/web-scrobbler/archive/dubtrack-fix.zip. See [here](https://github.com/david-sabata/web-scrobbler#unpacked-extension) for installation details.

It contains changes I described in #866. I'll propose a pull request if it helps to fix dubtrack scrobbling.

**Comment by Botanistt** [comment]
It worked!
Thank you so much!
