### ISSUE TITLE
Add Libre.fm scrobbling capability?

### ISSUE THREAD

**Issue by gafel** [david-sabata/web-scrobbler#898]
Would it be possible to add Libre.fm scrobbling capability to this extension?
Similar to https://play.google.com/store/apps/details?id=com.adam.aslfms&hl=en

**Comment by alexesprit** [comment]
Yes, it is possible, but not fully implemented yet. See #756 for details.

**Comment by gafel** [comment]
Great! Thanks! Looking forward to it
