### ISSUE TITLE
LastFM Scrobbler not scrobbling Google Play

### ISSUE THREAD

**Issue by spjcc** [david-sabata/web-scrobbler#907]
Hey, 

The scrobbler has stopped scrobbling from Google Play recently. It continues to work for Spotify & Youtube. I have tried re authenticating with LastFM but this has not resolved this issue. Any ideas on how to resolved this?

**Comment by alexesprit** [comment]
Hi!

Hmm, it works fine for me. Can you provide logs? See [here](https://github.com/david-sabata/web-scrobbler/wiki/How-to-debug-the-extension) for details.

**Comment by spjcc** [comment]
Ah, it's working again! 

I'm on a Chromebox and using the multiple sign in function and had it configured in a way that every time I clicked on  'Reauthenticate with LastFM' the pop up was appearing in a new invisible window rather than a new tab or visible window. 

Thanks Alexey

**Comment by pink999** [comment]
it really is (last fm) down for all scrobbling right now and  did same as spcc, I even prayed to good and evil and tossed salt, but it is last fm's end, what I was wondering what is the mag glass/ you click on it and you can add new music, did you update or chrome?
