### ISSUE TITLE
Connect on Bandcamp custom domains

### ISSUE THREAD

**Issue by Ipsquiggle** [david-sabata/web-scrobbler#910]
Bandcamp allows artists to display their music under a custom domain. As an example, look at this search result (which is on Bandcamp) https://bandcamp.com/search?q=zoe+keating&from=corphome

If you click on the result for "Through The Trees", it actually goes to zoekeating.com, but this is clearly a standard Bandcamp album page.

Would it be possible to "hint" your scrobbler, so I could go to that page and say something like, "Hey, I'm pretty sure this is a bandcamp page, please start scrobbling it?"

Even better would be if there is some kind of marker on the page that you could use to detect and automatically use the Bandcamp connector. (For example, I see the page header contains <meta property="og:url" content="http://zoekeating.bandcamp.com/album/into-the-trees">, which clearly contains a bandcamp URL.)

Thanks!

**Comment by inverse** [comment]
This would be super cool to have. We can support custom domains through the config section. But you need to manually specify these. Having the ability to hint what we feel is detected would be cool but would also require running some heuristics on all pages visited.

**Comment by Ipsquiggle** [comment]
A compromise might be to only run the heuristic on command, e.g. If I notice a page isn't scrobbling, I click the tool at button and it scans the page, white listing it if it is successful. 

Of course that's Wishlist. Just being able to manually add it would suit me too!

**Comment by inverse** [comment]
Certainly having this done as a active action could be good. As for the manual setup. Checkout the options for this extension and the settings for the individual connector. :+1:

**Comment by Ipsquiggle** [comment]
Cool this works perfectly. Thanks for this! There wasn't any info on the format though, so I ended up using *://music.zoekeating.com/* via a peek through the code ... is that correct? An example or tooltip in the dialog might be nice for discoverability.

**Comment by inverse** [comment]
@alexesprit should we close this? Perhaps having a more general way to "scrobble site site with connector x"  might be better, although that could get messy with patterns.
