### ISSUE TITLE
Icon in Address Bar Gone

### ISSUE THREAD

**Issue by LinkCable** [david-sabata/web-scrobbler#914]
It looks like the icon that popped up in your address bar when you were scrobbling no longer appears.

Was this change intentional? Or is it due to some Chrome update? (I'm on Version 49.0.2623.75 beta (64-bit)) If so I'd love the ability to reenable it as I liked having it pop up in my address bar and not have to have the extension taking up space in my Chrome Menu to see if the extension is scrobbling properly or not.

Thanks!

**Comment by inverse** [comment]
I think this was a change from Chrome itself. Not sure if we can bring it back.

**Comment by Paszt** [comment]
This is a change in Chrome itself, they've removed the ability to add icons in the address bar. You can still show the icon in the toolbar, but not the address bar.  Right click an icon in your menu to get to the "Show in toolbar" command.  You can also resize the toolbar by clicking just to the right of the address bar and dragging.  It's also possible to move icons by clicking and dragging.

They've said this is a security issue and that all extension icons should always be visible either in the toolbar or the menu. That should makes it easier to detect an extension installed by malware.

**Comment by LinkCable** [comment]
@Paszt alright, thanks for letting me know
