### ISSUE TITLE
Scrobble youtube repeat

### ISSUE THREAD

**Issue by Rebkos** [david-sabata/web-scrobbler#918]
After pressing repeat button which appears instead of play button after the video finishes, scrobbling starts again - which is perfectly fine.

However, when using repeat function added by Magic Actions extension 
or 
right-clicking video and selecting Loop - scrobbling won't start again. It just stays on Scrobbled (song name), no matter how many times video gets repeated.

Is it just me? Am I doing something wrong? Or is this "function" not added yet. If so, would you consider looking into it, perhaps working it out somehow?

Thanks for great extension though ;-)

**Comment by alexesprit** [comment]
Hm, I tested both repeat functions (Youtube built-in and Magic Actions ones). It works well on Chrome and Opera.

**Comment by Rebkos** [comment]
Did it really saved as another scrobble? 

Depending on your settings, when you reach 50% of song or 4 minutes, it "saves" it as scrobbled and if the song is still running, at last.fm you will see another entry of the same song saying - now scrobbling which disapears after you finish the song or start new one. 

It also stays on - now scrobbling when i use both repeat functions, but disappears after i stop listening to the song or play something else - but it won't "save it" as scrobbled, no matter how many times it was repeated.

**Comment by f1u77y** [comment]
`<video>` element has `currentTime` and `duration` properties and generates `progress` event
(dunno what to do with flash youtube videos if they still exist)
