### ISSUE TITLE
Songs Not Recognized ... when played from a saved list or direct link

### ISSUE THREAD

**Issue by Euther** [david-sabata/web-scrobbler#919]
Please see these two links...
Direct Youtube: https://www.youtube.com/watch?v=6i30IhVTpDA
List: https://www.youtube.com/watch?v=6i30IhVTpDA&list=PL5Zh27YEkR7mHw4k3k2QhPAjV27-2y_OG&index=3

When I enter song info as scrobbler suggests, entries made fine, when I play the song again, song not recognized... is there anything else I can do?

thx
E

Edit: I reauthenticated ... now I get an magnifinglass saying "looking up null - null"

**Comment by alexesprit** [comment]
I have the same issue too. Web scrobbler asks user to input the song artist & track name when the same one starts playing again, but it should't do that.

Infinity "magnifying glass icon" often means you have need to reauthenticate again. And, of course, reauthentication doesn't resolve this issue.

**Comment by Euther** [comment]
> Infinity "magnifying glass icon" often means you have need to reauthenticate again. And, of course, reauthentication doesn't resolve this issue.

Thanks Alexesprit ... I fixed that.  :D  same issue persists .

**Comment by Paszt** [comment]
> I have the same issue too. Web scrobbler asks user to input the song artist & track name when the same one starts playing again, but it shouldn't do that.

This functionality hasn't been implemented yet, it needs to be added to the pipeline. The _UniqueID_ property of the song is meant to be used for that - that property isn't being used at all currently.

**Comment by Euther** [comment]
Any thoughts on why Scrobbler is not recognizing the yourtube song at all???

**Comment by Paszt** [comment]
Not sure what you mean by channel, but the at the link you gave above, the title of the video is just "Gator Country" - that's not enough information to recognize the song.

**Comment by Euther** [comment]
Sorry, wasn't clear...  The examples provide on the 1st entry are part of this channel: Molly Hatchet - Topic. No songs in the lists associated to channel are recognized by Scrobbler. I played them all. 

https://www.youtube.com/channel/UCQemljjiGrwXkGC7c--uFNQ

**Comment by Euther** [comment]
Ah... @Paszt, looking at your last comment... Scroobler just looks at TITLE, only? In the description is show this:

Auto-generated by YouTube.
Category: Music
License: Standard YouTube License
Music: "Gator Gountry" by Molly Hatchet

Is there a way for this tool to look in the comment for the "Music"?

**Comment by Leo1212abc** [comment]
I have the same Problem. I use Amazon Alexa, if I play a song from a playlist, the song is not recognized (The Playlist name appears in Lst.fm) but when I’m playing the song outside of the playlist, the song is known and everything is fine.

**Comment by alexesprit** [comment]
> Is there a way for this tool to look in the comment for the "Music"?

Youtube changed their design, and now this info is not available until the description block is expanded.
