### ISSUE TITLE
Chrome "--app" windows causing scrobble issues

### ISSUE THREAD

**Issue by sphinx9** [david-sabata/web-scrobbler#922]
Hi,

Just to make sure this is known, starting Chrome with argument --app=<url> allows you to start browser windows in "app" mode, which looks like this: https://i.gyazo.com/b19a9617be33144d1b26076fb31bfb13.png (right-click menu to show that extensions are still being loaded).

The issue is that it seems songs aren't being scrobbled when they are opened in this manner.

I've tried testing this with a few videos, both in 'normal' Chrome tabs and like this, and with 'simpler' video titles (ie, "Artist - Track" and "Track - Artist" as well as the more complicated ones with brackets and pipes etc).

**Comment by ex47** [comment]
I cannot figure out how to use this argument :c

**Comment by alexesprit** [comment]
@sphinx9 are you still experiencing this issue? I cannot reproduce it.
I opened Youtube in an 'app' mode and played a random song, that was scrobbled successfully.

I can only guess that you weren't authorized while scrobbling songs in the 'app' mode.

For those who also want to reproduce this issue but don't know how to run Chrome in this mode:
```sh
 > chrome --app=https:\\youtube.com\
```
