### ISSUE TITLE
Icon in the address field is missing

### ISSUE THREAD

**Issue by MartinL0815** [david-sabata/web-scrobbler#927]
With Google Chrome Version 49.0.2623.87 I do not see the scrobbler icon in the address field anymore.
I use scrobbler only with the Amazon Music Library  and notice the notifications created by the scrobbler, but the icon is missing and so the knowledge if a track is recognized or not.

**Comment by alexesprit** [comment]
The icon was gone due to Google Chrome changes. Now it's placed in the extensions toolbar. See #914 for details.
![image](https://cloud.githubusercontent.com/assets/1119267/13914804/e18d1ab6-ef61-11e5-9d74-6ebec0300ed6.png)

**Comment by MartinL0815** [comment]
Sorry - was like the other address bar extensions out of sight ...!
