### ISSUE TITLE
F(eature )R(equest): what's about pre-filling the entry/edit fields with last detected or entered strings?

### ISSUE THREAD

**Issue by MartinL0815** [david-sabata/web-scrobbler#93]
Currently using the Amazon Cloud Player I have to enter all songs information, so I'd really be glad, if the UI to enter unrecognized song information would pre-fill the two entry/edit fields with the last detected or entered strings.

**Comment by janbaykara** [comment]
@david-sabata Can close this. This is now the behaviour of the popup (old and new).
