### ISSUE TITLE
Options and localStorage

### ISSUE THREAD

**Issue by inverse** [david-sabata/web-scrobbler#933]
Is there a reason that the majority of the options use `localStorage` and not the abstraction to `chome.storage`?

**Comment by ex47** [comment]
It's easy to use!)

http://stackoverflow.com/a/24281357/1617131

**Comment by alexesprit** [comment]
`chrome.storage` is asynchronous and uses callback to return storage data. Since the source code is almost "callback-based" it's not a good solution to use this storage API.
But, since we use `ChromeStorage` that wraps `chrome.local`, the possible option is to use Promises:
```js
const options = ChromeStorage.getNamespace('Options');

options.get().then((data) => {
    return data.useNotifications;
}).then((useNotifications) => {
    // Do your staff here
});
```

**Comment by alexesprit** [comment]
I added new storage wrapper, and replaced `localStorage` to `chrome.storage.local` in https://github.com/alexesprit/web-scrobbler/commit/d56bda9937bda37d0f2b8e563cd1bfe139b3c8c7, but these changes depends on multi-scrobble2 branch, so I'm think it's can be used if multi-scrobble2 will be merged.

**Comment by inverse** [comment]
Oh nice - good work :)
