### ISSUE TITLE
Song titles aren't read when playing from Bandcamp user pages

### ISSUE THREAD

**Issue by Regenspaziergang** [david-sabata/web-scrobbler#935]
When playing songs from one's own collection or another user page, the plugin icon shows a question mark and has a wrong title in the text field.

Example URL: https://bandcamp.com/donnerpartyofone. Then click play on any of the album covers.

There is a special case for songs which are released as stand-alone releases, such as "Den Lille Piges Død" by Myrkur, which might have to be treated differently when played (the HTML does not have the `<a class="fav-track-link" ...>` which denotes the song title for other albums).

**Comment by inverse** [comment]
Could you try the PR I just submitted? I noticed there was an issue with the way it was parsing the track title which should be resolved now.

**Comment by Regenspaziergang** [comment]
Thanks, I did, but there's still largely the same issue. Please see my comment there.

**Comment by david-sabata** [comment]
:white_check_mark: #937
