### ISSUE TITLE
Youtube scrobbler doesn't work with at least some playlist

### ISSUE THREAD

**Issue by intari** [david-sabata/web-scrobbler#936]
Youtube scrobbler doesn't work with at least some playlists
Example of non-working playlist https://www.youtube.com/watch?v=M9xqqsXnE1g&list=PLlVPY4ANNw8I811O-oMLVLu-NG6ylf76k&index=1&ab_channel=%D0%A5%D0%B5%D0%B4%D0%BB%D0%B5%D1%81%D1%81%D0%9E%D1%80%D0%B8%D0%B3%D0%B0%D0%BC%D0%B8

вокалоиды дочь зла(з части) and other songs doesn't scrobble 

Chrome 49.0.2623.87 (64-bit) on OS X

**Comment by alexesprit** [comment]
Try to disable `Scrobble only Music category` option in extension preferences.

**Comment by intari** [comment]
it's not enabled

**Comment by alexesprit** [comment]
The song from URL you provided (and some other ones) won't be scrobbled because they have "malformed" title. It's not Web scrobbler's fault.

**Comment by alexesprit** [comment]
As I said before, this is not a bug. The video title doesn't contain full information about the playing song.
