### ISSUE TITLE
Authentication issues in Chrome

### ISSUE THREAD

**Issue by eugenesvk** [david-sabata/web-scrobbler#938]
I'm having authentication issues with your addon — it's being asked for on every browser relaunch.
Also, I get the following errors in the authentication process in Chrome console
![last fm](https://cloud.githubusercontent.com/assets/12956286/14233418/86f8958e-f9d0-11e5-9fa4-27a3d6b303a6.PNG)

Windows 10
Chrome Version 49.0.2623.110 m (64-bit)

**Comment by Smokex365** [comment]
Had a similar issue. If yo haven't already fixed it, try removing the extension, restarting the browser, reinstalling the extension, authenticating and then restarting a couple of times to make sure it sticks. Fixed it for me at least.

**Comment by alexesprit** [comment]
@eugenesvk The log you provided isn't related to Web scrobbler extension. Are you still experiencing the issue?

**Comment by alexesprit** [comment]
Closed as outdated.
