### ISSUE TITLE
http://new.vk.com/ scrobbling doesn't work

### ISSUE THREAD

**Issue by Diyago** [david-sabata/web-scrobbler#941]
As you might know Vk.com lauched new beta version of the site new.vk.com . Unfortunately scrobbling stopped to work(( 
![image](https://cloud.githubusercontent.com/assets/8073766/14308599/cb5a14a8-fbdf-11e5-86c1-69653e900075.png)

**Comment by Diyago** [comment]
New vk design is released. Not its not the beta. The problem is still actual.

**Comment by seyfer** [comment]
+1, vk have been apdated recently to new version and srobbling not working now!

**Comment by david-sabata** [comment]
:white_check_mark: #1000
