### ISSUE TITLE
Scrobbler Not Scrobble in Chrome Versione 49.0.2623.110 m (64-bit)

### ISSUE THREAD

**Issue by ingcelsi** [david-sabata/web-scrobbler#942]
Just noticed that your web-Scrobbler is not Scrobbling at all in Chrome 49.0.2623.110 m (64-bit) with windows 10
Tested with Youtube.
Removed and Reinstalled, same issue.

**Comment by jeanleonino** [comment]
Could not reproduce it here. Can you try logging in to last.fm again?

**Comment by allan-shoup** [comment]
I'm seeing the same thing. Chrome 49.0.2623.112 (64-bit). Mac. Tested with YouTube, Google Music, and Amazon. Logged into last.fm and re-authenticated as well.

**Comment by Paszt** [comment]
[How to debug the extension](https://github.com/david-sabata/web-scrobbler/wiki/How-to-debug-the-extension)

**Comment by allan-shoup** [comment]
Thanks @Paszt. Using that I was able to see there were authentication problems
```
POST https://ws.audioscrobbler.com/2.0/?method=track.updatenowplaying&track=Ophe…0d3269646f740544d9def2c95&sk=null&api_sig=561fd7c8e7ae5a9a62762a7f5674fd54 403 (Forbidden)
L.FM response to https://ws.audioscrobbler.com/2.0/?method=track.updatenowplaying&track=Ophe…0d3269646f740544d9def2c95&sk=null&api_sig=561fd7c8e7ae5a9a62762a7f5674fd54 : error
Forbidden
```

I disabled all other extensions and re-authenticated and it seems to have worked. I managed to re-enable all extension and it still works. Not sure which one was conflicting, but happy it is working for the time being.
