### ISSUE TITLE
Amazon Music in Chrome Not Working

### ISSUE THREAD

**Issue by brarig219** [david-sabata/web-scrobbler#948]
The scrobbler is stopped working when streaming via Amazon Music while using it in the Chrome browser.  It was sketchy the past few weeks (having to choose an artist and then refresh the page to get the scrobbler to recognize it), but it seems like it is completely gone - the icon is gray, and does not even say that the site is enabled for scrobbling.

**Comment by hilgi** [comment]
Not working for me either. I deleted, rebooted, etc. I see people posting code, is that something I should add, if so, where and how?

**Comment by X-Cite86** [comment]
Same problem here, nice to see that this issue is allready known an fixed :-)
@hilgi this issue is fixed with pull request #949, we have to wait for the pull request is getting merged into master and a new scrobbler-version.

**Comment by MartinL0815** [comment]
Realizing that scrobbling is not working on Amazon(.de), I tried to re-authorize - without error.
But it didn't help.
Then I realized, that the flash-plugin is blocked now and that Amazon does not rely anymore on flash.

So with Google Chrome 50.0.2661.75 scrobbling on Amazon(.de) does not seem to work anymore out of the box.

**Comment by X-Cite86** [comment]
BTW: Downloaded Master and the three changed files from "Paszt:Amazon", copied the three files into Master and installed the extension in chrome. Scrobbling at music.amazon.de works fine! Thanks!

**Comment by hilgi** [comment]
So is this something I need to manually change or will the plugin receive the fix?

**Comment by lourinaldi** [comment]
@hilgi unfortunately @david-sabata hasn't cut a release (v1.57) since Mar 13. There are 6 commits to master since that release, not to mention the fine work that @Paszt has done here.

**Comment by MartinL0815** [comment]
Now we and of June - any chance for a commitment about a new release date fixing this issue?
