### ISSUE TITLE
Last.fm Token expired.

### ISSUE THREAD

**Issue by VDK** [david-sabata/web-scrobbler#952]
The app prompts me to do an authentication of my last.fm account.
When I try to do this, Last.fm says: "Token expired. Please return to Last.fm scrobbler for web and try again." 

It seems an API key has expired?

**Comment by MartinL0815** [comment]
Currently no problem for me.

**Comment by VDK** [comment]
today, I was able to grant permission to the Last.fm scrobbler, where earlier I got that "token expired" message.
