### ISSUE TITLE
Slacker Not Scrobbling

### ISSUE THREAD

**Issue by kmehlin** [david-sabata/web-scrobbler#953]
It appears to be just a Slacker thing. Other sites I scrobble from seem to be working properly.

**Comment by alexesprit** [comment]
I've just tested Slacker scrobbling, works fine.

**Comment by kmehlin** [comment]
Damn, I hate when it's just me. Even the old re-authenticate trick didn't work. :/

**Comment by alexesprit** [comment]
How is it "not scrobbling"? Is Web scrobbler does not recognize the song metadata? Or anything else?
Anyway, it's would be good to see your logs: https://github.com/david-sabata/web-scrobbler/wiki/How-to-debug-the-extension

**Comment by kmehlin** [comment]
It's not recognizing the track, yes. Acting as if nothings playing. This was what was at the bottom of the log. I included the last successful scrobble from Google Music before I switched to Slacker.

Tab 471: state update: {"track":"Let's Get It On","artist":"Marvin Gaye","album":"Let's Get It On","uniqueID":null,"duration":291,"currentTime":4,"isPlaying":false,"url":{"hash":"#/wmp","search":"","pathname":"/music/listen","port":"","hostname":"play.google.com","host":"play.google.com","protocol":"https:","origin":"https://play.google.com","href":"https://play.google.com/music/listen#/wmp","ancestorOrigins":{}},"trackArt":"https://lh4.ggpht.com/R9IXfFDs-ycDkPNqCD188cnFGTsf2Ad474pywcFjMwLZBHu6CA0X7AF-OioeNxYP2e5dpKQ4e5I=s90-c-e100"}
controller.js:129 Tab 471: isPlaying state changed to false
inject.js:120 -- subsequent ajax navigation, the scripts are already injected
controller.js:48 Tab 471: received empty state - resetting
notifications.js:181 Notification onClicked: C2A89FF3-A009-4731-8C66-D482AABC0176
inject.js:79 -- loaded for the first time, injecting the scripts
inject.js:107 	injecting vendor/jquery-2.1.0.min.js
inject.js:107 	injecting vendor/underscore-min.js
inject.js:79 -- loaded for the first time, injecting the scripts
inject.js:107 	injecting vendor/jquery-2.1.0.min.js
inject.js:107 	injecting core/content/reactor.js
inject.js:107 	injecting vendor/underscore-min.js
inject.js:107 	injecting core/content/connector.js
inject.js:107 	injecting core/content/reactor.js
inject.js:107 	injecting connectors/v2/slacker2.js
inject.js:107 	injecting core/content/connector.js
inject.js:107 	injecting core/content/starter.js
inject.js:107 	injecting connectors/v2/slacker2.js
controller.js:324 Tab 164: created controller for connector: {"label":"Slacker (main page)","matches":["*://www.slacker.com/*"],"js":["connectors/v2/slacker2.js"],"version":2}
inject.js:107 	injecting core/content/starter.js
controller.js:324 Tab 164: created controller for connector: {"label":"Slacker (main page)","matches":["*://www.slacker.com/*"],"js":["connectors/v2/slacker2.js"],"version":2}
inject.js:120 -- subsequent ajax navigation, the scripts are already injected
21572 console messages are not shown.

**Comment by alexesprit** [comment]
Strange. Seems like it's broken due to Slacker site changes, but scrobbling works for me.
Well, there's another place where Web scrobbler stores its logs. It is developer console shown by Ctrl+Shift+I. You need "Console" tab. It's often a lot of output in this console, so you can use filter to find needed logs:
![image](https://cloud.githubusercontent.com/assets/1119267/14750329/eaf588ca-08cc-11e6-99c1-600e3f44ccb9.png)
Can you try to play some song and send logs from that console?

**Comment by kmehlin** [comment]
I didn't see any logging with that filter one, but the second image is what it looked like unfiltered right after the song started. Not sure if it help.

![filter](https://cloud.githubusercontent.com/assets/1565086/14750718/3910ecd6-0894-11e6-9df7-b4b330f5bed3.png)

![no-filter](https://cloud.githubusercontent.com/assets/1565086/14750720/3d99d1f0-0894-11e6-8865-96d55bc1cde1.png)

**Comment by scruff67** [comment]
Stopped scrobbling from Slacker... all other scobbling sources still work... 
Every track says "The song not recognized..."

**Comment by alexesprit** [comment]
@scruff67  I fixed Slacker scrobbling in #1185. It would be great if you check the latest version from the repository.

**Comment by scruff67** [comment]
Oh wow, great - thank you!

Now the only problem is I'm a complete noob with installation of versions not from the Chrome Store... on the bright side I can probably figure it out given a shove in the right direction... Any advice as a good place for me to start?

**Comment by alexesprit** [comment]
We have a short HOWTO for this. Here it is -- https://github.com/david-sabata/web-scrobbler#unpacked-extension.

**Comment by scruff67** [comment]
Thanks for the hand on that!!!  I'm back in business with Slacker scrobbling, and now as a bonus know a bit more about extensions.  MANY THANKS!!!
