### ISSUE TITLE
Not scrobbling anything

### ISSUE THREAD

**Issue by Geordiegirl80s** [david-sabata/web-scrobbler#957]
My extension is set to scrobble from Google Play Music, Amazon, Deezer and Youtube and is not scrobbling anything, I've tried disabling and re-enabling each one with no joy. Any ideas?

**Comment by alexesprit** [comment]
I've tested scrobbling from Youtube, works fine for me.
Have you tried to reauthenticate with Last.fm in extension preferences?

**Comment by ODyckhoff** [comment]
Hi Geordiegirl80s, I had the same issue when only trying to scrobble from YouTube.

I logged into my last.fm account on the website, went to http://www.last.fm/settings/website#playback and selected "YouTube" and clicked "Save" and now that works.

Not sure *why* it works, but it does... If you can only select one source at a time, then I'm afraid this is likely a limitation set by last.fm and not necessarily a problem with the web-scrobbler. Further investigation will be needed.

**Comment by alexkirkp** [comment]
Mine stopped working, the extension recognized music was playing but it wasn't being recorded at last.fm.  I tried re-authenticating but nothing happened.  Just now when I visited last.fm it said I needed to verify my e-mail (I have had an account for 2 years and verified it when I got it), after that I re-authenticated and it is working again.

**Comment by koyuawsmbrtn** [comment]
I've reinstalled the extension and it worked. This might be a possible workaround, but this should be fixed.
