### ISSUE TITLE
failing to scrobble from archive.org

### ISSUE THREAD

**Issue by MbiraBeat** [david-sabata/web-scrobbler#959]
While I am able to scrobble from other websites such as youtube, bandcamp, 8tracks, etc. I am still unable to scrobble from archive.org . I've checked the log from the extension, and it appears that there's not enough information on the track I'm trying to scrobble as seen here:

Tab 501: state from connector doesn't contain enough information about the playing track: {"track":"speading comets - andrey kiritchenko","artist":"","album":null,"uniqueID":null,"duration":0,"currentTime":0,"isPlaying":true,"url":{"hash":"","search":"","pathname":"/details/mn001","port":"","hostname":"archive.org","host":"archive.org","protocol":"https:","origin":"https://archive.org","href":"https://archive.org/details/mn001","ancestorOrigins":{}},"trackArt":"https://ia800309.us.archive.org/17/items/mn001/mn001.jpg?cnt=0"}

I do hope that I can get some help in resolving this issue so I can begin to scrobble from archive.org . I have attempted to authorize and re-authorize my last.fm account several times, but it just doesn't seem to work either, if that information is any help.

Edit: I forgot that I tried to mess around with the configuration of the connector and I got the Tab240 error saying that the connector didn't contain enough information, though now that I've removed it, I still get the same response.

**Comment by david-sabata** [comment]
:white_check_mark: #961
