### ISSUE TITLE
TIDAL - Multiple Artists Scrobbling

### ISSUE THREAD

**Issue by themkc** [david-sabata/web-scrobbler#960]
Scrobbling multiple artists from TIDAL ends up with something the artists coming out like this:
- Beyonce / Kendrick Lamar
- INTO BeyonceKendrick Lamar

Example: http://www.last.fm/music/Beyonc%C3%A9Kendrick+Lamar/_/FREEDOM

**Comment by forenta** [comment]
This shouldn't be closed as the issue is not yet fixed in 2.82.1, @alexesprit.
![grafik](https://user-images.githubusercontent.com/2451238/235321828-905f7d72-8b1d-4620-bb58-92bdf921490a.png)

**Comment by inverse** [comment]
@forenta please create a new issue - the original one was closed in 2016.
