### ISSUE TITLE
Avoid scrobbling advertisements

### ISSUE THREAD

**Issue by BalooUriza** [david-sabata/web-scrobbler#962]
Google Play Music Radio now inserts ads every 2-5 songs.  It would be nice to not scrobble these fake tracks during the ads, as otherwise it quickly becomes the top listened to track.

**Comment by alexesprit** [comment]
There's already a fix of this issue. See #951 for details. You can wait for next Web scrobbler release or install it as unpacked extension from @Paszt repository.

**Comment by david-sabata** [comment]
Closed by #951
