### ISSUE TITLE
Comments on chrome store indicate scrobbling no longer working.

### ISSUE THREAD

**Issue by famewolf** [david-sabata/web-scrobbler#966]
**Several users have reported the extension asking them to re-auth every time they open chrome and that scrobbling is not occuring:**

_andreas_ petersson paintnerModified Mar 16, 2016

Stopped working. Connected Spotify and Last.FM to it etc but it is always grey-ed out.

Also each time i start Chrome it asks (out of nowhere) to re-auth to Last.fm.
Was this review helpful?   YesNoReply | Mark as spam or abuse

Matthew HarrisApr 20, 2016
Same here :(
Was this review helpful?   YesNoMark as spam or abuse

Rob SlaterApr 7, 2016
I also can't get it to scrobble and i'm getting the re-auth message each time i start chrome.
Was this review helpful?   YesNoMark as spam or abuse

Indran FernandoModified Apr 28, 2016

Asks to reauthorize each time I restart. Used to work well. Seems to be a common problem with ppl recently.
Was this review helpful?   YesNoReply | Mark as spam or abuse

Ioana HarasimModified Apr 5, 2016

Ok... so this didn't work at first at all although it looked green and said the song was playing. What I did to make it work was to: change my last.fm password, clean my history and browsing data and go to the Manage Extensions tab from Chrome and disable/enable the app again. It asked me to allow it to get access to my last.fm profile, I accepted and now it's finally scrobbling. 3 stars for smashing my brains to the wall trying to make it work. After it works it's actually a good app.
Was this review helpful?   YesNoReply | Mark as spam or abuse

Adam HartfileApr 9, 2016
All I had to do was disable then enable it and it's working again on youtube.
Was this review helpful?   YesNoMark as spam or abuse

Pete MorrowModified Apr 7, 2016

Used to just work perfectly in the background. Just recently it asks to be connected to my Last.fm account every single time I start-up. Kind of a pain.
Was this review helpful?   YesNoReply | Mark as spam or abuse

Indran FernandoApr 28, 2016
me too.
Was this review helpful?   YesNoMark as spam or abuse

Paul BurdenModified Apr 26, 2016

Connected once, but ever since it refuses to reconnnect, even if uninstalled and re-installed.
It remains permanently greyed out.
Was this review helpful?   YesNoReply | Mark as spam or abuse

Anthony MahonModified Mar 18, 2016

it is greyed out and doe not work at all
Was this review helpful?   YesNoReply | Mark as spam or abuse

Mikhail PushkinModified Apr 23, 2016

Asking for reauthentication at every start. Useless if this is not fixed.
Was this review helpful?   YesNoReply | Mark as spam or abuse

Bobby HiltzModified Apr 3, 2016

This extension has stopped working with Google Play...I have downloaded the extension from the git site and it works fine. What's the deal?

Update: Extension worked then stopped again...tells us that the dev is doing his job and trying to stay up to date.
Was this review helpful?   YesNoReply | Mark as spam or abuse

Saskia de KorteModified Mar 30, 2016

Greyed out and it asks me to connect my account each time I launch my browser.
Was this review helpful?   YesNoReply | Mark as spam or abuse

Enrico PiciarelliModified Mar 24, 2016

greyed out and stopped working. no help from support.
Was this review helpful?   YesNoReply | Mark as spam or abuse

Emily TaylorModified Apr 18, 2016

I used to use this for a bunch of things, but it doesn't work for TuneIn Radio despite saying that it does. Unfortunate.
Was this review helpful?   YesNoReply | Mark as spam or abuse

Patrick SmithModified 4 days ago

not working
Was this review helpful?   YesNoReply | Mark as spam or abuse_

**Comment by BenjaminHCCarr** [comment]
@famewolf @david-sabata I am having this same problem as well, on OSX and Windows, Chrome, Canary, and Chromium. Happy to test/log, but while I have debugged FF stuff, never done Chrome extension work.

**Comment by alexesprit** [comment]
These comments don't contain any useful information how to reproduce issues. I read comments on Chrome Web Store, but all of them are like "It's not working", and they are completely useless to resolve issues.

@BenjaminHCCarr if you still experiencing this same problem (btw, which problem of that ones?), please create a new issue with detailed description. You can find all information about debugging in the issue template.

**Comment by famewolf** [comment]
You'd probably have better chances to fix things if you didn't wait 8 months to reply.

**Comment by alexesprit** [comment]
@famewolf I'm sorry, what do you mean?

**Comment by famewolf** [comment]
I mean that we reported these issues back in May 2016.  If you had asked for more details we probably could have provided them at that time.  8 months later in January 2017 it's doubtful any of the people who encountered the errors are even still using the extension.  Why would they when it didn't work?

**Comment by alexesprit** [comment]
Well, we already have threads where we discussed a auth issue that some people mentioned in Web Store comments (#981, #458 and some others that are closed as duplicates). As you can see, there's no steps to reproduce the bug in that threads. Looks like no one is interesting to resolve these issues.
