### ISSUE TITLE
[Youtube] Music videos with title in quotes ("") is not recognized.

### ISSUE THREAD

**Issue by VladimirAmiorkov** [david-sabata/web-scrobbler#967]
For example [this](https://www.youtube.com/watch?v=Pj0UnN7jW1k&feature=share) music video is not recognized and scrobbled.

Any youtube video in the following format is not recognized: `<Artist name> "<Song name>"`

**Comment by VladimirAmiorkov** [comment]
After looking at the source code my guess is that the issue comes from the [`findSeparator`](https://github.com/david-sabata/web-scrobbler/blob/d8c15d856bd496e1e5486709ad97d5ceafe0b111/core/content/connector.js#L407-L422) function. I will try to make a pull request that fixes this issue once I find the time.

**Comment by lacivert** [comment]
:+1:

**Comment by bothbears** [comment]
actually, it's something I'm about to start working on, too - not just the artist "song" case, but some more cases I found on YouTube while listening
