### ISSUE TITLE
TuneIn & Google Music

### ISSUE THREAD

**Issue by hrrgn** [david-sabata/web-scrobbler#980]
No scrobbling. Song playing, ext says "This site is supported for scrobbling". Auth with Last.fm is good

**Comment by papermana** [comment]
I just had the same problem with Google Play Music, but now I can't replicate it anymore. (Basically, I reloaded and it started working.) I remember seeing in the console a warning that `Connector.playerSelector` couldn't be found, however the `#player` element was definitely present on the site. Perhaps something happens sometimes during loading/initialization of the site?

**Comment by skywinder** [comment]
TuneIn doesn't scrobble.

**Comment by alexesprit** [comment]
@papermana you're totally right, that happened randomly.

**Comment by alexesprit** [comment]
Google Play Music should work fine after applying #1176. TuneIn is fixed some time ago and works fine, as I mentioned above.
