### ISSUE TITLE
Scrobble eMusic cloud

### ISSUE THREAD

**Issue by mrbootle** [david-sabata/web-scrobbler#988]
Would great if you could support eMusic's cloud streaming service
http://www.emusic.com/music-cloud/

**Comment by inverse** [comment]
Behind a paywall :( @mrbootle do you have any JS experience? We have documentation on our wiki.

**Comment by mrbootle** [comment]
Just saw this… sorry :-) No JS experience sadly. I'll ask them directly

**Comment by OwnageIsMagic** [comment]
You can open player by clicking track number
