### ISSUE TITLE
i have to constantly reconnect to last.fm

### ISSUE THREAD

**Issue by linussblanket** [david-sabata/web-scrobbler#990]
seems  that every time i start the browser, a pop-up asks me to authenticate the application

**Comment by ssebbass** [comment]
Same issue.

Ubuntu Xenial
Google Chrome 51.0.2704.106-1

**Comment by ifthenelse** [comment]
Isn't it a duplicate of #981 ?

**Comment by ssebbass** [comment]
Yes, could be a duplicate...

About the issue, it seems to drop access on one browser (for instance my home pc), when I login in my other computer.
I have stopped login in in all except for one computer, and then it stops asking for access to last.fm.

**Comment by david-sabata** [comment]
Closed in favor of #981
