### ISSUE TITLE
New version of vk.com was released and scrobbling doesn't work.

### ISSUE THREAD

**Issue by seyfer** [david-sabata/web-scrobbler#994]
[https://new.vk.com/](https://new.vk.com/)

There is already some fix proposed, maybe it should be merged?

https://github.com/david-sabata/web-scrobbler/pull/947

**Comment by Sakurachansky** [comment]
Please, support this!

**Comment by ex47** [comment]
The fix doesn't work, does it?

**Comment by ex47** [comment]
#1000
