### ISSUE TITLE
No exception made for YouTube titles with "... Remix" between [].

### ISSUE THREAD

**Issue by PlaylistsTrance** [david-sabata/web-scrobbler#995]
YouTube titles with the format Artist - Song [2nd Artist Remix] are being scrobbled as just Artist - Song.

**Comment by david-sabata** [comment]
Yes, this is because of _cleanup_ which is done on the title in order to get really just artist and track names. Although we may introduce more customizable filtering later, for now this is the intended behavior, expected by most of the users
