### ISSUE TITLE
Notify when song can't be resolved

### ISSUE THREAD

**Issue by dufferzafar** [david-sabata/web-scrobbler#997]
Sometimes the scrobbler can't detect which song is playing (any idea why this occurs?) and the icon changes to a question mark one. I then have to manually click on it, and submit the song.

I think the user should be notified that the song couldn't be detected.

**Comment by ex47** [comment]
![screenshot_5](https://cloud.githubusercontent.com/assets/2480069/17136764/ff545fa4-533f-11e6-8d43-350d86983b74.png)

Looks ok?

**Comment by dufferzafar** [comment]
Yeah, that looks neat!

**Comment by alexesprit** [comment]
Added in #1002 with some changes.
